### ISSUE TITLE
Custom log instance used by ggez

### ISSUE THREAD

**Issue by Bowarc** [ggez/ggez#1002]
**Describe the bug**
When i unable a logger (the log crate), i have a ton of "INFO - Created buffer 8" (The number changes) messages

**To Reproduce**
Set up the log crate for your project with the log lvl INFO enabled

**Expected behavior**
To se only my logs

**Screenshots or pasted code**
![image](https://user-images.githubusercontent.com/63136904/146894428-c538a603-ca0b-4d1b-a7fb-16be0fa9c4d2.png)
this is less than 200 milliseconds 

**Hardware and Software:**
 - ggez version: 0.6.0
 - OS: Windows 10
 - Graphics card: geforce gtx 2070
 - Graphics card drivers: up to date

**Comment by PSteinhaus** [comment]
This seems to be a common problem. If you want to set the log level per crate/module you have to use a logger which allows you to do that, such as `env_logger`. For an example on how to use it look here: https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html

**Comment by Bowarc** [comment]
> This seems to be a common problem. If you want to set the log level per crate/module you have to use a logger which allows you to do that, such as `env_logger`. For an example on how to use it look here: https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html

Yeah thx, i tried it and it works as i wanted, thanks !
