### ISSUE TITLE
Adapt Canvas implementation to remember current Canvases

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#1003]
Recently, @liquidev asked on Discord whether Canvases could be used like this:
```rust
canvas.draw_stuff(|ctx| {
  // draw things to the canvas here
}) ;
```
They can't.
But what if we actually changed the API to allow this? Specifically, I'm thinking about changing/expanding the API to include `graphics::use_canvas`, similar to `graphics::use_shader`.

As a possible implementation I could imagine to wrap the canvas data in a new struct `CanvasHandle` (again, like we do with shaders), which is wrapped in a Rc. Inside the context we could store `Weak<CanvasHandle>`s for all the Canvases created. Every once in a while we could go through this list and remove all `Weak<CanvasHandle>`s that cannot be upgraded to `Rc`s anymore, implicating that the Canvas has been dropped. (We don't currently do anything like this with shaders, because shaders are usually long lived and few).

This would of course add some overhead, mainly due to the use of the `Rc`s and having to upgrade and maintain the `Weak`s.

The question is: What would be the use cases of such functionality? I dimly remember that it might have been useful to have something like this when implementing the resolve shader workaround for multisampled canvases, but I really don't have any actual use cases in mind right now, so I'd be interested in hearing some opinions on that.

**Comment by liquidev** [comment]
My use case for this was composability with outside code. Without a way to get (or perform a scoped reset of) the canvas, the caller of a function must ensure that they're drawing to the correct canvas. Say you're writing a library that does post-processing effects. You want it to be usable everywhere, without the user having to worry about the global state being… whatever the post-processing library needed it to be. For instance:
```rs
graphics::use_canvas(ctx, Some(&canvas), |ctx| {
  post_process.use_canvas(ctx, |ctx| {
    // draw here
  });
  post_process.apply_shader(&my_shader);
  post_process.finish();
  // draw additional things after post-processing
});
```

**Comment by nobbele** [comment]
wouldn't it be better to just add a get_canvas function like the löve api

**Comment by PSteinhaus** [comment]
I'd prefer that as well, but it would further complicate the API surface, wouldn't it?

`get_canvas` would have to return a reference to the `CanvasHandle` (or whatever) held by the Canvas that is current. So we'd have to make it public as well. I don't think that's worth it.

**Comment by PSteinhaus** [comment]
With the wgpu-PR merged the canvas being drawn to is now always explicitly given in all drawing-functions, meaning you can choose what canvas you want to render to at any moment.
The downside of this is of course that without an implicit _current canvas_ you now always have to hand the canvas you want to draw on around in your program. But right now I think that change is worth it. It makes dealing with shaders and blend modes easier as well, as they're just part of a canvas' state now.
