### ISSUE TITLE
z-value in DrawParam

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#1007]
Currently there is no way of defining z-order in ggez. The z-order is defined only through the order in which the draw calls are made.

This is not good.
First off there are many situations where it's just more comfortable to set the z-order explicitly than it is to dance the "which draw call next"-dance. Then there is `Spritebatch`. You can't set z-order in a spritebatch, except through clearing it and pushing all sprites into it again in the new desired order. This is possible, but ridiculous and unnecessary.

The change wouldn't need to be big. We could just introduce a z-value field to `DrawParam` and adapt the function that calculates the matrices to respect that value and we'd be done. Alternatively we could change `dest` from a 2D point to a 3D one, but that would require changing a lot of code, both in our examples and also for people updating their ggez.

I lean towards the first approach, as it's both simpler and possibly less confusing, as ggez IS a 2D engine and it therefore makes sense for positions to be specified in two dimensions, though I realize this point is very much debateable.

**Comment by nobbele** [comment]
z-order isn't that simple if you want transparency cause the depth buffer doesn't work in that case. It can work if we use a queue system so they can be reordered before drawing.

**Comment by PSteinhaus** [comment]
Hmm, you're right I didn't think of that.
That would mean that `draw` and `Spritebatch::add` would become insertions into something like a z-based priority queue, which would mean that `flush` would need to no longer pass on an already existing and filled command buffer, but instead, it would need to create that buffer and fill it itself, so that the z-oder can be respected.

The question that I have then is: What would this mean for things like post-processing, where you draw on a canvas and then draw that canvas using a different shader? Approaches where you don't want order of actions to be based on z-order, but actually on the order in which they were called in code.

**Comment by nobbele** [comment]
Oblivion already has a queue system, it only lacks Z-sorting. Each canvas has a separate queue so there's shouldn't be any problems with drawing to a canvas and then drawing the canvas with a different shader in the queue system.

**Comment by PSteinhaus** [comment]
Ok, right, then with Oblivion this should hopefully be a bit easier to implement.

But the question remains: If the queues are z-sorted how do we specify that you want a certain canvas to be drawn _before_ another _although_ it has a lower z-priority?

**Comment by PSteinhaus** [comment]
Ok, the wgpu PR should solve this problem beautifully, as render passes drawing canvases are now explicit, so I‘ll unpin this issue now.

**Comment by PSteinhaus** [comment]
Ok, z-values _should_ now be respected everywhere, even internally inside of `InstanceArray`s, as long as you set `InstanceArray::ordered` to true.
