### ISSUE TITLE
`duration_to_f64` is already in the stdlib

### ISSUE THREAD

**Issue by aleokdev** [ggez/ggez#1014]
[`ggez::timer::duration_to_f64`](https://github.com/ggez/ggez/blob/50918f133785e1ee585c022d94a0176ea0e73887/src/timer.rs#L166) attempts to have the same functionality as [`time::Duration::as_secs_f64`](https://doc.rust-lang.org/stable/std/time/struct.Duration.html#method.as_secs_f64). `f64_to_duration` has the same issue (`time::Duration::from_secs_f64`)

**Comment by PSteinhaus** [comment]
Indeed, it seems it's time to remove these.

**Comment by PSteinhaus** [comment]
Removed in 7ec47a407fd8e7dcd3ab29af66c3e35d3a7a2a10
