### ISSUE TITLE
`remaining_update_time` has an unneccesary mutable borrow

### ISSUE THREAD

**Issue by aleokdev** [ggez/ggez#1015]
[`remaining_update_time`](https://github.com/ggez/ggez/blob/50918f133785e1ee585c022d94a0176ea0e73887/src/timer.rs#L248) takes a mutable borrow to the context for apparently no reason. As mutability isn't required, the parameter should be switched to an immutable borrow.

**Comment by PSteinhaus** [comment]
True, thanks for finding. I'll change it tomorrow morning.

**Comment by PSteinhaus** [comment]
Changed in 7ec47a407fd8e7dcd3ab29af66c3e35d3a7a2a10
