### ISSUE TITLE
Consider removing From<tuple> implementations for DrawParam

### ISSUE THREAD

**Issue by aleokdev** [ggez/ggez#1023]
Applicable to #1020.

Currently, `DrawParam` has a set of `From` implementations for tuples of data. This might seem like a good idea for initializing quickly from a set of data, but it has several drawbacks:
- It depends on the order the data is given in. For example, `(P, f32, P, V, Color)` can convert into a `DrawParam`, but `(P, f32, P, Color, V)` can't.
- It's inconsistent: There's an implementation for `(P,)` and another one for `(P, Color)` so, from order, you'd expect the next one to be `(P, Color, f32)`, but it is actually `(P, f32, Color)`.
- It's unclear what each tuple item is referring to:
```(vec2(0., 0.2), 0.6, vec2(1., 4.), vec2(64., 64.), Color::WHITE)```
Sure, `Color::WHITE` refers to the color of the draw param, but what are the vector parameters referring to? Compare this to the explicit version:
```rs
DrawParam::new()
    .dest(vec2(0., 0.2))
    .rotation(0.6)
    .offset(vec2(1., 4.))
    .scale(vec2(64., 64.))
```
Sure, it is a bit longer, but it is *much* more readable in comparison. Plus, doing it this way also allows removing default values, such as the color, which is not possible by using the `From` implementation.

Overall, I think it could be confusing for beginners and it isn't good practice, so from my point of view removing it would be a good idea. We could take advantage of the WGPU rewrite to insert this change in as well.

**Comment by nobbele** [comment]
I never liked this either but it might be worthwhile to keep (P,) and (P, Color)

**Comment by PSteinhaus** [comment]
I second that. How about we remove all tuple implementations and instead only keep this?:
```rust
impl<P> From<P> for DrawParam
where
    P: Into<mint::Point2<f32>>,
{
    fn from(location: P) -> Self {
        DrawParam::new().dest(location)
    }
}
```
As `From<(P,)>` is indeed handy and this is basically just a less weird version of it.

**Comment by aleokdev** [comment]
Looks good!
