### ISSUE TITLE
the trait `ggez::graphics::Drawable` is not implemented for `Result<Mesh, ggez::GameError>`

### ISSUE THREAD

**Issue by Mergpijp** [ggez/ggez#1027]
**Describe the bug**
I am trying to draw graphics with a mesh containing draw_polygon but the title error is displayed.

**To Reproduce**
See code

**Expected behavior**
Multiple voronoi polygons in a rectangle.

**Screenshots or pasted code**
culprit code:
```
impl ggez::event::EventHandler<GameError> for State {
    fn update(&mut self, _ctx: &mut ggez::Context) -> GameResult {
        Ok(())
    }
    fn draw(&mut self, ctx: &mut ggez::Context) -> GameResult {
        ggez::graphics::clear(ctx, ggez::graphics::Color::BLACK);
        for shape in &self.shapes {
            // Make the shape...
            let mesh = match shape {
                &Shape::Rectangle(rect) => {
                    ggez::graphics::Mesh::new_rectangle(ctx, ggez::graphics::DrawMode::fill(), rect, ggez::graphics::Color::WHITE)?
                }
                &Shape::Circle(origin, radius) => {
                    ggez::graphics::Mesh::new_circle(ctx, ggez::graphics::DrawMode::fill(), origin, radius, 0.1, ggez::graphics::Color::BLACK)?
                }
            };
            // ...and then draw it.
            ggez::graphics::draw(ctx, &mesh, ggez::graphics::DrawParam::default())?;
        }
        for (i, poly) in self.vor_polys.iter().enumerate() {
            let mut mint = Vec::new();
            for p in poly {
                mint.push(
                    mint::Point2{
                    x: p.x.into_inner() as f32,
                    y: p.y.into_inner() as f32,
                    }
                );
            }
            mint.sort_unstable_by(|a, b| sort_clockwise(Point2::new(a.x as i32, a.y as i32), Point2::new(b.x as i32, b.y as i32),  Point2::new(1920/2, 1080/2)));
            let poly_mesh = ggez::graphics::Mesh::new_polygon(ctx, ggez::graphics::DrawMode::fill() , &mint, ggez::graphics::Color::BLUE);
            ggez::graphics::draw(ctx, &poly_mesh, ggez::graphics::DrawParam::default())?;
        }
        ggez::graphics::present(ctx)?;
        Ok(())
    }

}
```

**Hardware and Software:**
 - ggez version: For example, release 0.7.0, latest release
 - OS: Windows 11
 - Graphics card: RTX 3080 laptop
 - Graphics card drivers: 512.15

**Comment by Mergpijp** [comment]
So I missed the question mark at the end of the poly_mesh variable.
It now draws a big blue rectangle at the left part of the canvas. Also there are some polygons in vor_polys with less then 3 points.

**Comment by PSteinhaus** [comment]
> So I missed the question mark at the end of the poly_mesh variable.

Exactly. The same goes for `mesh` of course. You have to get the `Mesh` out of the `Result` to be able to draw it.

> It now draws a big blue rectangle at the left part of the canvas. Also there are some polygons in vor_polys with less then 3 points.

A polygon with less than 3 points isn't a polygon, it's a line. You can't create a mesh from it. It's weird that you don't get [a `LyonError` when you try to do that](https://docs.rs/ggez/latest/src/ggez/graphics/mesh.rs.html#597-601).

**Comment by Mergpijp** [comment]
Thank you @PSteinhaus ,
I did get the error I now put a condition enforcing three points minimum.
Here is the code:
```
impl ggez::event::EventHandler<GameError> for State {
    fn update(&mut self, _ctx: &mut ggez::Context) -> GameResult {
        Ok(())
    }
    fn draw(&mut self, ctx: &mut ggez::Context) -> GameResult {
        ggez::graphics::clear(ctx, ggez::graphics::Color::BLACK);
        for shape in &self.shapes {
            // Make the shape...
            let mesh = match shape {
                &Shape::Rectangle(rect) => {
                    ggez::graphics::Mesh::new_rectangle(ctx, ggez::graphics::DrawMode::fill(), rect, ggez::graphics::Color::WHITE)?
                }
                &Shape::Circle(origin, radius) => {
                    ggez::graphics::Mesh::new_circle(ctx, ggez::graphics::DrawMode::fill(), origin, radius, 0.1, ggez::graphics::Color::BLACK)?
                }
            };
            // ...and then draw it.
            ggez::graphics::draw(ctx, &mesh, ggez::graphics::DrawParam::default())?;
        }
        
        for (i, poly) in self.vor_polys.iter().enumerate() {
            if poly.len() > 2 {
                let mut mint = Vec::new();
                for p in poly {
                    mint.push(
                        mint::Point2{
                        x: p.x.into_inner() as f32,
                        y: p.y.into_inner() as f32,
                        }
                    );
                }
                mint.sort_unstable_by(|a, b| sort_clockwise(Point3::new(a.x as i32, a.y as i32), Point3::new(b.x as i32, b.y as i32),  Point3::new(1920/2, 1080/2)));
                //let poly_mesh = ggez::graphics::Mesh::new_polygon(ctx, ggez::graphics::DrawMode::fill() , &mint, ggez::graphics::Color::BLUE)?;
                let line_mesh =  ggez::graphics::Mesh::new_polyline(ctx, ggez::graphics::DrawMode::stroke(2.0), &mint, ggez::graphics::Color::BLUE)?;
                ggez::graphics::draw(ctx, &line_mesh, ggez::graphics::DrawParam::default())?;
            }
            //mint = mint.as_slice();

        }
        
            
        //for p in mint {
        // let line_mesh =  ggez::graphics::Mesh::new_line(ctx, &mint, 3.0, ggez::graphics::Color::BLUE)?;
        // ggez::graphics::draw(ctx, &line_mesh, ggez::graphics::DrawParam::default())?;
        ggez::graphics::present(ctx)?;
        Ok(())
    }

}
```

I get a result but some polygons are open how did this happen?
<img width="1920" alt="vorionio_result" src="https://user-images.githubusercontent.com/53097999/163580969-408fbd52-2c50-4040-b41b-913996fa580a.png">

**Comment by Mergpijp** [comment]
I think because I took the code from veronoi example I must plot in lines how do I plot a line with 2 points?

**Comment by PSteinhaus** [comment]
> I get a result but some polygons are open how did this happen? 

They are open because now you're not drawing any polygons at all. You're drawing polylines, [which are](https://docs.rs/ggez/latest/ggez/graphics/struct.Mesh.html#method.new_polyline)
> series of connected lines

> I think because I took the code from veronoi example I must plot in lines how do I plot a line with 2 points?

Use either `new_polyline` or `new_line`. `new_polyline` is defacto almost identical to `new_polygon`, with the difference that `new_polygon` closes each figure by adding a final line from the last to the first point given.

**Comment by Mergpijp** [comment]
Ok thanks for the reply. I decided to use new_line because that was used in the example.
A code snippet:
```
        for (i, poly) in self.vor_polys.iter().enumerate() {
            if poly.len() > 0 {
                let mut mint = Vec::new();
                for p in poly {
                    mint.push(
                        mint::Point2{
                        x: p.x.into_inner() as f32,
                        y: p.y.into_inner() as f32,
                        }
                    );
                    //graphics::line(ctx, &[Point {x: p.x.into_inner(), y: p.y.into_inner()}, Point {x: 400., y: 500.}])?;
                }
                for i in 0..mint.len()-1 {
                    let line_mesh =  ggez::graphics::Mesh::new_line(ctx, &[mint[i], mint[i+1]], 3.0, ggez::graphics::Color::BLUE)?;
                    ggez::graphics::draw(ctx, &line_mesh, ggez::graphics::DrawParam::default())?;
                }
```
I get the following error: 
Error on EventHandler::draw(): LyonError("Trying to build mesh with < 3 vertices, this is usually due to invalid input to a `Mesh` or MeshBuilder`.")
Why is this invalid for new_line?

**Comment by PSteinhaus** [comment]
Hmm, that’s a good question. You may just have found a bug.

The reason you get this error is that this check is made on all meshes that are built, lines included, though it may not make any sense for lines, as they _may_ be fine having just two points (depending on how Lyon sees this), but I can’t test this right now. I‘ll try to do so after easter.

**Comment by Mergpijp** [comment]
@PSteinhaus , I tried your solution but deeper in the code it will complain about not having a vertex. It does not see overlapping lines as a two lines meet so no vertex. I also tried graphics::line but it requires a context and graphics maybe this is a workaround? Happy easter!

**Comment by PSteinhaus** [comment]
Ok, I tested it and looked into it now and I can confirm that getting such an error with `new_line` or `line` is possible, and I may have found a reason why this happens to you.

The simple way to get this error is to only give one single point to the function, or no points at all. Anything else, from 2 points onwards, just works for me, so to me the functions seem to work as intended...

BUT, if I only pass in _2 identical points_, then I can get the error as well. This makes sense. Lyon gets those two points and doesn't know how to tesselate a polygon that's really just a point, so it doesn't create any vertices at all (or perhaps only one, or something) and you end up with invalid output.

As soon as you add a non-identical third point, however, you'll again get a beautiful line to draw, as there now actually _is_ a line to draw at all.

## About your approach in general

Now that I look closer at all of this I realize that I could/should have given you a certain piece of advice a bit sooner:
When you're trying to create and draw one big mesh-thing and don't care about the lines being individual `Mesh`es each, then I urge you to directly use a `MeshBuilder` to achieve this, a bit like in example [`03_drawing`](https://github.com/ggez/ggez/blob/03a6f4e2886d990ce408a51b62d457286c18b533/examples/03_drawing.rs#L41-L74).
Instead of creating a `Mesh` for each entry in `vor_polys` you only create one big `Mesh`, that contains all of your lines. It's much more efficient and in your case it also has the added benefit that as long as _any point list at all in `vor_polys` holds 2 non-identical points_ (so as long as there actually _is_ any line at all to be drawn), then your code won't throw you that error. If it does, then that would probably mean that there aren't any lines to draw at all, so the failure is unimportant and you can just go on in your control flow.

**Comment by Mergpijp** [comment]
Okay thank you for your detailed answer. I am trying to build a MeshBuilder with lines just as in the example but I get MeshBuilder not found in `graphics`.
`let mb = &mut graphics::MeshBuilder::new();`
with import: 

`use ggez::graphics::MeshBuilder;`

**Comment by Mergpijp** [comment]
oh wait I just add ggez:: in front. I am new to Rust btw.

**Comment by Mergpijp** [comment]
Hmm I am doing something wrong I just get nothing drawn on screen here is the code:

```
    fn draw(&mut self, ctx: &mut ggez::Context) -> GameResult {
        //let rect_s =  first(&self.shapes).unwrap()
        let mut rect_s = ggez::graphics::Rect::new(
            192.0,
            108.0,
            1536.0,
            864.0,
        );
        ggez::graphics::clear(ctx, ggez::graphics::Color::BLACK);
        for shape in &self.shapes {
            // Make the shape...
            let mesh = match shape {
                &Shape::Rectangle(rect) => {
                    ggez::graphics::Mesh::new_rectangle(ctx, ggez::graphics::DrawMode::fill(), rect, ggez::graphics::Color::WHITE)?
                }
                &Shape::Circle(origin, radius) => {
                    ggez::graphics::Mesh::new_circle(ctx, ggez::graphics::DrawMode::fill(), origin, radius, 0.1, ggez::graphics::Color::BLACK)?
                }
            };
            // ...and then draw it.
            ggez::graphics::draw(ctx, &mesh, ggez::graphics::DrawParam::default())?;
        }
        let mb = &mut ggez::graphics::MeshBuilder::new();
        let colors = [ggez::graphics::Color::BLUE, ggez::graphics::Color::RED, ggez::graphics::Color::YELLOW, ggez::graphics::Color::GREEN];
        let mut mint = Vec::new();
        for (i, poly) in self.vor_polys.iter().enumerate() {
            if poly.len() > 1 {
                for i in 0..poly.len()-1 {
                    mint.push(
                        Vec2::new(poly[i].x.into_inner() as f32, poly[i].y.into_inner() as f32)
                    );
                    mint.push(
                        Vec2::new(poly[i+1].x.into_inner() as f32, poly[i+1].y.into_inner() as f32)
                    );
                }
            }
            else {
                println!("IN!");
            }
        }
        mb.line(
            &mint,
            4.0,
            ggez::graphics::Color::BLUE,
        )?;
        mb.build(ctx);
        ggez::graphics::present(ctx)?;
        Ok(())
    }
}
```

**Comment by Mergpijp** [comment]
Oo I am so lazy the example does explain it. (in code)

**Comment by Mergpijp** [comment]
Hmm i got the following error:
`let mesh = build_mesh(ctx);`
^^^ expected struct `graphics::Context`, found struct `ggez::Context`

I thought that the example uses the same ctx object I am confused.

**Comment by PSteinhaus** [comment]
Ok, maybe first off: with example, do you mean `03_drawing`? Because you also mentioned some kind of voronoi example, but I have no idea where I'd find something like that...

```
        // ...
        let mut mint = Vec::new();
        for (i, poly) in self.vor_polys.iter().enumerate() {
            if poly.len() > 1 {
                for i in 0..poly.len()-1 {
                    mint.push(
                        Vec2::new(poly[i].x.into_inner() as f32, poly[i].y.into_inner() as f32)
                    );
                    mint.push(
                        Vec2::new(poly[i+1].x.into_inner() as f32, poly[i+1].y.into_inner() as f32)
                    );
                }
            }
            else {
                println!("IN!");
            }
        }
        mb.line(
            &mint,
            4.0,
            ggez::graphics::Color::BLUE,
        )?;
        mb.build(ctx);
        ggez::graphics::present(ctx)?;
        Ok(())
    }
}
```

This won't do what you want. This will create ONE LINE, going over all the given points. That means it doesn't only include `point0 -> point1`, `point2 -> point3`, etc., BUT ALSO `point1 -> point2`, `point3 -> point4`, etc.

A better example for how to use `MeshBuilder` to achieve your goal would have probably been `imageview.rs` (really bad name, btw. should probably rename it to `crazylines` or something). There, a `MeshBuilder` is used to create a `Mesh` from many **non-consecutive lines**, artificially creating one _consecutive line_ (a bit of a waste really, but whatever). So to come back to your code, what you want to do is use `line` a bit like that, but more sensible:
```
        // ...
        let mut mint = Vec::new();    // why "mint", btw?
        for (i, poly) in self.vor_polys.iter().enumerate() {
            if poly.len() > 1 {
                for i in 0..poly.len() {
                    mint.push(
                        Vec2::new(poly[i].x.into_inner() as f32, poly[i].y.into_inner() as f32)
                    );
                }
                // then, if your polygon points don't wrap around to the first one (which I assume)
                // you'll have to close the polygon by drawing a line from end to start
                mint.push(
                        Vec2::new(poly[0].x.into_inner() as f32, poly[0].y.into_inner() as f32)
                );
            }
            else {
                println!("IN!");
            }
            // this adds a line with multiple segments to the builder, which is independent from other lines before
            mb.line(
                &mint,
                4.0,
                ggez::graphics::Color::BLUE,
            )?;
        }
        mb.build(ctx);
        ggez::graphics::present(ctx)?;
        Ok(())
    }
}
```

This _should_ do what you want. I don't know your exact situation, but I feel like using `MeshBuilder::polygon` with a `DrawMode::Stroke` would be easier/better though, as you don't have to manually close the polygon. That's just done automatically.

**Comment by PSteinhaus** [comment]
> Hmm i got the following error: `let mesh = build_mesh(ctx);` ^^^ expected struct `graphics::Context`, found struct `ggez::Context`
> 
> I thought that the example uses the same ctx object I am confused.

It does. But in your code I don't see any function called `build_mesh`...

**Comment by Mergpijp** [comment]
Yeah I changed a lot of code. My only issue now is that it gives an error on draw:

`graphics::draw(ctx, &self.mesh, ggez::graphics::DrawParam::new())?;`

It says draw not found in graphics.
If I put ggez:: in front it says: 
the trait `ggez::graphics::Drawable` is not implemented for `Result<Mesh, ggez::GameError>`
Might be that the example is old code?

**Comment by PSteinhaus** [comment]
No problem ^^
I remember being new to Rust. Back then I used ggez to learn the language too. To me, supplying this kind of playground is one of the most important uses of ggez still.

Is there anything else / is your code now working as intended?

**Comment by Mergpijp** [comment]
So I draw lines like it did in the example:
```
    for i in 0..poly.len()-1 {
        graphics::line(
            color,
            2.0,
            [poly[i].x.into(), poly[i].y.into(), poly[i+1].x.into(), poly[i+1].y.into()],
            c.transform,
            g
        )
    }
```
See code attached. 

```
extern crate piston;
extern crate opengl_graphics;
extern crate graphics;
extern crate touch_visualizer;
 
#[cfg(feature = "include_sdl2")]
extern crate sdl2_window;
 
extern crate getopts;
extern crate voronoi;
extern crate rand;

use glam::*;
use touch_visualizer::TouchVisualizer;
use opengl_graphics::{ GlGraphics, OpenGL };
use graphics::{ Context as Gcontext, Graphics};
use piston::window::{ Window, WindowSettings };
use piston::input::*;
use piston::event_loop::*;
#[cfg(feature = "include_sdl2")]
use sdl2_window::Sdl2Window as AppWindow;
use voronoi::{voronoi, Point, make_polygons};
use rand::Rng;
 
static DEFAULT_WINDOW_HEIGHT: u32 = 1080;
static DEFAULT_WINDOW_WIDTH:  u32 = 1920;
 
struct Settings {
    lines_only: bool,
    random_count: usize
}

use ggez::*;
use ggez::{Context, GameResult};
use oorandom::Rand32;
use ggez::graphics::Rect;
use ggez::conf::WindowMode;
use std::convert::TryInto;
use core::cmp::Ordering;
use embedded_graphics::{geometry::Point as Point3, prelude::*, primitives::*};
use ggez::graphics::MeshBuilder;

struct State {
    shapes: Vec<Shape>,
    vor_polys: Vec<Vec<Point>>,
    mesh: GameResult<ggez::graphics::Mesh>,
}

enum Shape {
    Circle(mint::Point2<f32>, f32),
    Rectangle(ggez::graphics::Rect),
}
 
impl State {
    /// Load images and create meshes.
    fn new(ctx: &mut ggez::Context) -> GameResult<State> {
        let mut shapes = Vec::new();
        let countries_tot = 36.0;
        let countries_row = 6.0;
        let countries_col = 6.0;
        let max_w = 1728.0;
        let max_h = 972.0;
        let incr_w = max_w/(countries_row+1.0);
        let incr_h = max_h/(countries_col+1.0);
        let mut vor_pts = Vec::new();
        shapes.push(Shape::Rectangle(ggez::graphics::Rect::new(
            192.0,
            108.0,
            1536.0,
            864.0,
        ))); 
        for x in 1..countries_row as i64 + 1 {
            for y in 1..countries_col as i64 + 1 {
                let xx = (x as f32*incr_w) + (192.0/2.0);
                let yy = (y as f32*incr_h) + (108.0/2.0);
                vor_pts.push(Point::new(xx as f64, yy as f64));
                //dots.push([x, y]);
                shapes.push(Shape::Circle(
                    mint::Point2{
                        x: xx,
                        y: yy,
                    },
                    6.0,
                ));
            } 
        }
     
        
        let vor_diagram = voronoi(vor_pts, DEFAULT_WINDOW_WIDTH as f64);
        let mut vor_polys = make_polygons(&vor_diagram);
        
        let width = 1920f32;
        let height = 1080f32;
        let window_mode = WindowMode {
            width,
            height,
            resizable: true,
            ..Default::default()
        };
        ggez::graphics::set_mode(ctx, window_mode);
        ggez::graphics::set_screen_coordinates(ctx, ggez::graphics::Rect{x: 0.0, y: 0.0, w: width, h: height}).unwrap();        
        

        let mesh = build_mesh(&mut vor_polys, ctx)?;
        ggez::graphics::draw(ctx, &mesh, ggez::graphics::DrawParam::default())?;
        ggez::graphics::present(ctx)?;
        let state = State { shapes: shapes, vor_polys: vor_polys, mesh: Ok(mesh) };
        
        // event::run(ctx, event_loop3, state);
        Ok(state)
    }
}
pub fn main() -> GameResult {

    //let (mut ctx, events_loop) = ggez::ContextBuilder::new("generative_art", "awesome_person")
    let c = conf::Conf::new();
    let (mut ctx, event_loop2) = ContextBuilder::new("generative_art", "awesome_person")
        .default_conf(c)
        .build()
        .unwrap();
    println!("{}", ggez::graphics::renderer_info(&ctx)?);
    let state = State::new(&mut ctx).unwrap();
    event::run(ctx, event_loop2, state)
}

impl ggez::event::EventHandler<GameError> for State {
    fn update(&mut self, _ctx: &mut ggez::Context) -> GameResult {
        Ok(())
    }
    fn draw(&mut self, ctx: &mut ggez::Context) -> GameResult {
        //let rect_s =  first(&self.shapes).unwrap()
        let mut rect_s = ggez::graphics::Rect::new(
            192.0,
            108.0,
            1536.0,
            864.0,
        );
        ggez::graphics::clear(ctx, ggez::graphics::Color::BLACK);
        for shape in &self.shapes {
            // Make the shape...
            let mesh = match shape {
                &Shape::Rectangle(rect) => {
                    ggez::graphics::Mesh::new_rectangle(ctx, ggez::graphics::DrawMode::fill(), rect, ggez::graphics::Color::WHITE)?
                }
                &Shape::Circle(origin, radius) => {
                    ggez::graphics::Mesh::new_circle(ctx, ggez::graphics::DrawMode::fill(), origin, radius, 0.1, ggez::graphics::Color::BLACK)?
                }
            };
            // ...and then draw it.
            ggez::graphics::draw(ctx, &mesh, ggez::graphics::DrawParam::default())?;
        }
        //ggez::graphics::draw(ctx, &self.mesh, ggez::graphics::DrawParam::default())?;
        
        Ok(())
    }

}
fn build_mesh(vor_polys: &mut Vec<Vec<Point>>, ctx: &mut ggez::Context) -> GameResult<ggez::graphics::Mesh> {
    let mb = &mut ggez::graphics::MeshBuilder::new();
    let colors = [ggez::graphics::Color::BLUE, ggez::graphics::Color::RED, ggez::graphics::Color::YELLOW, ggez::graphics::Color::GREEN];
    let mut mint = Vec::new();
    println!("poly length {}", vor_polys.len());
    for (i, poly) in vor_polys.iter().enumerate() {
        if poly.len() > 1 {
            for j in 0..poly.len()-1 {
                mint.push(
                    Vec2::new(poly[j].x.into_inner() as f32, poly[j].y.into_inner() as f32)
                );
                mint.push(
                    Vec2::new(poly[j+1].x.into_inner() as f32, poly[j+1].y.into_inner() as f32)
                );
            }
        }
        else {
            println!("IN!");
        }
    }
    mb.line(
        &mint,
        4.0,
        ggez::graphics::Color::BLUE,
    )?;
    mb.build(ctx)
}
fn first<T>(v: &Vec<T>) -> Option<&T> {
    v.first()
}
fn sort_clockwise(a: Point3, b: Point3, center: Point3) -> Ordering {
    let d_ax = a.x - center.x;
    let d_bx = b.x - center.x;

    let cmp_ax = d_ax.cmp(&0);
    let cmp_bx = d_bx.cmp(&0);

    match (cmp_ax, cmp_bx) {
        // d_ax >= 0 && d_bx < 0
        (Ordering::Greater, Ordering::Less) | (Ordering::Equal, Ordering::Less) => {
            Ordering::Greater
        }
        // d_ax < 0 && d_bx >= 0
        (Ordering::Less, Ordering::Greater) | (Ordering::Less, Ordering::Equal) => Ordering::Less,
        // d_ax == 0 && d_bx == 0
        (Ordering::Equal, Ordering::Equal) if a.y - center.y >= 0 || b.y - center.y >= 0 => {
            a.y.cmp(&b.y)
        }
        (Ordering::Equal, Ordering::Equal) => b.y.cmp(&a.y),
        _ => {
            // Compute the cross product of vectors (center -> a) x (center -> b)
            let det = (d_ax) * (b.y - center.y) - (d_bx) * (a.y - center.y);

            match det.cmp(&0) {
                Ordering::Less => Ordering::Greater,
                Ordering::Greater => Ordering::Less,
                Ordering::Equal => {
                    // Points a and b are on the same line from the center. Check which point is closer to
                    // the center.
                    let d1 = (d_ax) * (d_ax) + (a.y - center.y) * (a.y - center.y);
                    let d2 = (d_bx) * (d_bx) + (b.y - center.y) * (b.y - center.y);

                    d1.cmp(&d2)
                }
            }
        }
    }
}
fn demo<T, const N: usize>(v: Vec<T>) -> [T; N] {
    v.try_into()
        .unwrap_or_else(|v: Vec<T>| panic!("Expected a Vec of length {} but it was {}", N, v.len()))
}
fn random_point() -> [f64; 2] {
    [rand::thread_rng().gen_range(0., DEFAULT_WINDOW_HEIGHT as f64), rand::thread_rng().gen_range(0., DEFAULT_WINDOW_WIDTH as f64)]
}
 
fn random_color() -> [f32; 4] {
    [rand::random::<f32>(), rand::random::<f32>(), rand::random::<f32>(), 1.0]
}
 
fn random_voronoi(dots: &mut Vec<[f64;2]>, colors: &mut Vec<[f32;4]>, num: usize) {
    dots.clear();
    colors.clear();
 
    for _ in 0..num {
        dots.push(random_point());
        colors.push(random_color());
    }
}
```
 



<img width="1188" alt="voronoi_poly" src="https://user-images.githubusercontent.com/53097999/164544101-d565857b-d659-47fa-aba2-9bee8a592d9d.png">

This is not what I expected I expected nice polygons and more screen usage.

**Comment by PSteinhaus** [comment]
Ok, concerning "more screen usage" I can give you a tip. In this line you wrote:
```rust
ggez::graphics::set_screen_coordinates(ctx, ggez::graphics::Rect{x: 0.0, y: 0.0, w: width, h: height}).unwrap();
```
I assume you set width and height to 1080x1920 because that's the resolution you want to aim for? That's not what screen coordinates do though. They have nothing to do with resolution and everything with how the coordinates of the things you draw (such as you the position of your meshes and their vertices) are translated to actual positions inside your window.
To make your window cover the whole voronoi diagram and nothing but it, search for the smallest and biggest x and y values over all of its points, and then make a `Rect` out of that and give it to `set_screen_coordinates`.

As for "nice polygons" you'll have to be a bit more specific. What exactly are you expecting?
[As I mentioned in a previous comment](https://github.com/ggez/ggez/issues/1027#issuecomment-1101697105) your method of drawing the polygons creates open polygons, where the final line connecting the last and the first point is missing.

The other MUCH BIGGER PROBLEM is this:

> This won't do what you want. This will create ONE LINE, going over all the given points. That means it doesn't only include `point0 -> point1`, `point2 -> point3`, etc., BUT ALSO `point1 -> point2`, `point3 -> point4`, etc.
> 
> A better example for how to use `MeshBuilder` to achieve your goal would have probably been `imageview.rs` (really bad name, btw. should probably rename it to `crazylines` or something). There, a `MeshBuilder` is used to create a `Mesh` from many **non-consecutive lines**, artificially creating one _consecutive line_ (a bit of a waste really, but whatever). So to come back to your code, what you want to do is use `line` a bit like that, but more sensible:
> 
> ```
>         // ...
>         let mut mint = Vec::new();    // why "mint", btw?
>         for (i, poly) in self.vor_polys.iter().enumerate() {
>             if poly.len() > 1 {
>                 for i in 0..poly.len() {
>                     mint.push(
>                         Vec2::new(poly[i].x.into_inner() as f32, poly[i].y.into_inner() as f32)
>                     );
>                 }
>                 // then, if your polygon points don't wrap around to the first one (which I assume)
>                 // you'll have to close the polygon by drawing a line from end to start
>                 mint.push(
>                         Vec2::new(poly[0].x.into_inner() as f32, poly[0].y.into_inner() as f32)
>                 );
>             }
>             else {
>                 println!("IN!");
>             }
>             // this adds a line with multiple segments to the builder, which is independent from other lines before
>             mb.line(
>                 &mint,
>                 4.0,
>                 ggez::graphics::Color::BLUE,
>             )?;
>         }
>         let line_mesh = mb.build(ctx)?;    // CREATE the mesh (and bind it to a variable)
>         ggez::graphics::draw(ctx, &line_mesh, ggez::graphics::DrawParam::default())?;    // DRAW it
>         ggez::graphics::present(ctx)?;
>         Ok(())
>     }
> }
> ```

**Comment by Mergpijp** [comment]
Hey, to let you help me a bit I took the voronoi example from this [link](https://github.com/ctrlcctrlv/interactive-voronoi/blob/c9fff204c3efac28f16ad0f023524457d0d27d0a/src/main.rs#L133-L136) . I think I made a mistake by just drawing lines I could try to draw polygons instead; what do you think?  I dont want to cover the whole voronoi diagram just a rectangle inside but I am still doing it wrong yes you are right. Will change that.

**Comment by PSteinhaus** [comment]
> EDIT: I also made a repo to the [code](https://github.com/Mergpijp/risk_rust/blob/main/examples/voronoi.rs)

That's indeed helpful. From what I've seen applying the changes suggested in [this comment](https://github.com/ggez/ggez/issues/1027#issuecomment-1105788819) should probably solve most of your problems. If it doesn't or you still have questions, I'll clone it and give it a try.

**Comment by Mergpijp** [comment]
Hmm im still getting the polygons drawn in the lower left quarter of the screen:

```
        let mut min_x = 9999.0;
        let mut max_x = 0.0;
        let mut min_y = 9999.0;
        let mut max_y = 0.0;

        for (i, poly) in vor_polys.iter().enumerate()  {
            for j in 0..poly.len() {
                if (poly[j].x.into_inner() as f32) < min_x {
                    min_x = poly[j].x.into_inner() as f32
                }
                if (poly[j].x.into_inner() as f32) > max_x {
                    max_x = poly[j].x.into_inner() as f32
                }
                if (poly[j].y.into_inner() as f32) < min_y {
                    min_y = poly[j].y.into_inner() as f32
                }
                if (poly[j].y.into_inner() as f32) > max_y {
                    max_y = poly[j].y.into_inner() as f32
                }
                
            }
        }
        
        let width = 1920f32;
        let height = 1080f32;
        let window_mode = WindowMode {
            width,
            height,
            resizable: true,
            ..Default::default()
        };
        ggez::graphics::set_mode(ctx, window_mode);
        ggez::graphics::set_screen_coordinates(ctx, ggez::graphics::Rect{x: min_x, y: min_y, w: max_x, h: max_y}).unwrap();
```

**Comment by Mergpijp** [comment]
Ok good thing you spotted that but I am kind of lost how to correct this?

**Comment by PSteinhaus** [comment]
Take a look at [this PR](https://github.com/Mergpijp/risk_rust/pull/1).  : )

**Comment by Mergpijp** [comment]
Yes that is kind of you! I did not use the described workflow of ggez. Its just that it does not draw in side the box (rectangle) I defined.

**Comment by PSteinhaus** [comment]
This is what I get:
![Unbenannt](https://user-images.githubusercontent.com/40324631/170022555-58cf882b-89f2-45e4-89a8-4b0b0190564f.png)

Does this not match your expectations?
Your white rect and black circles are placed exactly where you specified, which is at `192.0, 108.0` with dimensions of `1536.0 x 864.0`.

I think one thing that might suprise you is that the circles are squashed. Thats because your voronoi-space is a square while your screen-space isn't. Using your voronoi-space as the coordinate system means that the aspect ratio of things will be off.

**Comment by nobbele** [comment]
closing this as stale
