### ISSUE TITLE
WGPU panics with Validation Error if the scissor rect is larger than window rect

### ISSUE THREAD

**Issue by gzhynko** [ggez/ggez#1033]
**Describe the bug**
When the window is resized to a size less than the size of the scissor rect, WGPU appears to panic:
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 165, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

'
```
This panic originates from [this check](https://github.com/gfx-rs/wgpu/blob/202d81a64a85f4587d0074ad3d792ad87a625bff/wgpu-core/src/command/render.rs#L1491) in WGPU code.

**To Reproduce**
Here's a modified version of the [`01_super_simple`](https://github.com/ggez/ggez/blob/devel/examples/01_super_simple.rs) example:
```Rust
//! The simplest possible example that does something.
#![allow(clippy::unnecessary_wraps)]

use ggez::{
	conf,
    event,
    graphics::{self, Color},
    Context, GameResult,
};
use glam::*;

struct MainState {
    pos_x: f32,
    circle: graphics::Mesh,
}

impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let circle = graphics::Mesh::new_circle(
            &ctx.gfx,
            graphics::DrawMode::fill(),
            vec2(0., 0.),
            100.0,
            2.0,
            Color::WHITE,
        )?;

        Ok(MainState { pos_x: 0.0, circle })
    }
}

impl event::EventHandler<ggez::GameError> for MainState {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        self.pos_x = self.pos_x % 800.0 + 1.0;
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        let mut canvas = graphics::Canvas::from_frame(
            &ctx.gfx,
            graphics::CanvasLoadOp::Clear([0.1, 0.2, 0.3, 1.0].into()),
        );
        
        // set the scissor rect's size to be less than window size
        // this is here to prevent the scissor rect from being resized to match window size, the panic still happens even without this line
        canvas.set_scissor_rect(ggez::graphics::Rect::new(0., 0., 400., 350.));

        canvas.draw(&self.circle, Vec2::new(self.pos_x, 380.0));

        canvas.finish(&mut ctx.gfx)?;

        Ok(())
    }
}

pub fn main() -> GameResult {
    // make sure the window can be resized
    let mut c = conf::Conf::new();
    c.window_mode.resizable = true;
    
    let cb = ggez::ContextBuilder::new("super_simple", "ggez").default_conf(c);
    let (mut ctx, event_loop) = cb.build()?;
    let state = MainState::new(&mut ctx)?;
    event::run(ctx, event_loop, state)
}
```
To reproduce simply resize the window to a size lower than the scissor rect size.

**Expected behavior**
Expected no panics when resizing the window.

**Hardware and Software:**
 - ggez version: current git devel branch
 - OS: Manjaro Linux x86_64
 - Graphics card: NVidia GTX 1060
 - Graphics card drivers: proprietary NVidia drivers (v. 510.68.02)

**Comment by gzhynko** [comment]
Related issues: Yatekii/imgui-wgpu-rs#77, iced-rs/iced#1111, gfx-rs/wgpu#1750

**Comment by jazzfool** [comment]
I'm unable to repro the panic on resize *without* `set_scissor_rect`. Regardless, I believe the intuitive behavior here is to clamp to image extents. In cases where a 0x0 scissor is set by the user, I think a panic is okay until WGPU removes that restriction (although, we could go as far as emulating a 0x0 scissor ourselves).

**Comment by PSteinhaus** [comment]
I agree that clamping to the image dimensions should be our response. Instead of panicing I'd just return an `Err` though.

**Comment by gzhynko** [comment]
Alright, yeah, I wasn't able to reproduce the panic without `set_scissor_rect` on another device, so there was probably something wrong on my end. In that case simply clamping the scissor rect before applying it should do the trick.
