### ISSUE TITLE
Cannot detect double key input

### ISSUE THREAD

**Issue by Sharmiko** [ggez/ggez#1036]
Is there a way to detect double key tap? Could not find anything in docs or examples to make it work.
`is_key_repeated` only detect if key is held for some time.
It would be great if there was better control over keyboard input. Making some api function public would be nice. Like `set_key` function implementation in `KeyboardContext` struct. Then  I would have ability to set some keys as "not pressed" and check again if it was tapped again.

I am using:
- ggez: 0.7
- OS: Manjaro Linux 21.2.6 Qonos

**Comment by PSteinhaus** [comment]
It's true, the repetition doesn't start immediately.
We could change this to start immediately in the following frame by adding some kind of function call to the event loop that just assumes previous keyboard inputs to be repeated. Then, later, when going through the actual events, this would be reverted to false, if the key was released.

I think there is no harm in changing `is_key_repeated` to be more strict like this. Its current main use is distinguishing whether the system triggered a repetition event of the key, when a keyboard event is called. This would still work.

Allowing keys to be synthetically set is probably a good idea too. On that I'd like to hear @nobbele's opinion first as well though.

**Comment by PSteinhaus** [comment]
Oh, and another thing: For a quick workaround you can also just poll `is_key_pressed` every frame and keep notes on key repetition yourself. This is a workaround though and we shouldn't force people to rely on it.

**Comment by PSteinhaus** [comment]
Oh and also also, we have `is_key_just_pressed`. With that you should be able to directly detect double key tap reliably, as it only returns true, if the key has just been pressed this frame, but not yet in the frame before.

**Comment by Sharmiko** [comment]
> 
Hello, thanks for reply and tips. I could not find `is_key_just_pressed`, I am using latest version of `ggez`. Maybe it exists in older versions?

**Comment by PSteinhaus** [comment]
Ah, right, that's why I didn't find it at first. It only exists in `devel` currently.

And `devel` (aka soon 0.8.0-rc0) holds massive changes compared to 0.7, as it includes the switch to wgpu.

**Comment by PSteinhaus** [comment]
> EDIT: While doing so we should probably also replace the `last_pressed`, `current_pressed` fields in the keyboard context by something like `repeated_keys_set`, analogous to `pressed_keys_set`. This would allow multiple keys to be recognized as repeated.

I just realized that this is nonsense. Key repetition is a global thing and tapping a new key resets the delay timer. I don't think any OS supports repeating keys and tapping in other keys in non-repeating mode at the same time.

**Comment by Sharmiko** [comment]
I looked at early 0.8.0-rc0 release docs. They are quite interesting and cool changes. I will close this issue now, because upcoming stable version 0.8.0 will solve keyboard issue.
