### ISSUE TITLE
Support for compression in Zip-based Filesystems

### ISSUE THREAD

**Issue by expeditiousRubyist** [ggez/ggez#1039]
While testing out this library, I have discovered an issue with the `add_zipfile_bytes` function when used with a zip file created with the standard Unix zip utility. This issue was a panic in initializing the ContextBuilder, along the lines of:
```
thread 'main' panicked at 'Should never happen!: UnsupportedArchive("Compression method not supported")'
```
Upon some investigation with the `zipinfo -v` command, there are no issues with the file, and the compression method is `deflated`, a common compression algorithm that should be supported by any library dealing with zips. I then did some investigation into the zip crate that is used by ggez. Indeed, it does support the deflate compression method, provided that this feature is included. It is actually in the default features, but in the Cargo.toml file for ggez, we have the line
```toml
zip = { version = "0.5", default-features = false }
```
With this set of features, the zip crate will only support the compression method "stored"... which is no compression at all. This is contradictory to the expectations one might have when using any function dealing with zip files. Accordingly, I would like to request one of the following two changes be made:
1. Support standard compression algorithms by removing the `default-features = false` line from the Cargo.toml file
2. If it is not desirable to support compression, then make it abundantly clear in all documentation that involves interacting with zip files, that all zip files must be uncompressed.

**Comment by nobbele** [comment]
Thank you for pointing this out. I'm not sure why default features are disabled by default right now but we could probably add a feature to ggez to enable zip's feature at least (feel free to make a PR!)

**Comment by expeditiousRubyist** [comment]
> It seems the default features were disabled [way back](https://github.com/ggez/ggez/pull/307), to avoid C/C++ dependencies that came with them. But it seems that `flate2` as used by the default `deflate` feature in zip doesn't use these at all, so we should just be able to enable it by default (for example by adding "zip/deflate" it into our default features). At that point we probably want to look into the other features of zip and perhaps expose them as well.

I did a little bit of research on the current version (0.6.2) of the zip crate, the compression algorithms it supports, and which dependencies those use.
* Deflate can use a Rust backend or a C backend using zlib. The default is to use the Rust backend. This is when you would set `default-features = ["deflate"]`. The C backend (which y'all would prefer not depending on) uses `"deflate-zlib"` instead of `"deflate"`. There is also a `"deflate-miniz"` option, but this appears to just use the Rust backend when you trace it back to the Cargo.toml file of the flate2 crate.
* Bzip2 depends upon a `bzip2-sys` crate, which uses C.
* Zstd depends upon a `zstd-safe` module, which uses bindgen and C code.

Accordingly, the one feature you could use that avoids any C dependencies would be deflate. This alone would still present a significant improvement in usability, since it is the default compression mechanism for most zip programs.
