### ISSUE TITLE
0.8.0-rc0 Notes

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1042]
Add more helpers to `TextLayout`

**Comment by nobbele** [comment]
I see, then maybe it should be wrapped in RefCell or similar. Semantically, getting the dimension doesn't modify anything even if it technically does.

**Comment by PSteinhaus** [comment]
> should we export glam too? to fix version mismatches

I'm not sure. I think properly pointing out which version of mint to use and how might be better. We can add an explanation as to what to do to get glam running in a project using ggez, if one wants to, but I don't know whether we should re-export it.

What would be possible downsides? If they're very minor I guess re-exporting glam would make using ggez more comfortable.

**Comment by nobbele** [comment]
As most issues have been fixed here, I think it's better to keep the remaining issues separate
