### ISSUE TITLE
More fine-tuned present mode (vsync)

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1044]
[PresentMode](https://docs.rs/wgpu/latest/wgpu/enum.PresentMode.html) supports 3 modes but currently ggez's vsync only switches between Mailbox and Fifo. 
Should we have add a config to switch between Mailbox and Immediate for non-vsync configurations?

**Comment by PSteinhaus** [comment]
Perhaps. The more power to the user the better, but I think I'd only want to add it if we find a good example on when you'd want to use either one, to be able to write a helpful documentation on that option.

**Comment by nobbele** [comment]
I'm not really sure what the use-case or the difference is, need to investigate.

**Comment by nobbele** [comment]
not very useful now that we have auto
