### ISSUE TITLE
Clarify sampler usage

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1046]
Adding a comment like "use this in pixel art games or the game will look blurred" to examples and maybe in `set_sampler` too

**Comment by PSteinhaus** [comment]
We actually kindof already have one of them [in the animation example](https://github.com/ggez/ggez/blob/f6c34de7a14859bef05d02aef8a2e12d2b6fc19e/examples/animation.rs#L271). But I agree that we could add such a line to the docs of `set_sampler`. Though [`Sampler::nearest_clamp`](https://docs.rs/ggez/0.8.0-rc0/ggez/graphics/struct.Sampler.html#method.nearest_clamp) already points at pixel art.

**Comment by Vixeliz** [comment]
This appears to be fixed I'm gonna go ahead and close it.
