### ISSUE TITLE
Automatic batching (with limits)

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1047]
Some system to automatically batch simple draw calls should be possible to some extent. Investigate whether it is worth the overhead.

**Comment by nobbele** [comment]
Maybe this isn't ggez's job, could easily be done by a separate crate using InstanceArray's

**Comment by PSteinhaus** [comment]
I agree. I always liked ggez for being not that `smart` and doing things the simple way that's most easily understood, giving us more complex stuff like `InstanceArray` for when we actually want to use them.
