### ISSUE TITLE
Circles don't have the correct number of segments

### ISSUE THREAD

**Issue by 0tt** [ggez/ggez#105]
![image](https://user-images.githubusercontent.com/5253130/28252924-99fdb0fe-6a51-11e7-91ae-f3fa21db14dc.png)
![image](https://user-images.githubusercontent.com/5253130/28252926-a8b6169a-6a51-11e7-9409-0a7858413b4a.png)
This circle only has 3 sides when it should have 4.

**Comment by 0tt** [comment]
Alternative: update the docs to say "number of points" instead of "number of segments"

**Comment by icefoxen** [comment]
Thank you, I'll check this out!

**Comment by icefoxen** [comment]
Might want to do the lyon update (#116) before tackling this, because that will need a fair bit of rewriting anyway.

**Comment by icefoxen** [comment]
This has been made more or less obsolete by the Lyon update.  Since Lyon now doesn't let you say "I want X segments", you instead say "I want my tolerances within X of perfection", which is less convenient for constructing shapes but better for actually drawing nice stuff.
