### ISSUE TITLE
Drawn image size is different between GGEZ 0.7.0 compared to 0.8.0-rc0 when using a src rectangle

### ISSUE THREAD

**Issue by RossBrunton** [ggez/ggez#1052]
**Describe the bug**
I have this image:
![Test](https://user-images.githubusercontent.com/662364/175829893-9bbb39de-1596-4f0c-bcda-a0fcb1294334.png)
Which consists of four tiles, and I want to only draw the top-left one. So I set the DrawParam's "src" rectangle to (0, 0, 0.5, 0.5), and then draw it to the screen.

On GGEZ 0.7.0, this gives this:
![0 7 0](https://user-images.githubusercontent.com/662364/175830001-3b6e883e-db94-4101-86a3-f2cea7c176bc.png)

While on GGEZ 0.8.0 gives this:
![0 8 0](https://user-images.githubusercontent.com/662364/175829958-5c4a0455-4c7d-4061-a5bf-585054696fd1.png)

(The background is a red 48x48 square).

It seems that when drawing the image, the "original" size is used now, rather than new sliced size.

**To Reproduce**
```rust
    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        let mut canvas = graphics::Canvas::from_frame(
            ctx,
            graphics::CanvasLoadOp::Clear([0.1, 0.2, 0.3, 1.0].into()),
        );

        let blank = graphics::Image::from_solid(&mut ctx.gfx, 48, Color::RED);
        canvas.draw(&blank, graphics::DrawParam::new());

        let image1 = graphics::Image::from_path(ctx, "/Test.png", true)?;
        canvas.draw(&image1, graphics::DrawParam::new().src(Rect::new(0.0, 0.0, 0.5, 0.5)));

        canvas.finish(ctx)?;

        Ok(())
    }
```

This is the version in 0.8.0 draw function that created these.

**Expected behavior**
I expected the behaviour to be consistent with 0.7.0 and draw the pixels 1:1 because the scale is 1.0, although I don't know enough about graphics hardware to say if this is correct or not.

If this is the new intended behaviour, might be worth adding it to the patch notes as well as instructions to mitigate it. I know it can be worked around using:
```rust
param.src(rect).image_scale(false).scale([scale * w, scale * h])
```
But that doesn't seem intuitive or discoverable to me.

**Screenshots or pasted code**
```rust
use ggez::{
    event,
    graphics::{self, Color},
    Context, GameResult,
};
use glam::*;
use std::{env, path};
use ggez::graphics::Rect;

struct MainState {
}

impl MainState {
    /// Load images and create meshes.
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let s = MainState {
        };

        Ok(s)
    }
}

impl event::EventHandler<ggez::GameError> for MainState {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        /*let mut canvas = graphics::Canvas::from_frame(
            ctx,
            graphics::CanvasLoadOp::Clear([0.1, 0.2, 0.3, 1.0].into()),
        );*/
        graphics::clear(ctx, Color::BLACK);

        let blank = graphics::Image::solid(ctx, 48, Color::RED)?;
        //canvas.draw(&blank, graphics::DrawParam::new());
        graphics::draw(ctx, &blank, graphics::DrawParam::new());

        // Draw an image.
        let image1 = graphics::Image::new(ctx, "/Test.png")?;
        //canvas.draw(&image1, graphics::DrawParam::new().src(Rect::new(0.0, 0.0, 0.5, 0.5)));
        graphics::draw(ctx, &image1, graphics::DrawParam::new().src(Rect::new(0.0, 0.0, 0.5, 0.5)));

        // Finished drawing, show it all on the screen!
        //canvas.finish(ctx)?;
        graphics::present(ctx);

        Ok(())
    }
}

pub fn main() -> GameResult {
    let resource_dir = if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        let mut path = path::PathBuf::from(manifest_dir);
        path.push("resources");
        path
    } else {
        path::PathBuf::from("./resources")
    };

    let cb = ggez::ContextBuilder::new("drawing", "ggez").add_resource_path(resource_dir);

    let (mut ctx, events_loop) = cb.build()?;

    let state = MainState::new(&mut ctx).unwrap();
    event::run(ctx, events_loop, state)
}
```
Full file I used for testing (this is the 0.7.0, with 0.8.0 stuff commented out).

**Hardware and Software:**
 - ggez version: 0.7.0, 0.8.0-rc0, aa035d8e9 still has this issue.
 - OS: Linux Mint 20
 - Graphics card: Nvidia GTX 970
 - Graphics card drivers: Proprietry Nvidia driver 470.129

**Comment by PSteinhaus** [comment]
Thanks for opening this. I almost forgot about it again.

We briefly discussed this question in the big wgpu-PR, where I laid down [my opinion at the time](https://github.com/ggez/ggez/pull/1020#issuecomment-1100002997).

But we've recently been discussing this again and I think reverting the behavior back to how it is in ggez 0.7 might be the better choice after all. Sure, it's a bit inconsistent on the technical level, but it just makes more sense intuitively.

When you draw an image, scaled to it's size in pixels, then it makes absolutely no sense to a user to suddenly see only a portion of the texture stretched to the size of the original image for no apparent reason, that image being cropped after all (this effect should be even more puzzling when using a src parameter like `[0.5, 1.0]`).

I'd love to hear your opinion on this.

I agree in any case that pointing out this change in the changelog will be a very necessary step, should we choose to keep things this way.

**Comment by RossBrunton** [comment]
I don't really have much experience with graphics libraries, but I think the way 0.7 does it makes sense. I can't think of many circumstances where you're taking a slice of an image yet want it to be scaled to the full size of the image.

If there's a technical reason or de-facto standard to the way 0.8.0 is doing it, I'd be fine with that. However, I'd like to see how to scale it correctly mentioned in the documentation for Image. If the way I'm doing it is the correct way of doing it, it doesn't feel intuitive, and makes the meaning of "scale" confusing.

**Comment by Sharmiko** [comment]
I agree with @RossBrunton, the way 0.7 does it is better in my opinion. I was experimenting with 0.8.0-rc0 too and found this behavior puzzling.
