### ISSUE TITLE
Maybe move drawables constructor to GraphicsContext?

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1053]
`Image::new(&(&ctx.gfx, &ctx.fs), filename", false)` -> `ctx.gfx.new_image(&ctx.fs, filename, false)`
`Canvas::from_frame(ctx, Color::WHITE)` -> `ctx.gfx.new_canvas_from_frame(Color::WHITE)`

If we did this, I don't think you'd ever need to do the ugly tuple borrow (gets rid of `HasTwo`). Also even more similar to how löve2d looks `love.graphics.newImage(filename, settings)`

**Comment by PSteinhaus** [comment]
I think this is a bit too much.
Yes, it would get rid of `HasTwo` (if we also did something similar to the audio context I think), but as a user I'd be a bit annoyed to search for the constructor to a thing and find it somewhere outside. Discoverability is more important than ergonomics here, imo.
