### ISSUE TITLE
InstanceArray doesn't draw all instances.

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1058]
**Describe the bug**
When I pass in 4 DrawParam's, it draws the first 2. If I only pass the last 2, it only draws the 3rd one.

I assume the data isn't getting passed to WGPU properly.

**Hardware and Software:**
 - ggez version: [d6d41e4](https://github.com/ggez/ggez/commit/d6d41e4a2f308b995d3bdbc71b539e5ae1cbb7e7)

**Comment by PSteinhaus** [comment]
I have a feeling that this line is at fault:
https://github.com/ggez/ggez/blob/a1aeb4e9a0d092fde7ab398159b37679bff76ae6/src/graphics/instance.rs#L75

Isn't there a factor 4 missing?

**Comment by PSteinhaus** [comment]
> `std::mem::size_of::<u32>()` == 4 already?

Nevermind, missed that. We should change the latter case to use `std::mem::size_of::<u32>()` too instead of a literal 4.

**Comment by nobbele** [comment]
can't reproduce it anymore
