### ISSUE TITLE
Setting image_scale(false) DrawParam disappears image, ggez 0.8.0-rc0

### ISSUE THREAD

**Issue by Sharmiko** [ggez/ggez#1062]
**Describe the bug**
This is follow up to  [1052](https://github.com/ggez/ggez/issues/1052) issue. When we try to draw partial image we see that it is scaled to fit the image dimensions. One to disable this behavior as suggested is to set `image_scale(false)`. But when I run the program image won't be displayed.

**To Reproduce**
```rust
use std::env;
use std::path::{self};

use ggez::{Context, ContextBuilder, GameResult};
use ggez::graphics::{self, *};
use ggez::event::{self, EventHandler};


fn main() {
    let mut cb = ContextBuilder::new("Rust 2d game", "Giorgi Sharmiashvili")
        .window_mode(ggez::conf::WindowMode::default()); 

    if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        let mut path = path::PathBuf::from(manifest_dir);
        path.push("resources");
        cb = cb.add_resource_path(path);
    }
    
    let (mut ctx, event_loop) = cb.build().expect("aieee, could not create ggez context!");

    let my_game = MyGame::new(&mut ctx);

    event::run(ctx, event_loop, my_game);
}

struct MyGame {

}

impl MyGame {
    pub fn new(_ctx: &mut Context) -> MyGame {

        MyGame {
        }
    }
}

impl EventHandler for MyGame {
    fn update(&mut self, _ctx: &mut Context) -> GameResult<()> {

        Ok(())
    }

    fn draw(&mut self, _ctx: &mut Context) -> GameResult<()> {
        let mut canvas = graphics::Canvas::from_frame(_ctx, graphics::Color::WHITE);
        canvas.set_sampler(graphics::Sampler::nearest_clamp());

        let image = graphics::Image::from_path(_ctx, "/chars/cyborg/Cyborg_idle.png", true).unwrap();
        
        let (w, h) = _ctx.gfx.drawable_size();
        let params = graphics::DrawParam::default()
            .src(graphics::Rect{
                x: 0.,
                y: 0.,
                w: 0.5,
                h: 1.
            })
            .dest([w / 2f32, h / 2f32])
            .image_scale(false);  // commenting this lines draws image

        canvas.draw(&image, params);

        canvas.finish(_ctx)
    }
}
```

**Expected behavior**
I expected default scaling behavior to be disabled.

**Hardware and Software:**
 - ggez version: 0.8.0-rc0
 - OS: Manjaro Linux 21.3.1 Ruah
 - Graphics card:  NVidia RTX 3060
 - Graphics card drivers: Vendor provided driver, Driver Version: 515.48.07

**Comment by PSteinhaus** [comment]
The problem is that you're now asking ggez to draw a quad that's 0.5 x 1 pixels large, which may result in nothing or at most 1 pixel being rendered.

Setting `image_scale` to `false` means that you no longer want the surface you draw (a simple quad) to be internally scaled to the size of the image in pixels.
Honestly, I'm not really sure if I want to keep this field, or remove it, as one can achieve the same effect of `image_scale = false` with `.scale([1/w, 1/h])`, or by just drawing a `Mesh` created from `Rect::one()` with the image as specified texture.

**Comment by Sharmiko** [comment]
Ah, after your feedback and few experiments. I got what I was looking for. 
So, generally setting `image_scale` to false and multiplying image width by width from `src` and scale factor gives me same result as in 0.7.0.
In my case, `src` width is 0.5. So `image.width() as f32 * 0.5 * MY_SCALE_FACTOR.` setting this as a scale factor works.
