### ISSUE TITLE
README's Discord "Rust Gamedev server" link seems to be outdated/broken

### ISSUE THREAD

**Issue by 64kramsystem** [ggez/ggez#1063]
I think that the "Rust Gamedev server" link in the README, is outdated/broken.

The link is: https://discord.gg/yNtPTb2.

Whenever I click on it, it (ultimately) leads to a channel called "rules-n-lobby", which seems not to exist anymore; I get this:

![image](https://user-images.githubusercontent.com/1595356/177618841-8f3d8063-3671-4b8a-a75e-43f87e0b3247.png)

I guess the link should be updated to `#rules-n-information`.

**Comment by PSteinhaus** [comment]
Well, it's still the official invite link to the gamedev server.
I mentioned it on the server and the response was:

> This channel actually does exist, it just gets disabled once you verify you're not a bot.

**Comment by 64kramsystem** [comment]
Thanks for checking! :smile:
