### ISSUE TITLE
Several problems with fullscreen handling

### ISSUE THREAD

**Issue by 64kramsystem** [ggez/ggez#1066]
**Describe the bug**

I'm having several problems with fullscreen handling. I'm not sure whether I'm using the APIs the intended way, but I couldn't find clear indications about what do. If any of the problem mentioned is a misinterpretation of mine, I'm ok to be redirected to the relevant documentation :smile: 

I'm adding each of the problems in a section at the bottom.

**Hardware and Software:**

ggez version: 0.7.0
OS: Linux (Ubuntu 20.04)
Graphics card: Should be (not 100% sure, though) UHD Graphics 620 (Whiskey Lake)
Graphics card drivers: Open source

## Problem 1: `FullscreenType::Desktop` drawable size is less than expected

I'm trying to find the drawable size of the screen, in `FullscreenType::Desktop` mode + borderless, however, I don't get the full screen size; it seems that borderless has no effect. Snippet:

```rs
    let mut context_builder = ggez::ContextBuilder::new(GAME_ID, AUTHOR)
        .window_setup(ggez::conf::WindowSetup::default().title(WINDOW_TITLE))
        .window_mode(
            ggez::conf::WindowMode::default()
                .borderless(true)
                .fullscreen_type(ggez::conf::FullscreenType::Desktop),
        );
    let (mut context, event_loop) = context_builder.build()?;

    let (screen_width, screen_height) = ggez::graphics::drawable_size(context);
```

The last statement returns 1920x1052, while my screen is 1920x1080.

## Problem 2: drawable size is either not set, or not returned correctly

Based on my understanding of the documentaiton, drawable size is the physical screen size, valid only on true fullscreen. This matches my experience; if I set an invalid value, the library panics.

However, after I set the drawable size, the API `ggez::graphics::drawable_size`, still returns the pre-change size. Snippet:

```rs
    let mut context_builder = ggez::ContextBuilder::new(GAME_ID, AUTHOR)
        .window_setup(ggez::conf::WindowSetup::default().title(WINDOW_TITLE))
        .window_mode(
            ggez::conf::WindowMode::default().fullscreen_type(ggez::conf::FullscreenType::True),
        );
    let (mut context, event_loop) = context_builder.build()?;

    ggez::graphics::set_drawable_size(context, 1920., 1080.)?;
    println!("DS: {:?}", ggez::graphics::drawable_size(context));
```

The last statement prints `DS: (800.0, 600.0)`.

## Problem 3: display corruption

Ignoring the issues above, when I try to actually display the game fullscreen, the screen is corrupted (the viewport is displayed multiple times, in different sizes and locations)

This is the snippet:

```rs
    let mut context_builder = ggez::ContextBuilder::new(GAME_ID, AUTHOR)
        .window_setup(ggez::conf::WindowSetup::default().title(WINDOW_TITLE))
        .window_mode(
            ggez::conf::WindowMode::default().fullscreen_type(ggez::conf::FullscreenType::True),
        );

    let (mut context, event_loop) = context_builder.build()?;

    ggez::graphics::set_drawable_size(context, 1920., 1080.)?;

    ggez::graphics::set_screen_coordinates(
        context,
        Rect::new(
            -60.,
            -0.,
            1800.,
            1080.,
        ),
    )
```

The values come from some calculations that I have omitted here; they just adjust the proportions to the game area.

In order to reproduce this:

```sh
git clone git@github.com:64kramsystem/rust-game-ports
cd rust-game-ports
git checkout fullscreen_true_attempt
cd boing-ggez
cargo run
```

The file with the screen setup logic is in `main.rs`.

Sample corruption: ![corruption](https://user-images.githubusercontent.com/1595356/179219123-0e1f93ae-7038-4d25-831c-8f7a0881891e.png)

## Follow-up

I've done other attempts, and there may be other problems, but at this stage I'm extremely confused, so if the points above are clear, I'll know how to tackle them.

**Comment by PSteinhaus** [comment]
Ok, I'll try to reply to your problems, though I sadly can't reproduce them on my Windows-Nvidia system.

You say you're running custom open source drivers on your graphics chip? That sounds... wild. Could you elaborate a tiny bit on that? ^^

# Problem 1

Do you not get the full screen size in terms of actual (borderless) window size, or are the values returned incorrect?
On my system borderless fullscreen seems to work fine, with correct values.
I'd guess that this is a winit bug, perhaps.

# Problem 2

Question: Does the resolution actually get set to what you enter, or does it stay on 800x600 ?
If it actually changes to it, then I'm a bit confused, as `drawable_size` doesn't do anything more than just return the physical inner size of the window in pixels.
Again I'd refer to winit, as it might be a winit bug showing through (or us using it in an invalid way, who knows).

# Problem 3

This I sadly cannot reproduce as I can't get your repo to run. There's no cargo file on the top level and if I go into `ggez-boing` and `run cargo` there I get errors about missing resources and also missing config.

**Comment by 64kramsystem** [comment]
Hello! Thanks for taking the time.

> You say you're running custom open source drivers on your graphics chip? That sounds... wild. Could you elaborate a tiny bit on that? ^^

They're standard, actually (not sure if I gave the impression that they're custom :grimacing:). On Linux, Intel drivers are open source; AMD drivers also (but with an additional, optional, [closed-source one](https://wiki.archlinux.org/title/AMDGPU_PRO)); Nvidia generally closed source, as the open source version sadly doesn't work well.

> ## Problem 1
> 
> Do you not get the full screen size in terms of actual (borderless) window size, or are the values returned incorrect? On my system borderless fullscreen seems to work fine, with correct values. I'd guess that this is a winit bug, perhaps.

OK, thanks! My expectation is that, on a 1920x1080 screen, in `FullscreenType::Desktop`+borderless fullscreen mode, I'd get the full resolution, since there is no surrounding window.

> ## Problem 2
> 
> Question: Does the resolution actually get set to what you enter, or does it stay on 800x600 ? If it actually changes to it, then I'm a bit confused, as `drawable_size` doesn't do anything more than just return the physical inner size of the window in pixels. Again I'd refer to winit, as it might be a winit bug showing through (or us using it in an invalid way, who knows).

I'll check this, it's a very good point. I stopped investigating this, but it's important to find out the exact behavior.

> ## Problem 3
> 
> This I sadly cannot reproduce as I can't get your repo to run. There's no cargo file on the top level and if I go into `ggez-boing` and `run cargo` there I get errors about missing resources and also missing config.

Sorry for that. Beside the missing `cd boing-ggez`, I actually keep forgetting the existence of the - ahem - reference gaming O/S :grimacing: (and hardcode paths with slashes... :facepalm:).

Anyway, you actually gave me the good idea of trying in a Windows VM. Again, I think it's important to find out the exact behavior.

I'll post the updates of points 2. and 3. here (before deciding how to proceed), so the problems are documented :smiley:.

**Comment by 64kramsystem** [comment]
Hello!

Ok, well, the drawable size functionalities seem to be completely bonkers on my system.

In this moment, if I do the sequence:

```rs
foo.fullscreen_type(ggez::conf::FullscreenType::True);
ggez::graphics::set_drawable_size(context, 1920., 1080.)?;
println!("{:?}", ggez::graphics::drawable_size(context));
```

the screen resolution is set to something around 800x600 (I can see this because I've replace the background with a 1080p image, and only a fraction is displayed), and the printed value is indeed 800x600.

I've done other attempts and I get very weird behavior (e.g. no switch to fullscreen).

Given the above, I'm not investigating problems 1. and 2. separately, since there's something more fundamentally broken. Hard to say at which level, though.

Regarding problem 3, I've actually tested on a VM (I've made the resource paths code compatible with Windows nonetheless), and still get similar corruption.

I was hoping for a bug in my code :smile:. While this is certainly possible, the background drawing code is extremely simple:

```rs
// menu images
graphics::draw(
    context,
    &self.menu_images[self.num_players - 1],
    graphics::DrawParam::new(),
)?;

// table image
self.table_image.draw(context, DrawParam::new())?;
```

so if the bug is the game implementation level (rather than at library level), it must be (relatively) subtle.

Damn! I was hoping for a smooth experience with at least one library... :grimacing:

**Comment by PSteinhaus** [comment]
Ok, if the behavior is non-deterministic I think it's highly likely that it's a winit/driver bug.
I've seen through the code and all we do to change the fullscreen mode to exclusive mode is going through the supported modes returned by the monitor and selecting the one with the size that was asked for (if there is one), calling `Window::set_fullscreen(Some(winit::window::Fullscreen::Exclusive(v_mode)))` on our winit window with that v_mode. So if winit _thinks_ the v_mode has the correct size, but setting it doesn't lead to that resolution, as it seems to me now, I'd say this variant of your problem must be a winit bug, or one on an even deeper level.

The reason why you might only get this bug here could be that exclusive/video mode fullscreen is not how fullscreen is usually done nowadays an many libraries don't provide it I'd guess. (I remember being asked why I added it on Discord and my best answer was something like "because I could" and "why not give that option", well...)

**Comment by PSteinhaus** [comment]
I now also managed to get your branch `fullscreen_windowed_attempt` to run. The symbolic link (or whatever it is) that you placed as the resources directory doesn't work on my system, so I had to replace it with a copy of the actual resources (or perhaps a symbolic link created through Windows could have worked as well, didn't try).

What I get is this:
![with](https://user-images.githubusercontent.com/40324631/180594681-c05345f7-d78b-4324-8ea9-2626b1a95a65.png)

without `configure_window_and_viewport` I get this:
![without](https://user-images.githubusercontent.com/40324631/180594690-7c421566-e631-4012-99bc-cae56a90436a.png)

**Comment by 64kramsystem** [comment]
> Ok, if the behavior is non-deterministic I think it's highly likely that it's a winit/driver bug. I've seen through the code

Thanks for that! I'll open a bug in Winit.

Just for general information, there's [another Winit bug](https://github.com/rust-windowing/winit/issues/2306) that may affect game engines, including ggez.

> (I remember being asked why I added it on Discord and my best answer was something like "because I could" and "why not give that option", well...)

No good deed goes unpunished 😂

> I now also managed to get your branch fullscreen_windowed_attempt to run. The symbolic link (or whatever it is)

AAARGH! I've pushed the fix before posting my previous reply, but forgot to advertise it. Sorry, and thanks for the testing 🙇🙇

I had problems also with the viewport, which I don't know if they're related or not. I'll wait for a response/fix from Winit, before digging into this!

**Comment by 64kramsystem** [comment]
ok, well, it seems that Winit fullscreen is, uh, known to be "quite" buggy: 

- https://github.com/rust-windowing/winit/issues/2087
- https://github.com/rust-windowing/winit/issues/2081

The first may or may not be one of the problems I've reported in this issue, but given the bugginess of the functionality, at this stage it doesn't matter much.

Now, the big question - assuming that the API I've used are unusable due to Winit, is there any other way I can get a working fullscreen and logical resolution setting, through ggez?

**Comment by PSteinhaus** [comment]
I believe it might not be possible.
You can access the raw winit [`Window`](https://docs.rs/winit/0.25.0/winit/window/struct.Window.html), but I don't really believe that any other kind of input to it's functionality will fix this.

One idea might be to create a borderless window (but not in fullscreen as that seems to be buggy) and then set the window size and position so that you effectively create a fullscreen window. But this approach would probably not be portable between OSes, if it works out at all...

**Comment by 64kramsystem** [comment]
> I believe it might not be possible. You can access the raw winit [`Window`](https://docs.rs/winit/0.25.0/winit/window/struct.Window.html), but I don't really believe that any other kind of input to it's functionality will fix this.
> 
> One idea might be to create a borderless window (but not in fullscreen as that seems to be buggy) and then set the window size and position so that you effectively create a fullscreen window. But this approach would probably not be portable between OSes, if it works out at all...

I see. Thanks for your work :smile: This issue can be closed on my side.

It's... interesting that, since 3 of the 4 major Rust engines (the other two being Fyrox and I think Bevy) are also based on Winit, right now they can hardly work fullscreen on Linux/X11 :exploding_head:.

**Comment by PSteinhaus** [comment]
That’s a good point actually. Does borderless windowed fullscreen work for you in any of these other engines?

If so the error should actually be on our side and we might be able to fix it by orienting ourselves on them.

**Comment by 64kramsystem** [comment]
> That’s a good point actually. Does borderless windowed fullscreen work for you in any of these other engines?
> 
> If so the error should actually be on our side and we might be able to fix it by orienting ourselves on them.

I'll try. In that project (rust game ports), Bevy is used only for ECS, so it can't be directly used (there are other projects, of course). But the Fyrox game ("soccer") is 100% Fyrox, so it can be tried. I'll post the result here, although it will take a bit.

**Comment by 64kramsystem** [comment]
It seems that this has been fixed with the latest ggez version - see investigation branch [here](https://github.com/64kramsystem/rust-game-ports-dev/blob/investigate_ggez_fullscreen/boing-ggez/src/main.rs).

Now, this is a tricky problem to isolate, because ggez v0.8 has a different logic - for this reason, I can't say (without knowledge of the underlying code) if:

- there was a bug with ggez, and a similar one in fyrox
- there is a bug in winit, but the new ggez logic doesn't trigger it

I need to verify it with a full port (the investigation was on a minimal test case), but I'm optimist.

Is there any chance for a ggez release which includes the fix for [this regression](https://github.com/ggez/ggez/issues/1154)? If I complete the game upgrade, referring to ggez development version would be undesirable.

**Comment by 64kramsystem** [comment]
Ok, well, I've ported the game to v0.8-devel, and it works fine. can be closed for me.

For reference, the upgrade PR is https://github.com/ggez/ggez/issues/1066.

**Comment by Vixeliz** [comment]
This appears to be fixed feel free to correct me if not and i'll reopen.

**Comment by 64kramsystem** [comment]
> This appears to be fixed feel free to correct me if not and i'll reopen.

Thanks! The fullscreen issue is now solved (there's a speed issue now, but currently, I haven't pinpointed the cause).
