### ISSUE TITLE
TextLayout and TextAlign

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1068]
to center some text you currently have to type
```rs
TextLayout::Wrap {
    h_align: TextAlign::Middle,
    v_align: TextAlign::Middle,
}
```
Adding some constructors such as `TextLayout::wrap_center()` would make it significantly easier to write

**Comment by devmeat** [comment]
Added 'wrap_center'.
Before I create a PR, I can also rename:

- tl_single_line -> single_line_tl
- tl_wrap -> wrap_tl

Just for consistency?

**Comment by nobbele** [comment]
Making it center_wrap is also an option, not sure which to go with. Keeping the existing ones would break less code again

**Comment by PSteinhaus** [comment]
I think it doesn’t matter that much. Let’s not break any code and just go with `center_wrap`.
