### ISSUE TITLE
RenderError("failed to find suitable graphics adapter")

### ISSUE THREAD

**Issue by Gers2017** [ggez/ggez#1070]
Hi, sorry if this is a dumb question, I tried to play the demos like this:
```sh
git clone https://github.com/ggez/ggez.git
cd ggez
cargo run --example 05_astroblasto
```
But I got this error
![image](https://user-images.githubusercontent.com/49139988/179340341-ce3762de-7a6c-4d5f-9767-f8ec8c96d69f.png)

As you see it says `RenderError("failed to find suitable graphics adapter")`
I'd like to run the demos, what can I do to solve this?

**Comment by nobbele** [comment]
try devel branch (git switch devel), I implemented a fix for this there

**Comment by nobbele** [comment]
I'll close this for now, please re-open if you still get the error!
