### ISSUE TITLE
Error in Getting Started documentation

### ISSUE THREAD

**Issue by EvilScott** [ggez/ggez#1075]
**Describe the bug**
When following the instructions in https://github.com/ggez/ggez/blob/master/docs/guides/HelloGgez.md I encountered the following error during the `cargo run` for the final step
```
error[E0609]: no field `time` on type `&mut ggez::Context`
  --> src/main.rs:10:23
   |
10 |         self.dt = ctx.time.delta();
   |                       ^^^^ unknown field
   |
   = note: available fields are: `filesystem`, `timer_context`, `audio_context`, `keyboard_context`, `mouse_context` ... and 2 others
```

**To Reproduce**
Follow the instructions found in https://github.com/ggez/ggez/blob/master/docs/guides/HelloGgez.md

**Expected behavior**
The `time` field should be available on `ctx` or else the documentation should be updated (it specifies version `0.7` but the code seems to be using version `0.8`).

**Hardware and Software:**
 - ggez version: 0.7.0
 - OS: MacOS 12.4
 - Graphics card: N/A
 - Graphics card drivers: N/A

**Comment by EvilScott** [comment]
Not sure its needed but here's my full source code from following the tut:

```rust
use ggez::*;

struct State {
    dt: std::time::Duration,
}

impl ggez::event::EventHandler<GameError> for State {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        self.dt = ctx.time.delta();
        Ok(())
    }
    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        println!("Hello ggez! dt = {}ns", self.dt.as_nanos());
        Ok(())
    }
}

fn main() {
    let state = State {
        dt: std::time::Duration::new(0, 0),
    };
    let c = conf::Conf::new();
    let (ctx, event_loop) = ContextBuilder::new("hello_ggez", "awesome_person")
        .default_conf(c)
        .build()
        .unwrap();
    event::run(ctx, event_loop, state);
}
```

**Comment by nobbele** [comment]
slightly confusingly, master branch currently points to 0.8.0-rc0.

**Comment by EvilScott** [comment]
> slightly confusingly, master branch currently points to 0.8.0-rc0.

The Getting Started tutorial specifies to use `0.7`
https://github.com/ggez/ggez/blob/master/docs/guides/HelloGgez.md?plain=1#L38

**Comment by nobbele** [comment]
You're right, that and all the links are an oversight

**Comment by InterruptSpeed** [comment]
// works in both ggez 0.7 and 0.8.0-rc0
self.dt = timer::delta(ctx);

// works only in ggez 0.8.0-rc0
self.dt = ctx.time.delta();
