### ISSUE TITLE
Support for multi-line text

### ISSUE THREAD

**Issue by arteme** [ggez/ggez#108]
It would be nice to be able to render multi-line text. Currently line breaks (``"\n"``) are treated as text characters.

**Comment by icefoxen** [comment]
Rendering multi-line text is nontrivial because different use cases may have different ideas of how much space should go between lines.  The font gives you this information but you never have to actually use it.

Still, a sane default might be nice.

**Comment by icefoxen** [comment]
There IS now support for creating wrapped text yourself; see `Font::get_wrap()`

**Comment by icefoxen** [comment]
If we do #132 then this will come with it, I think.

**Comment by icefoxen** [comment]
Fixed by #362!
