### ISSUE TITLE
Removal of `Image::from_bytes`

### ISSUE THREAD

**Issue by snyball** [ggez/ggez#1085]
Was `Image::from_bytes` removed by mistake? If not it should be added to the changelog, with a note explaining that users should migrate to the `image` crate and just [do what `from_path` does internally](https://docs.rs/ggez/0.8.0-rc0/src/ggez/graphics/image.rs.html#125-151).

**Comment by nobbele** [comment]
[from_pixels](https://docs.rs/ggez/0.8.0-rc0/ggez/graphics/struct.Image.html#method.from_pixels)?

**Comment by nobbele** [comment]
[from_pixels](https://docs.rs/ggez/0.8.0-rc0/ggez/graphics/struct.Image.html#method.from_pixels) exists, it should be noted, thanks

**Comment by snyball** [comment]
@nobbele I know, but `from_pixels` takes raw pixel data, and is [what `from_path` does internally](https://docs.rs/ggez/0.8.0-rc0/src/ggez/graphics/image.rs.html#125-151), which was my suggested workaround. The `Image::from_bytes` function accepts encoded image data, e.g raw `.png` or `.jpg` data (without having to load it from the filesystem.)

**Comment by snyball** [comment]
I currently just export this from a `ggez_compat` file to port my code:

```rust
pub trait FromBytes: Sized {
    fn from_bytes(ctx: &mut Context, encoded: &[u8]) -> Result<Self, GameError> {
        Self::from_bytes_srgb(ctx, encoded, true)
    }

    fn from_bytes_srgb(ctx: &mut Context, encoded: &[u8], srgb: bool)
                       -> Result<Self, GameError>;
}

impl FromBytes for Image {
    fn from_bytes_srgb(ctx: &mut Context, encoded: &[u8], srgb: bool) -> Result<Image, GameError> {
        let decoded = image::load_from_memory(encoded)
            .map_err(|_| GameError::ResourceLoadError(String::from("failed to load image")))?;
        let rgba8 = decoded.to_rgba8();
        let (width, height) = (rgba8.width(), rgba8.height());

        Ok(Image::from_pixels(
            ctx,
            rgba8.as_ref(),
            if srgb {
                ImageFormat::Rgba8UnormSrgb
            } else {
                ImageFormat::Rgba8Unorm
            },
            width,
            height,
        ))
    }
}
```

**Comment by PSteinhaus** [comment]
You're definitely right that this should be noted, thanks! It was somehow lost in the rebuilt of the graphics stack it seems.
Now the question is:

Should we note in the changelog that this function has been removed (and semi-replaced by `from_pixels`), or should we re-add it?

Personally, I don't see many situations where one would want to hand over an encoded image file that one already has at hand somehow, instead of loading it then. I'd be happy to know what your situation with this is, if I may ask of course :)

**Comment by snyball** [comment]
@PSteinhaus My specific use-case for this was embedding `.png` images with `include_bytes!(...)` for quick mockups (makes it easier to just send someone an executable and have it work.)

I guess that's a bit niche, but it's necessary for any loading of encoded images where one wants to sidestep ggez's built-in resource management. That could be necessary for e.g retrieving images from the network, letting a user pick an image from anywhere in the filesystem, etc (correct me if I'm wrong about this not being possible with ggez's fs system.)

**Comment by PSteinhaus** [comment]
Oh, good that you say so, that's not a niche use case to me at all! (after all that's how good-web-game operates mostly 😅)

Then I'm all for re-adding `Image::from_bytes`.

**Comment by Bowarc** [comment]
Yes! Please keep`Image::from_bytes`

It's very usefull with crates like `rust_embed` to be able to load modded textures from real filesystem but load default textures from the binary.

Or any other case that uses `include_bytes!()`
