### ISSUE TITLE
Anything after `ggez::event::run` is unreachable, is it nessesary ?

### ISSUE THREAD

**Issue by Bowarc** [ggez/ggez#1087]

**Comment by PSteinhaus** [comment]
Code after `event::run` isn’t unreachable per se. It’s reached as soon as the event cycle terminates and the window closes.

Why are you asking specifically? Is an example using this weirdly?

**Comment by nobbele** [comment]
is code after run really ran? IIRC winit returns !

**Comment by PSteinhaus** [comment]
Ok, my bad. The return type of `run` is `!`, i.e. `never`, so it can't return anything and everything beyond this function will be dead code, yes.

Anyway: Could you please elaborate a little on how and where this question might come up?

**Comment by Bowarc** [comment]
I wanted to play with error/crash handling.
That said, i could also do that in `event::EventHandler::quit_event`, `event::EventHandler::on_error` or with a custom launcher.

I just was wondering if that was necessary and if so why ?

**Comment by PSteinhaus** [comment]
> Sorry for the delay i diddn't checked gh's notifs 😅

No problem :)

> I wanted to play with error/crash handling. That said, i could also do that in `event::EventHandler::quit_event`, `event::EventHandler::on_error` or with a custom launcher.
> 
> I just was wondering if that was necessary and if so why ?

The intended place to deal with errors which you don't know how to / don't want to handle immediately is `on_error`, as you can then simply propagate all errors for which you want a centralized error handling up using nothing more but `?` and then handle them in one place.

That being said this probably only makes sense for errors which inadvertently interrupt your game in a way big enough to cause such a cascade. You don't _need_ to use it at all. You... wait...

_*_ **re-reads the question** *

Ok, sorry, I just realized you probably mean if it's necessary that `run` doesn't return (i.e. returns `never`).
It communicates the intend of `run`, which is to run the event cycle until it breaks, thereby [not calculating any meaningful value](https://doc.rust-lang.org/std/primitive.never.html).
Another way to look at it is that [`winit::EventLoop::run`](https://docs.rs/winit/latest/winit/event_loop/struct.EventLoop.html#method.run) returns `never`, so we do that as well, by extension.

I think it might even be technically necessary, as implementations on different platforms differ and breaking the winit event loop actually causes a hard process exit on some of them, so anything after `ggez::event::run` needs to be treated as dead code, yes.

**Comment by Bowarc** [comment]
> as implementations on different platforms differ and breaking the winit event loop actually causes a hard process exit on some of them,

Oh, ok. Makes more sense.
Regrettable but understandable, Thank you for taking the time to answer and explain; Have a good day!
