### ISSUE TITLE
Unsolved merge conflict in shadow example

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#1089]
And it seems the shadow example shader needs to be adapted (or it's just a typo).

EDIT: Ok, no it fails on `devel` as well, meh.
2nd EDIT: There is an unresolved merge conflict left in `shadows.rs` from #1080

_Originally posted by @PSteinhaus in https://github.com/ggez/ggez/issues/1083#issuecomment-1231899043_

**Comment by nobbele** [comment]
fixed in #1095
