### ISSUE TITLE
Lowered limits broke macOS window of size 2560x1920 due to max_texture_dimension

### ISSUE THREAD

**Issue by chamons** [ggez/ggez#1097]
**Describe the bug**
After updating my ggez from an older spot in devel to latest, I now crash on macOS with this:

```
    In Device::create_texture
    Dimension X value 2400 exceeds the limit of 2048
```

Doing a bisect I was able to pinpoint it down to the exact commit: 4b86be71df9ddadf0f270e987354777f5041d6fb

Reverting it with this patch:

```
--- a/src/graphics/context.rs
+++ b/src/graphics/context.rs
@@ -186,15 +186,8 @@ impl GraphicsContext {
                 label: None,
                 features: wgpu::Features::default(),
                 limits: wgpu::Limits {
-                    // 1st: DrawParams
-                    // 2nd: Texture + Sampler
-                    // 3rd: InstanceArray
-                    // 4th: ShaderParams
-                    max_bind_groups: 4,
-                    // InstanceArray uses 2 storage buffers.
-                    max_storage_buffers_per_shader_stage: 2,
-                    max_storage_buffer_binding_size: INSTANCE_BUFFER_SIZE,
-                    ..wgpu::Limits::downlevel_webgl2_defaults()
+                    max_bind_groups: 5,
+                    ..Default::default()
                 },
```

Fixed it locally for me.

**To Reproduce**

I don't think you need anything beyond this context:
```
    let mut cb = ContextBuilder::new("My Game", "me")
        .window_setup(conf::WindowSetup {
            title: "Title".to_string(),
            ..Default::default()
        })
        .window_mode(conf::WindowMode {
            width: 2560.0,
            height: 1920.0,
            ..Default::default()
        });

```
on my MacBook Pro (14-inch, 2021) laptop. 

**Expected behavior**
Previously working game to crash on launch.

**Comment by chamons** [comment]
Pinging @nobbelea who did the commit in question.

**Comment by chamons** [comment]
Doing a bit more poking, this appears to be the minimum diff needed to trigger it/make it go away:

```
                    ..Default::default()
                    // max_storage_buffers_per_shader_stage: 2,
                    // max_storage_buffer_binding_size: INSTANCE_BUFFER_SIZE,
                    // ..wgpu::Limits::downlevel_defaults()
```

**Comment by chamons** [comment]
Possible fix in https://github.com/ggez/ggez/pull/1098, please review

**Comment by PSteinhaus** [comment]
Thanks for finding. 2048 is really small as a max texture size and we can probably safely choose something slightly larger.

I looked a tiny bit into this and it seems that 4096x4096 [might be a safe size](https://github.com/gpuweb/gpuweb/issues/1327) to choose. Alternatively we could also build in conditional compilation for wasm (and later perhaps android) choosing this or maybe even 2048 when compiling for these platforms.

Or we could go one step further and make this configurable via the `conf.toml`. That way people could choose for themselves what size they actually need and which devices they actually want to support. While this would be the most flexible solution it would of course also be the one with the most added complexity/breakage.

**Comment by nobbele** [comment]
Looking further in that issue, 8k seems fine too. I'm for just increasing the limit rather than having it configurable for now
