### ISSUE TITLE
Two APIs needed to recreate ggez event loop are not public visible

### ISSUE THREAD

**Issue by chamons** [ggez/ggez#1099]
**Describe the bug**
I am playing around with hot reload in my game, and to make it work I need to control the event loop when in debug/hot reload mode. 

There is [a sample](https://github.com/ggez/ggez/blob/devel/examples/eventloop.rs) showing how to do this, but is is incomplete as it does not handle keyboard/mouse input.

I was able to dig into the source code of ggez and produce [this variant](https://gist.github.com/chamons/953f8456911f658b8a205fb6f3989740).

However, it does not compile against devel today, as there are two APIs used by ggez's `event::run` that I do not have access to. 

[This patch](https://gist.github.com/chamons/b5ea88b18530a57c1b0052992afd72b9) fixes it locally for me, and everything works.

**Is this an extension that ggez's developer community would be willing to consider?**

**To Reproduce**
Try to create an event loop with ggez that includes keyboard and mouse support.

**Expected behavior**
These APIs to be public.

**Comment by nobbele** [comment]
Seems fine, open a PR and I'll merge it

**Comment by chamons** [comment]
Opened - https://github.com/ggez/ggez/pull/1100
