### ISSUE TITLE
Strange Text Centering Behavior

### ISSUE THREAD

**Issue by chamons** [ggez/ggez#1105]
**Describe the bug**

I want to center some text inside a rectangle. I am using [this code](https://github.com/chamons/ggez_text_bug/blob/master/src/main.rs#L29-L46) in devel and I get:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/6392201/193091301-fc49069f-5880-4929-973e-d57e12d2940f.png">

But when I port it back to 0.7 with [this code](https://github.com/chamons/ggez_text_bug/blob/0.7/src/main.rs#L28-L54) I get:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/6392201/193091454-7d323515-e1ce-437f-82bb-f9f7e600f858.png">

**To Reproduce**
[Sample Project](https://github.com/chamons/ggez_text_bug). master has devel repro, branch 0.7 has the previous stable port.

**Expected behavior**
I expect these two versions to draw the same.

**Comment by chamons** [comment]
I just pulled latest devel and it still reproduces.

I'm digging through ggez's render code, and it's getting at least to a glyph_brush::Section with centered alignment intact.

**Comment by chamons** [comment]
More rubber duck debugging, it looks like we're setting the Section with these arguments:

https://github.com/ggez/ggez/blob/devel/src/graphics/text.rs#L256-L265

And we are setting the screen position to 0,0 unconditionally, that seems weird to me?

**Comment by chamons** [comment]
Actually, that looks like it should be handled by param.transform. This is all Greek to me.

**Comment by chamons** [comment]
Turns out https://github.com/ggez/ggez/pull/1104/files actually has the fix inside it, once I fixed a typo!

<img width="512" alt="image" src="https://user-images.githubusercontent.com/6392201/193102179-c495ad23-f35b-4b5b-9337-d189647ff3cb.png">

I'll PR just that shortly.

**Comment by nobbele** [comment]
Shoud align represent alignment within the bounds or not, is the question
#1102 doesn't
#1103 does
#1104 does both
