### ISSUE TITLE
Alsa freeze

### ISSUE THREAD

**Issue by andrewbaxter** [ggez/ggez#1110]
**Describe the bug**
I get `ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred` randomly for a while (around 1/sec, but with lots of jitter) then suddenly get flooded with
```
an error occurred on output stream: A backend-specific error has occurred: ALSA function 'snd_pcm_poll_descriptors' failed with error 'UnknownErrno: Unknown errno'
```
I can't close the window (window stays, but stops responding), or if I can close the window the program doesn't end and continues flooding the above error.

**To Reproduce**
```
use std::ops::Rem;
use std::thread;
use std::time::Duration;

use ggez::conf::WindowSetup;
use ggez::event::{self, Axis, GamepadId};
use ggez::glam::Vec2;
use ggez::graphics::{self, Color, DrawParam, Rect};
use ggez::input::gamepad::gilrs::ev::Code;
use ggez::input::keyboard::KeyCode;
use ggez::mint::Vector2;
use ggez::{Context, GameResult};

struct State {
}

impl State {
    fn new(ctx: &mut Context) -> GameResult<State> {
        Ok(State {})
    }
}

impl event::EventHandler<ggez::GameError> for State {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        let mut canvas = graphics::Canvas::from_frame(ctx, Color::BLACK);

        canvas.finish(ctx)?;

        Ok(())
    }
}

pub fn main() -> GameResult {
    let (mut ctx, event_loop) = ggez::ContextBuilder::new("a", "b")
        .window_setup(WindowSetup::default().vsync(true).title("menu"))
        .build()?;
    let state = State::new(&mut ctx)?;
    event::run(ctx, event_loop, state)
}
```

It happens if I wait a while, but sometimes I can trigger it by switching desktops or windows back and forth.  It's harder to reproduce with the above example, it's easier when I'm drawing stuff.

**Expected behavior**
No lockup, no audio error messages in general.

Not quite a fix, but is there any way to disable audio?  As a short term workaround.

**Screenshots or pasted code**

**Hardware and Software:**
 - ggez version: `0.8.0-rc1`
 - OS: Arch, updated a few days ago
 - Graphics card: `GeForce GTX 1050`
 - Graphics card drivers: Kernel modules `nvidia_drm nvidia_modeset nvidia_uvm nvidia`

I'm using pipewire with the pulse audio bridge.

FWIW while my ggez program is running, I can't play new music.  If I'm playing music (pulse) at the time I start the program (or for maybe 10-20s after I stop playing music) when I start my program I get these (non-fatal) error messages and the above issue doesn't manifest:
```
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
```
(`/dev/dsp` doesn't exist on my system unrelated to the above)

This isn't critical for me, and I'm guessing is a quirk of (just?) my system but I thought I'd create this issue just in case.

**Comment by nobbele** [comment]
the "audio" feature is on by default, you can try disabling default features

**Comment by andrewbaxter** [comment]
Ah cool, didn't notice that. Thanks!

**Comment by andrewbaxter** [comment]
Reproduced with just rodio, I'll move the ticket there.
