### ISSUE TITLE
Vertex shaders

### ISSUE THREAD

**Issue by andrewbaxter** [ggez/ggez#1113]
AFAICT ggez only supports fragment shaders (is this correct? the readme and other docs just say "shader").  I need to wiggle some meshes around.

I see the original shader MR was originally going to be named PixelShader but got renamed to Shader with the comment that it should be simple to add vertex shaders afterward.  How much work would this be and is there a rough overview of what needs to be done?

Alternatively, by the cube example it looks like I could use gfx directly, but how much of the ggez tooling would I have to throw out? It looks like you might need to do everything the gfx way down to the render pipeline.

If supporting vertex shaders would be significant work, could a way to use gfx shaders with the existing stack be opened up somehow?

**Comment by andrewbaxter** [comment]
Ah, it looks like maybe vertex shaders were supported pre #1020? The new api seems very easy, it would be great if it worked for vertex shaders too.

**Comment by PSteinhaus** [comment]
Ah, dammit. Just when we were getting ready to release 0.8.0 you remind us of so many good things to do that we have forgotten about...

**Comment by PSteinhaus** [comment]
Ok this one should luckily be relatively easy to do.
We only need to change these lines to no longer hard-code the vertex shader but get it from the `Shader`, like we do with the fragment shader:
https://github.com/ggez/ggez/blob/8052ded79ae0339d04923564db3e413e9d26c39b/src/graphics/internal_canvas.rs#L574-L587

And then, of course, we need to add such a field to `Shader` and allow for setting it in creation. It should probably be an `Option`, so we can default to the hard-coded shader when there is `None`.

@nobbele also suggested to introduce a builder pattern for this purpose, maybe something like this:
```rust
let test_shader: Shader = ShaderBuilder::new_wgsl().fragment_path(path, name).vertex_source(source, another_name).build();
```
With `vertex_path` and `fragment_source` being valid methods as well, of course.

**Comment by andrewbaxter** [comment]
I'll take this if that's cool.  I'll definitely need some hand holding though.

**Comment by andrewbaxter** [comment]
#1115
