### ISSUE TITLE
Default shader params sampler

### ISSUE THREAD

**Issue by andrewbaxter** [ggez/ggez#1118]
could we pass the canvas's current sampler by default perhaps?

_Originally posted by @nobbele in https://github.com/ggez/ggez/pull/1115#discussion_r1001815442_

**Comment by PSteinhaus** [comment]
I'd like to keep it explicit. Less opportunity for confusion and not too ugly.

**Comment by andrewbaxter** [comment]
Ah okay. :+1:

**Comment by andrewbaxter** [comment]
Feel free to close this and the PR.

**Comment by nobbele** [comment]
I agree that it's not too bad as is
