### ISSUE TITLE
ggez 0.7.0 depends on rodio 0.14, which no longer compiles

### ISSUE THREAD

**Issue by BartMassey** [ggez/ggez#1123]
Debian linux current, Rust 1.64.0. Trying to build my app with `ggez` 0.7.0 with `--no-default-features` no longer works; compilation fails in `rodio` with a bogus `nix` dependency issue. Upgrading `ggez`'s `rodio` dependency to `0.16.0` solves the problem: everything builds normally.

**Comment by PSteinhaus** [comment]
Thanks for the info. Then I'd say we create a new 0.7 support branch, update to `rodio` and release `ggez` 0.7.1.

I'll see to it this evening.

**Comment by PSteinhaus** [comment]
Opened [a support branch for 0.7](https://github.com/ggez/ggez/tree/0.7-support) and released `ggez` 0.7.1 with `rodio` 0.16 and other dependency updates.

**Comment by BartMassey** [comment]
Thanks much. Trying to move to 0.8, but wanted to be able to build the old version as well while I am working on that.
