### ISSUE TITLE
Feature: `Canvas` configurable to draw z-order also as temporal order to better support transparency

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#1126]
Link to the original Discord discussion on this: https://discord.com/channels/1031224392174293002/1031224393126387764/1036199537720696874

## The problem

Currently, if you don't care about transparency (or draw using `InstanceArray`s) you can just use `ZIndex` and be happy.
But not if you want to have proper transparency. Then you have to worry about temporal draw order and make sure it's right on your own, which is horribly annoying, as it makes me personally think "well, this `ZIndex` stuff is nice and all, but I better not use it at all as I might want to add something with transparency at some point".

`InstanceArray` luckily alleviates this problem, as we sort the draw calls internally on request which creates a temporal order that matches (or rather emulates) the z-order, which is wonderful.

But if you can't solve it all in one `InstanceArray` then you still have to worry about temporal draw order, which is annoying.

## An idea to solve this

So: Could we perhaps make `Canvas` just hold a `TreeMap` (or `BTreeMap`) or `BinaryHeap` keeping all the draw calls pushed to it in sorted order matching the z-order of calls? Then we could draw in that order and achieve correct temporal order leading to transparency _just working_ without users having to worry about it.

A question would be: Would we want to make this configurable, probably on `Canvas` creation, for people who don't need it and want that slight bit more performance instead, or do we just want to hard-code it?

I'm currently more on the hard-coding side, as one shouldn't really have that many draw calls to begin with, so keeping them in a sorted structure or even just sorting them at the end doesn't make much of a difference.

**Comment by jazzfool** [comment]
[...is this not already the case?](https://github.com/ggez/ggez/blob/master/src/graphics/canvas.rs#L29)

**Comment by jazzfool** [comment]
Everything that respects Z-order does so by re-ordering draws

**Comment by PSteinhaus** [comment]
... fascinating. I never noticed 😅
No idea how I ended up being so convinced we just used camera z-order to order things...

Shows again that you designed the whole thing quite beautifully ^^

Then I'm going to close this, as this is exactly what I would desire 😌
