### ISSUE TITLE
Sampling seems broken

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1127]
**Originally reported by maatflow#5009 on Discord.**
[crisp (0d8ab27)](https://media.discordapp.net/attachments/1031224393126387764/1036344163836383262/unknown.png)
[blurry (ff3709c)](https://media.discordapp.net/attachments/1031224393126387764/1036345307547582526/unknown.png)
I suspect cbb3d20 is the cause but I'm not sure, narrowing it down to the exact commit seems not so simple in git.

Confirmed on my machine as well.

**Comment by jazzfool** [comment]
That commit is indeed the problem. Originally, `curr_sampler` was set before the bind group was made, but now it uses the previous sampler, so changing the sampler is always one step behind.

https://github.com/ggez/ggez/blob/master/src/graphics/internal_canvas.rs#L631

Either move `curr_sampler = next_sampler` before or just use `next_sampler` when making the bind group.
