### ISSUE TITLE
Make contributing easier

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#113]
* ~~Have a CONTRIBUTING.md~~
* ~~Mark easy bugs~~
* List contact/support info and contributing.md link ~~in readme~~ and website
* ~~code of conduct~~

Source: https://www.youtube.com/watch?v=Qsiu-zzDYww

**Comment by onelson** [comment]
Was recently looking over this https://github.com/nrc/dev-tools-team/blob/master/contribution/checklist.md which is fairly relevant.

**Comment by icefoxen** [comment]
This is basically now just part of issue #164
