### ISSUE TITLE
Vsync option doesn't have full platform support anymore

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1130]
**Originally reported by @4iy4 on Discord**

We are currently using `Mailbox` because old wgpu had fallback to `Fifo` but newer wgpu doesn't so we should probably switch to present modes to `AutoVsync` and `AutoNoVsync`

See: https://docs.rs/wgpu/latest/wgpu/enum.PresentMode.html

Error example: `thread 'main' panicked at 'Error in Surface::configure: requested present mode Mailbox is not in the list of supported present modes: [Fifo]'`

**Comment by PSteinhaus** [comment]
That seems right. Good to have these new enums : )
