### ISSUE TITLE
Multiple exit events get produced

### ISSUE THREAD

**Issue by griffi-gh** [ggez/ggez#1134]
**Describe the bug**
`exit_event` gets called multiple times

**To Reproduce**
Repo: https://github.com/griffi-gh/opgd/tree/4d9ef78fcc37fc3d5712c016b883f7db67622497
(can add a simple example if needed)

**Expected behavior**
`exit_event` should be only called once

**Screenshots or pasted code**
![image](https://user-images.githubusercontent.com/45996170/200079521-46641559-bd3a-4aa1-aa75-d0d12f0b2598.png)

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: Windows 10
 - Graphics card: NVIDIA GTX 1050Ti
 - Graphics card drivers: Latest official nv drivers

**Comment by nobbele** [comment]
fixed
