### ISSUE TITLE
game_id should set app-id on Wayland

### ISSUE THREAD

**Issue by snyball** [ggez/ggez#1142]
On Wayland (Linux/BSD) windows have an app-id attribute, which is separate from the title. winit supports setting this attribute using `.with_name` on `WindowBuilder`. ggez should support setting this attribute to the `game_id` given to `ContextBuilder::new`, which should then be (build-time conditionally based on the same predicate as in winit) forwarded to winits `.with_name` in `GraphicsContext::new_from_instance`. I think this is the least surprising behavior for `game_id` on Wayland.

My primary use case for having to set this attribute is to be able to keep `cargo watch -x 'run'` running in the background, and to have my window-manager automatically move the app window to a specific workspace on restart. An app-id attribute is necessary to do this, at least in sway wm.

I can create and submit a pull request for this, but am checking if maintainers agree first :)

**Comment by PSteinhaus** [comment]
Thanks for the observation!
That's a good idea. I agree that setting it to `game_id` makes sense.

If you want to submit a PR for this I'll gladly take a look over it :)
