### ISSUE TITLE
Drawing doesn't work with latest nightly build on windows

### ISSUE THREAD

**Issue by Flippchen** [ggez/ggez#1145]
**Describe the bug**
When you start the game, the game logic functions as normal but anything except text will not display.

**To Reproduce**
- Install Windows (11)
- Get the ggez example from https://ggez.rs/
-  Install latest nightly toolchian.
- Build Project/ Start game
- No drawings are shown

**Expected behavior**
A White Ball moving from left to right should appear. Only the background color is available.

**Screenshots or pasted code**
--/

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: Windows 11, latest updates and driver
 - Graphics card: Intel  UHD Graphics, RTX3050 Ti mobile edition
 - Graphics card drivers: Latest from Intel/Nvidia

**Comment by qwitwa** [comment]
This sounds awfully like #1146. Once that's merged, could you pull the devel branch and see if the examples work for you?

**Comment by Flippchen** [comment]
Of course :)

**Comment by qwitwa** [comment]
@Flippchen actually could you try [the branch](https://github.com/sphenlee/ggez/tree/fix-non-instanced-draw ) before it's merged? I don't know why I didn't say that in the first place aha

**Comment by nobbele** [comment]
should be fixed now
