### ISSUE TITLE
Building on Windows using Cygwin64 fails

### ISSUE THREAD

**Issue by bennett-sh** [ggez/ggez#1147]
**Describe the bug**
When I try to build this, it will fail at zstd-sys.

**To Reproduce**
Create a Rust project with ggez and run cargo build on Windows with cygwin64 installed.

**Screenshots or pasted code**
Output of cargo run: https://pastebin.com/knfKXLim

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: Windows 11
 - Graphics card: NVidia GTX 970
 - Graphics card drivers: Official NVidia Game-Ready Drivers (latest version)

**Comment by nobbele** [comment]
can you try with default features disabled?

**Comment by bennett-sh** [comment]
thanks, that worked
