### ISSUE TITLE
Present mode 'Mailbox' is not in the list of supported present modes

### ISSUE THREAD

**Issue by Bowarc** [ggez/ggez#1149]
**Describe the bug**
When sending a project to a friend, he got this error at runtime, it comes from wgpu-0.14.0\src\backend\direct.rs:274:9

the only way he could run the game was by setting the backed to Dx12 (tried: All, Dx12, Vulkan and default) but had shit fps (2 to 5 percent the usual)

**To Reproduce**
it only happened on my project so, it might come from me. i'll tell him to run the first ggez example and give you an update here:
- update: `Empty for now`

**Expected behavior**
I'd expect the game to run

**Screenshots or pasted code**
`Nothing for now`

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: w10
 - Graphics card:  AMD Radeon RX 6500  XT
 - Graphics card drivers: 'latests' 10/12/22

**Comment by nobbele** [comment]
can you try the devel branch?

**Comment by PSteinhaus** [comment]
This might have been fixed in https://github.com/ggez/ggez/issues/1130

Could you try to send him a new attempt using the devel branch please?

**Comment by Bowarc** [comment]
Sorry for the late response,
Yes, it's working fine with the devel branch

**Comment by PSteinhaus** [comment]
Hey, no problem. Thanks for checking!
