### ISSUE TITLE
ggez::event::EventHandler docs refer to old global ggez::graphics::clear and ggez::graphics::present functions 

### ISSUE THREAD

**Issue by qwitwa** [ggez/ggez#1152]

**Comment by PSteinhaus** [comment]
And also other outdated links like `input::gamepad()` or `graphics::set_mode()`.
Should definitely be updated, yes. Thanks for pointing it out!

**Comment by qwitwa** [comment]
``graphics::set_screen_coordinates`` is mentioned on line 198 of examples/input_test.rs

**Comment by nobbele** [comment]
fixed
