### ISSUE TITLE
bug with requestDeviceError please help

### ISSUE THREAD

**Issue by momonoski55555** [ggez/ggez#1153]
will i've been having this issue with multiple engines using rust 

`lize graphics, trying secondary backends.. Please mention this if you encounter any bugs!
thread 'main' panicked at 'aieee, could not create ggez context!: RequestDeviceError(RequestDeviceError)', src/main.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

here is my code for refrence

`use ggez::{Context, ContextBuilder, GameResult};
use ggez::graphics::{self, Color};
use ggez::event::{self, EventHandler};

fn main() {
     
    let (mut ctx, event_loop) = ContextBuilder::new("altirarija", "Momonoski55")
        .build()
        .expect("aieee, could not create ggez context!");

    let state = Mainstate::new(&mut ctx);

    
    event::run(ctx, event_loop, state);
}
struct Mainstate{

}

impl Mainstate{
    pub fn new(_ctx: &mut Context) -> Mainstate {
       Mainstate {  

       }
    
    }
}
impl  EventHandler for Mainstate {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, _ctx: &mut Context) -> GameResult {
        Ok(())
    }
    
}
`

**Comment by nobbele** [comment]
what graphics card(or integrated) and what OS?

**Comment by momonoski55555** [comment]
Manjaro and radeon 7000m series

**Comment by nobbele** [comment]
if it supports vulkan, try installing that if you didn't already, such as vulkan-radeon

**Comment by momonoski55555** [comment]
Turns out, the laptop that my brother gave me ,its GPU stopped working long time ago so yea.
thanks for help.
