### ISSUE TITLE
Some elements are not displayed on v0.8 (regression)

### ISSUE THREAD

**Issue by 64kramsystem** [ggez/ggez#1154]
**Describe the bug**

Some elements are not displayed. For example, when running the `05_astroblasto` example, the level and score texts are displayed, but not the ship and the asteroids.

The game is actually running - after some time, the ship will hit an asteroid, and the game will end.

When I run the example on ggez 0.7.1, it runs fine.

**To Reproduce**

Run the `05_astroblasto` example.

**Expected behavior**

The elements should be drawn.

**Screenshots or pasted code**

![image](https://user-images.githubusercontent.com/1595356/210414873-45b3a957-1cde-4b10-a45b-05679ba3a53f.png)

**Hardware and Software:**

 - ggez version: 0.8.1
 - OS: Linux (Ubuntu 22.04)
 - Graphics card: AMD Radeon RX 6600 XT
 - Graphics card drivers: Open source (kernel v6.1.2); the issue happens regardless of `AMD_VULKAN_ICD` unset or set to `RADV`.

I've tried several Bevy examples (I suppose it uses wgpu as well), and they run fine, so this is not necessarily a graphic card/wgpu bug.

**Comment by nobbele** [comment]
should work on devel

**Comment by 64kramsystem** [comment]
> should work on devel

Ah! It does indeed. Thanks 😁
