### ISSUE TITLE
No way to create a blank image?

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1156]
There's `from_solid` but that makes a square only?
`new_canvas_image` does the right thing though

**Comment by PSteinhaus** [comment]
implemented in #1189

Is that what you had in mind?
I'd say we could also just rename this new `new_blank_canvas_image` function to `from_solid`, replacing the current `from_solid`.
I agree that having a few more simple controls/options on `from_solid` as a debug function makes sense, at least to allow it to create other shapes then squares.

Or would you prefer something more akin to a wrapper around `new_canvas_image`, just with `format` and `samples` hardcoded for easier use?

**Comment by tversteeg** [comment]
I would prefer `from_color` over `from_solid` or maybe `new_solid_color` but the current one is also good.

**Comment by nobbele** [comment]
I actually forgot exactly what I meant/wanted here

**Comment by PSteinhaus** [comment]
> I would prefer `from_color` over `from_solid` or maybe `new_solid_color` but the current one is also good.

I think that `from_color` makes the most sense, too.
I made a little PR renaming it like this and removing `from_solid`, as it's the same function, just without the option to specify both dimensions: #1194
