### ISSUE TITLE
Creating an Image/Canvas leaks tons of memory

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1159]
like, crashes within a minute with a single image+canvas
TODO
caused by calling `new_canvas_image` every frame

**Comment by nobbele** [comment]
Just creating one doesn't leak, only when you also use it

**Comment by Vixeliz** [comment]
Should be fixed with 0.9.2 so i'm gonna go ahead and close feel free to tell me to reopen if the problem still exist.
