### ISSUE TITLE
Lyon update

### ISSUE THREAD

**Issue by nical** [ggez/ggez#116]
Hi there,

There's been some good progress in lyon since 0.4, including quite a bit of bug fixes and some extra features. There's also been some breaking changes chief among which the removal of `tessellation::basic_shapes::fill_ellipse` (with the idea that one can use `fill_circle` and stretch the vertices).
Since ggez appears to be the main user of lyon, don't hesitate to ask for features. for example if having a specific helper for ellipses is important for you, let me know and I can look into adding it back.

**Comment by icefoxen** [comment]
Good to know, I've been wanting to get around to this eventually.

**Comment by nical** [comment]
Heads up I found a silly silly bug in the stroke tessellator that caused the strokes width to be half of what it should be. It will be fixed in lyon 0.7 which I will release tomorrow or so.

**Comment by nical** [comment]
For ellipses, see https://github.com/nical/lyon/issues/125

**Comment by icefoxen** [comment]
I have a (very) basic example working (as far as I can tell right now, which isn't enough).  BUT it does seem to work, and should be enough to make the rest of the drawing functionality just a matter of copy-paste-and-tinker.

**Comment by icefoxen** [comment]
This is now starting to work as of commit b7aeb70.  Concerns remaining:

 * Code really needs refactoring and cleanup
 * Doing a filled polyline has no "not closed" option???  Verify.
 * Some cleanup should happen when we decide on a math library (Issue #106)
 * We currently do nothing with Lyon results, even ones that just give useful info like how many points were actually used in a tessellation
 * Currently some functions take the global line width while others take a parameter?  This should at least be consistent.

**Comment by nical** [comment]
> Doing a filled polyline has no "not closed" option??? Verify.

Filling an open shape automatically closes it (otherwise we wouldn't be able to fill it).

> // BUGGO: Annoyingly have to copy these points to lyon's point type;

You can create an iterator of euclid points that consumes whatever point type ggez uses without allocating memory.

For example:

```rust
stroke_polyline(
    [ [0.0, 1.0], [1.0, 1.0], [1.0, 0.0], [0.0, 0.0] ].iter().map(|array| { euclid::point2(array[0], array[1]) }),
    is_closed,
    options,
    output,
);
```

**Comment by icefoxen** [comment]
Aha, got the iterator thing to work.  Fantastic.

**Comment by icefoxen** [comment]
Pretty much finished now!  The API has been heavily refactored with the advent of MeshBuilder so there's not anything terribly useful we can actually do with Lyon's point counts, alas.  Still!  It's VERY nice.
