### ISSUE TITLE
meshes not rendering with Intel Iris Xe and 11th gen intel core, after Windows KB5022404

### ISSUE THREAD

**Issue by jpetkau** [ggez/ggez#1162]
**Describe the bug**
Meshes do not render at all, including the ggez examples. The window opens and clears to the right color, and text renders fine, but meshes just don't show up. It used to work, mysteriously stopped working recently.

This is a weird one.

Nothing changed in between when it was working and now except for one irrelevant-seeming Windows update.

* It used to work fine, as recently as a few weeks ago.
* I updated neither ggez nor my graphics drivers between then and now. The only update of any kind between when it was working and when it wasn't was KB5022404 on 2023-01-22, but that doesn't appear to contain anything graphics-related.
* I see the same problem with both the Vulkan and DX12 backends.
* After the problem started, I updated Intel graphics drivers to see if that helped, from (31.0.101.1999, 5/31/2022) to (31.0.101.4032, 12/21/2022). No change.
* The same project works on my other machine with different HW.

I'm filing this in ggez because other projects that use wgpu seem to be fine. E.g. Bevy projects with a wgpu backend work, as does running wgpu's own examples directly. I'm only seeing the problem in ggez.

**To Reproduce**
(in ggez repo, on Windows with Intel Iris Xe)
cargo run --example 05_astroblasto
(window opens, score text is visible but nothing else)

I don't expect this report will be very useful directly, but if there's some additional logging or debug info I can get to help narrow it down, I'm happy to do that.

**Expected behavior**
Ship and rocks render. (Or whatever meshes are supposed to be visible.)

**Screenshots or pasted code**
![image](https://user-images.githubusercontent.com/764676/215286990-63660727-52f9-4c2a-a258-5f715f5434cb.png)

**Hardware and Software:**
 - ggez version: tried current git master (8504318a9717) and 0.8.1. wgpu is at 0.14.2 in both.
 - OS: Windows 11
 - Graphics card: Intel Irix Xe
 - Graphics card drivers: Intel 31.0.101.1999 or 31.0.101.4032

**Comment by nobbele** [comment]
should work on devel

**Comment by jpetkau** [comment]
> should work on devel

Thanks! Confirmed, yes it works on devel. Sorry, should have tried that first.
