### ISSUE TITLE
Offset with InstanceArray does not apply

### ISSUE THREAD

**Issue by buxx** [ggez/ggez#1164]
**Describe the bug**

When use `.offset` of a `DrawParam` in a `InstanceArray`, offset is not applied.

**To Reproduce**

1. Clone `ggez` repo
2. Checkout `devel` branch (or `f87f078346729737b4691b9618eab3f95d61c8ad` commit)
3. Modify example `examples/colorspace.rs` as follow : 

```diff
diff --git a/examples/colorspace.rs b/examples/colorspace.rs
index a031b9a..92ad023 100644
--- a/examples/colorspace.rs
+++ b/examples/colorspace.rs
@@ -105,11 +105,13 @@ impl MainState {
         demo_instances.push(
             DrawParam::default()
                 .dest(Vec2::new(250.0, 350.0))
+                .offset(Vec2::new(0.5, 0.5))
                 .scale(Vec2::new(0.25, 0.25)),
         );
         demo_instances.push(
             DrawParam::default()
                 .dest(Vec2::new(250.0, 425.0))
+                .offset(Vec2::new(0.5, 0.5))
                 .scale(Vec2::new(0.1, 0.1)),
         );
```diff
4. Start the example with `cargo run --example colorspace`

Produced images are not offset as expected.

**Expected behavior**

The image are offset as given to `DrawParam`.

**Screenshots or pasted code**

See "To Reproduce" steps.

**Hardware and Software:**
 - ggez version: devel (`f87f078346729737b4691b9618eab3f95d61c8ad`)
 - OS: Linux (Ubuntu 22.04)
 - Graphics card / Graphics card drivers: `VGA compatible controller: Intel Corporation Device 9a49 (rev 01)`

**Comment by buxx** [comment]
Note I discover this bug by upgrading my game (https://github.com/buxx/OpenCombat/commits/upgrade-ggez) from ggez 0.7 to 0.8 and so, replacing `SpriteBatch` by `InstanceArray`.

**Comment by buxx** [comment]
Update : Offset are now absolute ! If this is a "normal" change, I can make documentation pull request.

**Comment by PSteinhaus** [comment]
Hi there.
I'm sorry that this caused you trouble, but it's actually a "normal" change. And, if I see correctly, it has also been reflected in the documentation as well. ([FAQ about offsets](https://github.com/ggez/ggez/blob/master/docs/FAQ.md#offsets)) ([docs on `Transform`](https://docs.rs/ggez/latest/ggez/graphics/enum.Transform.html#variant.Values.field.offset))

Though we could/should be more explicit about it being absolute when applied to an `InstanceArray` as a whole in the docs, I agree.

But at least I promise that this will be the last time we changed this stuff. I really hope that it will just stay this way now in following releases.

**Comment by buxx** [comment]
Okay thanks for this clarification :)

And thanks for all your awesome work !!
