### ISSUE TITLE
Meshes are not rendered on linux

### ISSUE THREAD

**Issue by gridbugs** [ggez/ggez#1167]
**Describe the bug**
On linux (tested on ubuntu and nixos) meshes are not visible. For example the `01_super_simple` example is supposed to draw an animated circle using a mesh but on linux I see a blank (dark blue/green) screen. I've tested on macos and it works fine there.

I did a `git bisect` and the last good revision is 4da2bf0db8661dea538a2489a29caa31844e8fe3. The next revision (c5d797e8a604cc7b03632bb6676db396361f25d4) doesn't build, and the problem first appears in 5f038b0abb931dd34c02422dd25d273d73edf135.

**To Reproduce**
(on linux)
```
cargo run --example 01_super_simple
```

**Expected behavior**
It should open a window and draw a white circle moving from the left of the screen to the right

**Hardware and Software:**
 - ggez version: master branch, and 0.8.0 and 0.8.1
 - OS: NixOS, and Ubuntu 22.10 (in a virtual machine)
 - Graphics card: Radeon 6900
 - Graphics card drivers: amdgpu

**Comment by nobbele** [comment]
try 0.8.1-rc0

**Comment by gridbugs** [comment]
Ah that works. Thanks!
