### ISSUE TITLE
No way to clear Text or copy settings without fragments

### ISSUE THREAD

**Issue by chamons** [ggez/ggez#1172]
I have code that builds up large descriptions of game objects, and produces many TextFragments inside one Text. 

In one portion, the space is limited, and I want to only draw the subset of that text that fits.

I want to write a function like this:
```
pub fn trim_text_to_height_if_needed(text: &mut Text, height: f32, gfx: &GraphicsContext) {
    if text.dimensions(gfx).unwrap().h > height {
        let mut trimmed_text = text.clone();

        for fragment in text.fragments() {
            trimmed_text.add(fragment.clone());
            if trimmed_text.dimensions(gfx).unwrap().h >= height {
                *text = trimmed_text;
                return;
            }
        }
    }
}
```

It adds fragments one at a time to a new Text, then once it's too big stops. 

However, the new text doesn't have any of the configuration of my existing one, font, font size, layout, wrapping, etc.

- I could clone the existing text, but there is no way to clear the fragments.
- I can't access the existing layout/wrap/scale/font to copy them over
- I can't remove fragments from the original text (which would be preferred)
- There doesn't seem to be a way to clip the rendered text to a frame (which would not be ideal but solve the problem

**To Reproduce**
Try to create trim_text_to_height_if_needed and note the missing APIs

**Expected behavior**
This function on Text:
```
    pub fn clear(&mut self) {
        self.fragments.clear();
    }
```

**Comment by PSteinhaus** [comment]
As you've kindly added the desired feature yourself I'll consider this done.
