### ISSUE TITLE
Graphics doesn't render to the screen.

### ISSUE THREAD

**Issue by Asurakun1** [ggez/ggez#1174]
When trying the examples.
the window loads and the game runs

but the screen is either completely black
or different background color

but the screen itself does not draw at all.

**Comment by nobbele** [comment]
try devel branch

**Comment by chamons** [comment]
@Asurakun1 - This is an example of how:

https://github.com/ggez/ggez/issues/1148#issuecomment-1410439931

except you likely need to replace the version with `0.9.0-rc0` now.

**Comment by cinmay** [comment]
I can confirm. I had the same issue. using  0.9.0-rc0 works fine.

**Comment by alexdaguy** [comment]
For me `0.8.1` only works using Rust toolchain 1.66, so if you need to use this version try that

**Comment by forgemo** [comment]
I had the same issue (with  Rust 1.68), . ..  and I can also confirm that switching to "0.9.0-rc0" fixed the issue.
