### ISSUE TITLE
No output to application window

### ISSUE THREAD

**Issue by arminveres** [ggez/ggez#1185]
**Describe the bug**
When doing e.g, `cargo run --example 03_drawing` the application compiles but the window stays colored.
I tried switching window managers, but neither GNOME nor AwesomeWM makes a difference.
Also, astroblasto outputs sound.

UPDATE: I found [this reddit post](https://www.reddit.com/r/rust_gamedev/comments/10mwfca/ggez_rendering_broken_after_updating_rust/) that had the exact same problem. If I export the examples into a separate project, and use the '0.9.0-rc0', then the output works again. As they said in the comments, it probably relates to the new rust compiler and how it lays structs out.

**To Reproduce**
Run examples 03-05: `cargo run --example 03_drawin`

**Expected behavior**
I expected for the shapes to turn up, or in 04 to be able to play snake.

**Screenshots or pasted code**
03_drawing:
![image](https://user-images.githubusercontent.com/45210978/232315866-7e8b140c-c512-4642-95f9-9751ebf86839.png)
04_snake:
![image](https://user-images.githubusercontent.com/45210978/232315968-6fd26d52-aad4-43a2-a806-0d9874dadbb5.png)
05_astroblasto:
![image](https://user-images.githubusercontent.com/45210978/232316004-0154be19-78df-434b-9d11-c9c9dd5c9ed5.png)

**Hardware and Software:**
 - ggez version: 0.8.1
 - OS: Fedora 37
 - Graphics card:  AMD Radeon 6900 XT
 - Graphics card drivers: Mesa 22.3.7
 - Tried with Rustc 1.67 and 1.68.
 I also installed the Linux dependencies.

**Comment by LuckyToaster** [comment]
i am experiencing the same issue, I've tried changing to version 0.9.0-rc0 as suggested in [https://github.com/ggez/ggez/issues/1174](url), but all the example games still look just like the screenshots you provided, and most of the examples still dont work.

However, I've made a little project like the "bunnymark" example but using meshes with circles, and if I change from version 0.9.0-rc0 to 0.8.1, the circles are not visible. So switching to 0.9.0-rc0 has fixed some things for me, but the examples still do not work. I am on windows 10.

**Comment by arminveres** [comment]
What rustc version are you using? Even though I am on linux 1.67< + 0.9rc0 combination could work for you as well. Otherwise using a compiler version below 1.67 with 0.8.1 worked as well.

**Comment by LuckyToaster** [comment]
I am on 1.68.2

**Comment by PSteinhaus** [comment]
I can reproduce this using rustc 1.69.0 and ggez 0.9.0-rc0.
However, using the devel branch seems to fix the problem. I am not sure why this fixed the problem, but my guess would be that it's related to the upgrades in `wgpu` or perhaps `winit` adapting to the compiler changes.

Could you please check whether this solves your problem as well?

**Comment by arminveres** [comment]
> I can reproduce this using rustc 1.69.0 and ggez 0.9.0-rc0. However, using the devel branch seems to fix the problem. I am not sure why this fixed the problem, but my guess would be that it's related to the upgrades in `wgpu` or perhaps `winit` adapting to the compiler changes.
> 
> Could you please check whether this solves your problem as well?

Yeah using the `devel` branch aka. 0.9.0-rc0 solves the issue with newer compilers. My guess is the same as well. I read somewhere it related to how structs are aligned on the gpu, probably `wgpu` or `winit` as you said.
I just locked it to `rc0` in [my application](https://github.com/arminveres/algo-viz-rs).
