### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#1188]
Hi there.

As many who read this probably have already noted I have been neglecting ggez the past few months.

The reason for this has been my thesis, which will be finished somewhere at the start of June.

After that I plan to come back and work on some of the bugs and issues that have piled up.
This is going to be temporary though.

[As I said when I was given the honor of maintaining ggez](https://github.com/ggez/ggez/issues/875#issuecomment-822307887) I am neither deeply skilled in computer graphics (though I can say I learned quite a few things maintaining ggez) nor able to promise that I’ll maintain it forever.

Today I need to confess that I want to step back from maintaining ggez.
There just aren’t many things left that I’d want to develop further on it.

As I understand it nobbele feels a bit different, with one thing he still wants to achieve being greater platform support (Android and WASM), which I wholeheartedly support, though my desire to achieve it is weaker.
But, as nobbele too is currently occupied by other things and will be for quite a while, we think it is time to give someone else the chance to leave their mark on ggez and to help handle and organize all of the generous contributions that we receive from you and that deserve more attention than the two of us can currently provide.

If you’ve found ggez to be useful or fun to you and feel the desire to make it shine a little, then please go ahead and reply.

I can only say that I surely felt this way back then and am glad that I did ^^

Apart from this I only want to say: It has been a wonderful time with all of you. Thank you for walking a bit of this way with us :)

**Comment by sampullman** [comment]
I've been slowly writing a couple games with ggez over the past couple years(?!), and while I'm not really confident with either graphics or Rust programming, I'm interested in working on WASM support at some point.

I don't have a lot of time to spare, but may be able to assist with project management (responding to issues, PR reviews, docs, CI, etc).

Either way, it could be useful to put together a simple roadmap, or more detailed milestones, for potential future maintainers. Maybe expanding on or clarifying status of the items in #681 would be helpful.

Thanks for all your effort so far on the project!

**Comment by a1phyr** [comment]
Hi !

I don't have much time either nor a good acquaintance with the codebase, but I can definitely help with daily project maintenance.

**Comment by PSteinhaus** [comment]
On that note:

@tversteeg: As you've mentioned that you might be willing to take a look on ggez in general too (and seem to be handling the aseprite crate much better than we did ^^) I've now sent you an invitation to the group as well.

**Comment by Bowarc** [comment]
Hey, congrats on your thesis !

As much as i like the project, i don't think i have the time nor the knowledge (in graphics mostly) to tackle complex issues;
But i'd be glad to help (issues, pr reviews, discord, docs,  etc..).

**Comment by Bowarc** [comment]
Hey, congrats on your thesis !

As much as i like the project, i don't think i have the time nor the knowledge (in graphics mostly) to tackle complex issues;
But i'd be glad to help (issues, pr reviews, discord, docs,  etc..).

**Comment by Bowarc** [comment]
Hey, congrats on your thesis !

As much as i like the project, i don't think i have the time nor the knowledge (in graphics mostly) to tackle complex issues;
But i'd be glad to help (discord, docs, (some)issues, pr reviews, etc..).

**Comment by Vixeliz** [comment]
I don't know how confident I feel offering as I constantly doubt my skills lmao. However I have a lot of freetime and have come to really take a liking to ggez and have started to use it for some projects. I don't have advanced graphics api knowledge but I know enough I'm pretty sure to get around. I've been thinking about making my own framework for a while but just haven't I wanted to look at other options first. I'm also curious what thinks you do or don't want in ggez? Like for example it doesn't provide 3d out of the box rn which is fair but like is that something open to happening? I don't even mean complicated 3d just simple 3d for simple games(it's something I think would be a valuable edition longterm but could also see living in another crate). Either way point is I'm up to helping with this project. As for what I personally am working on in case that makes anyone feel more or less confident. I do a lot of random projects as I love programming and it's what I do most of the time. My main project is a voxel library/game based off of said lib. Anyways just wanted to offer assistance I guess cause I happen to be someone who has lots of freetimes and really like ggez and think I have at least some of the skills that may be needed.

**Comment by Vixeliz** [comment]
Are you still looking for maintainers who have a decent amount of time?

**Comment by Vixeliz** [comment]
I have a lot of time to work on ggez so I'm gonna go ahead and close this.

**Comment by nobbele** [comment]
@a1phyr @sampullman @tversteeg to those who are still here, can you join the discord server and ping me?
I'd like to clean up the member list a bit so also tell me if you're planning to be active and want to stay
