### ISSUE TITLE
Introduce a Blank/Nothing/None color

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#1198]
And in cases where it makes sense, it can be specialized to mean "no color" (as in no clearing color for canvases for example)

**Comment by Vixeliz** [comment]
I know I'm new but I would like to state my opinion I personally think options make sense in this case as that's what they are for. Other wise my other thought is as an enum is maybe a next best option?

**Comment by nobbele** [comment]
Option makes sense but `Some(Color::RED)` any time you want a color is ugly

**Comment by Vixeliz** [comment]
Yeah I wish rust would just wrap a value in some if it's a value

**Comment by Vixeliz** [comment]
Maybe we could make a macro?

**Comment by nobbele** [comment]
Clearing a canvas as blank and keeping the old copy is not the same
