### ISSUE TITLE
Filesystem::is_dir() doesn't work with zip files

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#12]
Because zip files have no idea of directories, they just store names, which may be paths.

We could fake it, but I'm not sure if it's a good idea or not.

**Comment by svenstaro** [comment]
How about physfs?

**Comment by icefoxen** [comment]
That's pretty much what we want but I'm not going to write a Rust binding for it anytime soon...

**Comment by onelson** [comment]
There already is a binding: https://github.com/PistonDevelopers/physfs-rs

**Comment by icefoxen** [comment]
Good to know, thanks!  Alas, that seems to conflict with issue #29 ...

**Comment by onelson** [comment]
Got it.

Owen Nelson

**Comment by icefoxen** [comment]
Zip files don't really have directories so the best you can do is "is there a file name that starts with this prefix".  Of course, this is a linear search.  

But 

So I'm classifying this as "more trouble than it's worth until someone complains more or I need it".  Bah.

If I ever do need it, what I was going to do was something like this.

```rust
fn zip_file_with_prefix(name: &str, archive: &mut zip::ZipArchive<T>) -> bool
    where T: io::Read + io::Seek
{
    // This still isn't a real directory search since it will match
    // say that "/a/b/foo" is a 'directory' containing "/a/b/foobar",
    // but I'm pretty much beyond caring.
    //
    // We dodge by saying a directory must have a terminating / even though
    // that's pretty wrong.
    if name.last() != '/' {
        return false
    }
    for i in 0..archive.len() {
        let file = zip.by_index(i).expect("Should never fail?");
        if file.starts_with(name) {
            return true;
        }
    }
    return false;
}
```

You can see the problems.
