### ISSUE TITLE
astroblasto example sleeps for 0 seconds

### ISSUE THREAD

**Issue by jonas-schievink** [ggez/ggez#121]
https://github.com/ggez/ggez/blob/5960c1b11d8a21a24fb16590686c54812deef921/examples/astroblasto.rs#L620

```
timer::sleep(Duration::from_secs(0));
```

This doesn't strike me as useful. If it is, a comment explaining what the semantics of such a sleep are would be appreciated.

**Comment by icefoxen** [comment]
Thank you!  Comment has been added explaining what this does.

**Comment by jonas-schievink** [comment]
I am not sure if that explanation is correct. For one, there's `std::thread::yield_now` which does the same thing. And doing that does not necessarily prevent 100% CPU use, since the scheduler will just run the same process again when there's nothing else to do.

**Comment by icefoxen** [comment]
I wasn't aware of `yield_now`, thank you!  That's probably a better way of achieving that.

Also upon experimenting you seem to be irritatingly correct about the CPU use.

**Comment by icefoxen** [comment]
Updated example to use `yield_now()`.  Better sleeping behavior would be nice...
