### ISSUE TITLE
Potential gpu memory leak

### ISSUE THREAD

**Issue by Bowarc** [ggez/ggez#1211]
**Describe the bug**
[The original message](https://discord.com/channels/1031224392174293002/1031224393126387764/1123947796102389860)
My gpu memory is getting filled fast when creating a new graphics::Image every ggez::event::EventHandler::Draw call

**To Reproduce**
I don't rly know why, i guess it's the fact that i'm creating a new `ggez::graphics::Image` every frame ?

**Expected behavior**
have my graphic memory not fill and my pc staying alive more than 10 secconds

**Screenshots or pasted code**
[This is the (ugly) code that lead to the problems ](https://github.com/Bowarc/ggez_potential_gpu_leak)

**Hardware and Software:**
 - ggez version: 0.9.0
 - OS: w 10.0.19045
 - Graphics card:  NVidia Geforce GTX 2070.
 - Graphics card drivers: up to date (driver version: 536.23)

**Comment by Bowarc** [comment]
I don't know if that's relevant but the game im making (Vupa)
While standing still, render calls doesn't fluctuate, no new image (nor sound but i don't think that matters) are loaded,
This is the fame stat debug: (stays consistent across time in the test)
![image](https://github.com/ggez/ggez/assets/63136904/8dbe08e2-d62c-457e-9be9-3f249bafb569)

The render loop keeps loosing frames per sec.

Timings at the start:
Game render request fetching: 100-200µs,
Frame debug stat render request fetching: 118-150µs,
Gui render request fetching:  100-100ns,
Request rendering: 800-990+µs,

Timings at the end:
Game render request fetching: ~140µs,
Frame debug stat render request fetching: ~140µs
Gui render request fetching:  ~100ns,
Request rendering:  7ms,

The Request rendering only creates canvases(one for each game layer (map is drawn before characters etc..)), and render images, meshes, text, and egui windows on thoses canvases.
Then `.finish()` the canvases.

I gathered more infos with an external tool (process hacker).
Gpu stats across time
![image](https://github.com/ggez/ggez/assets/63136904/01f7b21a-116a-4a02-9ace-da53f8e95ab2)

fps infos ?
![image](https://github.com/ggez/ggez/assets/63136904/b2579ef3-2334-433d-9f7e-a78318055325)

Cpu stats across time
![image](https://github.com/ggez/ggez/assets/63136904/0edfc753-4129-43c3-8546-7705e23ee4ca)


Hope that helps :c

**Comment by Bowarc** [comment]
My 'render' code (of my 'Vupa' game) may be flawed, so i'll add the usefull parts here.
`render_request.rs`
```rust
pub struct RenderRequest {
    pub inner: HashMap<render::Layer, Vec<(RenderRequestBit, render::DrawParam)>>,
}

#[derive(Clone, Debug)]
pub enum RenderRequestBit {
    Sprite(sprite::SpriteId),
    Mesh(graphics::Mesh),
    MeshBuilder(graphics::MeshBuilder),
    Text(graphics::Text),
    EguiWindow,
}
```
^Some utils functions and From implementation were removed.
The drawparam struct is a small wrapper over the `ggez::graphics::DrawParam` that has dynamic scale depedning on the target size of image vs the size of the image in the `ggez::graphics::InstanceArray` (simply store a target size and at render time, get the size of the image in the IA and divide the target by the image size).

`render.rs`
```rust
pub fn render(
    ctx: &mut Context,
    mut render_request: RenderRequest,
    sprite_bank: &mut sprite::Bank,
    camera: Camera,
    general_config: config::WindowConfig,
    menu_backend: &mut ggegui::Gui,
    loader_handle: &mut loader::Handle,
) -> GameResult<RenderLog> {
    let mut log = RenderLog::new();
    for lyr in Layer::iter() {
        if let Some(render_request_bits) = render_request.get_mut(&lyr) {
            let (layer_log, canvas) = render_nosort(
                ctx,
                render_request_bits,
                sprite_bank,
                camera,
                general_config,
                menu_backend,
                loader_handle,
            )?;
            log += layer_log;
            canvas.finish(ctx)?;
        }
    }
    Ok(log)
}


fn render_nosort(
    ctx: &mut Context,
    render_request_bits: &mut [(RenderRequestBit, DrawParam)],
    sprite_bank: &mut sprite::Bank,
    camera: Camera,
    window_config: config::WindowConfig,
    menu_backend: &mut ggegui::Gui,
    loader_handle: &mut loader::Handle,
) -> GameResult<(RenderLog, graphics::Canvas)> {
    let mut log = RenderLog::new();

    let mut canvas = graphics::Canvas::from_frame(ctx, None);

    let mut used_sprites: Vec<sprite::SpriteId> = Vec::new();

    log.elements += render_request_bits.len() as i32;

    for (bit, dp) in render_request_bits.iter_mut() {
        match bit {
            RenderRequestBit::Sprite(sprite) => {
                let ia = sprite_bank.get_sprite(ctx, *sprite, loader_handle);
                let img = ia.image();

                ia.push(dp.to_ggez_scaled((img.width(), img.height())));
                if !used_sprites.contains(sprite) {
                    used_sprites.push(*sprite);
                }
                log.sprites += 1;
            }
            RenderRequestBit::Mesh(mesh) => {
                canvas.draw(mesh, dp.to_ggez_unscaled());
                log.meshes += 1;
                log.draw_calls += 1
            }
            RenderRequestBit::MeshBuilder(meshbuilder) => {
                canvas.draw(
                    &ggez::graphics::Mesh::from_data(ctx, meshbuilder.build()),
                    dp.to_ggez_unscaled(),
                );
                log.meshes += 1;
                log.draw_calls += 1
            }
            RenderRequestBit::Text(text) => {
                text.set_font(font::FontId::HasklugNF);
                canvas.draw(text, dp.to_ggez_unscaled());
                log.texts += 1;
                log.draw_calls += 1
            }
            RenderRequestBit::EguiWindow => {
                // In the ggegui implementation, the drawparam is discarded
                canvas.draw(menu_backend, dp.to_ggez_unscaled());
                log.draw_calls += 1;
            }
        }
    }

    for sprite in used_sprites {
        let ia = sprite_bank.get_sprite(ctx, sprite, loader_handle);
        canvas.draw(ia, ggez::graphics::DrawParam::new());
        ia.clear();
        log.draw_calls += 1;
    }
    Ok((log, canvas))
}
```
`sprite::Bank` is where all the IA are stored.
`sprite::SpriteId` is an enum that is used as key to get the correct IA in the bank

**Comment by Vixeliz** [comment]
I believe on discord you said this one was fixed too. So i'm gonna go ahead and close feel free to tell me to reopen if the problem still exist.
