### ISSUE TITLE
Filesystem: Can't create files

### ISSUE THREAD

**Issue by leod** [ggez/ggez#123]
The following code fails at runtime when trying to create a new file:
``` rust
extern crate ggez;

use ggez::conf;
use ggez::Context;

pub fn main() {
    let c = conf::Conf::new();
    let ctx = &mut Context::load_from_conf("helloworld", "ggez", c).unwrap();
    let f = ctx.filesystem.create("gg.txt").unwrap();
}
```

Error message on Windows:
>thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResourceNotFound("gg.txt", ["C:\\Users\\Leo\\Projects\\ggez-bug\\target\\debug\\resources", "C:\\Users\\Leo\\AppData\\Roaming\\ggez\\helloworld"])', src\libcore\result.rs:860

Using b7aeb70e14a709c4c63c06a1659d70f031dfd745.

The reason seems to be that `Filesystem::new` creates all the PhysicalFS as readonly. Code that would create a writeable PhysicalFS is [commented out](https://github.com/ggez/ggez/blob/b7aeb70e14a709c4c63c06a1659d70f031dfd745/src/filesystem.rs#L148).

Regardless of how this is addressed, it would be preferable if `OverlayFS::open_options` did not swallow the error message given by `PhysicalFS::open_options`, i.e. if the user actually sees that all mounted filesystems are readonly.

**Comment by icefoxen** [comment]
Well that's embarrassing.  Thank you for the bug report.

Fixed in 79099b3e261363ae1c0f080e6e756ca3eeb0153a .
