### ISSUE TITLE
Could not compile ggez due to use of unstable library feature

### ISSUE THREAD

**Issue by aditya-exe** [ggez/ggez#1231]
Use of unstable function is_okay_and() in image.rs

**To Reproduce**
Just add dependency of ggez 0.9.3 and build

**Expected behavior**
Build will fail

**Screenshots or pasted code**
![Screenshot 2023-07-14 001947](https://github.com/ggez/ggez/assets/47419610/751346a2-cba0-40d6-b37e-efe0d2e7c0be)

**Comment by Vixeliz** [comment]
Try updating your rust compiler for now if possible. We are still unsure on what compiler version we should target it but that should work for now if u are able to

**Comment by aditya-exe** [comment]
> Try updating your rust compiler for now if possible. We are still unsure on what compiler version we should target it but that should work for now if u are able to

will try that, thanks!
