### ISSUE TITLE
Expose possible values of ggez::event::Mod

### ISSUE THREAD

**Issue by leod** [ggez/ggez#124]
It seems that, in order to actually access the contents of `ggez::event::Mod`, the user needs to add a dependency on sdl2, and use `sdl2::keyboard::{CAPSMOD,LALTMOD,LCTRLMOD,...}`.

Figuring out how to use this was a bit confusing for me. Maybe I've missed something. How about re-exposing the possible values in `ggez::event` to make it a bit easier?

**Comment by icefoxen** [comment]
This SHOULD be done already, see <https://docs.rs/ggez/0.3.3/ggez/event/struct.Mod.html>.

Is it not working properly?

**Comment by icefoxen** [comment]
Oh, derp.  I frankly did not see those constants.  Should be fixed now.
