### ISSUE TITLE
failed to run custom build command for `libudev-sys v0.1.4`

### ISSUE THREAD

**Issue by zxcqirara** [ggez/ggez#1240]
When I build my project, cargo throws me the error:
![image](https://github.com/ggez/ggez/assets/36239195/927eee52-a7ff-48c7-866c-be1ae4eece47)
but I have it already installed:
![image](https://github.com/ggez/ggez/assets/36239195/b9796d36-d1f0-46b8-95ca-c91d95630f9e)

**Comment by a1phyr** [comment]
This is an issue with `libudev-sys`, not `ggez` : https://github.com/dcuddeback/libudev-sys/issues/13

**Comment by RuofengX** [comment]
Install libudev-sys may help. On my fedora pc, it fixed by `sudo dnf install systemd-devel`
