### ISSUE TITLE
Filesystem::open_options is inaccessible

### ISSUE THREAD

**Issue by leod** [ggez/ggez#125]
It is not possible to use `Filesystem::open_options` as `vfs::OpenOptions` is not exposed to the user. A possible fix would be to `pub use vfs::OpenOptions` in `ggez::filesystem`.

**Comment by icefoxen** [comment]
Sorry for the delay on this one, life has been a little slammed.

`vfs::OpenOptions` has now been re-exported as `ggez::filesystem::OpenOptions`, please confirm it works as you want it to when you have a moment.
