### ISSUE TITLE
Drawn images have messed up colors

### ISSUE THREAD

**Issue by HenryTheCat** [ggez/ggez#126]
I followed the examples in the `/example` folder to draw a square with a solid color (say green). Then, after selecting a foreground (say red), I superimposed a png image composed by a transparent area and a white area.

The transparency works as expected (that is, it shows the underlying green color). The white area, instead, is a mixture of the underlying green color and the selected red color.

I attach the png image and a screenshot as a reference (which is more complex than the example I described, but the issue should be clear anyway).

![barbute](https://user-images.githubusercontent.com/13203616/29461937-72d14cd2-8425-11e7-8ed1-baa9d982f5bb.png)

![screen-1](https://user-images.githubusercontent.com/13203616/29461926-671fd494-8425-11e7-9127-13f8a9f92eec.jpeg)

**Comment by EGhiorzi** [comment]
After some experimentation, I worked out that setting the foreground color to `WHITE` before drawing the images produces the right result. Though, should the foreground color influence the way the image is printed?

**Comment by icefoxen** [comment]
The foreground color is multiplied with the image color, as in Love2D.

This should probably be better documented though.

**Comment by EGhiorzi** [comment]
I see, but then why does a white image with red foreground give that result? It looks like the color is multiplied with the underlying green color as well, which does not seem right.

**Comment by icefoxen** [comment]
Sorry, it's unclear to me what exactly you're doing here.  If you have a white image and do 

```rust
graphics::set_foreground_color(ctx, [1.0, 0.0, 0.0, 1.0].into())?;
graphics::draw(ctx, my_thing, dest, angle)?;
```

then you should get a red image no matter what you're drawing it on.  In the screenshot you posted you have red images drawn upon two different shades of green background, and green images drawn on both green and grey background, and the image color appears to be the same in all cases.

**Comment by HenryTheCat** [comment]
Ok, that's embarassing, but I tried again and it actually worked alright. I don't know what I was messing up before. Thanks for the answer, to me the issue can be closed.
