### ISSUE TITLE
ResourceNotFound Error when running example 02

### ISSUE THREAD

**Issue by mmhamdy** [ggez/ggez#1263]
Hi 👋

I'm trying to run the `02_hello_world.rs` example but it doesn't seem to be able to locate the font file.

## Version
```
ggez = "0.9.3"
```

**Comment by Bowarc** [comment]
Could not reproduce, did you ran using ?
```bash
cargo r --example 02_hello_world
```

**Comment by sampullman** [comment]
Closing as non-reproducible. Comment or re-open it if you're still having trouble, or can provide more detail!
