### ISSUE TITLE
Conceptual questions about Mesh and InstanceArray

### ISSUE THREAD

**Issue by w4ngzhen** [ggez/ggez#1272]
Hello everyone, after reading the official documentation of `ggez` and the related sample code, I have the following questions: 
1. For text rendering, I flipped through the previous issue and saw that there is a concept that is clearly TextCache or something, but now there seems to be no such thing, is there no such caching mechanism now, because ggez is cached when rendering internally? 
2. Can I understand the relationship between Mesh and InstanceArray: Mesh can be used as a "template". At the time of rendering, the "draw_instanced_mesh" is based on this Mesh instance, combined with multiple DrawParam in the InstanceArray, to render to the screen for better rendering performance? So, if I want to render hundreds of rectangles at different locations on a screen, I just need to construct a Mesh of one rectangle and then provide hundreds of DrawParams?

**Comment by jazzfool** [comment]
1. that's right, text/textfragment are now just lightweight structures (basically a vec of strings) and batching+caching happens internally, you don't need to "queue up" text draws anymore either as that is automatic now
2. correct, an instancearray is just a big list of drawparams (instances) tied to an image - by default it will render with the "Quad" mesh (so actually you don't need to create a rectangle mesh yourself), but with draw_instanced_mesh you can select a mesh you want to draw for each instance instead - this replaces the MeshBatch behavior from 0.7.x

**Comment by w4ngzhen** [comment]
> 1. that's right, text/textfragment are now just lightweight structures (basically a vec of strings) and batching+caching happens internally, you don't need to "queue up" text draws anymore either as that is automatic now
> 2. correct, an instancearray is just a big list of drawparams (instances) tied to an image - by default it will render with the "Quad" mesh (so actually you don't need to create a rectangle mesh yourself), but with draw_instanced_mesh you can select a mesh you want to draw for each instance instead - this replaces the MeshBatch behavior from 0.7.x

Thank you for the reply, ggez was fantastic!

**Comment by w4ngzhen** [comment]
> 1. that's right, text/textfragment are now just lightweight structures (basically a vec of strings) and batching+caching happens internally, you don't need to "queue up" text draws anymore either as that is automatic now
> 2. correct, an instancearray is just a big list of drawparams (instances) tied to an image - by default it will render with the "Quad" mesh (so actually you don't need to create a rectangle mesh yourself), but with draw_instanced_mesh you can select a mesh you want to draw for each instance instead - this replaces the MeshBatch behavior from 0.7.x

Thank you for your reply, ggez is really great!
