### ISSUE TITLE
ggez::graphics::clear() is missing

### ISSUE THREAD

**Issue by ldokduy20** [ggez/ggez#1288]
Is it intentional that the clear() function for the module graphics has been absent since version 0.8.0-rc0? If so, could you please tell me how to get the screen cleared?

**Comment by ldokduy20** [comment]
I apologize for not being clear enough; I meant to clear the canvas with various colors. And should I just fill the screen with a rectangle if clearing isn't an option?

**Comment by sampullman** [comment]
You can take a look at how the examples do it, here's one option from `02_hello_world.rs`:

```rust
let mut canvas =
            graphics::Canvas::from_frame(ctx, graphics::Color::from([0.1, 0.2, 0.3, 1.0]));
```

and another option from `05_astroblasto.rs`:

```rust
let mut canvas = graphics::Canvas::from_screen_image(ctx, &mut self.screen, Color::BLACK);
```

I'm not actually sure what's better, but both should work. Maybe somebody else can chime in.

**Comment by ldokduy20** [comment]
Thank you very much! I got it now.
