### ISSUE TITLE
Update to rodio 0.20 breaks sound playback with fade-in = 0

### ISSUE THREAD

**Issue by tryone144** [ggez/ggez#1296]
**Describe the bug**
The update to rodio 0.20 in https://github.com/ggez/ggez/commit/49a328c20691c57e063ce9628158d7db9bf6d15c broke sound playback.

The update added a new assertion to ensure the fade-in duration is &gt; 0ns: https://github.com/RustAudio/rodio/commit/9c0706afbfcd82391515a242fa44fb6b8ed1a402

Since the default value for the fade-in duration is a zero-length duration, this assertion is always triggered unless a different fade-in duration is selected before playing the sound.

https://github.com/ggez/ggez/blob/4ac5dcc4a328192617046e0c2af13424c57705a4/src/audio.rs#L217-L227
https://github.com/ggez/ggez/blob/4ac5dcc4a328192617046e0c2af13424c57705a4/src/audio.rs#L326-L345

**To Reproduce**
Run the `astroblaster` example `$ cargo run --example 05_astroblaster` and fire a shot.

**Expected behavior**
No panic when leaving parameters at default (or in general, really :sweat_smile:).

**Hardware and Software:**
 - ggez version: current git `devel` branch

**Potential solutions**
 - Only call `fade_in()` when fade-in is set to a value other than zero-length `time::Duration`.
 - Allow zero-length `time::Duration` in upstream rodio.

**Comment by a1phyr** [comment]
My bad, I should have tested this better. Thanks for reporting that !
