### ISSUE TITLE
smart-default is the shit

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#133]
and we should use it.  :D

**Comment by Manghi** [comment]
For those who don't know: https://www.reddit.com/r/rust/comments/6uj9xs/my_first_crate_smartdefault_a_default_derive_with/

**Comment by icefoxen** [comment]
Ok, it's a little less awesome because the values it deals with have to be strings which then get turned into rust expressions.

But it does seem to work; see c80b30f

**Comment by icefoxen** [comment]
Eh, added a couple more little things but I'm less sold on it than I used to be.  We'll roll with it for now.
