### ISSUE TITLE
Add "sprite batching"

### ISSUE THREAD

**Issue by termhn** [ggez/ggez#135]
As referenced in #127, I thought I'd open up its own issue as it's something I'd be interested in contributing to, so we can discuss how to do it The Right Way TM :P 

One thing I'd like to know people's thoughts on is if you think it would be good to try to implement generic automatic sprite batching for objects with some set of common characteristics that would lend themselves to be batched or if we want to make the user manually use a SpriteBatch?

**Comment by icefoxen** [comment]
Automatic batching for things that happen to be similar is a nightmare waiting to happen because it hides context-dependent information from the user.  It's that sort of trickery that makes OpenGL drivers so finicky (oh I reordered these two draw calls and now things are super slow)...  plus, gfx-rs caches unchanged context already.

If we want things to be fast we just need to select a certain amount of state that can be shared (basically the `DrawParams` object) and shove it into a UBO.  Look at how Love2D does it; it doesn't have to be super tricksy to be useful.

**Comment by termhn** [comment]
Fair enough, basically what I was thinking as well.

I do think it would be useful for SpriteBatching to be generic to all Drawables rather than just Images, which unless I'm understanding how this would work wrong, should be possible.

**Comment by icefoxen** [comment]
That's a bit of a taller order because `Mesh` breaks the assumptions that `Image` and `Text` both have.  (ie, that it's a textured quad.)  Still, it might be possible.

**Comment by termhn** [comment]
True. Perhaps, at the start anyway, have it only extend to rectangles at first so that `point`s and other uses of rectangles in procedurally-generated graphics (as had been mentioned in #127) would be able to take advantage without having to make small rectangle images to use as sprites.

**Comment by dpogretskiy** [comment]
I've made a tool, for parsing json from TexturePacker and creating other representation from it, i did some animations based on it already. Not sure about performance, but it basically shares one image to draw everything. Ui part is just a bunch of copy-pasted code, but other things can be useful.

https://github.com/dpogretskiy/spritesheet-marker

**Comment by termhn** [comment]
Gonna start playing with this later today I think. The way LOVE does it is nice--it's useful just on its own for batching one image on each sprite but also extensible enough through adding "Quads" which specify UVs on the underlying texture for each sprite to use that it also works in conjunction with sprite sheets/atlases... 

I'm not sure I like that every sprite instance must have its own quad in LOVE; I was thinking it might be better to be able to add "quads" to the batch and get an ID back for each, and then be able to optionally specify a quad ID when you add a new sprite instance to the batch.

Something like:
```rust
impl SpriteBatch {
    pub fn add_quad(x: f32, y: f32, width: f32, height: f32) -> usize {}
    pub fn add_from_quad(rect: graphics::Rect, quad: graphics::SpriteBatch::Quad) -> usize {}
}

let batch = SpriteBatch::new(blah);
let sprite1_quad = batch.add_quad(tx, ty, tw, th);
let sprite1_rect = graphics::Rect::new(px, py, w, h);
let sprite1 = batch.add_from_quad(sprite1_rect, sprite1_quad);
```

**Comment by onelson** [comment]
@dpogretskiy Loving your animation showcase. I have been very slowly developing https://github.com/onelson/omn-sprites-rs/ which deals with managing playback of tagged frame sets (clips) inside a spritesheet. I hadn't yet thought about using a state machine (yours looks like mine, which looks like the one from amethyst, :wink:) to transition from clip to clip.

**Comment by dpogretskiy** [comment]
@onelson you got me 😊 It's exactly amethyst thingy adaptation.
@termhn that would be handy, i basically want a convinient way of getting things into batches and most important out of them, without heavy lifting. Current ggez way of specifying `src` in draw parameters object is very artifact prone, cause of fractioning instead of pixel coordinate model, and calculating fractions feels awkward, so it's another place to look into.

**Comment by termhn** [comment]
@onelson I like what you've got going on there!

**Comment by icefoxen** [comment]
Yeah feel free to make PR's adding interesting/useful tools and toys you make to https://github.com/ggez/ggez/blob/master/docs/Projects.md .  ...Though I confess I can't get https://github.com/dpogretskiy/ggez-animation-showcase to work; it says it can't find a dependency `tilesheet-marker`, which I can't find in your github.

**Comment by onelson** [comment]
@termhn Thanks! Early still, but sort of fun. (Sorry for the off-topic posts here!)

**Comment by termhn** [comment]
@onelson No prob. 

I also have the same issue as @icefoxen, @dpogretskiy

**Comment by dpogretskiy** [comment]
@termhn @icefoxen Yeah, sorry for that, i removed that dep from the project, and just moved all needed stuff into it. Should be fine.

**Comment by icefoxen** [comment]
Gloriously implemented in PR #144.  Needs proofing, testing, and general banging-on, but it seems to work very well.

**Comment by termhn** [comment]
Yay :) gonna work on making it work for rects/points with no base image now as well

**Comment by dpogretskiy** [comment]
Not usable with camera from ggez-goodies rn, diggin into code, everything is positioned in y-reverse. And some few more weird artifacts, aside from camera. I guess something else was touched as well.

**Comment by termhn** [comment]
Hmmm, I'll take a look... it's more likely that there's some kind of bug
with the batch param code.

**Comment by termhn** [comment]
@dpogretskiy I'm not getting anything weird on the current ggez camera or my new version, but I can't get the "current" version of your animation showcase to compile... what kind of artifacts are you seeing?

**Comment by dpogretskiy** [comment]
@termhn damn, rushing is bad 😄 Basically version of ggez for other dep needs same ggez version, now it's on branch current of spritesheet-marker repo. As far as i got it, spritebatch does not properly propogate DrawParams across pieces, but some stranger things happen to player, since he does not use spritebatch.

**Comment by termhn** [comment]
Seems to work perfectly for me? 
![image](https://user-images.githubusercontent.com/887711/30264770-cdc2bd3a-968e-11e7-8baf-ca2db22f8df5.png)

Cool demo by the way.

**Comment by termhn** [comment]
Alright, I think I figured out what was going on as far as other sprites being messed up when spritebatches are used and submitted a PR #147 to fix it.

I think that other than that it's working fine with the camera, it's just possibly not as intuitive as you would think. If you use `Default::default()` as the draw param for `draw_ex_camera()` then it will attempt to place the origin (top-left corner or what would normally think of as `(0, 0)` in ggez screen coordinates) of the sprite batch at the point `(0, 0)` in the camera's world space (which is the center of the camera's initial frame). If you want the batch to be drawn in the same place as with no camera, you'd need to offset the `dest` in its `DrawParam` by `(-CAMERA_VIEW_WIDTH / 2.0, CAMERA_VIEW_HEIGHT / 2.0)`. I made a PR on the ggez-goodies repo that makes the camera test example use spritebatches like this that you can check out: https://github.com/ggez/ggez-goodies/pull/4

**Comment by termhn** [comment]
@dpogretskiy As far as the inversion... I looked into your code and I think it's your generator that is doing things backwards, not the sprite batching or integrating it with the camera. If I invert your y position in the level generation then it works perfectly. Change this line https://github.com/dpogretskiy/ggez-animation-showcase/blob/current/src/level/mod.rs#L250 to 

```rust
(-(pixel_height as i32) + v as i32 * 128) as f32,
```

**Comment by icefoxen** [comment]
ggez does some Magic to deal with inverted Image's when the coordinate system happens to be y-pointing-downwards: https://github.com/ggez/ggez/blob/master/src/graphics/mod.rs#L1108-L1113

I dislike this but still wobble back and forth over what the Right Solution is.

**Comment by termhn** [comment]
Yes, I use that code in Spritebatch currently, but without the y-invert part implemented... made a little comment here: https://github.com/ggez/ggez/blob/master/src/graphics/spritebatch.rs#L68

I thought of that initially when I was looking at @dpogretskiy 's code, so I pointed it to my local version of ggez and tried inverting the y-scale... this made the images invert as well and so they tiled properly, but it doesn't actually solve the problem as now the whole thing is just inverted. This doesn't actually apply in this particular case because the camera doesn't actually change ggez's coordinate system.

The thing to think about with the way that sprite batches work with the ggez-goodies (or any external) camera is that individual instance positions/transforms inside the batch are not affected by the camera state or its coordinate system transformation when you call one of the camera's draw functions on it; you have to do this manually when you add the instances. Only the transform of the batch as a whole is affected. There's not really an elegant way of making that happen internally with the way the camera is an add-on that doesn't actually modify internal ggez state... you'll have to use the camera's world-to-screen/screen-to-world conversions manually when creating your draw params to place things into the sprite batch. In order to integrate them better without the user having to make that effort, you'd need the camera to be more tightly coupled with the actual rendering pipeline.

**Comment by dpogretskiy** [comment]
@termhn @icefoxen totally, i inverted all sprite positions upside down, so that camera could turn them backwards,
but spritebatch is special in that regard, so i guess bringin camera into ggez itself is the only way to make it work really, without unnecesary heavy lifting. Especially as camera is such a generic thing, nothing can go wrong really.

**Comment by icefoxen** [comment]
"camera is such a generic thing, nothing can go wrong" but https://github.com/termhn/ggez-goodies/blob/fa0e877b28fc4daae822030fcecdf953bcf9a667/src/camera.rs is 800 lines, which is absurd to incorporate into `graphics/mod.rs` which is 1300 lines total.

Sprite batches have *already* made the camera code go wrong.

We don't need a camera that will try to do everything.  We need a system that allows a user to easily build cameras that do what they specifically need to do.

Anyway, for camera stuff please take it to a different issue.

**Comment by termhn** [comment]
Definitely agree; my rewritten camera is not the appropriate style to integrate into the core. After discussing a bit on IRC, I think an actual built-in camera probably isn't the way to go... but, that's another issue.

**Comment by icefoxen** [comment]
@termhn Do we think this is done?  It seems to work pretty well.  :heart:

**Comment by termhn** [comment]
Yep, I think it's done for now at least!

One thing to think about is that this will might to be changed somewhat if we want GL ES 2.0 support as I believe instance buffers/instanced rendering is only supported through an extension.

**Comment by termhn** [comment]
However, I think that's a problem for the future at this point so I'm going to go ahead and close this issue.

**Comment by acheronfail** [comment]
@icefoxen I just had one question about how I could use `SpriteBatch`:

I would like to render many items on the screen and have been having great success using `SpriteBatch` with `Image::solid`. But I'd like to render _circles_ on the screen rather than squares.

It looks like I could do this using `Image::from_rgba8`? - but I'm not sure about how I could do that to render a circle? Do you have any suggestions on how I could go about doing that without using an actual image file?

**Comment by icefoxen** [comment]
Using an actual image file is the easy way.

You can also use a `MeshBuilder` to construct a single mesh consisting of a bunch of circles.
