### ISSUE TITLE
Make window mode setup easier

### ISSUE THREAD

**Issue by Ironmaggot** [ggez/ggez#138]
Make setting the window mode up easier for beginners like me. The Conf doesn't offer any way to set such things. By mode I mean fullscreen, borderless desktop_sized window, windowed.

Possible solutions:

- Additional field for the Conf setup called "window mode"
- An example which is built to be fullscreen

Choosing a window mode shouldn't be a hard feature - pygame(a python gamedev API which also focuses on being simple) could do it, so should ggez.

**Comment by icefoxen** [comment]
https://docs.rs/ggez/0.3.3/ggez/graphics/fn.set_mode.html is what you want.

Though you are right, it should be simpler and/or documented better.

**Comment by icefoxen** [comment]
Fixed in a37f9fad7afd5bf2b12e4e2b25cff2714b9f3edd ; check it out.  :D
