### ISSUE TITLE
[question] Blit surfaces

### ISSUE THREAD

**Issue by sanpii** [ggez/ggez#139]
Hello,

Is it possible to do something like [that](https://raw.githubusercontent.com/tomassedovic/tcod-rs/master/examples/blit.rs)?

I found [Canvas](https://love2d.org/wiki/Canvas) in LÖVE but nothing to render its at an arbitrary position.

I don’t find canvas in ggez.

**Comment by icefoxen** [comment]
Short answer: not yet. We don't really have software surfaces, or render targets. It would be nice if someone wants to make a PR for it. :-)

**Comment by nlordell** [comment]
I submitted a PR that with a very basic Canvas implementation here #180. Might do what you are looking for.
