### ISSUE TITLE
Testing on Mac?

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#14]
Looks like Travis doesn't really do this, but it'd be really nice to be able to make sure ggez at least compiles and runs minimal tests on those platforms...

**Comment by svenstaro** [comment]
We can always cross-compile to OSX and Windows at least. Running Windows tests with wine works alright for me.

**Comment by icefoxen** [comment]
Well it's possible to at least build and run this by hand on windows using mingw, if you acquire the pre-built SDL libraries and manage to put them in the right place (they go somewhere under `~/.multirust`, not in the mingw system directories).  So it's good that it's at least possible.

**Comment by shmutalov** [comment]
![image](https://cloud.githubusercontent.com/assets/8098898/21224572/a05355b8-c2ee-11e6-928b-b01fdda64ffa.png)

Works on Windows 10 x64, rust 0.13 mingw, also with sounds

**Comment by icefoxen** [comment]
Great!  I just wish there were a good way to do so automatically.

**Comment by svenstaro** [comment]
I think we can. Travis does have Mac system's and we can certainly test Windows using Wine.

**Comment by Gordon-F** [comment]
@icefoxen How about using appveyor build like other Rust project do? For example - [zoc](https://github.com/ozkriff/zoc/blob/master/appveyor.yml).

Download SDL2 dll and compile like Travis do id.

**Comment by icefoxen** [comment]
Looks fairly reasonable, that might be a solution if we don't want to mess with Wine.  Any thoughts, @svenstaro ?

**Comment by shmutalov** [comment]
@icefoxen [ZoC](https://github.com/ozkriff/zoc) builds Windows binaries with AppVeyor:
1. [Makefile](https://github.com/ozkriff/zoc/blob/master/Makefile)
2. [appveyor.yml](https://github.com/ozkriff/zoc/blob/master/appveyor.yml)

**Comment by kevinw** [comment]
I'm on OS X 10.11.6 and just tried running the example program on the website, and got:

```
 🐇  RUST_BACKTRACE=1 cargo run
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/gg_test`
WARNING: Encountered error: ResourceNotFound("\'resources\' directory not found!  Should be in \"/Users/kevin/src/gg_test/target/resources\"")
WARNING: Encountered error: ResourceNotFound("\'resources.zip\' file not found!  Should be in \"/Users/kevin/src/gg_test/target/resources.zip\"")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownError("")', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x10dd8e828 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x10dd90b8f - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x10dd8fc85 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x10dd901d6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x10dd90074 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x10dd8ff92 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x10dd8fef7 - rust_begin_unwind
   8:        0x10ddb70b0 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x10dc7e0bc - core::result::unwrap_failed::h17c345877c1909d8
  10:        0x10dc7a7b5 - <core::result::Result<T, E>>::unwrap::hd08a8659915d4635
  11:        0x10dc82e63 - gg_test::main::h429237970e4d4bd7
  12:        0x10dd9114a - __rust_maybe_catch_panic
  13:        0x10dd8f7c6 - std::rt::lang_start::h538f8960e7644c80
  14:        0x10dc83249 - main
```

**Comment by icefoxen** [comment]
@kevinw Did try making a resources dir under `/Users/kevin/src/gg_test/target/resources` and putting the `DejaVuSerif.ttf` font file in it?

**Comment by kevinw** [comment]
@icefoxen that did remove the first WARNING, but ultimately did not fix the panic. a bit of googling tells me there's no line numbers on OS X :(

```
 🐇  RUST_BACKTRACE=1 cargo run
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/gg_test`
WARNING: Encountered error: ResourceNotFound("\'resources.zip\' file not found!  Should be in \"/Users/kevin/src/gg_test/target/resources.zip\"")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownError("")', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x101119828 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x10111bb8f - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x10111ac85 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x10111b1d6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x10111b074 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x10111af92 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x10111aef7 - rust_begin_unwind
   8:        0x1011420b0 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x1010090bc - core::result::unwrap_failed::h17c345877c1909d8
  10:        0x1010057b5 - <core::result::Result<T, E>>::unwrap::hd08a8659915d4635
  11:        0x10100de63 - gg_test::main::h429237970e4d4bd7
  12:        0x10111c14a - __rust_maybe_catch_panic
  13:        0x10111a7c6 - std::rt::lang_start::h538f8960e7644c80
  14:        0x10100e249 - main
```

**Comment by icefoxen** [comment]
@kevinw  Do any of the other example programs in the repository work?  Does it build when you remove all the code from the `GameState` methods?  It's kind of crappy that we can't see where the unwrap is actually happening, but the only unwraps in the example code are in the resource loading code...
