### ISSUE TITLE
about resources dir and the error :  does not have these features: `cargo-resource-root`

### ISSUE THREAD

**Issue by TakWolf** [ggez/ggez#140]
```
C:/Users/TakWolf/.cargo/bin/cargo.exe run --features=cargo-resource-root
error: Package `ggez-project-seed v0.1.0 (file:///F:/GitOSC/ggez-project-seed)` does not have these features: `cargo-resource-root`
```

It's run on the platform windows, but the same error on platform macOS.

I follow the docs [BuildingForEveryPlatform](https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md):

> Now run cargo run --features=cargo-resource-root and it should build and run! ...maybe. It depends on what platform you're on and what libraries you have installed. To make super-duper sure you have all the bits and pieces in the right places to make this always work, read on!

If i copy resources dir to target/debug/resources, it can regular work. But this way is ugly.

What the right way to appoint the resources dir?

============================

I see this is a fresh project being developing, and there must be a lot of problems that haven't been solved yet. At least I have a way to run it temporarily.

If the reason is in construction, please ignore this issues.

**Comment by icefoxen** [comment]
That is a mistake in the documentation, I believe.  For a separate project using ggez, the feature flag is on the ggez crate.

Try setting in your cargo.toml:

`ggez = { version = "0.3", features = ["cargo-resource-root"] }`

**Comment by TakWolf** [comment]
ggez = { version = "0.3", features = ["cargo-resource-root"] }

It works, thanks.
