### ISSUE TITLE
Can not run on platform Windows. ggez = "0.3.3"  and  SDL2 lib is 2.0.5

### ISSUE THREAD

**Issue by TakWolf** [ggez/ggez#141]
![image](https://user-images.githubusercontent.com/6064962/30063917-cf8ca122-9282-11e7-871c-362403879f5c.png)

```
C:/Users/TakWolf/.cargo/bin/cargo.exe run
   Compiling ggez-project-seed v0.1.0 (file:///F:/GitOSC/ggez-project-seed)
    Finished dev [unoptimized + debuginfo] target(s) in 6.31 secs
     Running `target\debug\ggez-project-seed.exe`
error: process didn't exit successfully: `target\debug\ggez-project-seed.exe` (exit code: 255)

Process finished with exit code 255
```

I set my sdl evn follow https://github.com/Rust-SDL2/rust-sdl2#windows-with-build-script

I seems like the sdl problems. Because https://github.com/Rust-SDL2/rust-sdl2/blob/master/changelog.md#v030

sdl2 0.30 has some breaking changes. And ggez dependencies sdl2 v0.29.1.

================

I run the same code on macOS, use sdl 2.0.5, it can work.

**Comment by icefoxen** [comment]
Do you have example code you can post so I can try to duplicate the error?

What graphics card do you use?  Is it the same computer as the one running macOS?

There's no reason sdl2 0.30 should break anything.  Any project using ggez should depend on the correct version of sdl2 automatically.

**Comment by TakWolf** [comment]
Hi @icefoxen , i have put the code here.    https://github.com/TakWolf/ggez-trace-sample

`ggez-project-seed` is the ggez project that cause error.
My evn is:
PC is dell inspiron 15r 5537
Windows 8.1 x64 
rustc 1.22.0-nightly (088216fb9 2017-09-04)
cargo 0.23.0-nightly (34c0674a2 2017-09-01)
rustup 1.6.0 (a11c01e8c 2017-08-30)
- 'stable-x86_64-pc-windows-msvc'
- 'nightly-x86_64-pc-windows-msvc'
Graphics card is AMD Radeon HD 8850M

I have the same error on windows 10 on friends PC.

I have follow the [windows-with-build-script](https://github.com/Rust-SDL2/rust-sdl2#windows-with-build-script) to set my sdl evn. I think the problem lies the build.rs script.
https://github.com/TakWolf/ggez-trace-sample/blob/master/ggez-project-seed/build.rs#L26
There define a var lib_dir, but not use at all. So the reason is coder do not link the libs?
I will try this way: https://github.com/Rust-SDL2/rust-sdl2#windows-msvc

---------------------------------------------------

`sdl2-seed` is the raw sdl2 demo use
- cmake
- mingw32 gcc
- SDL2-devel-2.0.5-mingw i686-w64 (although pc is x64)
On the same computer is can work.

**Comment by icefoxen** [comment]
Wait, I'm confused...  there shouldn't be any reason to use a build.rs script, if you have the SDL2 MSVC libraries in the locations for cargo to find it (as documented in https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md or https://github.com/Rust-SDL2/rust-sdl2#windows-msvc) then it should just work.  If not it shouldn't even compile.  Are the DLL's in the correct place as well?

I will try this out on my windows machine and see what happens.

**Comment by TakWolf** [comment]
I have tried this way following https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md#windows
It's the same error.

It seems the build.rs was really working. But some mistake here about my sdl2 evn.
I make sure dll at the correct position.(If sdl.dll not exsit or don't fit will cause other error.)
And compiled really did(Means libs linking is correct. If link error it will couse an other error like : rror: linking with `link.exe` failed: exit code: 1181).

I think it is sdl version of the problem, i will try old sdl2 dev sdk.

**Comment by icefoxen** [comment]
Finally got around to checking into this, sorry for the delay.  @TakWolf Have you been able to get it working or no luck?

 * Graphics card version should work fine.
 * I don't test on nightly so maybe try on 1.20
 * Try using the MSVC instead of mingw runtime and see what happens.
 * Your example project vanished so I can't try to dig into your build script or such :-(

**Comment by TakWolf** [comment]
@icefoxen

Hello, I am a non-English developer, and my English is very poor.
But I will try to clearly describe my problem. Please forgive my strange grammar.

=========================================================

I saw the news that sdl2 has a new release 2.0.6:   https://discourse.libsdl.org/t/sdl-2-0-6-released/23109
It reminds me of this issues, so I started to try ggez again with the new release 2.0.6.
Unfortunately, the error is still the same.

I have always doubted that the essence of error is [rust-sdl2](https://github.com/Rust-SDL2/rust-sdl2).
So I try to create a clean a project for rust-sdl2.
Surprisingly, it can run!
I use the code from [https://github.com/Rust-SDL2/rust-sdl2/blob/master/examples/demo.rs](https://github.com/Rust-SDL2/rust-sdl2/blob/master/examples/demo.rs)

**Comment by TakWolf** [comment]
### About evn:

- Windows 8.1
- I have Graphics card and it enabled
- rust toolchain is always MSVC, version is Microsoft Visual Studio 14.0。I never install mingw version rustc.
- clear sdl2 code running is ok (rust-sdl2,  c++sdl2-msvc, c++sdl2-mingw)
- stable or nightly seems to be irrelevant, because both sides I have tried

===========================================
### About rust-sdl2 build.rs script:

Please forget it!!
 I went a wrong way before about set sdl-rust2 environment on Windows.
I read the rust-sdl2 document again.
The build.rs is not needed.
My current step is :
1. make sure sdl2.dll in 'PATH' environment variable.
2. make sure SDL2*.lib in 'LIB' environment variable.
That's all. SDL can be worked. I does really work for me.

**Comment by icefoxen** [comment]
Don't worry about poor english, it's fine.

This is a very strange problem, I honestly have no idea what would be causing a crash like this, especially if the sdl2 crate runs fine.  Your OS should be fine, the toolchain should be fine, the graphics card should be fine, the SDL2 dll's should be fine, I haven't been able to reproduce anything like this...

Some things you might try (though you've probably done most of this):

 * See whether any of the ggez examples run
 * Remove the code that creates the `Font` and `Text` and just try to create an empty window
 * Remove the other graphics functions like `graphics::present()` and see if it changes then.
 * If you are using the current git version, try the published 0.3.3 crate.  If you are using the published crate, try the git version.
 * Grab the source code for [gfx-rs](https://github.com/gfx-rs/gfx/tree/v0.16) (the v0.16 branch) and see if any of the examples there work or if they create the same problem.  If pure sdl2 Rust code works then the problem is probably somewhere else, and the next best candidate is the graphics system.
 * Use the Visual Studio debugger to see if you can find exactly where the crash is happening :-/

We will find out what is wrong!

**Comment by TakWolf** [comment]
I have forked the last commit at https://github.com/ggez/ggez/commit/d4e9451ab41e47cc4f8e551afd34eae1ac375af9
and run examples.  still error.
![image](https://user-images.githubusercontent.com/6064962/31015478-e4122058-a552-11e7-840d-e6d33e9abfa3.png)

I use the command `cargo run --example xxxxx` ,  (I manually set the location of the resources.)

I don't know how to use Visual Studio debugger, and i don't know how to debug rust codes.
But it looks like the error comes from the Context init.

```
let ctx = &mut Context::load_from_conf("helloworld", "ggez", c).unwrap();
```

The reason is:

On macOS, everythign is OK. All examples can run.
But, if I don't set the resources corrected, it will cause an error like this:
<img width="570" alt="qq 20170929203523" src="https://user-images.githubusercontent.com/6064962/31016064-c84b8064-a555-11e7-9163-7bca7d198431.png">
https://github.com/ggez/ggez/blob/master/examples/hello_world.rs

But on my windows, if I don't set the resources corrected, it will not cause the Resources NotFound error.
Because the code does not execute on that line, the program exits.

```
impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let font = graphics::Font::new(ctx, "/DejaVuSerif.ttf", 48)?;  // This will cause Resources NotFound error.
        let text = graphics::Text::new(ctx, "Hello world!", &font)?;

        let s = MainState {
            text: text,
            frames: 0,
        };
        Ok(s)
    }
}

pub fn main() {
    let c = conf::Conf::new();
    let ctx = &mut Context::load_from_conf("helloworld", "ggez", c).unwrap();
    let state = &mut MainState::new(ctx).unwrap(); // But it seems that the program did not arrive here!!
    if let Err(e) = event::run(ctx, state) {
        println!("Error encountered: {}", e);
    } else {
        println!("Game exited cleanly.");
    }
}
```

**Comment by TakWolf** [comment]
I used a more stupid way to find the error reason, the error is this line:

https://github.com/ggez/ggez/blob/master/src/context.rs#L94

``` rust
   let graphics_context = graphics::GraphicsContext::new(video,
                                                              &conf.window_title,
                                                              conf.window_width,
                                                              conf.window_height,
                                                              conf.window_mode)?;
```

![image](https://user-images.githubusercontent.com/6064962/31017676-e91fe3c4-a55b-11e7-893f-e0a74ad0bc4e.png)

My hack code is here:

``` rust
impl Context {
    /// Tries to create a new Context using settings from the given config file.
    /// Usually called by `Context::load_from_conf()`.
    fn from_conf(conf: conf::Conf, fs: Filesystem, sdl_context: Sdl) -> GameResult<Context> {

        println!("from_conf");

        let video = sdl_context.video()?;

        println!("let video = sdl_context.video()?;");

        let audio_context = audio::AudioContext::new()?;

        println!("let audio_context = audio::AudioContext::new()?;");

        let event_context = sdl_context.event()?;

        println!("let event_context = sdl_context.event()?;");

        let timer_context = timer::TimeContext::new();

        println!("let timer_context = timer::TimeContext::new();");

        let font = graphics::Font::default_font()?;

        println!("let font = graphics::Font::default_font()?;");

        let graphics_context = graphics::GraphicsContext::new(video,
                                                              &conf.window_title,
                                                              conf.window_width,
                                                              conf.window_height,
                                                              conf.window_mode)?;

        println!("let graphics_context = graphics::GraphicsContext::new .....");

        let gamepad_context = input::GamepadContext::new(&sdl_context)?;

        println!(" let gamepad_context = input::GamepadContext::new(&sdl_context)?;");

        let mut ctx = Context {
            conf: conf,
            sdl_context: sdl_context,
            filesystem: fs,
            gfx_context: graphics_context,
            event_context: event_context,
            timer_context: timer_context,
            audio_context: audio_context,
            gamepad_context: gamepad_context,

            default_font: font,
        };

        println!("let mut ctx = Context ....");

        set_window_icon(&mut ctx)?;

        println!("set_window_icon(&mut ctx)?;");

        Ok(ctx)
    }

}
```

**Comment by icefoxen** [comment]
That's actually *very* helpful.  I still don't know what's going wrong but finding out where it's happening is a good start.  :-)

If you want to do the same thing in the `GraphicsContext::new()` function that would be great.  It's at <https://github.com/ggez/ggez/blob/master/src/graphics/mod.rs#L293>  It looks big and hairy but there's only a handful of major pieces: window setup (with SDL), gfx-rs setup, and setting a bunch of initial values.

I sort of doubt this is something I'll be able to fix at this point but if we can figure out where it's happening then we can at least figure out where to take the search next.

**Comment by TakWolf** [comment]
https://github.com/ggez/ggez/blob/master/src/graphics/pixelshader.rs#L88

The ultimate goal to this line, it seems cause a carsh on my Windows.
I can not go on, 
because the factory is a  `gfx::Factory<Self::Resources>` and code go deep into it the crate `gfx_core-0.7.2`

**Comment by termhn** [comment]
Interesting. See if you can clone the v0.16 branch of `gfx` and run one of their examples or if you hit the same error. If so, I think it would be time to punt this upstream.

```
git clone https://github.com/gfx-rs/gfx/
git checkout v0.16
cargo run --example cube
```

**Comment by TakWolf** [comment]
@termhn 
I have checkouted v0.16 on gfx-rs/gfx.
I did not run all examples, but which I run the examples are ok.

**Comment by TakWolf** [comment]
@termhn 
Yes, it's carshed!!
![image](https://user-images.githubusercontent.com/6064962/31032196-b5ee1e26-a58d-11e7-9e76-77157a349d64.png)

========================================
Follow examples are crashed:
- triangle
- shadow
.......

**Comment by termhn** [comment]
@TakWolf Can you try going into the `triangle` example and changing the lines 

```rust
let pso = factory.create_pipeline_simple(
        include_bytes!("shader/triangle_150.glslv"),
        include_bytes!("shader/triangle_150.glslf"),
        pipe::new()
    ).unwrap();
```
to
```rust
let pso = factory.create_pipeline_simple(
        include_bytes!("shader/triangle_120.glslv"),
        include_bytes!("shader/triangle_120.glslf"),
        pipe::new()
    ).unwrap();
```
And see if it runs? If so, it has something to do with your graphics card (or drivers) not supporting the proper OGL version. Are you sure your graphics card drivers are up to date?

**Comment by kvark** [comment]
Please provide the `RUST_LOG=gfx=debug cargo.exe run --example triangle` output. Also, would be great to run it with debugger to see more of local variables and the call stack.

**Comment by TakWolf** [comment]
@termhn 
I have do this:
```
let pso = factory.create_pipeline_simple(
        include_bytes!("shader/triangle_120.glslv"),
        include_bytes!("shader/triangle_120.glslf"),
        pipe::new()
    ).unwrap();
```
It is crashed.
![image](https://user-images.githubusercontent.com/6064962/31032913-a87d47e6-a590-11e7-934d-c8ba5e235624.png)

================

My computer is purchased with around 2014, and preloaded with Windows 8.
Model is Dell inspiron 15R - 5537, AMD Radeon HD 8850M.
Graphics card drivers should be up to date. But I'm not sure, because this model is out dated support.

> your graphics card (or drivers) not supporting the proper OGL version.
How should I detect my graphics card?

**Comment by termhn** [comment]
Hmm, well my hypothesis was wrong then... that seemed to be the common denominator as far as the difference between versions... at this point I may as well pass you off to @kvark, he's more knowledgeable than I on these things :)

**Comment by TakWolf** [comment]
Hi @kvark !

```
Please provide the RUST_LOG=gfx=debug cargo.exe run --example triangle output. Also, would be great to run it with debugger to see more of local variables and the call stack.
```

I do not clear understand too much.
`RUST_LOG=gfx=debug` How to set this flag? And I don't know about how to use debugger.
Could you give me some more clear instructions? Thanks!

**Comment by kvark** [comment]
@TakWolf 
First of all, I believe you are getting the crashes on GL backend only. All 3 examples are the only ones that would be using GL and not D3D11 on your system.

To enable the logging:
  1. Add `extern crate env_logger` to the top of  `triangle/main.rs`
  2. Add `env_logger::init().unwrap();` to the top of the `fn main()` in `triangle/main.rs`
  3. Run `set RUST_LOG=gfx=debug` in your terminal
  4. Run `cargo run --example triangle` in the same terminal

Please provide the output of this.

To debug: when the app crashes, I imagine Windows is showing a pop-up window with something like "searching for solutions". When it's done searching, there should be another popup window with one of the buttons saying "Debug". That will launch Visual Studio (if you have it), and point you to the call stack. If you don't have VS, then this path is not an option.

**Comment by TakWolf** [comment]
Hi, everyone!
I probably find the reason.
I updated my integrated graphics card driver, and everything is OK.
I do not know why, but now everything can work properly.

My device Info:

- Intel(R) HD Graphics Family    -> I updated this driver
- AMD Radeon HD 8850M

**Comment by icefoxen** [comment]
That's very weird!  But I'm glad you found the issue.  :-)

**Comment by kvark** [comment]
This might still be a bug in our implementation, which is now hidden by the drivers having different behavior. But I'm glad you are unblocked now, at least.

**Comment by icefoxen** [comment]
@kvark @TakWolf  Feel free to re-open the issue if you want to keep hunting.
