### ISSUE TITLE
Panic on unwrap? -- support different OpenGL versions

### ISSUE THREAD

**Issue by ateesdalejr** [ggez/ggez#143]
When compiling and running the example code from [the website](ggez.rs) with the following: `cargo run --target=i686-pc-windows-msvc`
Rust spits out a very nice error for me: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Could not create GL context: The operation completed successfully.\r\n"))', src\libcore\result.rs:860:4
```
Doing a quick google search doesn't give me anything... I have a feeling that this is a problem with SDL2 though. Hopefully it should be resolved quickly 👍 .

Here's the full error with backtrace enabled:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.15 secs
     Running `target\i686-pc-windows-msvc\debug\ggezgame.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Could not create GL context: The operation completed successfully.\r\n"))', src\libcore\result.rs:860:4
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:379
   1: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   2: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   3: std::panicking::begin_panic_new<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:553
   4: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   5: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:497
   6: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:92
   7: core::result::unwrap_failed<ggez::error::GameError>
             at C:\projects\rust\src\libcore\macros.rs:41
   8: core::result::Result<ggez::context::Context, ggez::error::GameError>::unwrap<ggez::context::Context,ggez::error::GameError>
             at C:\projects\rust\src\libcore\result.rs:738
   9: ggezgame::main
             at .\src\main.rs:36
  10: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  11: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  12: main
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  14: BaseThreadInitThunk
  15: RtlGetAppContainerNamedObjectPath
error: process didn't exit successfully: `target\i686-pc-windows-msvc\debug\ggezgame.exe` (exit code: 101)
```

**Comment by ateesdalejr** [comment]
Oops. Forgot to mention that I'm running 64 bit windows 10. Also I can compile and run things with SDL2-rust 0.30 just fine for some reason. (As well as cross compile.)

**Comment by icefoxen** [comment]
What is your graphics card?  Basically what this is saying is that you have no 3D accelerated graphics that it knows how to use.  Since it should try to use, OpenGL 3.2, which would hopefully be supported on any graphics card made after 2009 or so, that's not really expected.  However, there ARE plenty of machines still around made before then, so...

**Comment by ateesdalejr** [comment]
This is a really old machine. And it uses Intel integrated graphics. So is there a setting where I can tell it to stop trying to hardware optimize? (At least for me.)

**Comment by termhn** [comment]
Why are you using i686 on a 64-bit machine?

**Comment by icefoxen** [comment]
That's a tough question.  Literally all graphics these days is hardware accelerated using OpenGL or similar API's.

Can you check exactly what graphics chipset you use, or which version of OpenGL it supports?  Unfortunately Intel integrated graphics before the HD 3000 was pretty abysmal, and IIRC only supported OpenGL 2.1.  As I said ggez tries to use 3.2; it SHOULD be possible to use 2.1 but would require rewriting the shaders and possibly fiddling with some other parts of the graphics setup...  not a huge endeavour but not a five minute fix either.

**Comment by ateesdalejr** [comment]
@termhn I was trying to see if I could cross compile ggez projects to 32 bit. As it seems to work with rust-sdl2. 

@icefoxen It's Intel(R) HD Graphics 3000 exactly. With 1632 mb of graphics memory.

**Comment by ateesdalejr** [comment]
Found it! "OpenGL 3.1 (Intel(R) HD Graphics 3000 with 129 ext.)

**Comment by icefoxen** [comment]
Oooh. Interesting. Let me figure out how hard it would be to just support 3.1.

**Comment by Geemili** [comment]
Running the example code (on linux) I get this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Could not create GL context: GLXBadFBConfig"))', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:92
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:738
  11: astroblasto::main
             at examples/astroblasto.rs:620
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  14: main
  15: __libc_start_main
  16: _start
```

And the output of `visualinfo` tells me that my OpenGL version is 2.1.

Just putting this here for the record.

**Comment by termhn** [comment]
OGL 2.1 is.... ancient, to be honest, and not likely to be supported... if that's the maximum version your hardware can provide, it's probably time for an upgrade ;P

**Comment by icefoxen** [comment]
Welcome to pre-HD Intel GPU's, sadly.  There's tons and tons of them still out there, and for lots of people in lots of places "buy a newer laptop" isn't a realistic option.

It won't break my heart to not support OpenGL 2.1, but at least making the effort to see if it's possible is worthwhile.

**Comment by ateesdalejr** [comment]
@icefoxen I fear your are right. :/ The only reason I was looking to use 2.1 was because of the large amount of casual gamers who don't want to upgrade their PCs.

**Comment by icefoxen** [comment]
Well for a platform that's intended to make it easy to make casual-ish games, among other things, its still worth thinking about.

**Comment by jansol** [comment]
If the intention is to keep ggez focused on casual-ish 2D things then GL2.1 is a reasonable option. The main downsides are lack of some more recent batching features like instancing and indirect drawing as well as having to use the old GLSL syntax.

**Comment by icefoxen** [comment]
You can now specify which OpenGL version you want to request and specify custom shaders.

I'm chalking this up as done.

**Comment by ateesdalejr** [comment]
@icefoxen Awesome! Thanks so much! Now people that are on pretty old hardware can play my games. 👍

**Comment by icefoxen** [comment]
Well...  Potentially.  Drawing still tends to use instancing internally, so some things on OpenGL 2.1 might not work and I can't rewrite everything to use older OpenGL versions.

But at least there's a prayer now.

**Comment by ateesdalejr** [comment]
Righto. Most people should be fairly sane and use open GL 3.2 though.
