### ISSUE TITLE
Send transform data to the gpu as matrices

### ISSUE THREAD

**Issue by termhn** [ggez/ggez#145]
Will become easier when #102 hits, but this would mean we could compute one matrix on the cpu for each object and then send that to the gpu... or just convert all the current translations into matrices and send those... Not sure of the performance impact would be of either of those options (would have to profile) but in either case, it would make the operations happening in and data being sent to the shaders much more clear.

**Comment by icefoxen** [comment]
Do we really want to compute one matrix per object on the CPU, rather than on the GPU which is 1000x better at it?

I don't know, maybe. Having each object get a matrix rather than parameters might make it simpler to eventually  support different shaders...

**Comment by termhn** [comment]
Well, doing it on the CPU means it happens once per object instead of once per vertice. Also, correct me if I'm wrong, but I don't think the gpu is actually better at doing math, only at doing many math problems at the same time... so I think it might actually be less efficient to do on the gpu.

Could be nice for shaders, too.

**Comment by icefoxen** [comment]
If most objects are 4-6 vertices...  

I honestly don't know.  It deserves some research, I admit.

**Comment by termhn** [comment]
Haha yeah, that's exactly what I was thinking; for a 3d engine where there's often hundreds or thousands of vertices it seems like it could make more sense, but... I don't know really... that's why I included the "dunno performance impact, would have to profile" disclaimer originally ;P

**Comment by icefoxen** [comment]
@termhn Can this be closed or is there more you want to do?

**Comment by termhn** [comment]
Yep can be closed.
