### ISSUE TITLE
cargo-resource-root is annoying

### ISSUE THREAD

**Issue by robsaunders** [ggez/ggez#146]
Before you close the issue due to vague title - yes I checked this thoroughly :P the examples that use resources won't compile using the standard cargo examples syntax, which can be extremely disconcerting for people trying to check out the lib and evaluate its quality.

An example:

```bash
cargo run --release --example drawing
```

Will complain about resources not being present:
```bash
Requested GL 3.2 Core profile, actually got GL 3.2 Core profile.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResourceNotFound("/dragon1.png", ["/Users/rob/Projects/rust.workspace/_forks/ggez/target/release/examples/resources", "/Users/rob/Library/Application Support/drawing", "/Users/rob/Library/Application Support/drawing"])', src/libcore/result.rs:859
```

This location really doesn't exist, because the setup code for some reason uses relative directories as if it was being compiled and then run, which is not idiomatic cargo. There's no real reason to obfuscate and abstract where files are found, there are ways to do this with vanilla rust easily enough.

I changed the example in question to use PathBufs correctly, like this:
```rust
impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let mut pwd: PathBuf = env::current_dir()?;
        pwd.push("resources/dragon1.png");

        let image1 = graphics::Image::new(ctx, pwd.as_path())?;
```

But I'm still getting an error inside filesystem.rs even though this file DOES exist at the path specified by the error readout, and the pathbuf is perfectly valid. The path array at the end of the error readout is a little worrying, as if it might be interfering in some way. I didn't dig too deep since I probably won't waste too much time on a lib if the examples don't even compile.
``` bash
rob@tato ~/P/r/_/ggez> cargo run --release --example drawing
   Compiling ggez v0.3.3 (file:///Users/rob/Projects/rust.workspace/_forks/ggez)
    Finished release [optimized] target(s) in 1.66 secs
     Running `target/release/examples/drawing`
Requested GL 3.2 Core profile, actually got GL 3.2 Core profile.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResourceNotFound("/Users/rob/Projects/rust.workspace/_forks/ggez/resources/dragon1.png", ["/Users/rob/Projects/rust.workspace/_forks/ggez/target/release/examples/resources", "/Users/rob/Library/Application Support/drawing", "/Users/rob/Library/Application Support/drawing"])', src/libcore/result.rs:859
```

Lastly what if I want to include my assets inside the library using the `include_bytes!` macro (good practice for tiny examples like this imo)... the framework appears to prohibit this by wrapping standard rust stuff...

**Comment by termhn** [comment]
As mentioned in the README under Examples, this can be fixed easily for the examples by using `--features=cargo-resource-root` https://github.com/ggez/ggez#examples

Whether this is the best or a good way to do it is over my pay grade atm :P

**Comment by icefoxen** [comment]
It is the only terribly reasonable way to do it as far as I can tell.

Normally you want your program's data either next to the executable or in a system dependent data directory. While developing a game your exe ends up in target/debug or target/release. So really you want your data in your cargo root. But the only way to get this is to compile the path into the program and you don't want to release an exe that looks in random places on the user's hard drive for stuff. 

So we have a feature flag. Suggestions on how it could be better are welcome.

**Comment by robsaunders** [comment]
I'd suggest since these are examples, they aren't fully completed game projects and don't need to take every 'real world' circumstance into consideration or it would end up confusing. The point is simply to get across basic usage and capabilities of the library, so they should probably compile the idiomatic rust way, no?

**Comment by icefoxen** [comment]
Do we want to do the Right Thing by default, or do we want to do the Easy Thing by default?

I prefer the former.

**Comment by robsaunders** [comment]
That's a strange response to be honest. Subjective as Objective.

Subjectively, the 'easy thing' is to leave broken examples in your project due to strange opinions on how the rust and cargo ecosystem work. But your opinion would differ.

But if you consider that many rust build systems are adopting building the examples as part of a CI or test suite system, the answer is a little less subjective and the Right Thing becomes a little clearer.

People don't expect the examples to be complete projects, I've worked on and contributed to enough rust projects now to tell you - examples just show you how to use the api, not convey good programming practices. In fact, until ggez I had not encountered that opinion once.

For example, most projects would have you storing state somewhere, not just instantiate it in main() and loop {}, and dump it, and yet some of the most mainstream rust projects do this (glium, winit, gfx, etc). This is because, well, those projects are EXAMPLES of the api use and not in any way designed to instruct you how to make an actual application/game/whatever. People tend to know how to use assets when they come to your project, but they don't know the specifics of how your project works. You're telling them that your opinions on paths and project management matter more than an opening experience exploring ggez's api.

**Comment by icefoxen** [comment]
I agree that requiring extra arguments to run examples violates the Principle of Least Surprise.  I don't like it.  I just think the alternative, making the default behavior be to introduce subtle bugs into every program to ever use ggez, is worse.  You could document this behavior, but the current behavior is already documented under "Examples" in the readme and people still just never read it.  

If you have a better way to do it then I am all ears.  I just thought of one that might be worth experimenting with, we will see.

I expect examples to show how the heck to use a crate.  Part of ggez's functionality is providing a virtual filesystem interface to paper over platform-specific variations, and so the examples have to show you how to use this.  It comes with a gotcha or two, which the examples ALSO currently demonstrate.  ggez sets a policy on paths so that people don't have to do the work of setting a policy themselves, because it's tedious and error-prone and in the end where assets and save game files live doesn't *really* matter as long as it's somewhere that plays nice with the underlying OS's conventions.

**Comment by DTibbs** [comment]
Just a suggestion to make this less of an issue, show how the feature can be used in a more convenient way in the README:

...
ggez is built on the latest stable Rust compiler and distributed on
crates.io.  To include it in your project, just add the dependency
line to your `Cargo.toml` file:
``` text
ggez = "0.3"
```
Alternatively, to always use the cargo-resource-root for resources, add these lines to your `Cargo.toml` file:
```text
[dependencies.ggez]
version = "0.3"
features = ["cargo-resource-root"]
```
...


Related to this issue, I've also tried out `cargo-make` to do a post-build step w/ my ggez project:
```text
[tasks.post-build]
run_task = "deploy"

[tasks.deploy.windows]
description = "Copies the resources to the target build directory."
script = [
  "echo Copying resources to target\\debug\\resources",
  "mkdir target\\debug\\resources",
  "copy resources target\\debug\\resources"
]
```
This also has some drawbacks, though. Such as, cargo-make doesn't know the `OUT_DIR` or if you built `debug` or not, so you have to just forcefully copy resources to where you want them to go. At least I haven't figured that out yet.

**Comment by icefoxen** [comment]
Added `Filesystem::add_physical_path()` which makes it possible to easily sidestep this issue.  Updated all the examples to use it.  The `cargo-resource-root` flag remains since it does no harm and I like having the option.

**Comment by ishanjain28** [comment]
@icefoxen `Filesystem::mount()` is not used in examples but it hasn't been pushed to cargo. I am using `ggez 0.3.3` and it's not present. I am also having the same issue as him. Can you release a new version or suggest a solution to this?

**Comment by robsaunders** [comment]
cargo lets you point directly to a github repo

**Comment by icefoxen** [comment]
Yeah, right now the only real solution is "use git master" or "make cargo-resource-root work".  Unfortunately there's been so many changes that backporting stuff back to 0.3.3 is not terribly easy, though in this case it might be feasible.  *Hopefully* I'll manage to get 0.4 to release-able state someday soon.
