### ISSUE TITLE
Notes on experimenting with ggez+gfx

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#15]
I did some experimentation and want to write down the results somewhere:

It's possible to use gfx from ggez but it requires enough re-architecting of things to be a significant headache. Creating SDL2's Renderer type consumes a Window, and creating creating a gfx window context also consumes the Window, and ggez is currently designed to require a Renderer.  So you can't have both on the same window.

Getting them to interoperate would basically mean making a pluggable rendering backend for ggez, and between piston and gfx I feel like the Rust ecosystem has enough pluggable rendering backends.

**Comment by icefoxen** [comment]
Did some more tests, the gfx window context takes a `WindowBuilder`, not a `Window`.  So this might actually work!  Just need separate functions for "make window" and "make gfx window" perhaps.

**Comment by onelson** [comment]
Wondering where you left this. I started working with SDL2 and gfx and it has been a lot to learn for me.

You mentioned in the readme that you'd like to add support for shaders et al. Seems like running through a gfx render context would be a step in that direction.

**Comment by icefoxen** [comment]
I left it off by getting gfx working in an SDL window: https://github.com/icefoxen/gfx/tree/master/examples/triangle-sdl  that's about all I've done.

It should be pretty simple to just wrap all the gfx state up into something similar to the SDL Renderer and just replace it with that.  Then it's just a matter of writing all the drawing type code.

**Comment by icefoxen** [comment]
Something we want to make sure we provide is some way for a user to get their hands on all the `gfx` state objects they need, so they can do whatever 3D drawing they want.

**Comment by onelson** [comment]
There's one state object per window, or? I figured they would be something you could stash on the ggez context and treat as a global.

**Comment by icefoxen** [comment]
gfx has a few different types that do different things (`Factory`, `Encoder`, `Device`, maybe others), but all more or less add up to "the graphics context for this window".  Not sure how multiple windows are handled though.

**Comment by icefoxen** [comment]
Gotten this to draw a triangle, after some kerfuffling with version numbers.  Use gfx-rs 0.14, gfx_window_sdl 0.5, gfx_device_gl 0.13, and sdl 0.28.

The plan is probably to steal the instancing example from gfx and basically use that to re-implement the current drawing API with as few changes as possible.  Then on the NEXT version (0.4?) we can start making the drawing more powerful.

Some notes:  I don't even know if we can make the instancing example run on glsl 120 (OpenGL 2.1) which might be what we realistically have to target.  GLSL150 (OpenGL 3.2) would be nice if we can make it go properly.  We might want to handle OpenGL ES 2.0 as well.  Might want to look at Love2D and see how it handles it.  Realistically I kind of suspect we're going to have to either support multiple versions and detect which we have at runtime (if possible???), or be very conservative (OpenGL 2.1) in what we support.  I'd think   Play with <https://docs.rs/sdl2/0.28.0/sdl2/video/gl_attr/struct.GLAttr.html> on different platforms and see how it goes.  Explicitly requesting core instead of compatibility contexts might also be a good idea?

We should be able to just expose the basic gfx `Factory` and `Device` and such from the GraphicsContext and let anyone who wants to access them roll their own graphics pipeline... hopefully.  

Will be interesting to see what happens!

**Comment by icefoxen** [comment]
It appears we don't have to do anything too special with gfx to request a particular OpenGL version or profile; we just use the SDL GLAttr type to set what we want before building the window, and make sure to double-check it afterwards.  We should also ensure to request the Core profile so nothing too bogus (hopefully) happens.

Only OpenGL could have a deprecation system so screwy that it has to get deprecated.

**Comment by icefoxen** [comment]
GFX is no longer experimental, so I'm closing this. :D
