### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by termhn** [ggez/ggez#152]
I think we should definitely allow some kind (or possibly multiple kinds) of built-in antialiasing. For games other than pixel-art based (and even then), antialiasing is basically a requirement IMO. 

Possible options include using MSAA or doing post-processed antialiasing like FXAA in a shader. I honestly haven't done much research on these things so I don't have anything in mind as far as the best way to do this, but wanted to put it down to discuss as it's definitely something I want to work on in the future.

**Comment by icefoxen** [comment]
Doing FXAA is the easy way but requires some sort of shader framework.  Doing MSAA doesn't need shaders but does need backend support and I don't know exactly what the implications of that are right now.

**Comment by termhn** [comment]
MSAA is now implemented, not sure if we really need to add FXAA as well but it could be a good excuse to start working on user shaders...

**Comment by nlordell** [comment]
@termhn  I started looking at how to add support for shaders à la LÖVE (http://blogs.love2d.org/content/beginners-guide-shaders) and posted what I found in a new issue #157 - not sure if you are interrested...

**Comment by termhn** [comment]
Testing on my macbook today and multisampling appears to not work. Could be why I was getting screwed up in the first place. Not sure if it's an OS X thing or what; haven't had time to dig deeper.

**Comment by icefoxen** [comment]
I made an example program to play with this; it works great on my laptop.  Though it doesn't support 16x MSAA, so I made the default 1x.

**Comment by termhn** [comment]
Ha! That was the problem. My laptop doesn't support 16x either, works great with 8x though. Perhaps I should add a note about that in the documentation...

Also IMO it should default to either 4x or 8x; one of the things that was a bit of a turn off for me from ggez at the beginning was the really aliased look which makes things look worse than many other engines, when in reality it's just as capable.

I wonder if there's a way to automatically detect the capabilities of the host's graphics card as far as mutisampling goes...

**Comment by icefoxen** [comment]
Alas, graphics drivers.  When I tried to set it to 16x it panicked with a "cannot create video context with the given settings" type error, while it sounds like yours ran and just didn't use MSAA.  Do you have an nvidia graphics card by any chance?  :D

I lean towards defaulting to 1x because it means that, well, nobody will ever have the examples fail to run with a "cannot create video context with the given settings" type error.

I'm sure there's ways to query the graphics card capabilities but I'm not sure that SDL or gfx-rs exposes any of them...  hmm.  That would be a VERY good thing to have though.

**Comment by termhn** [comment]
I have an nvidia card in my desktop, but just intel integrated graphics in my laptop (4000 series I think?)

**Comment by icefoxen** [comment]
That's odd.  My limited experience says that Intel tends to either comply or say it can't, while NVidia drivers will say "well I don't support this option so I'm just going to do whatever I think is reasonable instead".  Oh well, was just curious.

Are we willing to call this done, or is there more work that needs doing?  :D

**Comment by termhn** [comment]
Yep! Closing this for now, perhaps we can add FXAA in the future if the need arises.

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/68897531-5beb5800-0736-11ea-90e7-4424b22bd76c.png)
This is supposed to be a circle....

**Comment by termhn** [comment]
That isn't caused by lack of antialiasing, it's caused by insufficient
tesselation of the circle. Use a lower tolerance value.

**Comment by cata0309** [comment]
You are right
