### ISSUE TITLE
Provide nicer function for framerate calculations?

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#153]
I recall a crate or such somewhere that found out what the sleep resolution provided by the platform was, then used `thread::sleep()` as much as it could and spun for the remainder until the given time had passed.

This SEEMS like the Right Behavior but needs more investigation.

At worst, we should make `timer::check_update_time()` return the actual amount of time passed, so you can do fix-your-timestep properly and do multiple small updates to catch up if necessary.

**Comment by svenstaro** [comment]
I think this is a good discussion on the topic: https://gafferongames.com/post/fix_your_timestep/

**Comment by icefoxen** [comment]
It is!  :D  I have read it multiple times, and still not enough time.  It's just a matter of figuring out what primitives we can provide to make that as easy as possible for users.

**Comment by icefoxen** [comment]
Ah, found the crate: https://github.com/alexheretic/spin-sleep

**Comment by svenstaro** [comment]
Oh that seems really cool. Gotta check that out.

**Comment by icefoxen** [comment]
Done in 2d66b143b5337326e61e147c1665d9c9025814bd
