### ISSUE TITLE
Add support for shaders

### ISSUE THREAD

**Issue by nlordell** [ggez/ggez#157]
I've noticed some discussion about adding support for shaders and would like to share what I have found (I was also interrested in it and started looking at to what would be involved in adding the support for this).

```rust
gfx_defines!{
    vertex Vertex {
        // vertex fields...
    }

    constant Transform {
        // tranform fields...
    }

    pipeline pipe {
        // "bindings"...
    }
}
```

Given the above invokation of the `gfx_defines`, a few things happen:
- `Vertex` and `Transform` structs are defined and implementations for `gfx::pso::buffer::Structure<F>` are generated (important as it is what allows the gfx crate to find the format and offset of a particular field by name).
- `pipe::Init`, `pipe::Data` and `pipe::Meta` types are generated
    - `pipe::Init` which implements `gfx::pso::PipelineInit` which creates a mapping (`init::Meta`) for a given program
    - `pipe::Data` which implements `gfx::pso::PipelineData<R>` which as far as I can tell is responsible for actually providing the data (given the mapping created by the `pipe::Init` type)
    - `pipe::Meta` the mapping for the PSO - basically the struct inside the `pipeline pipe` section of the `gfx_defines` call
- The function `fn pipe::new() -> pipe::Init;` is generated for creating new instances of `pipe::Init`.

Now, if you wanted to create a generic PSO you would have to implement (at least parts of) `gfx::pso::PipelineInit` and `gfx::pso::PipelineData<R>` but it is totally possible (see this [gist](https://gist.github.com/nlordell/550a7b112e095eb853c5ecd9618501b3) where I create a generic `JoinPipeline` struct for combining any two pipelines defined with `gfx_defines`).

I've started applying what I discovered to implement a LÖVE inspired shader API. 

Combining two separate pipelines is a little bit of overkill, especially since gfx allows you to group uniforms into structures that get passed as uniform interface blocks, we can change this:

```lua
myShader:send("screenWidth",800)
myShader:send("screenHeight",600)
```
to
```rust
my_shader.send(Data { screen_width:  800.0, screen_height: 600.0 })?;
```
So instead of being generic on a full pipeline (`pipe::{Init, Data, Meta}`) we just need to be generic on the block of data that we want to be accessible from the shader (implementing a `gfx::pso::buffer::Structure<F>`) and then implement a generic `gfx::pso::PipelineInit` `gfx::pso::PipelineData<R>` that only has one `ConstantBuffer<C>` field.

Note that we can still use `gfx_defines` macro to generate the `gfx::pso::buffer::Structure<F>` implementation for us:

```rust
gfx_defines!{
    constant Transform {
        // tranform fields...
    }
}
```

This was a rather long wall of text, sorry... Also I am fairly new to gfx so take the things I say here with a grain of salt and forgive me if my technical language is not very precise or accurate.

**Comment by termhn** [comment]
Sweet. Definitely something I'm interested in looking into but haven't yet other than to see how LOVE does it.

**Comment by termhn** [comment]
Based on my conversation with @kvark on IRC, it sounds like the best way to do this will be to create a dedicated PSO for each user shader and then swap in the proper one when you call `graphics::setShader()`

**Comment by nlordell** [comment]
Right now my PixelShader object looks something like this:

```rust
pub struct PixelShader<C: Structure<ConstFormat>> {
    data: ConstData<GlResources, C>,
    pso: PipelineState<GlResources, ConstMeta<C>>,
}
```

`ConstData` is a `PipelineData` implementation that wraps `graphics::pipe::Data` allowing you to add an extra constant buffer C.

I am also keeping my own `graphics::pipe::Data` instance per shader. This avoids PixelShaders needing to hold on to a `GraphicsContext` reference.

I'm still not 100% happy with my API but I think its getting closer. My example looks something like this:

```rust
gfx_defines!{
    constant Dim {
        rate: f32 = "u_Rate",
    }
}

struct MainState {
    dim: Dim,
    shader: graphics::PixelShader<Dim>,
}

impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let dim = Dim { rate: 1.0 };
        Ok(MainState {
            dim,
            shader: graphics::PixelShader::new(ctx, "/dimmer_150.glslf", dim, "Dim")?,
        })
    }
}

impl event::EventHandler for MainState {
    fn update(&mut self, _ctx: &mut Context, _dt: Duration) -> GameResult<()> {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx);

        graphics::circle(ctx, DrawMode::Fill, Point2::new(100.0, 300.0), 100.0, 2.0)?;
        {
            let lock = graphics::set_pixel_shader(ctx, &self.shader)?;
            graphics::circle(ctx, DrawMode::Fill, Point2::new(400.0, 300.0), 100.0, 2.0)?;
        }
        graphics::circle(ctx, DrawMode::Fill, Point2::new(700.0, 300.0), 100.0, 2.0)?;

        graphics::present(ctx);
        Ok(())
    }
}
```

There are still some things to iron out:
- should we do like LÖVE and process the source or just include it raw?
- Is this the API we want - is RAII a good idea for setting/unsetting `PixelShader`s

Focusing on getting it working first though :)

**Comment by nlordell** [comment]
Alright, I have something basic working... still needs some polish IMO.

https://github.com/nlordell/ggez/commit/c735e03784677f3b1f06bd500717753b15303f4b

(Not sure how to properly link commits...)

**Comment by termhn** [comment]
Looks pretty sweet to me, still have to look through in more detail. This is the important commit btw: https://github.com/nlordell/ggez/commit/54114ed42668ced7c3ddca263138ccebed0f6cbd

You should open up a PR, then we can do direct code review and discuss it in a more structured way.

**Comment by nlordell** [comment]
#158

**Comment by icefoxen** [comment]
The main concern I have is portability to different gfx-rs backends... which also means different versions of OpenGL.  If we want it to be possible to make portable games, are we going to shoehorn one shader language into OpenGL 3.2, WebGL, OpenGL ES 2.0, Vulkan, and whatever else?  Or force the user to write different shaders for each backend we support?

This is one of the (big) portability issues that gfx-rs currently punts on.  So we have to at least think about it.  Now that I'm feeling a little lazier and more pragmatic than I was when I started this project I'm open to the idea of forcing the user to write different shaders and having a fairly straightforward setup for selecting them based on graphics backend, as long as it's extensible and leaves some sort of logical path forward to the Good Times Ahead when everything just compiles to SPIR-V.

**Comment by termhn** [comment]
IMO at least for now forcing users to write their own shaders for each backend they want to take advantage of is the right decision. Creating our own shader language that would transpile to others seems like:

1. A lot of work to set up initially
2. A lot of work to continue to maintain
3. Solving a problem that's already being solved (the Good Times Ahead in theory)

In addition, since ggez doesn't have nearly as large of a community as LOVE, there would many less examples of our shader language actually being used. Having people use the standard shader languages would mean examples written in the already standardized shader languages would be able to be directly translated. Finally, shaders are frankly quite an "advanced" feature IMO, and in order to use them you kind of have to have knowledge of modern graphics pipelines and therefore shader languages anyway. Therefore I really don't think there's much benefit to making our own shader language.

**Comment by icefoxen** [comment]
I merged @nlordell 's PR #158 and it looks pretty seriously good.  Just wondering if there were any plans for making similar code to support vertex shaders at all?

I'm going to add a bit of metadata to the GraphicsContext that tells it what backend it's using, so we can query it, and then figure out the best way to do dispatching to the correct backend type.

**Comment by icefoxen** [comment]
I added some framework for specifying graphics backends (which sort of snowballed a little and lead to lots of refactoring of gfx generics) in commits 083ce1e646209817ab79adeaf94cc3be83d69ab4 and 10b6ae48fb9f844e7c34be3786dda421aa91af08 .  @nlordell I would appreciate suggestions for how to make this work nicely with being able to select shaders from a possible list of programs; I was sort of thinking of just having the `BackendSpec` trait inherit `Hash` and making a `HashMap` of `BackendSpec` -> shader program, but it ended up being a little more complicated...

Note we do also want a `PixelShader::from_u8()` method which doesn't need to load the source from the resource path, just for completeness/symmetry with other resource types.  That's easy though.

**Comment by nlordell** [comment]
I'll implement `PixelShader::from_u8()` and submit another pull request.
As for vertex shaders, I hadn't put any thought into it or made any plans. Do you have a specific use case in mind?

**Comment by icefoxen** [comment]
Nothing specific, it just seems like it should be there for completeness's sake.

Potential vertex shader effects include:

 * Wobbly shapes
 * Perspective hacks/distortions
 * Messing with texture coordinates
 * Preventing people from saying "where's the vertex shaders?"

**Comment by nlordell** [comment]
We can add them in then, make them super basic for now (pretty much only allow the overriding of the default vertex shader and specify constants like for the fragment shader) and then build on it as needed.

**Comment by icefoxen** [comment]
Sounds decent to me!

**Comment by icefoxen** [comment]
@nlordell Are you still inclined to add vertex shaders, or shall I go ahead and bodge it together as well as I can?

**Comment by nlordell** [comment]
@icefoxen Sure! I just set it asside because I was unsure of how we want to make it work with the current shader API - is it OK to break the current shader API?

**Comment by icefoxen** [comment]
Yeah, break away.  😁 

From what I've seen though, it should be possible to just make the existing `PixelShader` type contain both a pixel and vertex shader.  That would probably be the simplest way forward.

**Comment by nlordell** [comment]
That was the plan, I was going to rename it to `ShaderProgram` so its a bit more accurate as to what it actually is and maybe change a bit how you build one (its starting to have lots of parameters!).

Another small consideration is we could create a pixel shader both from a shader source file name and using `PixelShader::from_u8()` to pass it source directly. Do we want to be able to create new shader programs where the vertex shader comes from a file and fragment shader doesnt? I think if use a builder pattern for creating these `ShaderProgram`s we can make the API more ergonomic and have sane defaults for most of the parameters.

These are just some ideas... open to suggestions!

**Comment by icefoxen** [comment]
I think it seems reasonable to have `::from_u8` take literal text for both shaders and `::new()` take paths for both shaders. Either that or have a builder type for each pixel and vertex shaders that can take either of those sources, though not much else in the ggez API does that...  KISS where possible I guess.
