### ISSUE TITLE
Consider switching to `gfx_window_glutin`

### ISSUE THREAD

**Issue by nlordell** [ggez/ggez#160]
Might be worth considering using (glutin)[https://github.com/tomaka/glutin] instead of SDL2. That way it will no longer depend on having SDL2 installed and all depedencies are pulled through cargo.

The downside to switching (besides the work) is that it will break some of the `ggez::events::EventHandler` api since it uses SDL2 specifics (mouse and keycode types for example) for some of the callbacks.

**Comment by icefoxen** [comment]
It's certainly possible; someone made a fork that did just that, based off of the 0.3.3 code iirc: https://github.com/sjaustirni/ggez/tree/glutin

https://github.com/ggez/ggez/issues/29 has most of the discussions of pros and cons.  Basically what I want to be able to do before committing to ditching SDL: Controller support (probably solvable), mobile support (someone got glutin to work on android?  No idea about iOS or what gfx-rs needs?), emscripten support (????????).

It could be possible to take a proactive stance and say "If one of those is broken/missing we'll write stuff until it works" but I don't know enough about the various platforms and libraries to know how big a task that will be, and I'm already overcommitted in terms of projects.

**Comment by nlordell** [comment]
Going to close this for now, I feel like #168 covers enough of this to be considered duplicate
