### ISSUE TITLE
graphics_settings example should be better

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#162]
Things it should show off:

 * Resizing windows
 * Fullscreen'ing windows

**Comment by Manghi** [comment]
I would love to work on this low-hanging issue, if possible. 😄

**Comment by termhn** [comment]
Sure, make a PR! I also think the shape should be rotating and/or moving in some way to better show the difference that AA makes.

**Comment by icefoxen** [comment]
Now has fullscreen settings and window resizing

But we REALLY need to make it demonstrate how to properly set the screen coordinates after the screen resizes to pre-empt issues like #134 

Except it seems to be subtly broken somehow and I'm not sure why.

**Comment by icefoxen** [comment]
https://github.com/libgdx/libgdx/wiki/Viewports may be useful to look at.

**Comment by icefoxen** [comment]
It's pretty good now but needs to print out options

**Comment by icefoxen** [comment]
done
