### ISSUE TITLE
Update the website for 0.4

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#164]
sigh

**Comment by TatriX** [comment]
Ane eta on `0.4` release?

**Comment by icefoxen** [comment]
If I didn't have much else I had to do, maybe two or three weeks.

If I want to actually hit deadlines on other projects, maybe Christmas or so.

**Comment by TatriX** [comment]
Also I'd like to note that most of the newcomers hard a time time understanding that examples from the master branch won't work for the stable crate. So I think it should be better to match master branch to the latest crate on the crates.io and have a separate branch for a development version.

**Comment by icefoxen** [comment]
Good to know.  I've considered it a time or two and probably should switch to master being the stable version and having a separate dev version.

**Comment by icefoxen** [comment]
Okay, documentation for such has been updated in commit d6287103d507612f773243ec5f463d50125d2b97 and we will switch to keeping master stable and doing all work in a devel branch after the 0.4 release.

**Comment by icefoxen** [comment]
Reminder: need to list contact/support info and contributing.md link on the website.

**Comment by TatriX** [comment]
Do we have a gitter chat?

**Comment by icefoxen** [comment]
We don't, I usually hang out in #rust-gamedev on the Mozilla IRC network.

**Comment by svenstaro** [comment]
Indeed. Perhaps we should have a gitter? I'm not sure we're big enough already and we might just split the community more. I think we should stick to IRC for now and think about gitter a little later unless you disagree.

**Comment by icefoxen** [comment]
I'd considered something like it but it's hard to judge. Especially since contributors and activity seems to ebb and flow a fair bit.

I slightly dislike gitter for being closed, I'd prefer IRC or Matrix or something. But I'll bow to opinion if people think it's worth it.

**Comment by icefoxen** [comment]
Related: https://github.com/ggez/ggez.github.io/issues/4

**Comment by icefoxen** [comment]
Should make sure it links to: FAQ, building instructions, contact info.

Also update the copyright statement to 2018.  ;-)

**Comment by svenstaro** [comment]
I'm thinking of revamping the site with gutenberg quite soon. @icefoxen let's coordinate this with 0.4. I had this coming a long time anyway.

**Comment by icefoxen** [comment]
Heck yeah I've been wanting to play with gutenberg anyway.

**Comment by onelson** [comment]
TIL there is a gutenberg. Looks fun!

**Comment by icefoxen** [comment]
I did a very basic content update to the website, just to bring it in line with the readme and examples: https://github.com/ggez/ggez.github.io/commit/4d8e00163b2a0cca2015e8240737ce2a0a680767

**Comment by TatriX** [comment]
> Copright
Do you need any help with the site?

**Comment by icefoxen** [comment]
@TatriX Good catch, thank you.

If you want to help, we could probably use it, but I don't really know what @svenstaro has in mind.

**Comment by svenstaro** [comment]
@TatriX how would you like to help exactly?

**Comment by TatriX** [comment]
I thought you had some job with it based on the commit comment.
![2018-01-06-110057_602x173_scrot](https://user-images.githubusercontent.com/703150/34637890-e2e45c52-f2d0-11e7-9894-3676aaf8841b.png)

**Comment by svenstaro** [comment]
Well I once said that I want to rewrite it in Gutenberg but apart from that I'd appreciate some help with design. I kind of stopped the design of the site halfway last time I worked on that. Can you help on that front?

**Comment by TatriX** [comment]
I'm a terrible designer ;(

**Comment by svenstaro** [comment]
That makes two of us! I'll do the Gutenberg rewrite tomorrow.

**Comment by icefoxen** [comment]
See #23.
