### ISSUE TITLE
Slow down when using get_wrap (or maybe text draws?)

### ISSUE THREAD

**Issue by Manghi** [ggez/ggez#166]
Something I found while working on issue 168... I wanted to display a message when in fullscreen describing why the circle moved. I saw that ggez recently added `get_wrap()` to handle new lines in text strings. Figured why not add this to the example too. When drawn there is a visible impact to performance on my system. Wanted to know if it is just me or if other people see this too; also if the specific way I'm doing this is not performant with respect to how ggez/gfx works.

```Rust
    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx);

        {
            let message = "The circle moves position as it is placed using window coordinates, not game coordinates.";
            let font = ggez::graphics::Font::new(ctx, "/DejaVuSerif.ttf", 16)?;
            let (_, wrapped_msgs) = font.get_wrap(&message, 200);
            let mut offset = 0.0;
            for x in wrapped_msgs {
                let text = ggez::graphics::Text::new(ctx, x.as_str(), &font)?;
                ggez::graphics::draw(ctx, &text, Point2::new(600.0, 150.0+offset), 0.0)?;
                offset += 20.0;
            }
        }

        let rot_circle = graphics::Mesh::new_circle(ctx, DrawMode::Line(3.0), Point2::new(0.0, 0.0), 100.0, 4.0)?;
        rot_circle.draw(ctx, Point2::new(400.0, 300.0), self.angle)?;


        graphics::present(ctx);
        Ok(())
    }
```

**Comment by icefoxen** [comment]
Creating `Font` and `Text` objects are expensive operations.  If you are suddenly creating multiple `Text`'s instead of a single one then it will take longer.

**Comment by Manghi** [comment]
Is there a better way to do this? Maybe placing each "drawable", text or meshes, on an "canvas" (not sure if this is the correct terminology) and then drawing that object once instead of each call as I have listed above. I feel like this is related to #127.

**Comment by icefoxen** [comment]
The actual drawing really isn't the expensive part, the drawing is handled by the GPU which is really good at it.  The expensive part is loading the fonts, where you load and parse complex data structures, and rendering the text, where you iterate over every pixel in a texture and for each one do a bunch of math to figure out how to draw a shape.

The issue with #126 is getting the data into the GPU and keeping it cached there without having to do lots of expensive communication with the GPU, which is what spritebatches do.

What you *want* to be doing is create your resources once and then keep them around, something like this:

```rust

struct MyGameState {
   font: Font,
   wrapped_msgs: Vec<Text>,
}

impl MyGameState {
   fn new(ctx: &mut Context) -> GameResult<Self> {
        let font = ggez::graphics::Font::new(ctx, "/DejaVuSerif.ttf", 16)?;
        let message = "The circle moves position as it is placed using window coordinates, not game coordinates.";
        let (_, wrapped_lines) = font.get_wrap(&message, 200);
        let wrapped_msgs = wrapped_lines.iter()
            .map(|line| ggez::graphics::Text::new(ctx, line.as_str(), &font))
            .collect()?;
        Self {
            font,
            wrapped_msgs,
        }
   }
}

impl EventHandler on MyGameState {
    ...
    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx);
        {
            let mut offset = 0.0;
            for x in self.wrapped_msgs {
                ggez::graphics::draw(ctx, &text, Point2::new(600.0, 150.0+offset), 0.0)?;
                offset += 20.0;
            }
        }

        let rot_circle = graphics::Mesh::new_circle(ctx, DrawMode::Line(3.0), Point2::new(0.0, 0.0), 100.0, 4.0)?;
        rot_circle.draw(ctx, Point2::new(400.0, 300.0), self.angle)?;


        graphics::present(ctx);
        Ok(())
    }
```

**Comment by icefoxen** [comment]
@Manghi Any report on how this works out?

**Comment by Manghi** [comment]
This works fabulously! Moving the expensive parts into the initialization makes perfect sense now. 
Closing issue as not needed.
