### ISSUE TITLE
Can't easily cross-compile to Windows

### ISSUE THREAD

**Issue by vi** [ggez/ggez#168]
With Piston, cross-compilation works out of the box:

```
pistontest$ cargo rustc --release --target=i686-pc-windows-gnu -- -C panic=abort
   Compiling pistontest v0.1.0 (file:///mnt/src/_/pistontest)
    Finished release [optimized] target(s)

pistontest$ rabin2 -l target/i686-pc-windows-gnu/release/pistontest.exe
[Linked libraries]
dwmapi.dll
advapi32.dll
gdi32.dll
kernel32.dll
msvcrt.dll
opengl32.dll
shell32.dll
user32.dll
userenv.dll
ws2_32.dll

pistontest$ wine target/i686-pc-windows-gnu/release/pistontest.exe
(the window shows up)
```

But in ggez it seems to be not the way:

```
ggeztest$ cargo rustc --release --target=i686-pc-windows-gnu -- -C panic=abort
...
   Compiling ggez v0.3.3
   Compiling ggeztest v0.1.0 (file:///mnt/src/_/ggeztest)
error: linking with `i586-mingw32msvc-gcc` failed: exit code: 1
...
  = note: /usr/bin/i686-w64-mingw32-ld: cannot find -lSDL2
          collect2: error: ld returned 1 exit status
```

Is it by design or there will be alternative, pure-Rust engines allowing easy cross-compilation?

Note: [see below](https://github.com/ggez/ggez/issues/168#issuecomment-332679202) steps for doing less easy cross-compilation with downloaded pre-built SDL2.

**Comment by icefoxen** [comment]
Does it work if you give it a SDL2.lib?

(Caveat: I don't actually know how to tell it where SDL2.lib lives when cross-compiling.)

SDL2 is an external C library and so you need to provide that separately.  This causes some logistical problems; see issues #160, #29 .

**Comment by vi** [comment]
Where to get the SDL2.lib?

> is an external C library and so you need to provide that separately. This causes some logistical problems.

That is one of the motivators of keeping a project pure-Rust.

**Comment by vi** [comment]
Tried building with [this](https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio/sdl-visualstudio-3701.zip) - seems to be working (but I also need to put the DLL closer manually)

**Comment by termhn** [comment]
> Where to get the SDL2.lib?
> > is an external C library and so you need to provide that separately. This causes some logistical problems.

> That is one of the motivators of keeping a project pure-Rust.

Are you even able to build and run the project without cross compilation for your own machine? If so, your system is weird... you should have had to install the SDL2 libraries on your system to compile a ggez project at all. In order to cross compile, you'd need the SDL2 libraries for the platform you want to compile to as well.

As far as being pure rust, of course this is definitely one of the benefits of keeping a project pure rust. Unfortunately, it's not there yet. As is said in the README:

> The goal is to eventually have ggez be pure Rust, but we're not there yet. There's some blockers before we can drop SDL2 for glutin, see the issue tracker for more info.

**Comment by vi** [comment]
> Are you even able to build and run the project without cross compilation for your own machine?

Yes. It uses system `libSDL2-2.0.so`.

> If so, your system is weird...

Why? Being available for compiling against for local consumption is not that same as being available for cross-compilation. That's why cross-compiling qqez demo required downloading additional separate SDL package, which is in harmony with 

> In order to cross compile, you'd need the SDL2 libraries for the platform you want to compile to as well.`

.

**Comment by termhn** [comment]
I would think that most systems do not have a libSDL installed by default.
Usually in order to use the Rust-SDL2 crate (or compile anything using
SDL2) you need to download the required libs from their site or install
them using a package manager for your system.

This was true on all the systems I have used ggez  with so far anyway.

**Comment by vi** [comment]
Here by "system" i meant "package manager installed". And there are multiple other consumers of SDL2 in my system.

**Comment by icefoxen** [comment]
So the question seems to be

How can we make ggez easily cross-compile to Windows?

**Comment by termhn** [comment]
Well, what I meant by "weird" in the first place was having SDL2
development libraries installed by default.. If you installed them yourself
then that of course makes sense and aligns with having to install separate
ones for cross compilation.

**Comment by vi** [comment]
Probably the missing piece is a cross-compilation tuturial somewhere near documentation.

**Comment by icefoxen** [comment]
Sounds like something we should address in #118 

Unfortunately I haven't gotten around to that so far.  We'll get there!

**Comment by PSteinhaus** [comment]
Seeing that SDL2 is no longer used (and from personal experience using this library) it seems that this can be closed, since cross-compilation is now working beautifully, right?
