### ISSUE TITLE
Resizing window via set_mode() or set_resolution() doesn't fire resize_event()

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#170]
Only resizing the window from the window manager does.

Weird.

This is probably an SDL thing and I *sort* of understand the logic (since the resize doesn't come from an event caused by the user) but it's still basically never what we would want, afaict.

**Comment by icefoxen** [comment]
ahahaha it's worse than that... it only does it SOMETIMES!  At least on my Linux laptop.  Apparently only when you increase the screen to a resolution that's larger than what it already was?

Also if set_resolution() is redundant with set_mode() then we should remove it.

**Comment by icefoxen** [comment]
This is probably a bug with SDL or such so I'm just making it not-a-blocker for 0.4

**Comment by TatriX** [comment]
So how can I properly resize window *after* I created context?

**Comment by TatriX** [comment]
Well that worked:
```rust
graphics::set_mode(ctx, WindowMode::default().dimensions(screen_width as u32, screen_height as u32)).unwrap();
graphics::set_screen_coordinates(ctx, Rect::new(0.0, 0.0, screen_width, screen_height)).unwrap();
```

**Comment by icefoxen** [comment]
Fixed by switching to winit.
