### ISSUE TITLE
Support gradients?

### ISSUE THREAD

**Issue by TatriX** [ggez/ggez#172]
Is it possible to make a gradient?

**Comment by termhn** [comment]
I don't believe there's an easy helper function to do it. If you need it to be dynamically generated, you can do that with the current master version by writing and applying your own `PixelShader` (an OpenGL fragment shader that gets injected into the drawing pipeline). If you don't need it to be dynamic, then probably the easiest way is to just make a texture with a gradient and draw that.

**Comment by TatriX** [comment]
Can I make something like [this](https://love2d.org/wiki/Gradients)?

**Comment by termhn** [comment]
Yes. Untested, but something like this would give you the same result. You'll then have to scale it by however much you want to actually get the gradient to be the size you want or create a function similar to the `drawinrect()` in that love documentation to do it for you.

```rust
enum GradientDirection {
    Horizontal,
    Vertical
}

fn gradient(ctx: &mut Context, colors: &[graphics::Color], direction: GradientDirection) -> graphics::Image {
    let buf_size = colors.len();
    let mut buffer = Vec::with_capacity(buf_size);
    for color in colors {
        buffer.extend(color.into().iter());
    }
    let mut result;
    match direction {
        GradientDirection::Horizontal => {
            result = graphics::Image::from_rgba8(ctx, buf_size as u16, 1, &buffer);
            result.setFilter(graphics::FilterMode::Linear);
        },
        GradientDirection::Vertical => {
            result = graphics::Image::from_rgba8(ctx, 1, buf_size as u16, &buffer);
            result.setFilter(graphics::FilterMode::Linear);
        }
    }
    result
}
```

**Comment by TatriX** [comment]
Cool, thanks!
