### ISSUE TITLE
AppVeyor cache corruption

### ISSUE THREAD

**Issue by nlordell** [ggez/ggez#174]
I think that the AppVeyor cache might be corrupted which is causing false negatives. I stumbled across this RLS issue and it seams that it might be affecting other Rust projects:

https://github.com/rust-lang-nursery/rls/issues/510

Looks like there is a way to clear the cache which will hopefully stop the AppVeyor CI from failing when it shouldn't.

**Comment by icefoxen** [comment]
Seems fixed now.
