### ISSUE TITLE
Implement std::error::Error for GameError

### ISSUE THREAD

**Issue by LeoTindall** [ggez/ggez#176]
What it says on the tin. Currently, `std::error::Error` isn't implemented for `ggez::GameError`, which means it doesn't work with `error-chain` and other standard error handling.

**Comment by icefoxen** [comment]
Thought it was?  It should be.

**Comment by LeoTindall** [comment]
It definitely isn't. See: https://docs.rs/ggez/0.3.3/ggez/error/enum.GameError.html

**Comment by freiguy1** [comment]
Looks like it does, but maybe not in 0.3.3? See: https://github.com/ggez/ggez/blob/master/src/error.rs#L62

**Comment by icefoxen** [comment]
Yep, there we go: https://github.com/ggez/ggez/commit/8de41360d5290dbd240932eb485fd2d1bb0efe97

Would be easy to merge that into 0.3.3 and make a 0.3.4, but with so many people working on 0.4 it feels a bit redundant.  Still, if you want it, make a PR to the 0.3 branch and we'll see about a 0.3.4 release?

**Comment by LeoTindall** [comment]
No, I can move to 0.4. It's probably worth it anyway.
Thanks!

**Comment by freiguy1** [comment]
done! in #181. Working on my Hacktoberfest PRs! :)
