### ISSUE TITLE
Set conf::Conf.window_icon when context init stage could not use filesystem.mount.

### ISSUE THREAD

**Issue by TakWolf** [ggez/ggez#177]
I saw there is a new way to set resources dir (Last commit or  4.0).
I use the follow code to init my game:

``` rust
fn main() {
    let ctx = &mut Context::load_from_conf(
        "My-Some-Game",
        "TakWolf",
        Conf {
            window_title: String::from("My-Some-Game"),
            window_icon: String::from("/icon.png"), // -> There icon.png is in the resources dir, but here can not load
            window_width: 256,
            window_height: 240,
            window_mode: WindowMode {
                borderless: false,
                resizable: false,
                fullscreen_type: FullscreenType::Off,
                vsync: true,
                min_width: 0,
                min_height: 0,
                max_width: 0,
                max_height: 0,
                samples: NumSamples::One
            },
        }).unwrap();

    if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") { // The new way to append resources dir path
        let mut path = path::PathBuf::from(manifest_dir);
        path.push("resources");
        ctx.filesystem.mount(&path, true);
    }

    let app = &mut App::new(ctx).unwrap();
    event::run(ctx, app).unwrap();
}
``` 

filesystem.mount needs context, so when I set window_icon, I can't use filesystem.mount (beacuse context have not bean init.), even if the icon is in the resources dir.

**Comment by TakWolf** [comment]
I find that resources seams to be a convention.
Even if I did config nothing, the program will also search assets from "xx.exe/resources" dir.

Here is a suggestion:
1.Do not convene name "resources", let the resource search location start from the relative root directory. Because some one may be want flattened directories or define their own names like "assets". Put control to developers them selfs.
2.If 'CARGO_MANIFEST_DIR' available, make CARGO_MANIFEST_DIR in resources path default. So in the development phase, do not need to configure anything. (Some of the environment will be by default make project_dir in the path)

The above is only a personal proposal, for your information.

**Comment by TatriX** [comment]
I think using `/resources` from a root dir by default is a good idea.

**Comment by icefoxen** [comment]
I stumbled across that problem when I was implementing `mount()` but was in the middle of working on something else and forgot about it.  :-/

It's a bit of a dependency circle: You can't add more resource paths until you create the `Context`, and creating the `Context` needs to be able to load the icon so it can create the window.

There should be a way to break the cycle, just have to decide how.  Maybe put the list of paths to search in the `Conf` object?  That might be handy anyway.

**Comment by TatriX** [comment]
Why do you need a context to add a search path?

**Comment by icefoxen** [comment]
The search path gets stored in the context.

Now that I think of it there's another dependency loop, the game needs to be able to find the  conf.toml file to read settings out of it.

Maybe a function to create a context that takes a list of paths to add?

**Comment by icefoxen** [comment]
Actually I think that making a proper ContextBuilder might smooth things over here, then continue being useful for other things like #183, someday #186...

Should you he able to specify a list of resource paths to mount in the Conf object, though? It might be useful but it might start really violating OnceAndOnlyOnce...

**Comment by TakWolf** [comment]
An advice, consider APIs like this:

``` rust
let context = ContextBuilder::new()
    .window_config(WindowConfig::new()
        .title("My Game")
        .icon("icon.png")
        .size(800, 600)
        .vsync(true))
    .graphics_config(GraphicsConfig::new()
        .default_filter_mode(FilterMode.Nearest))
    .filesystem_config(FilesystemConfig::new()
        .game_id("MyGame")
        .author("TakWolf")
        .add_resources_path("resources/image")
        .add_resources_path("assets"))
    .audio_config(AudioConfig::new()
        .globle_volume(100))
    .some_other_config( .. )
   .build()
   .unwrap();
```

**Comment by icefoxen** [comment]
@TakWolf I've implemented a `ContextBuilder` somewhat along the lines of your suggestion, if you want to take a look and make sure it works for you.  See https://github.com/ggez/ggez/blob/master/examples/astroblasto.rs#L622-L647 for an example.

**Comment by icefoxen** [comment]
Works for me, closing this for now but feel free to re-open it.
