### ISSUE TITLE
About graphics::Rect, use scope definition, not pixels.

### ISSUE THREAD

**Issue by TakWolf** [ggez/ggez#179]
The global drawing function is graphics::draw_ex(),  from :

``` rust
fn draw_ex(&self, ctx: &mut Context, param: DrawParam) -> GameResult<()>;
```

The define of DrawParam is :

``` rust
pub struct DrawParam {
    pub src: Rect,
    pub dest: Point2,
    pub rotation: f32,
    pub scale: Point2,
    pub offset: Point2,
    pub shear: Point2,
}
```

About `DrawParam.src: Rect`

> /// a portion of the drawable to clip, as a fraction of the whole image.
> /// Defaults to the whole image (1.0) if omitted.

The problem is that rect use scope definition, not pixels.

I usually hope to use a sprite sheet image to create an animation. The image like this:
![ryu2](https://user-images.githubusercontent.com/6064962/31202357-dd532c58-a994-11e7-90e8-119bee0020f8.png)

This is a 3*3 sprite sheet image. So if I want to draw frame at position 0, the code is ：
``` rust
     graphics::draw_ex(ctx, & self.img, graphics::DrawParam {
            src: graphics::Rect::new(0.0, 0.0, 1.0 / 3.0, 1.0 / 3.0),
            ......
        }).unwrap();
```
The same, if I want to draw frame at position 4 (The center frame), the code is ：
``` rust
     graphics::draw_ex(ctx, & self.img, graphics::DrawParam {
            src: graphics::Rect::new( 1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0),
            ......
        }).unwrap();
```
The problem is that 1.0/3.0 can not be divisible.
So the rect real value is ：
``` rust
Rect {
    x: 0.33333....,
    y: 0.33333...,
    w: 0.3333......,
    h: 0.3333......
}
```
This maybe cause deviation ?

**Comment by TakWolf** [comment]
The same problem, the drawable seams to draw at the center at clip part, not left top.

For example, there is a image size = 15 * 15, wigth and height are odd numbers.
So the center is (7.5, 7.5), this will cause a pixel deviation,  you mast give a clear 0.5 to fix it.

===============================================
In addition, there some vague descriptions about Rect:
https://github.com/ggez/ggez/blob/master/src/graphics/types.rs#L20

```
/// A simple 2D rectangle.
///
/// The ggez convention is that `x` and `y` are the **center** of the rectangle,
/// with `width` and `height` being the total width and height, because this
/// is generally also how OpenGL tends to think about the world.
```

I did not understand the meaning here, that x and y are the center of the rectangle ? Not left top ?
The calculated looks so:
``` rust
 /// Returns the left edge of the `Rect`
    pub fn left(&self) -> f32 {
        self.x - (self.w / 2.0)
    }

    /// Returns the right edge of the `Rect`
    pub fn right(&self) -> f32 {
        self.x + (self.w / 2.0)
    }

    /// Returns the top edge of the `Rect`
    pub fn top(&self) -> f32 {
        self.y + (self.h / 2.0)
    }

    /// Returns the bottom edge of the `Rect`
    pub fn bottom(&self) -> f32 {
        self.y - (self.h / 2.0)
    }
```
But clip are not?

**Comment by icefoxen** [comment]
It uses the range 0-1 since OpenGL uses the range 0-1.  As far as the graphics card cares *all* coordinates are floating point numbers; how those translate to pixels is up to you to decide.

1/3 apparently cannot be represented exactly by floating point numbers, but if you set the filter mode to `Nearest` it will always choose the pixel (ok texel) nearest to the coordinate you give it.  This *should* work fine as far as I've ever seen?  Powers of two (including 1/2, 1/4, 1/8 etc) are basically always exact in floating point arithmetic, so making your sprite atlas 2x2 or 4x4 should always get you exact results.

And as the docs and code both say, the `Rect`'s x and y are the center of the rect, not the top-left corner.  If they are interpreted differently in `draw_ex()` then that is arguably a design mistake that should be fixed.

**Comment by PvdBerg1998** [comment]
Rect should be change to use 0,0 as it's top left imo

**Comment by icefoxen** [comment]
@TakWolf , rect now draws from the top left, make sure it works now? (Though rotation for Image is wrong, will try to fix that soon.)

**Comment by icefoxen** [comment]
Rotation for `Image` is now fixed.  By default things rotate from the top-left corner; to make them rotate from the center specify `Point2::new(0.5, 0.5)` for `offset`.
