### ISSUE TITLE
Travis CI failure tracking issue

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#18]
Basically the Travis build is failing because rust-sdl2 now depends on SDL2 2.0.4, while Travis only has 2.0.0 available.  Can we find a backport or some such?  Or just build it from scratch if necessary, though that sounds like a pain.

Distributions that include SDL2 2.0.4 include (see http://packages.ubuntu.com/search?keywords=libsdl2):

* Ubuntu Xenial
* Debian Stretch

There IS an issue request for a source for SDL2 specifically to be added: https://github.com/travis-ci/apt-source-whitelist/issues/307

**Comment by icefoxen** [comment]
No libsdl2 backports for Trusty or Precise, alas.

**Comment by icefoxen** [comment]
Got it to work by building from source, see commit 400bdb5045e3d479a1ffc801eb1bdc0fef114953

**Comment by svenstaro** [comment]
Seems to work. Good job. Closing.
