### ISSUE TITLE
Resize a graphics::Image

### ISSUE THREAD

**Issue by michaelbachner** [ggez/ggez#195]
Is it planned to include a resizing option for images? 
I need to resize an image. 
Or is there another way to achieve the same effect? 

I have a few pictures that need to be resized, so they fit on the game's screen. I can only tell on runtime how big they have to be, so I cannot edit the pictures beforehand.

**Comment by TatriX** [comment]
I believe you can use `graphcs::draw_ex` to achieve this.

**Comment by icefoxen** [comment]
You can use `draw_ex()` to have it draw at a different size, yes.  The scaling is done on the GPU so is basically free.

**Comment by michaelbachner** [comment]
Sounds great. I'll give it a try, when I have time again to work on my game. :-)

**Comment by icefoxen** [comment]
If this issue is resolved, I'm closing it.

**Comment by Ruddickmg** [comment]
graphics::draw_ex() doesn't seem to exist anymore.

**Comment by icefoxen** [comment]
`graphics::draw()` now provides all the functionality in a simpler fashion.
