### ISSUE TITLE
User Interface Support

### ISSUE THREAD

**Issue by Manghi** [ggez/ggez#198]
Hi,

I hacked a rough menu system in ggez on as you can see below. The current selection uses an arrow, '->'. I'll probably end up changing this to a soft glow effect once I figure it out. Overall it's not elegant but it's proof that it works.

![menus](https://user-images.githubusercontent.com/1715672/32154091-6da501e6-bceb-11e7-94dd-4b4b78f32f33.gif)

Are there any plans to add native UI support to ggez?

**Comment by icefoxen** [comment]
Essentially, no.  Such things should be able to be built on top of ggez without needing to have any support in the core code.

That said, a simple gui library for ggez would probably be pretty popular.  ;-)  I've considered making such a thing myself, but haven't had time.

**Comment by Manghi** [comment]
Perhaps what I drum up can be reused. Only time will tell. Thanks icefoxen.
