### ISSUE TITLE
Add SDL OSX setup docs

### ISSUE THREAD

**Issue by Arlefreak** [ggez/ggez#20]
Hi, I tried running

`cargo build --example astroblasto`
 
And got the following error:

```
note: ld: library not found for -lSDL2_mixer
error: Could not compile `ggez`.
```

Tried running: 

```
brew install sdl2
brew install sdl2_mixer --with-libvorbis
brew install sdl2_image
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"
```

And got the example to work

**Comment by icefoxen** [comment]
Thanks!  I'll get this added to the docs.

**Comment by icefoxen** [comment]
Linked to the rust-sdl2 setup docs, which are probably a better authority.

**Comment by Arlefreak** [comment]
Cool, closing this now
