### ISSUE TITLE
graphics::line flickering polygons

### ISSUE THREAD

**Issue by shiMusa** [ggez/ggez#200]
Hi all,

I'm learning the basics of ggez and while trying out the `graphics::line(...)` command, a strange flickering of random polygons appears:
relevant code:
```
let dat = *self.data.read().unwrap(); // some time-dependent value
graphics::line(ctx, &[
    Point{x: 100., y: 100.},
    Point{x: 200., y: dat},
    Point{x: 400., y: dat/2.}
]);
```
The `*self.data.read().unwrap()`-part is NOT the issue here, but rather the line-draw function!
For some reason, it draw some strange polygons. The sites of the polygons are not even correlated with the lines...

Any idea?

Thanks and cheers!

![2017-11-06](https://user-images.githubusercontent.com/17574234/32468678-4dbf8184-c31d-11e7-903c-517e3b1571d0.png)

**Comment by termhn** [comment]
This is a known bug in ggez 0.3 and is caused by a bug in the upstream rasterization layer that ggez uses (lyon) which has since been fixed, but those changes haven't been backported to 0.3. If you use the git master version of ggez, this issue should go away.

**Comment by shiMusa** [comment]
Ah, nice to hear that it's already being worked on! Thanks :)
