### ISSUE TITLE
Change event/window parameters to be f32 instead of u32

### ISSUE THREAD

**Issue by PvdBerg1998** [ggez/ggez#201]
This reduces `width as f32` boilerplate.

**Comment by icefoxen** [comment]
The main problem with this is that you can't reeeeally have fractional-size pixels...

**Comment by PvdBerg1998** [comment]
That's correct. But for every other function you need floats so every time you use the window resolution you end up converting it to a float anyway.

**Comment by Nokel81** [comment]
I would up to trying to implement this if it is still good to be implemented

**Comment by icefoxen** [comment]
@Nokel81 Sorry for the delayed response.  Go ahead, if you're still interested!

**Comment by Nokel81** [comment]
What does he mean by window parameters? Does he mean the canvas struct?

**Comment by Nokel81** [comment]
I was going to say that just adding `_f` events would be the best solution

**Comment by icefoxen** [comment]
This is handled more strictly and nicely by winit's dpi module now, so we'll be using that soon.
