### ISSUE TITLE
Can I add some methods on Rect like .contains(point), .overlaps(rect), etc...?

### ISSUE THREAD

**Issue by Zac-Garby** [ggez/ggez#204]
I think it'd be really useful to have this functionality, since it's such a common use of rectangles. Some ideas of methods I had were:

 - `.contains(&self, &Point) -> bool` If a rectangle contains a point.
 - `.overlaps(&self, &Rect) -> bool` If a rectangle overlaps another rectangle.
 - `.fits(&self, &Rect) -> bool` If another rectangle can fit inside this one.

Also, some other methods for translation/scaling which _could_ be done using operator overloads, or just normal methods:

 - `.translate(&self, x: f32, y: f32)` Translates the rectangle by (x, y). Could be `rect + (x, y)`
 - `.move_to(&self, x: f32, y: f32)` Moves the rectangle to (x, y)
 - `.scale(&self, sx: f32, sy: f32)` Scales the rectangles dimensions by (sx, sy). Could be `rect * (sx, sy)`
 - `.scale_centered(&self, sx: f32, sy: f32)` Like the last one, but scales about the middle of the rectangle instead of the origin
 - `.set_center(&self, x: f32, y: f32)` Sets the middle position of the rectangle to (x, y)

**Comment by Zac-Garby** [comment]
EDIT: Just realised the coordinates of a rectangle are in fact the center, so the last 2 methods would be redundant.

**Comment by Manghi** [comment]
Might I add 'intersects' as well? This was [present in ggez 0.2 ](https://docs.rs/ggez/0.2.2/ggez/graphics/struct.Rect.html#method.intersection)but is not in ggez 0.3+. It would be nice to have this back.

```Rust
fn has_intersection(&self, other: Rect) -> bool
Determine whether two rectangles intersect.
```
```Rust
fn intersection(&self, other: Rect) -> Option<Rect>
Calculate the intersection of two rectangles. The bitwise AND operator & can also be used.
```
```Rust
fn intersect_line(&self, start: Point, end: Point) -> Option<(Point, Point)>
Calculates the intersection of a rectangle and a line segment and returns the points of their intersection.
```

**Comment by Zac-Garby** [comment]
Yeah, good point - although `has_intersection` is the same thing as `overlaps`.

**Comment by icefoxen** [comment]
Totally, feel free to make a PR.  Though also see #179 and the discussion there; if we're going to change the coordinate system for `Rect`'s then we should do it *now*, do it *once*, and never think about it again.  I want to do this by the end of the month, because the screen and the `Rect` coordinate system should be the same and it has to be nailed down before fixing other issues like #134.

Anyone have any thoughts/opinions on that?

**Comment by Zac-Garby** [comment]
It's definitely quite weird having the coords of a rectangle at its centre. I only realised when I looked at the API docs -- otherwise I'd have never known. I think either change it to the top-left corner, or make it more obvious that its in the middle.

**Comment by Manghi** [comment]
I've always assumed it was at the top left because of the fact that the next two params were width and height. I think it should be corner Point and then its dimensions. My two cents.

**Comment by icefoxen** [comment]
Done in PR #205 , thank you.  :D  Coordinate system discussion will continue in #134
