### ISSUE TITLE
Stop sound before append

### ISSUE THREAD

**Issue by rap2hpoutre** [ggez/ggez#208]
Sometimes, when I call play twice on the same `audio::Source`, I don't want to just append the sound *after* the same sound, I would prefer stopping the previous one and play the new one. Uh, not sure it's clear. Let's try something else. Think about double jump in a game: I would like to cut the previous jump sound with the second one. Not waiting the first one to finish before appending the second one.

I tried to call `stop` before playing but it seems `stop` is called after the actual play (I'm not clear, again, sorry). It means that if I add this line:

```
self.sink.stop();
```
... in the `play` method (it's just a test, I don't want to modify the lib) of `audio.rs` like this:

```
pub fn play(&self) -> GameResult<()> {
    // Creating a new Decoder each time seems a little messy,
    // since it may do checking and data-type detection that is
    // redundant, but it's not super expensive.
    // See https://github.com/ggez/ggez/issues/98 for discussion
    let cursor = self.data.clone();
    let decoder = rodio::Decoder::new(cursor)?;
    self.sink.stop();
    self.sink.append(decoder);
    Ok(())
}
```

It plays and cuts the sound in the same cycle(?) or microsecond.

Does this request have an interest for this crate? Did I missed something?

**Comment by icefoxen** [comment]
I get what you mean, it is definitely something that we should be able to do.

**Comment by icefoxen** [comment]
Yes, thank you!
