### ISSUE TITLE
Warning resources.zip file not found

### ISSUE THREAD

**Issue by Arlefreak** [ggez/ggez#21]
Got the following warning:

`WARNING: Encountered error: ResourceNotFound("\'resources.zip\' file not found!)`

 when running:

`cargo run --example astroblasto`

Fixed by zipping and moved to target/debug/ folder

**Comment by icefoxen** [comment]
Yeah... this is technically correct but might not be worth printing a warning message.  It would be nice to have an easy way to make it tell you which of the various options it was actually loading things from though...
