### ISSUE TITLE
vsync ignored/off in example

### ISSUE THREAD

**Issue by turnage** [ggez/ggez#215]
I'd like to turn on vsync. It doesn't look like it is on in the example:

![screenshot](https://i.imgur.com/d3dIo25.png)

It appears to [default to true](https://docs.rs/ggez/0.3.4/src/ggez/conf.rs.html#69). I set it manually just to check but it doesn't have a visible effect.

Steps to reproduce:

1. `cargo new repro --bin`
2. copy example from ggez.rs
3. `pbpaste > src/main.rs`
4. add `ggez = "0.3"` to Cargo.toml
5. `cargo run`

Any suggestions?

I'm running a GTX 970 on Xubuntu 16.04; I tried with nouveau and proprietary drivers.

**Comment by turnage** [comment]
Correction! It works fine on the proprietary drivers; I made a mistake and thought I had turned them on.

Problem still exists on nouveau though.

**Comment by icefoxen** [comment]
Good to know, thanks. We need a list for driver bugs somewhere...

If you try something using glutin + gfx-rs do you still have the same problem? Try [the gfx-rs 0.16 examples](https://github.com/gfx-rs/gfx/tree/v0.16?)

**Comment by icefoxen** [comment]
Nothing going, closing for now. Reopen it if it's still a problem.
