### ISSUE TITLE
How to load conf.toml?

### ISSUE THREAD

**Issue by itmuckel** [ggez/ggez#217]
I want to save my Conf-settings in a toml file. I created a file named conf.toml with the following content:
```toml
window_title = "my_game"
```

Now I try to load it with the following code:
```rust
let mut f = File::open("conf.toml")?;
let conf = conf::Conf::from_toml_file(&mut f)?;
let ctx = &mut Context::load_from_conf("my_game", "itmuckel", conf)?;
```

I get an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConfigError("TOML decode error: a custom error")', src\libcore\result.rs:906:4
```

When I create the Conf struct programmatically everything works fine. What am I doing wrong?

**Comment by icefoxen** [comment]
Conf.toml should get loaded automatically if it exists in the game's data directory, see https://docs.rs/ggez/0.3.4/ggez/struct.Context.html#method.load_from_conf

Where it searches should be described in https://docs.rs/ggez/0.3.4/ggez/filesystem/index.html

The conf.toml file needs all the necessary fields filled out, it doesn't know how to fill in defaults if they're missing. That would be a nice thing to add.

**Comment by itmuckel** [comment]
Ah! That did it. I had to put the file in my `resources` folder and assign all fields. Thank you very much! :-)

**Comment by icefoxen** [comment]
This should get added to the FAQ
