### ISSUE TITLE
Implement operators for Point?

### ISSUE THREAD

**Issue by itmuckel** [ggez/ggez#226]
I just got this error:
![image](https://user-images.githubusercontent.com/18561536/34058059-fd1f8554-e1d9-11e7-8514-720ac8c5e380.png)

It might be useful to have subtraction, addition and (scalar-)multiplication for `ggez::graphics::Point` for all sorts of use cases. :-)

**Comment by icefoxen** [comment]
If you're using git master then `Point2` and such types are exported from `nalgebra` which implements these sorts of operations.

If not...  then you'll have to wait a month or so, I fear.  ;-)  Though I'll accept PR's into the 0.3 branch.

Oh, I'd forgotten about this... on 0.3 you can also build with the feature `mint` to use that for point types and such.

**Comment by itmuckel** [comment]
Okay, I think I'll wait for 0.4. I don't like to use unstable stuff. Or... what would you say? Is it safe to use the master branch? There is no develop branch yet, right?

**Comment by icefoxen** [comment]
Depends on what you're using.  master is... a little broken right now, mainly in terms of canvases and sprite rotation.  Hope to have both ironed out after this weekend.
