### ISSUE TITLE
Line rendering as large triangle

### ISSUE THREAD

**Issue by darrint** [ggez/ggez#227]
I ran into this while trying to implement debug draw for wrapped2d. I was rendering lots of polygons and line segments. Polygons were rendering without issue.

Sometimes graphics::line is rendering as a large triangle instead of a thin line. I can work around the problem in this one case by rounding the 200.001 in the sample code to 200.0. However, I have seen instances where rounding to a whole number still caused the triangle to render. 

This tiny sample program should have rendered a line:
![2017-12-16-102636_284x327_scrot](https://user-images.githubusercontent.com/108186/34071886-bcb5a594-e24b-11e7-89ad-baf0eee7f360.png)

```
extern crate ggez;
use ggez::conf;
use ggez::event;
use ggez::{GameResult, Context};
use ggez::graphics;
use ggez::graphics::{Point};
use std::time::Duration;

struct MainState;

impl event::EventHandler for MainState {
    fn update(&mut self, _ctx: &mut Context, _dt: Duration) -> GameResult<()> {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx);
        graphics::line(ctx, &[Point::new(200.001, 100.0), Point::new(100.0, 200.0)])?;
        //                               ^^^^^^^
        graphics::present(ctx);

        Ok(())
    }
}

pub fn main() {
    let c = conf::Conf::new();
    let ctx = &mut Context::load_from_conf("helloworld", "ggez", c).unwrap();
    let mut state = MainState{};

    if let Err(e) = event::run(ctx, &mut state) {
        println!("Error encountered: {}", e);
    } else {
        println!("Game exited cleanly.");
    }
}
```

**Comment by icefoxen** [comment]
What version of ggez are you using?  0.3 has a known bug similar to this: https://github.com/ggez/ggez/issues/200

Unfortunately we can't fix it without breaking API compatibility...

**Comment by darrint** [comment]
Thanks for the response. I'll try master.
