### ISSUE TITLE
Play with the SDL2 bundled build option

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#231]
Do we need to re-export the feature to make it work?

**Comment by neganp** [comment]
`sdl2`'s bundled option was added in `sdl2:0.31.0` but `ggez` transitively depends on `sdl2:0.30.0` via 'gfx_window_sdl`. It might be easiest to wait until `gfx_window_sdl` depends on the newer version?

**Comment by icefoxen** [comment]
This should be updated in the devel branch, which now depends on gfx 0.17, for which gfx_window_sdl is updated to use sdl2 0.31.  ....I think.

**Comment by neganp** [comment]
I can confirm that it has! :+1:

On `devel`, I observed that removing the system-level SDL package causes compilation to fail, but it succeeds again if the `sdl2` dependency in `Cargo.toml` is replaced with:

```
[dependencies.sdl2]
version = "0.31.0"
features = [ "bundled" ]
```

I'm hitting (what I'm pretty sure are unrelated) SDL errors elsewhere and can't run the examples, but this is worth pursuing.

**Comment by ozkriff** [comment]
Any progress on this? Seems extremely useful.

**Comment by icefoxen** [comment]
Not really.  I played with it a little bit with a friend on Windows but we couldn't get it to work, and set it aside without getting into why.

**Comment by ozkriff** [comment]
Hmmm, ok. With this diff

```diff
$ g diff
diff --git a/Cargo.toml b/Cargo.toml
index 203081b..03ade6b 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -30,6 +30,7 @@ bzip2 = ["zip/bzip2"]
 default = ["bzip2"]
 mint = ["nalgebra/mint"]
 multithread-image-decoding = ["image/hdr", "image/jpeg_rayon"]
+bundled = ["sdl2/bundled"]
 
 [dependencies]
 rusttype = "0.5"
```

I can run examples through cargo

```text
$ c r --example cube --features bundled
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/examples/cube`
FPS: 893.5919626764509
FPS: 562.2617767134786
FPS: 354.0809421952239
FPS: 258.85115644342653
Game exited cleanly.
```

but I can't run them as standalone binaries:
```text
$ ./target/debug/examples/cube
./target/debug/examples/cube: error while loading shared libraries: libSDL2-2.0.so.1: cannot open shared object file: No such file or directory
```

**Comment by Ratysz** [comment]
If I remember correctly, `bundled` is only relevant to building, as in, with that enabled `sdl2` will pull in and compile C dependencies on it's own. There *is* a [feature for static linking](https://github.com/Rust-SDL2/rust-sdl2/blob/master/Cargo.toml#L49) of said dependencies, however. I couldn't get it to work under Windows; admittedly, I haven't tried hard.

**Comment by icefoxen** [comment]
Ok, on Linux, using ozkriff's change, and running an external project that depends on ggez, I get the same results.  Running with `cargo run ...` works just fine.  Trying to run the binary directly says it can't find `libSDL2-2.0.so.1`.

I do find `libSDL2-2.0.so.1` in `./target/release/build/sdl2-sys-5347dd0cff02cecb/out/lib/`.  Copying it to the same directory as the binary still doesn't let me run the binary directly, I have to set the `LD_LIBRARY_PATH` environment variable, and then it works fine.  Adding `sdl2-sys` with the `static-link` feature flag also appears to work.

It's actually pretty slick.  I'll try it out on Windows in a bit.  In the long run I think this will be made obsolete by switching to winit (Real Soon Now™), but it's pretty easy to add the feature flags and I don't think it has any down-sides.

**Comment by icefoxen** [comment]
On Windows it appears to require `cmake` installed to build SDL2, and maybe some other stuff.  So, that doesn't really solve the problem as much as just push it back to a different dependency.

**Comment by icefoxen** [comment]
To do:

 * Add feature flags
 * Update build docs with this info

**Comment by dwgill** [comment]
For what it's worth, given the details in this issue, I was able to get the `hello_world.rs` example working on Windows 10 with the following steps:

- Install `cmake` via [Scoop](https://scoop.sh/)
- Run the `vcvarsall.bat` script with the single argument `x86_amd64`.
  - I believe this script is installed with the visual studio dev/build tools, which you should need to have installed already to compile Rust programs on Windows?
  - I found this script in buried in `Program Files (x86)`. Here's the command I ran with the absolute path of the script:
    ````
    "\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
    ````
- Modify the dependencies section of my `Cargo.toml` to look like the following:
  ````
  [dependencies]
  ggez = "0.4"

  [dependencies.sdl2]
  version = "0.31"
  features = ["bundled", "static-link"]
  ````

I don't know if any of that is useful but I thought I would share on the chance it could be. 😅

**Comment by icefoxen** [comment]
Seems to sorta work in some cases, buy now obsolete since we use winit instead.
