### ISSUE TITLE
Wrong version in 0.4 DOCS

### ISSUE THREAD

**Issue by JosefKuchar** [ggez/ggez#232]
There is wrong version in https://docs.rs/ggez/0.4.0-rc.1/ggez/ under "Usage" title: `ggez = "0.3"` => `ggez = "0.4.0-rc.1"`

**Comment by icefoxen** [comment]
Thanks, I'll get that fixed.

**Comment by icefoxen** [comment]
Should be fixed, will be on docs.rs with the next release.
