### ISSUE TITLE
audio::Source playing() returns true even if it's not playing

### ISSUE THREAD

**Issue by acheronfail** [ggez/ggez#233]
When new audio sources are instantiated their `playing()` method always returns true. 

Example:
```rust
let test = ggez::audio::Source::new(ctx, "/audio/shot.ogg").unwrap();
println!("test.playing() = {}", test.playing()); // "test.playing() = true"
```

Due to this it's not possible to check if a sound has started playing.

**Comment by icefoxen** [comment]
Thanks, that should be fixable.

**Comment by icefoxen** [comment]
@acheronfail This should be fixed now, please confirm that it works for you!

**Comment by acheronfail** [comment]
Sure does! Thanks for that 👍
