### ISSUE TITLE
Known rough spots

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#234]
These are just the areas that don't get banged on a lot in my own usage, and so might be sub-par.

 * audio -- https://github.com/ggez/ggez/issues/75
 * mouse and gamepad (not many tests or examples for those)
 * ~~breaking up `graphics/mod.rs` might be nice; it's 1300 lines.~~ Done in #256 
 * unit tests! #380
 * ~~Bitmap fonts~~ Refactor into separate crate.
 * ~~Filesystem -- could be refactored to top-level functions like the rest of the API instead of methods on the `Filesystem`~~ Done in b85a8d0eecf6a0f191028b7a6c2aea70d02447f0
 * ~~Clean up the `error` module... use `failure`?~~

**Comment by CaptainKraft** [comment]
I tried to switch to a bitmap font just before submitting a jam game, and didn't figure it out fast enough, so I resorted back to ttf fonts.

It seems like there is some minimum requirement for the characters required in the font string?

**Comment by icefoxen** [comment]
Shouldn't be any requirement besides them being fixed width in a horizontal line.  Were you using master or devel branch?

**Comment by CaptainKraft** [comment]
It looks like I have 0.4 in my Cargo.toml.

I would get an error when I passed in a string that was just capital letters. It would complain about missing characters.

**Comment by icefoxen** [comment]
Does your bitmap font have capital letters in it?  Are you passing it a description string that includes capital letters?

I mean, I assume so, but I gotta make sure.  Having problems with *only* capital letters is strange.  What error did you get?

**Comment by CaptainKraft** [comment]
I passed in " ABCDEFGHIJKLMNOPQRSTUVWXYZ" and got this error:

`Error encountered: GameError FontError("Character \'i\' not in bitmap font!")`

This is the file I'm trying to use:

![image](https://user-images.githubusercontent.com/1237356/37347073-a283f2b8-2696-11e8-90f0-05239fc86a6b.png)

There is a space as the first character and I inverted the colors so you can see it on this white background.

**Comment by icefoxen** [comment]
Sounds like the error message could be better then!  :D

**Comment by icefoxen** [comment]
Thoughts on unit tests: We should be able to have two sets of unit tests.  One that requires a `Context` to be created and so can't be run terribly well on headless servers, and one that tests things that don't need graphics/etc.  We'd be able to run the former set of tests at least locally.

**Comment by icefoxen** [comment]
Cleaned up `error` module a bit, or tried to.  Using `failure` is tempting but while it would reduce the boilerplate a bit I'm not sure it would actually make anything any easier.  We're basically wrapping other error types from a dozen different crates.
