### ISSUE TITLE
.set_transform() has no effect on some draw commands without call to .draw()

### ISSUE THREAD

**Issue by kaedroho** [ggez/ggez#241]
I've noticed an issue where if you use ``.set_transform()`` and ``.rectangle()`` together, the transform is not applied, but if you insert a ``.draw()`` call (which in my case is drawing a spritebatch) before the ``.rectangle()``, it seems to work properly.

For example, this won't apply the transform to the rectangle:
```rust
graphics::set_transform(ctx, ...);
graphics::rectangle(ctx, graphics::DrawMode::Fill, graphics::Rect::new(0.0, 0.0, 100.0, 100.0));
```

But this works:
```rust
graphics::set_transform(ctx, ...);
graphics::draw_ex(ctx, spritebatch, param);
graphics::rectangle(ctx, graphics::DrawMode::Fill, graphics::Rect::new(0.0, 0.0, 100.0, 100.0));
```

**Comment by termhn** [comment]
Thought I had this in the documentation but didn't--after calling a `set_transform`, `set_projection`, etc. you need to call `apply_transformations(ctx)`. This is so that if you make multiple changes at once it's not needlessly recalculating the MVP matrix when it doesn't need to be.
