### ISSUE TITLE
Present canvas / image to file

### ISSUE THREAD

**Issue by DenialAdams** [ggez/ggez#244]
It'd be neat if I could render a canvas, and then output that (or perhaps the underlying Image?) to a file. This would be nice for screenshots, but also for other stuff like rendering my world in full size so I can see it all at once rather than drawing to the size of the viewport.

(sorry if this is doable already, I couldn't figure out how!)

**Comment by icefoxen** [comment]
You're right, this should be doable!  But, is not currently.  Shouldn't be hard to add.

**Comment by DenialAdams** [comment]
Willing to try tackling this if you have any direction of where to look :)

**Comment by termhn** [comment]
Canvas data is currently just written to an Image, which is just a gfx `ShaderResourceView` on the backend, which should probably be easy enough to extract the buffer from (though I don't know how off the top of my head), which should just be an array of contiguous `u8`s in rgba format. Then you can probably use the [image](https://github.com/PistonDevelopers/image) crate, which is already in ggez, to encode that and save it to a file pretty easily.

**Comment by DenialAdams** [comment]
Ah ok, makes sense. I looked at ShaderResourceView initially but all the type stuff gfx was doing made my eyes roll back into my head :) I'll take a look tomorrow, thanks for the pointer.

**Comment by icefoxen** [comment]
The latest `gamma` example in gfx has screenshot functionality: https://github.com/gfx-rs/gfx/blob/v0.17/examples/gamma/main.rs

**Comment by DenialAdams** [comment]
> The latest gamma example in gfx has screenshot functionality: https://github.com/gfx-rs/gfx/blob/v0.17/examples/gamma/main.rs#L124-L158

Thanks! That worked great for taking a screenshot because of all the gfx "machinery" is present in GameContext. As for Canvas, I'm still trying to figure how to do anything with a ShaderResourceView, but hopefully I will do so and submit a PR with both features.

> We don't use gfx 0.17 but it shouldn't be hard to update to it if we need to for this functionality.

I was having some silly problems, so I updated gfx anyway (https://github.com/ggez/ggez/pull/246) but I don't think it was necessary for the screenshot functionality.

**Comment by DenialAdams** [comment]
Ok, I realized with the canvas stuff that because a canvas replaces `out`, we can actually output the canvas just by switching to a canvas and taking a "screenshot" the same way as was shown in the gfx example.

(so I'll probably have 2 global fns in graphics - one that is a true screenshot, and one that "screenshots" the active canvas. both can share a helper procedure that does the heavy lifting.)

Ostensibly this works, image dimensions match the canvas, but I'm very confused with what I am seeing in the canvas screenshot. The canvas is 3x bigger than the normal window size, but I am seeing the same amount of stuff as on screen (just stretched.) This could be a  bug in my game code rather than the screenshot functionality, but I want to figure it out to be sure.

**Comment by icefoxen** [comment]
Screenshots and "screenshot active canvas" should be the same thing, I would think. The first would just be the same code with no active canvas.

Do you have the color depth and such of your screenshot the same as what you're screenshotting? That's the first thing that comes to mind.

**Comment by DenialAdams** [comment]
> Screenshots and "screenshot active canvas" should be the same thing, I would think. The first would just be the same code with no active canvas.

Yep, that's fine!

> Do you have the color depth and such of your screenshot the same as what you're screenshotting? That's the first thing that comes to mind.

I don't think it's a color depth issue. What I am seeing is that if I run my game at 640x480, with tiles 32px wide I can see 640/32 = 20 tiles across the screen. (they're hex tiles and they're staggered so it's a bit weirder than that, but basically :P). Screenshotting works great.

![screenshot](https://i.imgur.com/CYWHhGN.png)

So if I make a 1600x1600 canvas and draw the world the same way, I would expect to see 1600/32 = 50 full tiles across the canvas. Screenshotting _this_ is messed up. I can still only see 20 tiles across the screen, it's just warped. Here is what I am seeing:

![level](https://i.imgur.com/akqO8w6.png)

If I increase the window size the level screenshot also changes. Somehow the size of the window is affecting the drawing....maybe? Trying to figure it out.

**Comment by DenialAdams** [comment]
teh, I'm just a moron who doesn't understand basic graphics programming at all. sigh.

`ggez::graphics::set_screen_coordinates` fixed it.

gonna clean up and make a PR.

**Comment by icefoxen** [comment]
Awesome!  And trust me, the amount of time I have spent messing around with `set_screen_coordinates` to try to figure out what the heck the actual *right* thing to do is quite embarrassing.

**Comment by icefoxen** [comment]
Closing this since the PR has been pulled
