### ISSUE TITLE
Playing the same sound several times appends instead of playing simultaneously

### ISSUE THREAD

**Issue by jupart** [ggez/ggez#245]
Currently, ggez::audio::Source.play() uses rodio::Sink.append(), which tacks the sound onto the end of the currently playing sound instance (when playing the same Source). To me, play() should probably play the new sound immediately, and not care about any other instances of the sound playing.

Similar rodio issue with possible solution: https://github.com/tomaka/rodio/issues/141

**Comment by icefoxen** [comment]
As discussed on IRC: Storing a SoundData and creating Source's from it as necessary should work, but you have to keep a hold of the Source until it finishes or else it will stop when it's dropped...  ggez should be able to keep track of this for you and GC Source's when they're done playing.

Cloning a `Source` also doesn't seem to work 'cause it contains a `rodio::Sink`, which isn't `Clone`.  Honestly we might be better off ripping up the sound API some and implementing something a bit more intuitive based on some of `rodio`'s newer stuff, like `DynamicMixer`.

**Comment by icefoxen** [comment]
Also see #208, #75

**Comment by jupart** [comment]
What do you think about letting `ggez::audio::Source` have a queue of `rodio::Sink`'s it can use, say `Vec<rodio::Sink; 4>` (everywhere I look folks seem to allow 4 simultaneous identical sounds: Kivent, Amethyst). When you call `Source.play()`, it'll grab an `.empty()` sink if there is one. Not sure what to do if there isn't one, maybe just ignore the `play()` call. 

We'll lose a little control over `Source.pause()`, `.stop()`, `.resume()`, and whatever else, but we could provide `.stop_all()`, `.stop_last_played()`, etc. which I think would be good enough for most use cases.

As a user, you could either use a stored container of `Source`'s or create a new `Source` for every thing (entity) that needs it.

Additional stuff (should probably be in a separate issue). I'd like to add:
* `SoundData::from_file()` for loading up `SoundData`'s to build `Source`'s as needed since `Source` doesn't impl Clone/Copy
* `SpatialSource` which uses `rodio::SpatialSink` and related set/getters or make `Source` use `SpatialSink` all the time, with defaults that make it act like a regular `Sink`
* `Source.repeat(bool)`

Thoughts/plans for later:
*  some way to create two loop points (loop point and point to return to after loop) on a `Source`, maybe using `rodio::Source.periodic_access()` or `.take_duration()`with a 
* `sink.empty()` callback

**Comment by jupart** [comment]
I've since changed my mind about `audio::Source` stored a `Vec<rodio::Sink>`. I don't think it's needed if the user makes copies of `audio::Source`'s as they need them. The status functions you provide like `playing()`, etc. are too valuable to mess up with a bunch of Sinks per Source.

**Comment by expenses** [comment]
The way I solved this was to have a `Vec<Sink>`, and when a sound was played, try to append it to an empty sink or create a new one if they're all being used. This means that you end up with as many sinks as there have been sounds playing concurrently, which imo is fairly efficient.

**Comment by jupart** [comment]
I thought this was a good solution too at first, but how would you stop and individual sound or pause it?

* If you pause the game, you'd want to pause all playing sounds, which you could do with a `Vec<Sink>`
* But if you'd like to cut a sound on a state change (say you were playing `shooting.wav` and want to stop and play `hurt.wav`, you'd be unable to without some handle to the `Sink` your thing is using

**Comment by termhn** [comment]
You could return a handle to the index in the Vec when the sink is created
and then use that in future operations... This is what we do with shaders
atm I believe.

**Comment by termhn** [comment]
No problem. Yeah that is somewhat of an issue... unless you're going to garbage collect the vec at some points or something, but that presents its own issues as well. A possible solution would be to have 

```rust
#[derive(Clone, Copy)]
struct SinkHandle {
    usize idx,
    u64 uuid,
}
```

Then you'd add a check in the `Source.pause` etc to check if the Sink in the provided index still matched with the uuid (could be a hash of the Sink or something). If not you'd return an `Err` indicating as such. Would add a small runtime cost but then you wouldn't need to continually grow the Vec everytime (could probably become a fairly significant memory issue fairly quickly depending on how frequent sounds are being played).

Really just talking off the top of my head here though, there could be a better solution :P

**Comment by expenses** [comment]
I'd use ascending order uuids, but yeah, that might work
