### ISSUE TITLE
Can we make resource loading asynchronous?

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#251]
Right now, the answer is "kinda".  All the `Image::load()` methods and such are entirely synchronous.  To make them async we would need to be able to hold on to the `Context`, but the `Context` is not really `Send` or `Sync` and so without rolling your own event loop you can only ever get a reference to it.  But loading stuff in the background without hanging the render thread would be nice.

It should be possible to do most of the I/O and decoding without touching the `Context`: open a file, give it to a background thread, read it and if necessary decode it into a buffer, then pass the buffer of raw data back to the main thread to be loaded with something like `Image::from_u8()`.  But that's a pain in the butt and it would be nice if we could make things smoother.  Maybe it can be implemented in an add-on library?

This would also be easier if we explicitly make the `Context` a collection of objects instead of one big do-everything thing, which would also have other benefits.

**Comment by Manghi** [comment]
Would Futures be the right tool for this job, or are there other ways? Futures is the only thing that came to mind though the **_how_** is a bit fuzzy at the moment.

**Comment by icefoxen** [comment]
Futures was more or less what I was thinking of.  Though from what I've been reading about them, futures are just an interface; it's up to you to implement what they actually do.

**Comment by icefoxen** [comment]
Now that I've played with futures... Not worth the effort ourselves, though warmy or another project might help. Loading stuff from disk is trivially threadable, and shipping textures to the graphics card almost never will be, so there's not much to gain from async.

**Comment by Geams** [comment]
Closing this issue makes no sense.
Async loading of game assets while displaying a splash screen with a progress bar is a must.
libgdx (Java) is able to provide that with its AssetManager.
I am a beginner of Rust that likes to get away from Java.
I also looked at piston and amethyst, but nobody has an example of the most common screen flow of pratically every commercial game.

**Comment by icefoxen** [comment]
Loading of game assets while displaying a splash screen can be easily done in a background thread.  You don't need futures or anything like that to do it, just a queue.  This doesn't need to be built into ggez.

**Comment by jDomantas** [comment]
Is there any documentation or examples on how to do this with a background thread? As far as I can see all the functions require mutable reference to context so I can't find how I could have load anything without blocking rendering.
