### ISSUE TITLE
Can we have pixel-based sizing for fonts?

### ISSUE THREAD

**Issue by makoConstruct** [ggez/ggez#268]
I'm trying to make a pixelated game, using pixel art and a pixel font. Regarding text, this doesn't seem to be doable? Point sizes are unusable for various reasons:

* Why would a gamedev want to deal in Pts? What are Pts? Do they even have a fixed meaning?

* My screen lies horribly about its DPI, many screens are the same. Very few screens give a completely accurate number. It can't really be relied on for anything.

* If I had access to the measured DPI I might use it to scale the text down to compensate away the DPI-sensitive code further up the toolchain, but there doesn't seem to be a way to get that number.

To hammer my point home, I will supply a picture of the hello world example as it appears on my machine https://imgur.com/a/TUXLr

**Comment by icefoxen** [comment]
A point is 1/72 of an inch.

I would love to have pixel-absolute sizes for fonts but I've yet to see a TTF renderer that really offers that.  :-/  If we can figure out how to do it, we should do it.

For now the easiest way to get pixel-absolute fonts is to use bitmap fonts.

**Comment by uggwar** [comment]
The DPI is calculated from the display size, and not the size of the window. So running my little game in the same sized window on my internal and external monitor gave different font sizes. I forced ggez to use 72 as DPI and the problem was "solved". Not pretty, but not sure how to fix this properly.

**Comment by icefoxen** [comment]
Notes on how SDL2 does it:

```
14:07 < m12y_> Icefoz: i've relied on SDL2's drawable_size for text rendering and it's worked perfectly for me (especially on mac/ios retina)
14:19 < m12y_> it returns the resolution in physical pixels (e.g. what you want to pass to glViewport), whereas the normal `size` method returns the resolution in (DPI aware) virtual pixels. i use`size` to lay out my UIs, and then `drawable_size` to determine the actual font size to draw in that UI
```

**Comment by icefoxen** [comment]
Honestly just having a function that builds a `Text` to a given pixel size would be very easy, even if it gets abused.  :|

**Comment by Sushisource** [comment]
I'm doing this by basically determining the pt -> pixel sizes experimentally and just saving that info statically for now. Having that function would be killer.

**Comment by icefoxen** [comment]
See commit 99fce38, it's a very small change.  Just needs testing.

**Comment by icefoxen** [comment]
Tested, it works.

**Comment by icefoxen** [comment]
Closing.  :cry: See #587 for basically the reason why.
