### ISSUE TITLE
Installing on Windows needs DLL's

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#28]
Apparently my system (and some others) already had it installed somewhere, but SDL2 mixer won't function without it.

We should provide a nice zip file of .dll's.  Or just make everything pure Rust.

**Comment by onelson** [comment]
The docs on distribution Love2D games talks about having to bundle a smattering of DLLs for the same reason on windows. iirc the DLLs must be produced with the same compiler as your binary. I'd been thinking about trying to include source for the deps and build against a static deps crate that'll build all that stuff in-line. Seems like a lot of work though...

**Comment by icefoxen** [comment]
Yeah it appears that SDL2_mixer's dll download includes a pile of codec DLL's along with SDL_mixer itself.  We need to make a bundle and include them all.  (Or solve issue #29 )

**Comment by icefoxen** [comment]
SDL_mixer is going away, but we really should provide a nice bundle of DLL's for the handiness of our users, as long as such things are necessary.

**Comment by Gordon-F** [comment]
@icefoxen How about using glutin and wininit instead of SDL2 ? Or distributing SDL2 source code in repo and compile it with ggez.

**Comment by icefoxen** [comment]
@Gordon-F Glutin is eventually the goal, it will take a little while though.  Joystick/game controller support is a sticking point, and there's myriad tiny things that are currently done through SDL so it's not going to be a super quick change.  And right now I'm busy working on other bits instead.

Distributing SDL2's source I honestly hadn't thought of.  Hmmm...

**Comment by Gordon-F** [comment]
@icefoxen But this will increase compile time. This is not a best part of Rust.

**Comment by onelson** [comment]
I feel like non-windows platforms make it easy enough to get sdl installed, and really providing DLLs for Win is probably the way to go in the short term.
(This is what Love2D does)
Longer term, I guess a pure rust input system is something to explicitly add to the roadmap.

Alternatively, maybe there's a way to get SDL statically linked for ggez projects? That's a thing, right?

**Comment by icefoxen** [comment]
This isn't going to stop while we use SDL2, and the rust-sdl2 peoples have better docs on installing the SDL2 dll's than we ever will.  Additionally, while developers can distribute the DLL's to dodge this problem for their binaries, we *can't* do that because our users are developers who need to compile against said DLL's.  So they're just going to have to suck it up and put them in the Right Place themselves.
