### ISSUE TITLE
GGEZ does not detect OpenGL 4.2

### ISSUE THREAD

**Issue by jprob** [ggez/ggez#282]
First of all thanks for supplying a gaming library for rust. On trying to run the hello_world example I get the following error

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Could not create GL context"))', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I found out that this is probably since ggez doesn't work with OpenGL 3.0. Running a command to get my OpenGL specs gives me

[jprob@jprob ggez]$ glxinfo | grep "OpenGL"
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.3.3
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.3.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.3.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

I don't know much about OpenGL but if I understand it right, I actually should be able to support 4.2/3.2 on my device with the core profile. 3.0 is only the legacy version. Would it be able for ggez to run on my computer?

**Comment by dannyfritz** [comment]
Check out issue #194
