### ISSUE TITLE
Need a simple API for telling the Context about input events.

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#284]
From #283:

> ... I don't like it, because it requires storing the mouse position from events in `event::run()`.  So if you roll your own event loop the mouse position no longer gets updated.  I do *not* like making this necessary because it's super easy to miss.  I dislike it more because there's already a way to get mouse position, from the `MouseMotion` event.  Adding a workaround that violates OnceAndOnlyOnce seems dirty, even if it is for the sake of API symmetry -- the alternative is to have `mouse::set_position()` with no matching `mouse::get_position()`, which doesn't seem much better.
> One possible solution would be to add a hook to feed events into the `Context` so it can update its own internal state based on them as necessary, which would cover both this case and the `resize_viewport()` call that's there anyway.  Basically, you would call `ctx.process_events()` on each event at the start of your own event loop.  That's probably the right choice...

I'm not considering this a breaking change, since it currently only affects code that already doesn't work.  So, we can put this in 0.4.1.

**Comment by dannyfritz** [comment]
Looks like the commit might already address it, but exposing the event buffer seems like a good idea to me: http://love2d.org/wiki/love.event

**Comment by icefoxen** [comment]
It's not a bad idea at all.  We sooooort of expose an event queue, but it's the SDL2 event queue and the SDL2 event queue is, shall we say, persnickity.  I don't really want to write another and have to make the two of them talk to each other, so for the moment that's that (at least as far as I am concerned).  When we someday switch to glutin maybe we'll be able to do more.
