### ISSUE TITLE
Creating a BoundSpriteBatch still requires to consume an image to create a SpriteBatch

### ISSUE THREAD

**Issue by theor** [ggez/ggez#293]
required code ATM: `SpriteBatch::new(some_image).with_image(&ref_to_another_image)`

what's the point then ?

**Comment by icefoxen** [comment]
Gooooood point.

Also I recently remembered that an Image is really just an Arc'ed texture handle, so cloning it is not expensive.

BoundSpriteBatch may be somewhat worthless. ^_^;

**Comment by icefoxen** [comment]
Marked `BoundSpriteBatch` as deprecated in 4726a7e6f5da3d2a0523a3e436415811c2304175
