### ISSUE TITLE
Owning a Context

### ISSUE THREAD

**Issue by itmuckel** [ggez/ggez#295]
This may be a basic rust question, but I ask it anyway.

In my game I have an `AssetManager` struct, which is responsible for initializing graphics and updating them. How can I let this AssetManager own the Context, so I don't need to pass a mutable context to it in every function call.

I know that the Context lives on the stack and gets passed to `ggez::event::run(...)`, but can I also have a mutable Reference to it for other classes? How do you deal with the Context in your games?

**Comment by icefoxen** [comment]
This is actually a tricky problem that phaazon and I have been grappling with as well.  (See https://github.com/phaazon/warmy/pull/4 for example.)

My workaround is "have the asset manager keep track of what it needs to load, and have it get passed the Context so it can load things", which sounds like what you want to avoid doing.  The other practical method seems to be "keep the Context in an Rc and give the AssetManager a copy of it", which should work fine but requires rolling your own event loop instead of using EventHandler.  Fortunately, [this is pretty easy](https://github.com/ggez/ggez/blob/master/examples/eventloop.rs).

As far as I can tell it's a matter of picking your poison, I guess...

**Comment by itmuckel** [comment]
Yeah, I've already looked into the code of the event loop; not too complicated. Wouldn't it be a nice addition to ggez, if the Context would be reference counted by default? I mean, there are a lot of places where you might need the Context in an engine that you build on top of ggez. Is there a benefit in having the Context on the stack instead of the heap?

**Comment by icefoxen** [comment]
It's not "stack vs heap", it's "owned vs. borrowed".  ggez's API is designed so it never needs to own the context, apart for in the EventLoop.  This seemed like a conservative choice at the time.  ...might be nice to change it so the EventLoop could take a reference, I suppose, and didn't have to own the Context.  That will take a bit of research though.

**Comment by icefoxen** [comment]
Now that I think of it, not sure there's any reason the default event loop in `event::run()` can't just take an `Rc<Context>` instead of `&mut Context`, though getting mutable references out of an `Rc` only works when the reference count is 1, and most things that need the Context need `&mut`.  So it may not be too useful.

**Comment by icefoxen** [comment]
https://github.com/ggez/ggez/issues/298 is sort of a sub-issue of this.

**Comment by icefoxen** [comment]
`Rc<RefCell<Context>>` totally works.

```rust
extern crate ggez;


use ggez::{conf, Context};
use ggez::event;
use ggez::graphics::{self, DrawMode, Point2};

use std::cell::RefCell;
use std::rc::Rc;

struct MainState {
    pos_x: f32,
    context: Rc<RefCell<Context>>,
    continuing: bool,
    events: event::Events,
}

impl MainState {
    fn new(ctx: Context) -> Self {
        let events = event::Events::new(&ctx).unwrap();
        Self {
            pos_x: 1.0,
            context: Rc::new(RefCell::new(ctx)),
            continuing: true,
            events: events,
        }
    }
    
    fn update(&mut self) {
        self.pos_x += 1.0;
    }

    fn draw(&mut self) {
        if let Ok(ctx) = self.context.try_borrow_mut().as_mut() {
            graphics::clear(ctx);
            graphics::circle(
                ctx,
                DrawMode::Fill,
                Point2::new(self.pos_x, 380.0),
                100.0,
                2.0,
            ).unwrap();
            graphics::present(ctx);
        } else {
            panic!("Aieee, something else is holding a reference to the context -- draw!!")
        }
    }

    fn handle_events(&mut self) {
        if let Ok(ctx) = self.context.try_borrow_mut().as_mut() {
            // Tell the timer stuff a frame has happened.
            // Without this the FPS timer functions and such won't work.
            ctx.timer_context.tick();
            // Handle events
            for event in self.events.poll() {
                ctx.process_event(&event);
                match event {
                    event::Event::Quit { .. }
                    | event::Event::KeyDown {
                        keycode: Some(event::Keycode::Escape),
                        ..
                    } => {
                        println!("Quitting");
                        self.continuing = false;
                    }
                    x => println!("Event fired: {:?}", x),
                }
            }
        } else {
            panic!("Aieee, something else is holding a reference to the context -- events!!")
        }

    }
}

pub fn main() {
    let c = conf::Conf::new();
    let ctx = Context::load_from_conf("eventloop", "ggez", c).unwrap();

    let mut state = MainState::new(ctx);

    while state.continuing {
        // Update
        state.update();

        // Draw
        state.draw();

        // Events
        state.handle_events();
        ggez::timer::yield_now();
    }
}

```

**Comment by icefoxen** [comment]
Closing this for now, I'm not going to revamp the context passing pattern before 1.0.
