### ISSUE TITLE
Rendering video in game

### ISSUE THREAD

**Issue by superlou** [ggez/ggez#296]
I've looked through the examples on rendering images from PNG files.  Is there a recommended way to draw video into the game window?

**Comment by icefoxen** [comment]
Don't have a ready way to do this, no.  It's not something I know a whole lot about.

**Comment by superlou** [comment]
Supposedly it is [possible in gfx-rs](https://github.com/gfx-rs/gfx/issues/1485), though the more I looked into it, the less I actually understood how to go about doing it.  I think I might be able to use GStreamer or ffmpeg/libav bindings to extract frames from the video, then copy them to a surface and then copy them to a texture.  Does GGEZ expose a way to render a surface?  I believe ggez::graphics::Image represents an in-GPU image.

**Comment by icefoxen** [comment]
If by "surface" you mean a CPU-side memory buffer, ggez has no separate type for that. It just builds an Image out of whatever `&[u8]` you give it. It doesn't really have a way to update the contents of an Image with new data, though it should probably be easy to add.

My suggestion: just create a new Image for each frame with `Image::from_u8` and see how it works. If it's not good enough, figure out how to do it with gfx-rs and get into ggez's guts a little to make it possible to do, and see how well it does.

**Comment by superlou** [comment]
Sounds like a plan, thanks.

**Comment by superlou** [comment]
@AndreaCatania, no, sorry. I ended up using a different framework for other reasons. I agree with @icefoxen that the right way is probably to find a library that will get the video frames and then create images from those.

**Comment by AndreaCatania** [comment]
What's the framework that are you using?

**Comment by superlou** [comment]
I am using [info-beamer](https://info-beamer.com/). I was essentially trying to make an open source clone using Rust and [Rhai](https://github.com/jonathandturner/rhai), but I didn't get far enough in time. I still really enjoy working with info-beamer.
