### ISSUE TITLE
Explore using arbitrary_self_types & 'WithContext' pattern from futures 0.2 rfc

### ISSUE THREAD

**Issue by termhn** [ggez/ggez#298]
https://github.com/rust-lang-nursery/futures-rfcs/pull/2#issuecomment-363923477

Seems like this could help improve ergonomics a lot by not having to explicitly pass around ctx everywhere.

**Comment by icefoxen** [comment]
That's an intriguing idea!  I'm a little skeptical 'cause it feels like you just have to manage the lifetime of the `WithContext` object, which isn't necessarily any easier.  Might be a little nicer to write though?

Improving context ergonomics in general is something I am interested in.  I don't really have the mental bandwidth to really work on it actively right now, but I'm happy to ponder and discuss.  Other things I've thought of: splitting the Context apart into its components more explicitly, or just `Arc`'ing the whole damn thing.  Neither is terribly satisfying.

This honestly feels a little bit like Haskell's `IO` monad: you want to pass along some context with your function calls without needing to explicitly talk about it.

**Comment by icefoxen** [comment]
Closing this to shunt further discussion to #295 since it's basically the same issue.
