### ISSUE TITLE
Rect docs say "x" and "y" are the center - but they're actually the top-left origin.

### ISSUE THREAD

**Issue by Sushisource** [ggez/ggez#303]
This made me feel like I was taking crazy pills today. I can submit a PR with the doc change - just wanted to open this to confirm.

**Comment by icefoxen** [comment]
You're not going crazy.  :sweat_smile: 

Version 0.3, the rect x and y were at the center.  0.4 moved it to the top-left, where it is going to stay until the sun burns out so we never have to change it again.  I thought I'd updated all the docs but it appears I missed a place or two.

**Comment by icefoxen** [comment]
Fixed in `devel`, please let me know if you find anything else.
