### ISSUE TITLE
Y offset incorrect when drawing a canvas

### ISSUE THREAD

**Issue by brianwp3000** [ggez/ggez#304]
The following code should create a blank green canvas and draw it to the center of the screen, but as of version 0.4.1 it instead draws the canvas centered on the X axis but towards the bottom of the screen on the Y axis:
```
// create blank green canvas
let canvas = graphics::Canvas::new(ctx, 100, 100, conf::NumSamples::One)?;
graphics::set_canvas(ctx, Some(&canvas));
graphics::set_background_color(ctx, graphics::Color::new(0.0, 1.0, 0.0, 1.0));
graphics::clear(ctx);

// draw green canvas to center of screen
graphics::set_canvas(ctx, None);
graphics::draw_ex(
    ctx,
    &canvas,
    graphics::DrawParam {
        dest: graphics::Point2::new(window_size_x / 2.0, window_size_y / 2.0),
        offset: graphics::Point2::new(0.5, 0.5), // change this to (0.5, -0.5) and it draws to the center of the screen as expected
         ..
        Default::default()
    })?;
graphics::present(ctx);
```
If I use that same code snippet to draw an Image instead of a Canvas it works as expected. As a workaround I'm able to set the offset to (0.5, -0.5) when drawing Canvases and that makes them draw to the center of the screen.

**Comment by icefoxen** [comment]
The culprit code is probably this, in `graphics/canvas.rs`

```rust
impl Drawable for Canvas {
    fn draw_ex(&self, ctx: &mut Context, param: DrawParam) -> GameResult<()> {
        self.debug_id.assert(ctx);
        // Gotta flip the image on the Y axis here
        // to account for OpenGL's origin being at the bottom-left.
        let mut flipped_param = param;
        flipped_param.scale.y *= -1.0;
        flipped_param.dest.y += self.image.height() as f32 * param.scale.y;
        self.image.draw_ex(ctx, flipped_param)?;
        Ok(())
    }
}
```

We might have to fiddle the offset similarly as well (`1 - offset`?), just need to sit down and crunch through the math.

**Comment by icefoxen** [comment]
Bug very much confirmed, see https://github.com/ggez/ggez/blob/devel/examples/canvas_subframe.rs#L100-L109

also it's a cool demo

**Comment by PSteinhaus** [comment]
It seems that this can be closed as well, right?
