### ISSUE TITLE
C/C++ compiler required when building due to Zip dependency

### ISSUE THREAD

**Issue by brianwp3000** [ggez/ggez#306]
Right now ggez requires a C/C++ compiler to build because of its dependency on the Zip crate. The Zip crate has an optional (but on-by-default) feature to enable handling of zip files compressed with bzip2, and it's that feature that requires a C/C++ compiler to build.

I propose that the zip/bzip2 feature gets surfaced as its own feature in ggez that is enabled by default. This way, users like me who don't want to install a C/C++ compiler can still develop with ggez by specifying "default-features=false". The only thing a person sacrifices by disabling bzip2 support is the ability to work with bzip2 zip files in their games, but that's easily worked around by the developer and bzip2 isn't the usual zip file compression scheme anyway (most zip files use Deflate).

This could also help with Issue #29 ("It would be nice if everything was pure Rust").

**Comment by icefoxen** [comment]
Merged your PR, thank you!
