### ISSUE TITLE
Drawing is *horribly* slow on Windows

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#31]
Like, what on Linux or Mac runs at 130 fps instead runs at 6 fps.

Good example program: https://github.com/icefoxen/ggj2017 at least as of commit 851f83782d0e4dd05cb6633fd4a4e1ea9f2d1376

I blame SDL2.  Still!  Should get to the bottom of it one way or another.

Tested on:
* Intel core i5 laptop with NVidia 5100M GPU running Windows 10
* Intel core i5 laptop with NVidia 425M GPU running Windows 7

**Comment by icefoxen** [comment]
To do: Test on different GPU's.

**Comment by Cobrand** [comment]
I'm just passing by randomly but you should test on different render engines as well ;)
By default Windows uses DirectX (named direct3d from SDL2), but sometimes when you want features from the render engine that aren't available in DirectX, it will swap to either OpenGL or Software Rendering. OpenGL is fine, but Software rendering is definitely the slowest thing you can have. It might not be related though, I'm just leaving this here as a hint ! (I'm not subscribing to this issue so mention me if you want me to come back to this issue ;) )

**Comment by icefoxen** [comment]
Drawing has all been ported to gfx but I guess I'm leaving this open until I actually get around to benchmarking it on windows again...

**Comment by onelson** [comment]
I just updated my toys to run from master - tested on windows and things look ok to me?

Was there a specific benchmark program you were running?

**Comment by icefoxen** [comment]
It does have to be updated but that sort of should be done anyway.  Master's drawing API is pretty much done so it would be interesting to see how it stacks up.

https://github.com/gfx-rs/gfx/pull/1221 is also going to help, I expect.

**Comment by icefoxen** [comment]
Benchmarked a little bit, seemed to work about the same as on Linux.
