### ISSUE TITLE
Relicense to MIT/Apache-2.0?

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#312]
Motivation: https://github.com/cmr/relicense-assistant/blob/master/single-issue-template.txt

**Comment by termhn** [comment]
The project seems outdated/unmaintained but I'd be fine with it (don't really have an opinion). In case we want to do this and my consent would be needed:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ozkriff** [comment]
Yeah, `relicense-assistant` repo is not active anymore, but the motivation section of the linked document is still fine.

`MIT/Apache-2.0` is kinda the default licensing in rust's ecosystem - I think that it's better to stick with it if there're no serious reasons not to do that for a specific project.

**Comment by icefoxen** [comment]
I'm fine with it but from my perspective it also just feels like a lot of sturm und drang for no concrete gain.

**Comment by ozkriff** [comment]
> it also just feels like a lot of sturm und drang

Maybe.
The PR itself is easy to make but collecting consents from all 42 contributors isn't an easy task -
 https://github.com/brendanzab/cgmath/issues/297 cgmath still can't do that :(

> or no concrete gain

Personally, I take licensing stuff religiously seriously)
But yep, realistically it can only become an issue if the project becomes really "big'n'popular" - it's hard to imagine how it can harm a small-medium sized project.

So, closing the issue then?

**Comment by icefoxen** [comment]
Well, I'd happily agree to the license change if someone else is going to micromanage it.

**Comment by Ratysz** [comment]
For what it's worth, I'm fine with a license change, as meager as my contributions are. That puts us at... 4 out of 42?

Side note & idle musings: there really ought to be some percentage threshold and/or a statute of limitations for this kind of thing. I predict, if we do try to follow through with this, we will be held back by a couple of PRs made by parties who have lost any and all interest long since.

**Comment by ozkriff** [comment]
When I was creating this issue I haven't thought that there're so many contributors already. Getting approval from 47 contributors actually seems not that much realistic :-(

I'll close the issue tomorrow if nobody minds.

**Comment by icefoxen** [comment]
Actually now that I think of it, probably most of those contributions are quite small, typo fixes or small big fixes. Those would be easy to deal with just by replacing/rewriting them where possible.

**Comment by icefoxen** [comment]
Closing this until someone who is interested enough to micro it for me comes along. :-p
