### ISSUE TITLE
Why is docs/Projects.md a separate doc and not a part of README?

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#315]
It contains an important information for many potential users of ggez, but it's not easy to discover it.

**Comment by icefoxen** [comment]
The readme got cluttered and I don't want to have to decide which projects are worth putting on the front page and which aren't.

**Comment by ozkriff** [comment]
Maybe then add some noticeable link `List of projects that are using ggez` or somethink alike to the readme?

**Comment by icefoxen** [comment]
That's a good idea!
