### ISSUE TITLE
SDL_mixer music is broken

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#32]
It plays for half a second, then sits around a while doing something ugly to out-of-bounds memory, then eventually crashes.  Usually within 10-20 seconds, sometimes up to 150 on my laptop.

Ugh.  Ugh ugh ugh.  Kill it with fire and replace it with something else.

**Comment by michaelfairley** [comment]
This is somewhat of a guess, but I think `rwops` is getting dropped (and thus closed) [here](https://github.com/ggez/ggez/blob/f72943811ff7124e966a76abf3882fdedc20d76f/src/audio.rs#L137), but `music` is going to continue to try reading from it.

**Comment by icefoxen** [comment]
Herp derp, quite possibly.  I thought that Music copied its values out of the RWops but maybe it doesn't!  It would probably be about the same type of bug as https://github.com/andelf/rust-sdl2_ttf/issues/43

**Comment by michaelfairley** [comment]
https://github.com/AngryLawyer/rust-sdl2/pull/592

**Comment by icefoxen** [comment]
Oof.  Thank you for passing the bug report on, let alone the pull request!  I intend to go and pass all the SDL2 bugs upstream but I haven't had time yet.

**Comment by icefoxen** [comment]
Closing this since I'm in the process of excising SDL_mixer anyway.
