### ISSUE TITLE
Add termhn/ggez_snake to examples?

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#321]
https://github.com/termhn/ggez_snake is simple, has no additional dependencies and doesn't use any assets - why not add it as one more example to the repo?

Examples that live outside of the core repo has a tendency to decay gradually.

**Comment by icefoxen** [comment]
Examples that live inside the core repo need to be maintained though.  ;-)

This is a good candidate though, yes.

**Comment by icefoxen** [comment]
Merged, need to update docs.

**Comment by icefoxen** [comment]
If you don't, I will, so no big deal.

**Comment by ozkriff** [comment]
Closed by https://github.com/ggez/ggez/pull/329
