### ISSUE TITLE
timer: access to residual_update_dt for fixed timestep interpolation

### ISSUE THREAD

**Issue by Steef435** [ggez/ggez#324]
Hi,

ggez currently provides direct support for a fixed timestep with timer::check_update_time, which is great. But I can't find a way to access the "delta time" or accumulated unhandled time which is generally used to implement interpolation (see The Final Touch in https://gafferongames.com/post/fix_your_timestep/).

If I read the code correctly this would correspond with residual_update_dt of the private TimerContext object. Could a way to access this be created? I'm new to rust but I wouldn't mind giving it a go if the feature is welcome.

**Comment by icefoxen** [comment]
That's a good catch and an easy improvement.  If you want to make a PR I'd gladly accept it.

**Comment by Steef435** [comment]
Nice! I wasn't sure what to do with the name but I've submitted a PR: #333

**Comment by icefoxen** [comment]
Yeah the name is tricky.  `get_remaining_update_time()` is an option...  I'll fiddle with it.

**Comment by icefoxen** [comment]
Merged and fiddled, I settled on `get_remaining_update_time()`.
