### ISSUE TITLE
Add a logo to README.md

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#327]
The most important part of the project!

I made dis
![](https://i.imgur.com/8KUFa4U.png)

**Comment by ozkriff** [comment]
Oh, you are right.

Btw, what's this one? 
![image](https://user-images.githubusercontent.com/662976/37926365-d5c4cbc6-313f-11e8-90a5-ffa54e807c7a.png)
..[salt?](https://i.imgur.com/8vs5INQ.png) O.o

**Comment by svenstaro** [comment]
Yeah, it's salt because [ggez](https://www.urbandictionary.com/define.php?term=ggez) itself is a fairly mean name and with that comes people [being salty](https://www.urbandictionary.com/define.php?term=being%20salty).

**Comment by icefoxen** [comment]
I honestly kiiiiind of don't like the name for that reason... but too late to change it now!  :man_shrugging:

**Comment by ozkriff** [comment]
> We need a version that works on a light background.

Hmm, and simply inverting colors doesn't make much sense as salt can't be black

**Comment by termhn** [comment]
Toss a tasteful rounded rectangle behind it with that sweet maroon color.

**Comment by ozkriff** [comment]
I love the name. When I was naming my engine [Häte2d](https://docs.rs/hate) I didn't mean it really hates you or anyone)


@termhn kinda like this?

![image](https://user-images.githubusercontent.com/662976/38103671-b20a8962-338f-11e8-9a73-94083e5d1370.png)

**Comment by svenstaro** [comment]
That looks super nice!

**Comment by Ratysz** [comment]
I can "commission" my artsy GF to draw a new/alternate logo (vector, of course) - it'll take her just a few minutes to whip [something](https://i.imgur.com/JC07awL.jpg) up.

**Comment by termhn** [comment]
@ozkriff yes, although I was thinking just around the salt shaker itself and then having the ggez text be the same color as the background (then you can just have the salt shaker standalone as well)

**Comment by ozkriff** [comment]
![image](https://user-images.githubusercontent.com/662976/38104256-4faa77c6-3391-11e8-81eb-58812bc4ba8b.png)

Hm?
Like this? Maybe, but the composition is broken as different colors give different weight to image's parts. Square needs to be rescaled or moved around - it's too hard for me, I'm not into logo design)

I would prefer the previous "full" variant for the readme and a separate svg with only the salt shaker for icons.

(Inkscape works fine on linux btw :-p )

**Comment by termhn** [comment]
Or, fully filled: 

![ggez-maroon-full-exp](https://user-images.githubusercontent.com/887711/38105795-d9a12344-3341-11e8-90b5-bcf99ef30313.png)
(for some reason it's getting clipped by github...?

**Comment by ozkriff** [comment]
I think that a PR with a filled version in the readme should be made.
Btw, where should the svg be placed? `docs`? `resources`?

**Comment by icefoxen** [comment]
I think SVG's for both the text-and-log and logo-only versions should go in `docs`.  :heart: 

But rectangle vs. circle... I don't know!  I kind of lean towards rectangle, but...

**Comment by ozkriff** [comment]
@termhn Will you do a PR with these svgs? :)

**Comment by termhn** [comment]
@ozkriff yes I will :D Haven't been on my machine that has them the past couple days :P

**Comment by icefoxen** [comment]
Resolved in #348 .  Glorious!  We can just leave it in the devel branch for now, unless anyone objects.  It gives me an excuse to work towards another patchlevel release.
