### ISSUE TITLE
CHANGELOG: Remove empty sections and add links to PRs

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#336]
What's the point of having these empty sections like

```md
 ## Deprecated
 
 ## Removed
```

?

Additionally, I propose to add PR or issue links whenever it makes sense for people who want to read some more details quickly:

> ## Added
>
> * Added a `bzip2` feature to allow opening zip files compressed with bzip2 algorithm #307
> * Added `timer::get_remaining_update_time()` to let you easily do sub-frame timing for interpolation and such. #333

**Comment by Ratysz** [comment]
I'd assume it's the effects of release procedure streamlining (aka laziness). Don't think it's that grating or malignant though, if anything it reassures the user that we didn't low-key take something out.

Changelog needs to be pasteable on say Reddit, those should probably be hard links.

**Comment by icefoxen** [comment]
Mainly so I don't forget those sections exist, and can copy-paste previous changelog entries and delete the contents and not lose sections. I'm waffling between leaving them empty and explicitly putting "* Nothing" in them.

Issue links should certainly be hard links and should always be present, but its not easy. Not every change has an associated issue, as well.

**Comment by icefoxen** [comment]
Updated the release notes to have a reminder to put a full issue/commit link in the changelog.
