### ISSUE TITLE
Test `vfs::tests::test_read()` fails on Windows 10

### ISSUE THREAD

**Issue by Ratysz** [ggez/ggez#337]
Haven't tested it on any other system; happens on master and devel alike.

```
---- vfs::tests::test_read stdout ----
        thread 'vfs::tests::test_read' panicked at 'assertion failed: `(left == right)`
  left: `"[package]\r\n"`,
 right: `"[package]\n"`', src\vfs.rs:776:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at src\libstd\sys\windows\backtrace/mod.rs:65
   1: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:68
             at src\libstd\sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src\libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at src\libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:522
   7: ggez::vfs::tests::test_read
             at src/vfs.rs:776
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at src\libtest/lib.rs:1449
             at C:\projects\rust\src\libcore\ops/function.rs:223
             at C:\projects\rust\src\liballoc/boxed.rs:815
   9: _rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:101
```

**Comment by icefoxen** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaa this has happened before and I don't recall why. Need to check the previous issues.

**Comment by termhn** [comment]
Probably because of the way windows files handle carriage returns/line endings... though I have no idea how that applies here specifically or how to fix it :P

**Comment by dannyfritz** [comment]
I believe there is a gitattribute you can set to force line endings.

**Comment by itmuckel** [comment]
@Ratysz Can you provide a minimal code example where this error occurs? 😏

**Comment by Ratysz** [comment]
@itmuckel It's a test. You open local `ggez` repo in cmd or PowerShell (we're on Win10, right?), and do `cargo test`.

If you mean an actual code example where the implications of this test failing will be felt, then no, sorry - haven't tinkered with `filesystem` enough. For what it's worth, what I did do with it (writing logs to a file) seemingly doesn't run into the underlying issue at all.

**Comment by icefoxen** [comment]
Yep, replicated this.  Not a ggez error, it's the windows line ending characters being not what the unit test expects, 'cause git does line ending conversions on different platforms by default.  

Fixed the test to ignore line endings.
