### ISSUE TITLE
SDL resource directory locations are unreliable.  >:-[

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#34]
It seems to vary between *next* to the executable and *above* the executable between versions of rust-sdl2???  It's awful, either way.

**Comment by onelson** [comment]
I don't think it's due to sdl versions. I can run the examples just fine as written, but when I build a new app with ggez as a dependency, I have to drop the resources in `target/` instead of `target/debug/` or `target/release`.

**Comment by icefoxen** [comment]
Maybe it's some difference between building ggez example apps versus including it as a crate?  That's weeeeeird.

Certainly makes distribution awkward, though.

**Comment by icefoxen** [comment]
Made redundant by progress on issue #29.  Still, issue #39 is necessary to actually fix it.
