### ISSUE TITLE
I can't compile project with GGEZ

### ISSUE THREAD

**Issue by Terisback** [ggez/ggez#340]
`note: Non-UTF-8 output: LINK : fatal error LNK1181: \xed\xe5 \xf3\xe4\xe0\xe5\xf2\xf1\xff \xee\xf2\xea\xf0\xfb\xf2\xfc \xe2\xf5\xee\xe4\xed\xee\xe9 \xf4\xe0\xe9\xeb \"SDL2.lib\"\r\n`

Sorry.

Log:
https://pastebin.com/BgY4vc19

**Comment by TerisbackDev** [comment]
Pls, help

**Comment by TerisbackDev** [comment]
Ok, I found problem. I doesn't installed SDL2
![default](https://user-images.githubusercontent.com/26527529/38111501-8934c808-33b8-11e8-8398-f3db6b31185b.png)
