### ISSUE TITLE
`graphics::get_size` documentation is incorrect

### ISSUE THREAD

**Issue by eugene-bulkin** [ggez/ggez#345]
The docs for `get_size` make the following claim:

>Returns the size of the window in pixels as (height, width).

However, `sdl2::video::Window::size` returns `(width, height)`, as you can see [here](https://github.com/Rust-SDL2/rust-sdl2/blob/master/src/sdl2/video.rs#L1194-L1199).

Was this an API change that wasn't updated or was this just a small mixup?

**Comment by icefoxen** [comment]
That's just a typo, then.  Easy to fix, thank you!

**Comment by icefoxen** [comment]
Fixed, docs will be published in the next version.
