### ISSUE TITLE
Automatic sprite batching

### ISSUE THREAD

**Issue by termhn** [ggez/ggez#346]
So, when we originally implemented batching, this was out of scope, but... it recently landed as a feature in Lua and I'm interested in trying to implement it in ggez now that I have more experience with graphics programming in general. Thought I'd open an issue as far as comments on whether people think this would be a good thing to have and if so thoughts on implementation details if anyone has them.

**Comment by icefoxen** [comment]
There's upsides and downsides.

Upsides: Drawing stuff becomes faster without anyone doing anything special...

Downsides: ...only sometimes, when they do drawing in a way that the sprite batcher can recognize.

I'm generally in favor but a little skeptical of sneaky under-the-hood optimizations.  OpenGL is a good example of the sort of mess that can lead to.

That said, LOVE doing this is generally a decent sign that it's doable nicely.  We should take a look at the LOVE 11.0 source code and see if there's anything particularly hairy in it, just in case.

**Comment by dannyfritz** [comment]
what about doing it as a macro block that batches the calls inside of it?

**Comment by termhn** [comment]
@icefoxen True, however I think this is a pretty standard optimization to do. In addition to LOVE, [three](https://github.com/three-rs/three) fairly recently implemented automatic instancing which I was thinking I might use as some amount of reference.

@dannyfritz Hmm, not entirely sure how that would work or if it could really work.

**Comment by icefoxen** [comment]
@dannyfritz Doesn't seem like that would gain much over just using a `SpriteBatch` anyway, apart from maybe a little syntactic sugar...

@termhn Yeah, that's true.  It certainly won't hurt, and making the rules of what can and can't be instanced clear in the docs is easy enough.  Let's try it and see how it works.

**Comment by dannyfritz** [comment]
Would that also flush the draw calls for images when doing other types of draws?

**Comment by onelson** [comment]
Would this devalue callers using SpriteBatch directly?
(from someone with a budding sprite anim library that won't go anywhere)

**Comment by Ratysz** [comment]
If this happens, we can give `Text` similar treatment, easily: have all draw calls on it only queue, and draw the entire queue after `EventHandler::draw()`. `gfx_glyph` handles all the caching and batching internally.

Obviously, we'll need to expose those centralized batch draw methods, for those rolling their own event loops.

**Comment by icefoxen** [comment]
@dannyfritz Probably, to make sure draw ordering is correct.

@onelson Maybe?  I think SpriteBatch would still have some utility for clarity and maybe a bit of extra efficiency since you don't have the overhead of checking whether you can batch or not.  It's something we'll have to explore though.

@Ratysz Again, I'm suspicious of ordering problems, and I think that this is more or less what `gfx_glyph` already does....

**Comment by icefoxen** [comment]
Based on the various complications of #561 I really don't want to do this.  There's too much sneaky global state involved.
