### ISSUE TITLE
SDL controller input doesn't work?

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#35]
At least on the Linux and Mac laptops I tried on, using an XBox 360 controller.  Investigate more.

**Comment by icefoxen** [comment]
Works on Linux using a Logitech F310 and F710 gamepad.  Can't find my Steelseries.

I should get a 360 controller for testing.

**Comment by obsoke** [comment]
I can verify that an Xbox One (wired) controller works with ggez (0.3.1) on Linux 4.11.6-1 using the default `xpad` kernel module. I have a few other controllers (incl. 360) that I'll test later.

**Comment by levicole** [comment]
I tested with a Steelseries Stratus and it works fine on a Mac.

**Comment by icefoxen** [comment]
Well nobody else has complained about this in a year so I'm closing it.  :-P
