### ISSUE TITLE
Allow getting timing data from audio playback

### ISSUE THREAD

**Issue by cessen** [ggez/ggez#353]
The audio APIs in ggez currently don't allow any way to get timing data of audio that is playing.  This is important for e.g. rhythm games, which need to sync events with the audio that is playing.

Rodio has an API that can be used for this purpose: the [PeriodicAccess](https://docs.rs/rodio/0.6.0/rodio/source/struct.PeriodicAccess.html) source.  It allows hooking in a closure to be executed at regular intervals during the audio playback.  Combined with an atomic integer, this can allow tracking how much of the audio has been played so far.

I'm thinking that it probably makes sense to just expose a similar API, to allow people to do whatever they like at regular intervals with the audio.  It solves this issue, but may also allow for some other interesting uses (though I'm not quite sure what they would be).

**Comment by cessen** [comment]
I'll take a crack at implementing this when I have the time.  But if anyone gets to it before me, I certainly won't be offended. :-)

**Comment by icefoxen** [comment]
@cessen Go right ahead!  Audio really needs the help right now, alas.

**Comment by nobbele** [comment]
This has been implemented, right?
