### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by osa1** [ggez/ggez#355]
I checked the FAQ but couldn't find anything relevant. Most (maybe all?) examples fail with this error on my system:

```
$ cargo run --example astroblasto
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/astroblasto`
Adding path "/home/omer/opt/ggez/resources"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(WindowBuildError(SdlError("Couldn\'t find matching GLX visual")))', libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This is Ubuntu 16.04 with Rust nightly.

**Comment by ozkriff** [comment]
hmmm, maybe something like https://stackoverflow.com/questions/41338549/sdl2-cant-create-window-since-it-couldnt-find-matching-glx-visual ?

**Comment by icefoxen** [comment]
Looks like Ubuntu 16.0 uses mesa 17.2, so it is unfortunately susceptible to this bug: https://launchpad.net/ubuntu/xenial/+source/mesa

I am suspicious of the different error message though, I gotta say.  @osa1 , can you please take a look at the #194 thread and various diagnostics and workarounds and see if this is indeed a duplicate?

**Comment by icefoxen** [comment]
Assuming it's the Mesa bug, now fixed in devel
