### ISSUE TITLE
Tiled map loading support

### ISSUE THREAD

**Issue by difarem** [ggez/ggez#358]
The current release of [rs-tiled](https://github.com/mattyhall/rs-tiled) doesn't seem to interface well with ggez's filesystem, so a batteries-included version could be an useful addition.

**Comment by icefoxen** [comment]
I've done it before and it worked fine, you just use <https://docs.rs/ggez/0.4.2/ggez/filesystem/struct.Filesystem.html#method.open> to load your data and then feed it into <https://docs.rs/tiled/0.7.4/tiled/fn.parse.html>.  What doesn't interface?

**Comment by icefoxen** [comment]
Ok now that I look at my old code it does take a bit of work to actually wire together all the `tiled` structures, load the right sprites, etc.  Sounds like a good job for an external crate.

**Comment by difarem** [comment]
https://github.com/difarem/rs-tiled/tree/ggez

Here's some preliminary work, with all the tests adapted to the new map loading workflow. It's still missing actual image loading, but it will happily load external tilesets from the `Filesystem` abstraction.

**Comment by difarem** [comment]
https://github.com/difarem/rs-tiled/tree/ggez

Added an *extremely* hacky (but working) demo.

**Comment by icefoxen** [comment]
Frankly a really good crate for this would be awesome.

**Comment by icefoxen** [comment]
@difarem Closing this in favor of an external crate; if you get your `ggez` version of `rs-tiled` merged into upstream, or fork it into its own thing, please submit a PR to add it to `docs/Projects.md`!
