### ISSUE TITLE
The GameState model is a bit squirrelly.

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#36]
The original setup uses a trait to defines callbacks matching Love2D's main callbacks: load, update and draw.  Then you just create a new `Game` object that is parametric on the type you define that trait for, which creates the object using the load callback and then runs it all.  The goal was to make it match up with Love2D's model as closely as possible.

This... works, but is really quite painful to do anything fancy with.  The problem is really the load callback.  In Love2D everything is dynamic, so you can piece together whatever you need in that callback and it works just fine.  In Rust everything is static, and so it is much harder to, say, build a scene graph or manage transitions between scenes in this.  You can do it, and it works, but it needs adding a lot of machinery  and management to even do something as simple as a title screen, with layers of indirection for input events and so on.  Magic Happens with regards to creating the ggez `Context` and bundling it together with your `GameState` type, so it basically becomes impossible to disentangle any part of the initialization apart from the whole.

I experimented with splitting things apart a little, so that you just have an `EventHandler` trait that handles update, draw, and event callbacks, and then separating `load()` out into its own thing.  It means an extra three lines of setup code when you create the game objects, but the process becomes much less twisty: you just create a `Conf`, create a `Context`, create whatever your `EventHandler` type is with all your game data, then pass them all to a `Game` to run your main loop.

Decoupling the `Context` from the `Game` creation also has some extra benefits, since a) you can write your own mainloop type stuff if you really want to, which appeals to some people, and b) it makes it trivial (with some minor API changes so the `Game` returns the `Context` when it is done) to create one `Context` and thread it through several `Game` objects to do simple scene transitions.  Or, presumably, do the same for more sophisticated scene management.

**Comment by icefoxen** [comment]
Experimental implementation of this is in https://github.com/ggez/ggez/commit/8b607cdcf6992f9fa3f88d2d08e45d047fa7dfef and it seems to work pretty well in practice.  Also see https://github.com/ggez/ggez-goodies/blob/6a54d1117660d5bdefa3cdf46e84f3740b999266/src/scene.rs for an example of how tricky it gets to do anything fancy with the old system.

**Comment by onelson** [comment]
> this is just a case of impedance mismatch between Lua and Rust and we should probably go with the solution that makes life easy in Rust.

I think the beauty of Love2D is "idiomatic simplicity." You shouldn't strive to translate word for word, but instead retain the meaning though localized idioms ;)

**Comment by icefoxen** [comment]
Resolved in commit 434984fff95491da035cdf0f60497d6e13d2d031 .  I started cleaning up the mainloop method `run()` to more nicely allow you to pass a Context in and out of it, which ended up basically refactoring the `Game` out of existence.  Since it did nothing, I took it out, and the `GameState` trait vanished too.  Well then!

This is going to need some doc cleanup.
