### ISSUE TITLE
Canvas vs. shader API's are inconsistent

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#368]
The shader functions returns a handle that pops to the old shader when it goes out of scope.  Canvas's have to be manually reset via `set_canvas(ctx, None);`.  The inconsistency irks me.  Which is better?

 * Shaders are strictly scope-bound because of this (I think?) unless you pass the handle around.  RAII style.
 * Canvas's are not, but don't have a stack structure either.  More C style.

Rust is generally more RAII-style but returning handles for a resource that are only used for freeing them somehow doesn't feel terribly Rust-y.  It happens, but shaders are sorta weird there 'cause you then don't DO anything with the handle, unlike say Mutex or such.

**Comment by icefoxen** [comment]
notttttt going to fix this right now, there's too much stuff to do already.

**Comment by icefoxen** [comment]
The RAII structure is better, because it restores the state automatically on errors or early returns... such as calling a function and using `?` after it.

**Comment by icefoxen** [comment]
Should be solved by the `ggraphics` branch.

**Comment by PSteinhaus** [comment]
`Shader` and `Canvas` APIs have been changed massively through the WGPU-PR.
Both choosing a canvas and choosing a shader are now strictly explicit:
- You either call `draw` directly on a canvas or hand over a reference to it when calling `Drawable::draw`.
- And you set the shader used for the following draw calls via `Canvas::set_shader` and probably `Canvas::set_default_shader`.
