### ISSUE TITLE
Matrix operation docs need to be better

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#369]
...ideally without having to write a full tutorial on matrix math ourselves.  Can we have an example that demonstrates fiddling with the stack or such, and outsource the actual math explanations to perhaps the nalgebra tutorial?

**Comment by buckle2000** [comment]
Here
http://ncase.me/matrix/

**Comment by icefoxen** [comment]
#367 is probably going to change this anyway so I'm going to procrastinate until that's done.

**Comment by icefoxen** [comment]
Moar procrastination :3
