### ISSUE TITLE
Add `points: u32` parameter to `graphics::Font::default_font` func

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#375]
Or create another function like `graphics::Font::default_font_with_points(points: u32) -> GameResult<Self>`.

**Comment by Ratysz** [comment]
Ideally, we'd allow the user app to override default font (via config or builder) entirely during context creation. This is very relevant to #362, and I have a few ideas how to handle it better - but the changes have to be sanity-checked and merged first.

**Comment by icefoxen** [comment]
I like Ratysz's idea.  But now that I think of it, `default_font_with_points()` or such would be pretty easy to make...  But then we'd need `default_fonts_with_px()` as well.  Might be nice to separate "a font with size information" from "raw font data" somehow...

Really the only reason I included a default font at all is to make life easy for writing debug text.

**Comment by icefoxen** [comment]
This is now obsolete since gfx_glyph takes size information when text is drawn, not when the font is loaded.
