### ISSUE TITLE
Are badges in ggez's top level doc comment really required?

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#379]
https://github.com/ggez/ggez/blob/f3592d613/src/lib.rs#L2-L7

They look weird when generating offline documentation:

![no images](https://i.imgur.com/OEWkGsW.png)

**Comment by icefoxen** [comment]
Good point.  They exist in the `README.md` and the module doc comments are just a copy of that, so the badges get carried along with that.  Might be worth removing them though.

I wonder if we can auto-generate this somehow, so we don't have to keep the docs in sync in two places.

**Comment by icefoxen** [comment]
Removed the badges in 693d3d6, but some sort of auto generation would really be ideal.

**Comment by icefoxen** [comment]
As of commit c090ee1, intro library docs are more concrete and minimal, while the readme is a bit more pick-up-and-go.  It could use a bit more refining but I'm calling this part done.
