### ISSUE TITLE
Give GameResult a default argument value

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#384]
I find myself writing a lot of functions that return just `-> GameResult<()> {`. Even ggez itself uses them more the 50% of the time atm:

```text
$ git grep 'GameResult<' | wc -l
198
$ git grep 'GameResult<()>' | wc -l
106
```

Personally, I think that this `<()>` looks a little awkward.
What do you think about giving a default value for `T` argument?

Change
`type GameResult<T> = Result<T, GameError>;`
to
`type GameResult<T = ()> = Result<T, GameError>;`
so we can just write `-> GameResult {` in such cases?

**Comment by icefoxen** [comment]
I didn't realize this was possible!  Sounds good to me though.  Is this a) an API breaking change, or b) require a rustc version change?

**Comment by ozkriff** [comment]
> Is this a) an API breaking change, or b) require a rustc version change?

a) Hmm

https://stackoverflow.com/questions/41185023/what-exactly-is-considered-a-breaking-change-to-a-library-crate

> Adding defaulted type parameters to a type or trait [not breaking].

Looks like it's not a breaking change.

b) I'm not sure at which exact version it was stabilized, but I've used this feature at least with 1.18 rustc (Jul 12, 2017).
