### ISSUE TITLE
Upgrade examples a little

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#385]
We can reorganize examples a bit to make life a little easier.  This is an umbrella issue tracking several others.

 * #369 
 * #382 
 *  ...

**Comment by icefoxen** [comment]
Part of it should be making it more clear which example to start with.  Number them?  Sort them by difficulty/complexity?

**Comment by neganp** [comment]
I think there are at least two different things that folks are trying to learn from the examples:

- How do I get started from scratch? What are the big-picture parts of a GGEZ program? (making a `Context`, implementing `event::EventHandler`, etc.).
- How do I do this specific thing? (e.g. statically inline images or sounds with `include_bytes`, use a vertex or fragment shader, implement pausing, take input from a gamepad, how do I implement saving and loading, etc.)

So I think the examples should be divided into a small set of "overview" examples and a longer list of "recipe" examples. The expected path for a learner would be to skim the overview, and then consult the recipes for the features they need.

**Comment by neganp** [comment]
Looks good! If there are specific examples that would help flesh out the list, I'd be happy to try to contribute some. I could also open issues for some different kinds of examples if that would be helpful; with a little guidance, that seems like an approachable sort of thing to contribute.

**Comment by icefoxen** [comment]
Basically done in dd9c36be922bbb295a8240a782150d090c15dde4 , or as done as it'll really get.
