### ISSUE TITLE
Improve line caps and joins

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#396]
Basically, remove the stateful bits and make you provide optional line styles in the drawing calls.

**Comment by bzm3r** [comment]
Could you explain what you mean by "stateful bits"?

**Comment by termhn** [comment]
Stateful would mean setting a global flag (piece of state) for the renderer, and instead when you draw you'd provide that information per call (say in a DrawParam or something like that)

**Comment by icefoxen** [comment]
Fixed by #396
