### ISSUE TITLE
OS X 1/4 window size viewport after toggling fullscreen

### ISSUE THREAD

**Issue by vbo** [ggez/ggez#409]
It seems glViewport is not being set correctly on OS X in some cases. This causes graphics to render only 1/4 of the window size, see screenshot below. I can repro this by running `examples/graphics_settings.rs`, switching to fullscreen and then back to windowed.

![image](https://user-images.githubusercontent.com/255308/41636601-50af5e26-7404-11e8-839f-7492f406cd07.png)

I am running OS X 10.11.6 on a retina macbook.

**Comment by icefoxen** [comment]
Now that's new, I have to admit.  One theory is that hidpi is pretending the screen is 1/4th the size of it is and the resize code is using that value instead of the true value.

What happens when you set `allow_highdpi` to `false` in your `Conf`'s `WindowSetup` field?

**Comment by vbo** [comment]
Just checked and setting `allow_highdpi` to `false` hides the bug successfully.

**Comment by vbo** [comment]
Some interesting posts I found on the web:
 http://forums.libsdl.org/viewtopic.php?p=41273
 https://stackoverflow.com/questions/44939492/sdl-setwindowsize-gives-a-new-window-that-cant-be-written-to


What they say is basically after SDL resizes window some things get invalidated and need to be reacquired.

With this in mind I tried just resizing window in `examples/graphics_settings.rs` and indeed hit the same issue without going fullscreen - just by changing window size back and forth.

Looks like we need to call something after resize to ensure high DPI is handled.

**Comment by icefoxen** [comment]
Very interesting, thank you!  This also has to be done on non-hidpi screens but is handled automatically [here](https://github.com/ggez/ggez/blob/master/src/graphics/context.rs#L443).  Apparently there's somewhere ggez is getting confused by the difference in resolution between what hidpi reports and what the screen really has, so it is using the wrong size there.

**Comment by swamulism** [comment]
I had the same issue with piston a while back. So it might be something with the graphics backend

**Comment by vbo** [comment]
Just tested on high-dpi Windows machine (Surface Pro) and there is no repro. Probably SDL works a bit differently on Mac and requires more state resetting after resize.

**Comment by icefoxen** [comment]
Will probably be fixed when [this](https://github.com/ggez/ggez/pull/623) or something like it is merged.  But I'm dropping support for Mac, so.  :cry:
