### ISSUE TITLE
Crash in Canvas with multi-sampling

### ISSUE THREAD

**Issue by mhlakhani** [ggez/ggez#411]
I'm on a Mac (High Sierra) with Intel HD graphics.

if I have this sample program:
```rust
extern crate ggez;

struct MainState {}
impl ggez::event::EventHandler for MainState {
    fn update(&mut self, _ctx: &mut ggez::Context) -> ggez::GameResult<()> { Ok(()) }
    fn draw(&mut self, ctx: &mut ggez::Context) -> ggez::GameResult<()> {
    	let _canvas = ggez::graphics::Canvas::new(ctx, 200, 200, ggez::conf::NumSamples::Two)?;
        ggez::graphics::clear(ctx);
        Ok(())
    }
}

pub fn main() {
    let c = ggez::conf::Conf::new();
    let ctx = &mut ggez::Context::load_from_conf("helloworld", "ggez", c).unwrap();
    let state = &mut MainState {};
    if let Err(e) = ggez::event::run(ctx, state) {
        println!("Error encountered: {}", e);
    } else {
        println!("Game exited cleanly.");
    }
}
```

It will crash with the following:

```
thread 'main' panicked at 'gl function was not loaded', /Users/mhl/projects/tmp/target/debug/build/gfx_gl-65d43bd88bdd17f0/out/gl_bindings.rs:1506:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:365
   6: gfx_gl::missing_fn_panic
             at ./target/debug/build/gfx_gl-65d43bd88bdd17f0/out/gl_bindings.rs:1506
   7: gfx_gl::Gl::TexStorage2DMultisample
             at ./target/debug/build/gfx_gl-65d43bd88bdd17f0/out/gl_bindings.rs:4317
   8: gfx_device_gl::tex::make_with_storage_impl
             at /Users/mhl/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/tex.rs:482
   9: gfx_device_gl::tex::make_with_storage
             at /Users/mhl/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/tex.rs:549
  10: <gfx_device_gl::factory::Factory as gfx_core::factory::Factory<gfx_device_gl::Resources>>::create_pipeline_state_raw::{{closure}}
             at /Users/mhl/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/factory.rs:421
  11: gfx_glyph::create_texture
             at /Users/mhl/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/graphics/canvas.rs:66
  12: <tmp::MainState as ggez::event::EventHandler>::draw
             at src/main.rs:7
  13: ggez::event::run
             at /Users/mhl/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/event.rs:282
  14: tmp::main
             at src/main.rs:17
  15: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  17: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  18: <std::io::Write::write_fmt::Adaptor<'a, T> as core::fmt::Write>::write_str
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  20: tmp::main
```

It seems to crash with any value for `ggez::conf::NumSamples` that is greater than `One`.

Happy to have this merged into https://github.com/ggez/ggez/issues/253, this seemed different as it was a crash.

**Comment by icefoxen** [comment]
Thank you!  I think keeping this separate from #253 is best since it's related but not the same.  Do you know what graphics chipset your Mac has, and what version of OpenGL it supports?  It looks like it is panicking attempting to call [`glTexStorage2DMultisample`](https://www.khronos.org/opengl/wiki/GLAPI/glTexStorage2DMultisample), which requires OpenGL >=4.3.  Unfortunately `gfx-rs` doesn't currently do version or compatibility checking very well; hopefully that will get better in the next release.

Of course, it's possible that your OpenGL driver has a bug, or `gfx-rs` has a bug, or `ggez` is giving wrong parameters, so more information would help.

**Comment by mhlakhani** [comment]
thanks @icefoxen! I wasn't sure what info to include.

My mac's system info says "OpenGL 16.5.10.0.0" -- I don't know what exact version that maps to. The card is "Intel HD Graphics 630 1536 MB"

**Comment by icefoxen** [comment]
Thank you!  We'll check this out as much as we can.

**Comment by kvark** [comment]
This is an issue on our side, filed as https://github.com/gfx-rs/gfx/issues/2181
Note that you'll get a proper error instead of a panic, but it will still fail.

**Comment by icefoxen** [comment]
@kvark Awesome, thank you.  :heart: 

@mhlakhani Could you please run `glxinfo` from a terminal and post the full output?  You might have to install X11 to have the `glxinfo` program.

**Comment by icefoxen** [comment]
Awesome.  Unfortunately, with OpenGL 2.1(???) and no `ARB_texture_storage_multisample` extension it looks like your GPU just doesn't handle multisampling in render targets.  :-/

...wait, why is your driver string "AMD Radeon Pro 555 OpenGL Engine" ?  That's weird...

**Comment by kvark** [comment]
@icefoxen not exactly. One can still use renderbuffer targets with multisampling on that machine, thanks to [GL_EXT_framebuffer_multisample](https://www.khronos.org/opengl/wiki/GL_EXT_framebuffer_multisample). gfx-rs decides to use a renderbuffer instead of a texture storage if the specified usage [allows that](https://github.com/gfx-rs/gfx/blob/4bf20b960c2ca1c204fcbca2c55231f6f6458791/src/backend/gl/src/factory.rs#L419), i.e. if there is any data or it's required to be accessible from shaders.

**Comment by nobbele** [comment]
Just tested, seems fixed
