### ISSUE TITLE
Ditch `conf::MonitorId`?  Or expand it?

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#419]
We don't really have a way to *query* monitor info right now, so can we just make fullscreen modes always use the "current" monitor?  Or just add a way to query monitor info?

**Comment by Ratysz** [comment]
While there is [a way](https://docs.rs/winit/0.16.1/winit/struct.Window.html#method.get_available_monitors) in `winit` 0.16, I'm in favor of ditching it. It's not very valuable, and doesn't serialize well.
