### ISSUE TITLE
Text::{height,width} and Font::{get_height,get_width} are inconsistent

### ISSUE THREAD

**Issue by dlight** [ggez/ggez#424]
`graphics::Text` methods return `u32`, and `graphics::Font` methods return `usize`; but `u32` ought to be enough for any pixel measurement (even `u16` should be enough). This can lead sometimes to code littered with casts for no reason.

Also, they should probably be named consistently. `Font::height` looks better than `Font::get_height`.

**Comment by dlight** [comment]
Oh, cool :)

If the "fix" will come in 0.5 and the existing API won't be fixed, I think I should close this bug then, and track this in #425.

And perhaps you should tag as wontfix?

**Comment by icefoxen** [comment]
Nah, it should stay open so we make *sure* it stays fixed in 0.5.

**Comment by icefoxen** [comment]
This should be fixed in develop now. Feel free to verify!
