### ISSUE TITLE
Make sure getters/setters are named consistently.

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#425]
Just go through everything and check.  Lots of API changes have happened recently

Though there's some friction between Love2D's `get_foo()` and the more Rust-y `foo()`, which tends to be a bit context-dependent whether it's a getter or setter (builders seem different than the usual).

**Comment by Ratysz** [comment]
For what it's worth, I'm partial to `get_*` (or `is_*` for boolean returns) and `set_*`, or `with_*` for builders. Can't rely on IDE or context tells alone.

**Comment by termhn** [comment]
I think in Rust it’s the generally accepted style guide that thing.noun()
is a getter, and thing.get_noun() is somewhat frowned upon.

**Comment by icefoxen** [comment]
For reference, winit uses `with_*` for builders, which I kind of like since it distinguishes them from non-builder setters.

**Comment by beatgammit** [comment]
Is there consensus on this? I'm willing to work on this, but I need to know if we're going with the Love2D conventions or the more Rusty syntax.

I prefer to use the idioms of the language I'm working in, but I'm happy to help out with whichever direction we choose to go.

My personal motivation here is to get a release with winit support so I can work on getting my project working on web and desktop platforms before it gets too complicated. This seems like a task that's blocking release and that I can help out with :)

**Comment by onelson** [comment]
I'd defer to https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis and favor `.foo()`, `.set_foo()`, and where required `.foo_mut()`

There's going to be a bigger payoff for using rust idioms than there is for "following the letter of the law" set by Love2D's api.

**Comment by beatgammit** [comment]
If I don't hear back on this issue, I might start working on this by following the Rust conventions. Feel free to complain in the PR if you really like the Love2D naming convention.

I'll probably go module by module, adding some simple tests if they're super easy.

**Comment by icefoxen** [comment]
Yeah, let's follow the Rust conventions then.  Thank you, @beatgammit !

**Comment by icefoxen** [comment]
Implemented and finished in #467 but it's a BIG change so I kinda want people to look at it and make sure it looks sane.
