### ISSUE TITLE
Screen flashes when closing window in windowed mode (in Linux)

### ISSUE THREAD

**Issue by dlight** [ggez/ggez#426]
The screens on all monitors flashes black for a brief time when I close the ggez window.

(and sometimes when opening too it seems, at least in the first times I run; but the flash in this case seems different, and I can't always reproduce it)

it looks like ggez is doing something related to modesetting even when opening a small window not in fullscreen (generally, when doing windowed or bordeless fullscreen, one wants to avoid messing with monitor resolutions). Or perhaps it literally draws a fullscreen black window on all monitors for a fraction of a second while it's quitting, but that's insane.

I suppose this is a known shortcoming because it appears even in the example at http://ggez.rs, but I can't find an existing issue so I'm opening this one.

My OS is Arch Linux, I use Plasma desktop 5.3, my xorg is 1.20, and I run xf86-video-ati 18 and xf86-video-intel 2.99.917 mesa drivers (but it's the same with either driver)

**Comment by icefoxen** [comment]
That's pretty interesting, and not something I've observed before.  We'll see if we can reproduce it.

**Comment by termhn** [comment]
I’m assuming this is on currently-released, cargo-version ggez and not the latest development version?

**Comment by icefoxen** [comment]
Please re-open if this is still a problem.  :-/
