### ISSUE TITLE
Transforms are broken -- tracking issue

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#435]
This has been the case for a while and I thought "oh it's just a quick fix" and I put it off forever and tried to mess with it yesterday and couldn't fix it so it's obviously not quick so I need to stop putting it off and give it its own issue.

Basically, in `Image::draw()`, the `offset` value is one way or another not being applied correctly.

There's also the various breakage with canvases and such, and in general all the drawing transform code needs to be looked over to make sure it Actually Works Right.

This is irritating since it's kinda spread out in various places and I don't understand how it composes well enough, so blah.

**Comment by icefoxen** [comment]
shear should probably be a Vector2 also.

**Comment by icefoxen** [comment]
Made a `transforms` example to have a nice way to play with this.  Results:

 * dest and offset are in units of pixels
 * shear and src are in units of image sizes

We want to be able to support both but not at the same time.

**Comment by icefoxen** [comment]
Text with `gfx_glyph` appears to not be affected by `graphics::set_screen_coordinates()`.

Things also get screwy as heck with dpi involved, sigh...

This is what I get drawing labels and points every 100,100 pixels on an 800x600 window on a display with dpi factor of 1.5...

![image](https://user-images.githubusercontent.com/1335133/43555690-ccf0e374-95c9-11e8-9ffe-50db2fec318b.png)

**Comment by icefoxen** [comment]
@termhn You're way better at math than me.  I'll buy you a cake if you help me with this, 'cause by now it's all some twisted mess and I can't figure out what's happening where, let alone what *should* be happening where.

**Comment by icefoxen** [comment]
Okay, so per #439 there's issues with the offset matrix calculation:

    translate * offset * rotation * scale * offset_inverse

(shear omitted for simplicity)

and it should be

    translate * offset * rotation * offset_inverse * scale

In 0.4 that code is [here](https://github.com/ggez/ggez/blob/master/src/graphics/drawparam.rs#L78), in 0.5 it is in the [same file but slightly different place](https://github.com/ggez/ggez/blob/devel/src/graphics/drawparam.rs#L212).

So I implemented this change in 0.5 and there's TWO issues

First, the offset isn't scaled properly by the size of the image, which is adjusted [here](https://github.com/ggez/ggez/blob/master/src/graphics/image.rs#L307).  

0.4 has MOST of the desired behavior: The image is drawn from the top-left corner minus `offset`, rotation starts from the `offset` point, and offset is in the range of `[0-1]`.  However, per #439 there are some bugs with that when using a custom coordinate system (and scaling?) which need to be looked in to more.

0.5 currently has Very Wrong behavior: The image is drawn from the top-left corner ignoring offset (or ignoring scale???), rotation starts from the `offset` point, and offset is in units of pixels (times whatever scale factor exists).  However, if I return it to the old way (`offset_inverse` multiplied after everything else) we still get wrong behavior: the image is drawn from the top-left corner + `offset`, rotation starts from the `offset` point, and offset is in unit of pixels (not multiplied by scale).

Well, progress?  I need to actually write down everywhere that a transformation to the coordinate system happens in this silly system..  Frankly the transform stack system doesn't really make that any easier, though in this case I'm not even using it at all so it does nothing; it just adds another thing going on to filter out.

**Comment by icefoxen** [comment]
`Image` is partially fixed in the `undo-drawtransform` branch, commit e698801abab0fe9a52d4eb433a831a88bd0d9b7e .  There is one obvious error that I can't find the cause of; in 0.4 if you draw something twice with the same coordinates but different offsets, it offsets the drawing as well as any rotation origin:

![image](https://user-images.githubusercontent.com/1335133/46099876-0486d300-c196-11e8-8dbe-dada99a6fbe9.png)

In devel currently that doesn't happen.  Which is weird since the math should be functionally identical?

**Comment by icefoxen** [comment]
Fixed that at least, in an ad-hoc way, in commit 27e40bd .  Text and canvases need fixing.

**Comment by Lokathor** [comment]
So I tried to fiddle with this a bit and I looked at old matrix math tutorials and ended up with

```rust
let transform = translate * offset * rotation * scale * offset_inverse;
```

And it _looks like_ what I think should be happening when I run the translations demo. The image rotates around it's "center" point while being scaled down and offset from one of the grid points.

link to my fork: https://github.com/Lokathor/ggez

**Comment by icefoxen** [comment]
Oh right, part of the pain in the ass is that `DrawTransform` is not actually helpful.  Sigh.  `Image` needs to fiddle with the scaling factors to make it so that one texel in the image lines up with one pixel on the screen, while *also* having the coordinates for the `offset` term be in units of 0 to 1.  Which is quite impractical with everything squashed down into a matrix.  Sooooo all that work is getting ripped out.

**Comment by icefoxen** [comment]
Resolving #493 will fix this for `Text`, since it currently just uses a `SpriteBatch` for text drawing and everything goes through the same graphics pipeline as `Image` does.  Ideally.  That is almost done, so that just leaves `Canvas`.

**Comment by icefoxen** [comment]
With 19a5df04e9d05a794ee8240f7f4ca788248a193e I'm pretty sure this is closed now.  \o/  The `shadows` example doesn't work, since it heckin' breaks even on minor changes and this has been anything but minor, but that'll get fixed as part of cleanup.
