### ISSUE TITLE
Drawing thousands of rectangles is slow

### ISSUE THREAD

**Issue by beatgammit** [ggez/ggez#440]
I have the following code ([full runnable gist](https://gist.github.com/beatgammit/0fb04d4ebed54a658aba607ab0916f47)):

    graphics::clear(ctx);
    for x in 0..50 {
        for y in 0..50 {
            let rect = graphics::Rect::new_i32(x*10, y*10, x+10, y+10);
            graphics::set_color(ctx, [(x as f32) / 50.0, 0.0, (y as f32) / 50.0, 1.0].into())?;
            graphics::rectangle(ctx, graphics::DrawMode::Fill, rect)?;
        }
    }
    graphics::present(ctx);

This loop takes ~35ms on my machine. I don't have anything fancy in my Cargo.toml, so I'm using default features, and this is running in release mode (debug mode is ~700ms).

Here's an example with `love` (takes <0.5-1.5ms most of the time):

    function love.draw()
      local start = os.clock()

      love.graphics.clear()
      for x=1,50 do
        for y=1,50 do
          local r = x/50
          local b = y/50

          love.graphics.setColor(r, 0, b, 1)
          love.graphics.rectangle('fill', x*10, y*10, 10, 10)
        end
      end

      print((os.clock()-start)*1000);
    end

I'm guessing drawing rectangles isn't quite optimized, but this seems quite a bit worse than "not optimized yet".

Am I doing something wrong? Or is this a bug in `gfx` or `ggez`?

Let me know what additional info you'd like to debug this. I've tried constructing the rect outside the loop and commenting out the `set_color` call, but the rendering time is still the same.

Dev system specs:

- CPU: Ryzen 1700 (3 GHz, 8 cores)
- GPU: Nvidia 960 GTX, proprietary drivers on Linux

I get similar results on Windows.

**Comment by termhn** [comment]
This is a matter of love automatically doing things behind the scenes to
speed this up for you (batching draw calls). Any time you make 2500 draw
calls in a single frame it’s gonna be slow. Take a look at the spritebatch
example to see how to use SpriteBatches which will speed this up immensely.

**Comment by beatgammit** [comment]
Yeah, I'll definitely use a sprite batch soon, but I was mostly concerned with the performance hit. Is `ggez` really not doing *any* batching at all? Is it basically making a separate call to the GPU at every iteration?

I guess I assumed that the `Context` was doing some kind of batching. If that's really all it is, I'll just port my code to use SpriteBatch and call it a day. :)

**Comment by termhn** [comment]
Yes, it’s not doing any batching internally. Each call to
graphics::rectangle corresponds to an individual draw call.
graphics::present is basically just swapping the frame buffers.

**Comment by beatgammit** [comment]
Huh, interesting. I followed the [snake example](https://github.com/ggez/ggez/blob/master/examples/snake.rs), which others may follow as well. At the very least, it should have a comment in the source somewhere saying that its approach doesn't scale.

**Comment by beatgammit** [comment]
Ok, with a sprite batch, it looks like my renders are now around 1ms. Thanks!

**Comment by beatgammit** [comment]
I'm willing to do some work on this, but I'm not particularly sure what should be done.

It seems to me that the snake example isn't a very good example since it doesn't scale *at all*, and there's nothing in the source to indicate that it is doing things incorrectly for a game that *can* scale. It's also the only example that links a video, and many newcomers like videos as an introduction.

I think I'll add a few comments to the example's source, indicating that this example is meant to highlight the general structure of a `ggez` game vs a `piston` game, but that its method of drawing is *not* the right approach for most games.

I understand that it's useful to have primitives for drawing. I'll try to throw together some comments in the code that would've helped my understand the limitations of the example.
