### ISSUE TITLE
TextCached doesn't scale on resize

### ISSUE THREAD

**Issue by reujab** [ggez/ggez#441]
I'm going to preface this by saying that great work has been put into this game engine, and I'm really enjoying using it.

---

When resizing a window, everything is automatically scaled to fill the window, but it seems that TextCached instances aren't.

This can be seen in the following example:
```rust
extern crate ggez;

use ggez::conf::Conf;
use ggez::event;
use ggez::event::EventHandler;
use ggez::graphics;
use ggez::graphics::DrawMode;
use ggez::graphics::Drawable;
use ggez::graphics::Point2;
use ggez::graphics::Rect;
use ggez::graphics::Text;
use ggez::graphics::TextCached;
use ggez::Context;
use ggez::GameResult;

struct MainState {
    text_cached: TextCached,
    text: Text,
}

impl EventHandler for MainState {
    fn update(&mut self, _ctx: &mut Context) -> GameResult<()> {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx);

        graphics::set_color(ctx, graphics::BLACK)?;
        let rect = Rect {
            x: 0.0,
            y: 0.0,
            w: self.text_cached.width(ctx) as f32,
            h: self.text_cached.height(ctx) as f32,
        };
        graphics::rectangle(ctx, DrawMode::Fill, rect)?;
        graphics::set_color(ctx, graphics::WHITE)?;
        self.text_cached.draw(ctx, Point2::new(0.0, 0.0), 0.0)?;

        graphics::set_color(ctx, graphics::BLACK)?;
        let rect = Rect {
            x: 0.0,
            y: self.text_cached.height(ctx) as f32 + 10.0,
            w: self.text.width() as f32,
            h: self.text.height() as f32,
        };
        graphics::rectangle(ctx, DrawMode::Fill, rect)?;
        graphics::set_color(ctx, graphics::WHITE)?;
        let dest = Point2::new(0.0, self.text_cached.height(ctx) as f32 + 10.0);
        self.text.draw(ctx, dest, 0.0)?;

        graphics::present(ctx);
        Ok(())
    }
}

fn main() {
    let mut conf = Conf::new();
    conf.window_setup.resizable = true;
    conf.window_mode.width = 200;
    conf.window_mode.height = 50;

    let ctx = &mut Context::load_from_conf("issue", "reujab", conf).unwrap();
    let default_font = ctx.default_font.clone();

    let text_cached = TextCached::new("This doesn't scale").unwrap();
    let text = Text::new(ctx, "This does scale", &default_font).unwrap();
    let state = &mut MainState { text_cached, text };
    event::run(ctx, state).unwrap();
}
```

Default window:
![small](https://user-images.githubusercontent.com/23725670/43168556-c5cfc60a-8f6b-11e8-8202-6364f2449cd2.png)

Resized window:
![big](https://user-images.githubusercontent.com/23725670/43168565-cc508fe6-8f6b-11e8-8f65-cd3791b28f8d.png)

What is the benefit of using `TextCached` over `Text`, and why doesn't it scale like everything else on a window resize? Could this be better explained in the documentation?

**Comment by icefoxen** [comment]
`TextCached` is much faster to draw than `Text` and more flexible, and is a little of an experiment in trying out a new rendering engine.  That said, this should probably be explained better, you are correct.

It *should* scale when the window is resized, so thank you for reporting this bug!

**Comment by icefoxen** [comment]
Depends on how it's implemented.  To avoid blurriness you generally want to render text at the actual size that you intend to display it at.  In 0.4.3 you can set the number of pixels with `Font::new_px()`

**Comment by icefoxen** [comment]
Related: #435

**Comment by icefoxen** [comment]
`TextCached`'s transform code is hacky placeholder stuff, and doesn't seem to take the `Context`'s projection into account, which is probably the problem here.

**Comment by PSteinhaus** [comment]
Weird that I missed this. Since `TextCached` is no longer existent and automatic scaling is also no longer a thing I think we can safely close this.
