### ISSUE TITLE
Create Image from &[u8]

### ISSUE THREAD

**Issue by mh84** [ggez/ggez#455]
I guess there should be a possibility to create an Image directly from a given byte buffer for some reason, mine would be that i would like to store all game related data (including images) in an sqlite database, so creating a method from_bytes would be appreciate.

If this would be agreed i will take care of this soonand  create a pull request providing this "feature" (if anyone would count 10 lines of rearranged code a new feature ;) )

With best regards!

**Comment by mbillingr** [comment]
This sounds like [`Image::from_rgba8()`](https://docs.rs/ggez/0.4.3/ggez/graphics/type.Image.html#method.from_rgba8) might work for you?

**Comment by mh84** [comment]
Not completely, I've seen that and had to `image::load_from_memory(&buf)?.to_rgba()` (from [Image::new()](https://docs.rs/ggez/0.4.3/ggez/graphics/type.Image.html#method.new)) myself because of storing .png files there directly, so i had to add this additional dependency, which i surely like to avoid for just that one call. Another option could be to re-export `image`, that would be okay too, or maybe even better though its image manipulating strength.

**Comment by termhn** [comment]
You say “just for that one call” but that one call under the hood is doing
a lot of stuff. If the image crate works excellently for all this stuff and
rustc is gonna elide all the extra code you don’t use anyway I don’t see
any reason we need to include it in ggez itself.

**Comment by mh84** [comment]
Sure, i will agree with your arguments, but i further would take in discussion that from users point of view, having an interface for creating `Image`s by loading files from disk and another creating them from a given `rgba &[u8]`, the middle part where having an bytestream for any source and being in need to create an `rgba &[u8]`, this could easily be provided through the library itself imho.

**Comment by onelson** [comment]
I think the only real reason to re-export the `image` crate would be if the types from `image` were to show up in `ggez` function signatures, meaning calling code would have to align their dependency on `image` with whatever `ggez` depended on. I'm not sure this is even the case.

Is the need to use `image::load_from_memory().to_rgba()` due to a color depth/channel mismatch or something? Seems like `Image::from_rgba8()` is really meant to be the thing for this.

**Comment by icefoxen** [comment]
I sympathize, but it does seem like the `image` crate is the right tool for the job of decoding images. ggez uses `image` already, so adding this functionality to ggez has no advantages to performance, binary size or compile time. It's just another function to maintain and document.

It's not really a big deal, so maybe it would be nice to have anyway. But it doesn't add much benefit either.

**Comment by icefoxen** [comment]
Sorry, but I'm going to give this a thumbs-down, for the reasons described.  `Image::from_rgba8()` is the best way to create an `Image` from raw data in memory, `Image::new()` is the best way to get an image file off disk, and `image::load_from_memory()` exists for everything else so I don't particularly see the need to provide it.  The added burden to making an `Image::from_memory`, is very small, but I see the added benefit as even smaller.

Anyone feel free to re-open this if you want to discuss it more.  This isn't really a big deal either way.
