### ISSUE TITLE
Suggestions for audio

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#464]
```
21:35 <Nick_64> yo
21:35 <Nick_64> idk if pitch is an appropiate name here
21:35 <Nick_64> https://github.com/ggez/ggez/blob/05eea40a6b175c7a0ee550b5afa14951771ee980/src/audio.rs#L176
21:36 <Nick_64> Isnt this the playback speed
21:39 <Nick_64> Also, have you considered making the sink public
                (https://github.com/ggez/ggez/blob/05eea40a6b175c7a0ee550b5afa14951771ee980/src/audio.rs#L309)
                and turning ` rodio::Decoder::new(cursor)?`
                (https://github.com/ggez/ggez/blob/05eea40a6b175c7a0ee550b5afa14951771ee980/src/audio.rs#L371)
                into a public method? I think that would allow library users to use all the functionality in
                rodio
21:39 <Nick_64> Even if its not wrapped by ggez atm
```

"speed" is probably a better name than pitch, yes.  I'm a little ambivalent about exposing `rodio` directly though.

**Comment by mbillingr** [comment]
`speed` seems to be a better name for the member variable.

 I do not think it would be a better name for the public function `set_pitch()`, though. That is because we want to actually change the pitch, and changing the speed is just an easy way to achieve that.

I'm actually in favor of exposing `rodio` (mainly because it would let me easier use my [ambisonic](https://github.com/mbillingr/ambisonic) crate with ggez), but I don't really know how to do that nicely.

**Comment by icefoxen** [comment]
Well, we expose `gfx-rs`, so there's good precedent for exposing `rodio`; if you think it's useful then let's figure out how to do it.  It looks like the easiest way is just to provide a method to get the `rodio::Device` structure; I think anything else can be done based on that.

**Comment by mbillingr** [comment]
What do you think about `Source.from_rodio(src: impl rodio::Source) -> Self` and `Source.to_rodio(&self) -> impl rodio::Source` members?

**Comment by nico-abram** [comment]
Now that https://github.com/ggez/ggez/commit/504e1de2c217502a760f18df92eafea55d79c377 has landed this can be closed right?

**Comment by mbillingr** [comment]
I'm inclined to agree. If anyone is still interested in exposing `rodio` another more specific issue can be opened for that.

**Comment by icefoxen** [comment]
Yep, looks like this just forgot to get closed.
