### ISSUE TITLE
Initial mouse position, without a single mouse move event

### ISSUE THREAD

**Issue by elszben** [ggez/ggez#465]
I can't seem to find a way to get the mouse position in a windowed app properly (did not test it in full screen, it may work there properly). The eventhandler's mouse events work properly but they only happen if the user actually moves the cursor after the app is started. If the user does not move the cursor, no event is generated and the get_position() function also returns 0,0. I even tried to query it in focus_event but get_position() gives the same result there as well. Other solution would be to query it in every single draw and/or update but that seems silly. What am I doing wrong? What's the proper method?

Thanks in advance.

**Comment by icefoxen** [comment]
SDL2 does not store absolute mouse position, you only are notified of its position in events when the mouse moves, via the `MouseMotion` event type.  So I'm not sure there is a way to ask what the mouse position is before there's an event.

**Comment by elszben** [comment]
Yeah, I've come to the same conclusion after googling for a while:( It is
not possible with SDL. Thanks anyway, I'll figure something out.

**Comment by icefoxen** [comment]
No problem!  Thanks for bringing it up, it's always nice to improve these edge-cases when we can.  Just doesn't seem possible in this case.
