### ISSUE TITLE
WrapMode objects can't be created without the gfx crate

### ISSUE THREAD

**Issue by bachm** [ggez/ggez#471]
WrapMode objects can't be created without `extern crate gfx;` and `use gfx::texture::WrapMode;`. It appears that creating a type alias of an enum only creates an alias for the enum's type but not its variants such that ggez::graphics::WrapMode::Clamp etc effectively do not exist for the compiler. They variants are not shown in the documentation either.

**Comment by icefoxen** [comment]
This should be fixed in develop, now!  Thanks again.  It was an easy mistake to make; I made a type alias instead of actually re-exporting the type.
