### ISSUE TITLE
Suggestion: adding ContextBuilder::set_config method

### ISSUE THREAD

**Issue by RGates94** [ggez/ggez#473]
Sometimes, it would be useful to be able to set all `Conf` fields of a `Context` at once.  As the `Conf` struct already exists in ggez, a method like this seems like the most logical choice:

`ContextBuilder::set_config(self, config: Conf) -> Self`

Alternatively, this method could be implemented for `Context`, which would allow for changing these properties after the `Context` has been created.

**Comment by icefoxen** [comment]
I'd considered something like this but hadn't really thought up a use case, but talking to OP on Discord came up with an interesting one: easily switching between different config files to test different pre-defined settings.  Let's do it.

**Comment by icefoxen** [comment]
Resolved by #474 :heart:
