### ISSUE TITLE
ggez starts up with black screen on Mac Mojave

### ISSUE THREAD

**Issue by d9n** [ggez/ggez#478]
- On a Mac with Mojave installed
- `$ cd path/to/ggez/examples`
- `$ cargo run --example super_simple`

Expected: ggez window starts up with a blue screen and a white circle racing across it
Actual: ggez window remains black. If you move the window by dragging it with your mouse, it starts rendering.

---

Other examples seem to exhibit the same behavior. I know this wasn't happening earlier this week, but I *just* updated my OS and started seeing this new issue. I'm a little paranoid that it may be some local issue - so to start, can anyone else verify if they're seeing it too?

**Comment by d9n** [comment]
Looks like an underlying issue with SDL2. I'm seeing the same behavior running this C++ SDL tutorial: https://www.willusher.io/sdl2%20tutorials/2013/12/18/lesson-6-true-type-fonts-with-sdl_ttf

Investigating further...

**Comment by d9n** [comment]
https://bugzilla.libsdl.org/show_bug.cgi?id=4272

Looks like a known issue in the SDL codebase, so I'm going to close my bug here! ggez should automatically start working properly again after the next version of SDL is released.

**Comment by icefoxen** [comment]
Thank you for doing some research on this!  We're gonna have to keep an eye on that and see how it pans out on the SDL side; we might have to update what version of SDL we use when it happens.

**Comment by seivan** [comment]
Doesn't happen on devel that uses `winit`.

**Comment by acheronfail** [comment]
@seivan I'm actually seeing this happening using the `devel` branch at the moment (updated the branch just today).

Did you do anything differently?
For reference, here's an example that uses the `devel` branch but still produces a blank screen on macOS 10.14: https://github.com/aochagavia/rocket/pull/92

**Comment by acheronfail** [comment]
From what I gather (from here https://bugzilla.libsdl.org/show_bug.cgi?id=4272) this seems to be fixed in SDL2 2.0.9.

The update to the brew formula is in a PR at the moment https://github.com/Homebrew/homebrew-core/pull/33781. We'll see if updating to that will fix this for our Mojave users.

**Comment by acheronfail** [comment]
Okay, can confirm, that on Mojave and using the `devel` branch this fixes the blank screen:

```diff
diff --git a/src/graphics/mod.rs b/src/graphics/mod.rs
index ef88dd9..8432f8e 100644
--- a/src/graphics/mod.rs
+++ b/src/graphics/mod.rs
@@ -422,6 +422,8 @@ pub fn present(ctx: &mut Context) -> GameResult<()> {
     gfx.encoder.flush(&mut *gfx.device);
     gfx.window.swap_buffers()?;
     gfx.device.cleanup();
+    gfx.window.resize(winit::dpi::PhysicalSize::new(1024., 640.));
+
     Ok(())
 }
 ```

Just to make things clear:

* `master`: Mojave shows **a black screen**
    * this is a bug in SDL2 which is fixed in SDL2 2.0.9
* `devel`: Mojave shows **a blank window**
    * this is a bug in `glutin`: https://github.com/tomaka/glutin/issues/1069

**Comment by icefoxen** [comment]
Thanks for your research on this!

**Comment by icefoxen** [comment]
I'm dropping support for Mac, so. cry See #587 for basically the reason why.
