### ISSUE TITLE
Adding game controller mappings

### ISSUE THREAD

**Issue by porglezomp** [ggez/ggez#488]
I'm trying to use joycons as controllers for a game, but it's not detected as existing. When I test with another SDL2 application I've written in the past, I get a "Couldn't find mapping for device." Is ggez silently swallowing this error, maybe?

**Comment by porglezomp** [comment]
Ah, this is caused by `controller_ctx.is_game_controller(i)`, which is means that only things recognized by SDL as supporting the game controller api work, not just the joystick API. This suggests that ggez should provide a way to add extra controller bindings.

**Comment by icefoxen** [comment]
Thanks for the report!

> This suggests that ggez should provide a way to add extra controller bindings.

Not sure what you mean here.  Do you have an example?

**Comment by porglezomp** [comment]
I added
```rust
println!(
    "Mappings loaded: {}",
    controller_ctx.load_mappings("gamecontrollerdb.txt")?
);
```
inside `GamepadContext::new` before it searches for gamepads. I think the *proper* way to do it would be to allow the `ContextBuilder` to specify paths to load mappings from, potentially using the resources system. I'm currently working on a fix, should I use `Filesystem::open` to open the path?

**Comment by icefoxen** [comment]
It looks like the SDL2 crate takes `Into<Path>` and opens it itself.  I would probably prefer to include the file with `include_str!()` or such so it gets built into the exe, and then feed it into <https://docs.rs/sdl2/0.32.0-beta.2/sdl2/struct.GameControllerSubsystem.html#method.add_mapping>.  Getting ggez to recognize that it's there would be harder though.  :-/  Maybe one could just create a new `GamepadContext` after adding the mappings and stick it into an existing `Context`...

It seems like the better way would be to get SDL2 itself to include Switch joycon mappings upstream though.

**Comment by porglezomp** [comment]
Ah, creating a new `GamepadContext` may be the right way to do things here…
```rust
ctx.sdl_context
    .game_controller()
    .unwrap()
    .load_mappings("./resources/");
ctx.gamepad_context = ggez::input::GamepadContext::new(&ctx.sdl_context).unwrap();
```
seems like a promising path. I'm gonna go see about getting `sdl2` to support loading mapping from a `Read` object so that I can use resources or `include_str!()`.

**Comment by icefoxen** [comment]
You can load mappings from a `&str` with `add_mapping()`, though I agree, a `Read` object would be nicer.

**Comment by porglezomp** [comment]
`load_mapping` does stuff like filtering different mappings by platform, which `add_mapping` does not. I suppose my particular use-case here I only need one platform, so I suppose that'll work.

**Comment by porglezomp** [comment]
For reference, https://github.com/Rust-SDL2/rust-sdl2/pull/801 adds `load_mappings_from_read`, so whenever that gets put into a release and ggez uses that release, that'll be the way to do it.

**Comment by icefoxen** [comment]
Woohoo, thank you so much!  When the next version of the sdl crate gets released we might have a version bumped ggez to use it.

**Comment by icefoxen** [comment]
Not using SDL2 anymore, so.  :-/  gilrs still uses SDL2's mappings though, so they should get any updated mappings around.  It WOULD still be nice to have our own function to add mappings though.  Just need to expose this: https://docs.rs/gilrs/0.7.1/gilrs/struct.GilrsBuilder.html#method.add_mappings

**Comment by PSteinhaus** [comment]
```add_mappings``` is exposed through a re-export of gilrs, so can this be closed?
