### ISSUE TITLE
WAV files do not play sound.

### ISSUE THREAD

**Issue by a2aaron** [ggez/ggez#489]
It appears that .wav files do not play sound, despite seemingly load correctly. ogg files do play correctly however.

**Comment by icefoxen** [comment]
Can you provide an example of a .wav file that doesn't work?

Thanks.

**Comment by a2aaron** [comment]
Apologies on getting this back so late. I believe that 24-bit integer and 32-bit float encoded WAV files do not play properly. I have attached these. None of these will play in ggez however.

Note that 16-bit int encoded WAV files do play, however. I've attached all of these as a zip.

[resources.zip](https://github.com/ggez/ggez/files/2522177/resources.zip)

**Comment by a2aaron** [comment]
Upon further investigation, I think this is actually a bug in Rodio. Gonna close this and open one there.

**Comment by icefoxen** [comment]
...I do have to ask though, why are you bothering with wav instead of flac if you want lossless audio?

**Comment by a2aaron** [comment]
The main reason is that wav and ogg are the only export options in LMMS (I am using it for music and sfx purposes), and I wanted to just directly export without going through Audacity. I don't actually need lossless audio for my project.

**Comment by icefoxen** [comment]
Fair enough, I was just wondering.  If it helps, ogg should work fine afaik.
