### ISSUE TITLE
Text color is always white

### ISSUE THREAD

**Issue by AaronM04** [ggez/ggez#49]
Hi, I tried to set text color using `graphics::set_color` but it doesn't seem to work -- the text foreground is always white.

**Comment by icefoxen** [comment]
Well that's interesting.  I'll check it out.  (Sorry for the slow response!)

**Comment by icefoxen** [comment]
Well gosh and golly, but you are correct!  Text is basically a `Texture` underneath, the same as an `Image`, and so you would need a `set_color_mod()` method on it just like Image.  But there isn't one.

So I added them and published ggez 0.2.2.  Enjoy!

**Comment by AaronM04** [comment]
Thanks for the fix! :)
