### ISSUE TITLE
Context::load_from_conf taking 40 seconds to run

### ISSUE THREAD

**Issue by isavegas** [ggez/ggez#490]
Running any of the examples on MSVC results in roughly 40 seconds of waiting for ggez to look for the `conf.toml`, which it never finds in any of the resources directories, including the one next to the binary in `target/debug` or `target/release`. Unfortunately, I'm unaware of any way to avoid using `load_from_conf` or how to rectify the issue.

Besides that, how can one load conf.toml from `/resources` in their Cargo directory if `$CARGO_MANIFEST_DIR/resources` can only be mounted to the filesystem after the context has been created, which requires a conf.toml to be searched for?

I'm using SDL 2.0.8 from [libsdl.org](https://www.libsdl.org/download-2.0.php).

**Comment by icefoxen** [comment]
WOW. Now THAT'S interesting! Is one of the directories it is looking in (there's a function somewhere to print the full list) in a network share or something?

The latter part is fixable using `ContextBuilder`, see the astroblasto example for a demonstration. This is a bit of a rough edge we didn't realize until after it was made; with ggez 0.5 everything will be done through the context builder all the time, so will be more consistent and obvious.

**Comment by isavegas** [comment]
Unfortunately, it looks like `ContextBuilder` is having the same issue. I'm getting a constant 40 second pause when creating the context. Using the following to prevent searching for a configuration file doesn't affect the load time. Is there anything else that could be causing such a huge delay in initialization time?

```rust
let mut ctx = ContextBuilder::new("helloworld", "ggez")
        .with_conf_file(false)
        .build().unwrap();
```

**Comment by icefoxen** [comment]
If it's not hung up on waiting for a file for a long time I have no idea what could be causing this delay!  It's wild.  If you're willing, I would recommend either adding a bunch of `println`'s to [context creation](https://github.com/ggez/ggez/blob/master/src/context.rs#L98), or outright tracing it in a profiler, so we can start to find exactly where the delay is happening.

What version of Windows are you on, what graphics card are you using, and what version of Rust are you using?

**Comment by isavegas** [comment]
Windows 10, Build 1809.
GTX 1070 with Nvidia driver version 416.34.
Rust 1.31.0-nightly. I've had the issue with the last few nightlies as well.

Oddly enough, using Visual Studio 2017 to profile my application causes it to crash as soon as it finishes initializing. In any case, I'm not going to pretend to have any clue what I'm doing, but it LOOKS as though an unknown function in `dinput8.dll` that's being called by SDL2 is causing the huge delay, although my lack of debugging symbols for the libraries isn't helpful.

![devenv_2018-10-15_18-54-24](https://user-images.githubusercontent.com/3105000/46984645-cfdaad00-d0ab-11e8-934d-ad0460ba352b.png)

Digging into the code, it looks like the delay is caused by [calling `sdl_context.game_controller()` in `GamepadContext::new`](https://github.com/ggez/ggez/blob/master/src/input.rs#L32). I've reproduced the issue with the controller and joystick subsystems in the `rust-sdl2` crate, so I'll create an issue for it on their repo, as it obviously isn't being caused by `ggez`. Thanks for the help!

**Comment by isavegas** [comment]
I had to dig my way through the `rust-sdl2` crate and then through SDL2's source code to realize that DInput8.dll was to blame, meaning that the issue I've been having has been entirely Microsoft's fault. Reverting to an older Windows build solved the issue.

**Comment by icefoxen** [comment]
Whew!  That sucks.  I'm happy you figured it out in the end though.
