### ISSUE TITLE
Add community gamepad mappings

### ISSUE THREAD

**Issue by porglezomp** [ggez/ggez#494]
SDL2 provides a set of controller mappings, but there's a larger community-provided set of mappings at https://github.com/gabomdq/SDL_GameControllerDB. gilrs has a function for adding all of these [`add_included_mappings`](https://gilrs-project.gitlab.io/gilrs/doc/gilrs/struct.GilrsBuilder.html#method.add_included_mappings). It would be nice to have an option in the game config to automatically call this. (Enabled by default? I found it confusing to not have my controllers recognized.)

If this is worth adding, it would also be good to bundle them for the existing SDL2 version, at least until gilrs has good enough platform support.

**Comment by icefoxen** [comment]
\o/

Thank you so much for this!  Also it's cool to actually meet someone at RBR who contributes to ggez.

We should bundle this, have a setting for enabling/disabling it in `ContextBuilder`, and have it enabled by default.

**Comment by porglezomp** [comment]
I'm working on this

**Comment by icefoxen** [comment]
Any news on this? For some reason I thought you were done but I can't find a PR.

**Comment by porglezomp** [comment]
The SDL2 implementation of this requires waiting for them to put out a new release for the code to compile, and so I got a bit stuck on that. I'll get around to the gilrs version within a few days—there was some difficulty on that, but I forget what.

**Comment by icefoxen** [comment]
@porglezomp any news on the gilrs bit?

**Comment by porglezomp** [comment]
Oh, right, sorry. According to the docs gilrs already includes the community mappings by default, so I'm not *sure* if we need it in the builder at all? I'm not sure what the use case for disabling it is, to be honest, my logic in making it enable-able in the first place was that it wasn't default before, but since it is here…

It would provide some API symmetry for the SDL2 patch later, but that's already going to be so different in other ways.

**Comment by icefoxen** [comment]
Okay.  Since `gilrs` already includes the community gamepad mappings, and we have no convincing use case for disabling them, it sounds like 0.5 will have the desired behavior.
