### ISSUE TITLE
Weird scaling behaviour when creating arbitrary-sized canvases

### ISSUE THREAD

**Issue by matju** [ggez/ggez#497]
I'm playing around with trying to colour-tint an image when drawing it onto the screen. There may be better ways, but my strategy for this is essentially:

1. Create a canvas the same size as the image
2. Fill the canvas with a particular colour
3. Switch to `BlendMode::Multiply` and draw the image into the canvas
4. Switch to `BlendMode::Add` and draw the a rectangle of another colour over the whole canvas
5. Draw the canvas contents onto the screen

Presumably related to #435, what I've found is that, regardless of the size of the canvas specified in step 1:

-  In steps 2 and 4 the rectangle I must specify in order to cover the whole canvas is equal to the size of the whole window - e.g. if my window is 800 x 600 but my canvas was created as having dimensions 64 x 64 then I must still use the rectangle `(0, 0, 800, 600)` in order to cover the canvas, not `(0, 0, 64, 64)`.
- In step 3, in order to fill the canvas I must scale the image in the `DrawParam` struct when drawing it so that it has the same width and height as the whole window (e.g. `scale: Point2::new(800.0/image_width, 600.0/image_height)`.

It's as though the canvas always has internal logical dimensions equal to the window size (800 x 600 in my examples) - even though interrogating the dimensions of its internal `Image` returns the original dimensions I created it with.

Perhaps I'm misunderstanding the purpose of `Canvas` and creating small canvases of arbitrary size for things like this isn't an expected use-case?

This is using ggez 0.4.4.

**Comment by icefoxen** [comment]
`Canvas`'s are, unfortunately, a place there's lots of weird edge cases in the coordinate transforms and such.  Can you just use the `color` parameter of `DrawParam` to tint the image?

If not, I'll see if I can dig into this.

**Comment by icefoxen** [comment]
Man, sorry for taking a heckin' month to get back to you on this.

First off again, for color tinting, would the `Color` option for a `DrawParam`.  Does this not do what you want?

Second, ideally drawing a `Canvas` should be exactly like drawing an `Image`, but there may be some stuff in the projection not getting correct values.  We test some of that in the `hello_canvas` example but that's taking a screen-sized canvas and shrinking it down, not taking a smaller sized thing and blowing it up.  Should be easy to check for at least.

**Comment by Matthew-Maclean** [comment]
I don't know if this is still a relevant topic, but you can use `graphics::set_screen_coordinates` with a `Rect` with the width and height of the Canvas to get regular scaling happening (and even other scalings, if you so desite). This is the same/similar behavior as when the screen is resized, with the scaling being off unless you manually set the screen coordinates to the new window size. This might imply that this behaviour is not really `Canvas` specific, but applies to the whole drawing stack instead.

**Comment by PSteinhaus** [comment]
@Matthew-Maclean is right. I think we can safely close this.

**Comment by JonathanMurray** [comment]
Hi! I also ran into issues related to small canvases of arbitrary size now. `graphics::set_screen_coordinates` indeed seems to solve it. Should we perhaps add a note about this to the `Canvas` documentation? I read the documentation here https://docs.rs/ggez/0.5.1/ggez/graphics/type.Canvas.html to try and understand if I was missing some obvious design detail but couldn't find anything that explained the behaviour I was seeing.

I'm even thinking that maybe updating the screen coordinates is something that should happen by default when `graphics::set_canvas` is called (?) Or are there legitimate situations where one would prefer the current behaviour?

**Comment by JonathanMurray** [comment]
In case it helps clarify my situation, here are two screenshots showing what's rendered with and without the `set_screen_coordinates` calls.

without:
<img width="1012" alt="Screenshot 2021-04-02 at 22 10 37" src="https://user-images.githubusercontent.com/3257474/113450651-9d020c00-9400-11eb-851f-df016c965060.png">

with:
<img width="1011" alt="Screenshot 2021-04-02 at 22 10 53" src="https://user-images.githubusercontent.com/3257474/113450675-a4291a00-9400-11eb-945d-863f183abd4a.png">

coordinates/dimensions as below:
```
const WINDOW_SIZE: [f32; 2] = [1000.0, 500.0];
const CANVAS_SIZE: [u16; 2] = [400, 400];
const CANVAS_POS_ON_SCREEN: [f32; 2] = [50.0, 50.0];
const CIRCLE_RADIUS: f32 = 150.0;
const CIRCLE_POS_IN_CANVAS: [f32; 2] = [200.0, 200.0];
```

**Comment by PSteinhaus** [comment]
@JonathanMurray I see your point.
Adding a bit of explanation to the documentation is probably a good idea.

I'd prefer to not to call ```set_screen_coordinates``` inside of ```set_canvas``` though. I don't have a real use case to justify it right now, but my basic reasoning would be that this is how ggez handles screen coordinates everywhere else as well. If you resize the window for example the coordinate system stays the same as well. It's just simpler. If you want the coordinate system to change as well, then just say so (i.e. call ```set_screen_coordinates```).

But I understand that this can lead to some confusion, so updating the docs seems very reasonable to me.

**Comment by JonathanMurray** [comment]
@PSteinhaus Alright! I made an attempt at adding something to the doc: https://github.com/ggez/ggez/pull/923 Do you think it's somewhat accurate?

**Comment by PSteinhaus** [comment]
I think it gives new users enough information to get behind why things drawn on their canvases might look off and how to fix it, so I think it's fine, thanks :)

But of course @icefoxen will have the last word on this.
