### ISSUE TITLE
Drawing an image/loading an image issue with no error

### ISSUE THREAD

**Issue by hunterkepley** [ggez/ggez#498]
I have a new game I am making, 95% of the time, no issues, but the other 5%, the player image fails to render/maybe fail to load. No error, no crashing, runs just fine. Here is where the player is defined in the game state:

```struct GameState {
    text: graphics::Text,
    frames: usize,
    pl: player::Player,
    platforms: Vec<platform::Platform>,
    is_a_pressed: bool,
    is_d_pressed: bool,
    is_space_pressed: bool,
}

impl GameState {
    fn new(ctx: &mut Context) -> GameResult<GameState> {
        let font = graphics::Font::new(ctx, "/DejaVuSerif.ttf", 12)?;
        let text = graphics::Text::new(ctx, "Platformgame", &font)?;
        let pl = player::Player::new(ctx, "/player.png", (0.0, 0.0), 450.0);
        let mut platforms: Vec<platform::Platform> = Vec::new();
        platforms.push(platform::Platform::new(ctx, "/platform.png", (300.0, WINDOW_SIZE.1 - 75.0), pl.move_speed*1.5));
        let is_a_pressed = false;
        let is_d_pressed = false;
        let is_space_pressed = false;
        Ok( GameState { pl, platforms, text, frames: 0, is_a_pressed, 
            is_d_pressed, is_space_pressed } )
    }
}
```

the part of the player struct that has the image:

```impl Player {
    pub fn new(ctx: &mut Context, image_location: &str, position: (f32, f32), move_speed: f32) -> Player {
        let player_image = graphics::Image::new(ctx, image_location).unwrap();
        let batch = graphics::spritebatch::SpriteBatch::new(player_image.clone());
```

Drawing the player [in player struct]:

```    pub fn draw(&mut self) {
        self.batch.add(
            graphics::DrawParam {
                dest: graphics::Point2::new(self.position.0, self.position.1),
                ..Default::default()
            }
        );
    }
```

```    pub fn return_param(&mut self, dpi_scale: graphics::Point2) -> graphics::DrawParam {
        // Parameters for the player
        graphics::DrawParam {
            dest: graphics::Point2::new(0.0, 0.0),
            scale: dpi_scale,
            ..Default::default()
        }
    }
```

in the game state draw method:

```        // Player drawing
        self.pl.draw();
        let pl_param = self.pl.return_param(dpiscale);
        graphics::draw_ex(ctx, &self.pl.batch, pl_param)?;
        self.pl.batch.clear();
        // End of player drawing
```

Reiteration of problem: It's the same exact game, just the player image isn't on the screen. No error, nothing is wrong other than it doesn't draw. The platform I am rendering is drawn the _exact_ same way, except using a for loop through a Vec of platforms.

Hopefully it's an error on my end, or a simple fix.

** It tends to happen after not running for a few minutes, or after pulling from my repo. Running it many times in a short period of time never causes it

* Edited a lot because I messed up the markdown for code

**Comment by icefoxen** [comment]
That's reeeeally weird.  Is there some way you can link the whole repo for me to take a look at?

Thanks.

**Comment by hunterkepley** [comment]
@icefoxen [here is a collab invite link](https://github.com/hunterkepley/platformgame/invitations)

**Comment by PSteinhaus** [comment]
Hmm... I kind of want to close this, since it's so old and something most probably already fixed this bug because we've never had anything like it again (AFAIK).
But then again, maybe I get around to forking your repo and porting it to 0.6.0-rc1 or something one day...

**Comment by hunterkepley** [comment]
> Hmm... I kind of want to close this, since it's so old and something most probably already fixed this bug because we've never had anything like it again (AFAIK).
> 
> But then again, maybe I get around to forking your repo and porting it to 0.6.0-rc1 or something one day... (since it's riiight at the edge of being small enough to do this without hopefully to much work)

Wow, never thought this issue would be looked at again-- if you end up doing that, let me know what caused it after all these years :)

**Comment by PSteinhaus** [comment]
Well, we DO have other things to take care of first, so I'll be honest and say that this is pretty much at the bottom of our priority list right now 😅
But I think it would be fun to try, nevertheless. Maybe someday.

**Comment by nobbele** [comment]
Closing as probably fixed? and stale
