### ISSUE TITLE
Use of deprecated item 'graphics::spritebatch::BoundSpriteBatch'

### ISSUE THREAD

**Issue by johnthagen** [ggez/ggez#499]
Check out trunk of `ggez` from GitHub.

```
$ cargo run --example astroblaster
...
   Compiling ggez v0.4.4 (/Users/user/GitHub/ggez)                                                                  
warning: use of deprecated item 'graphics::spritebatch::BoundSpriteBatch'                                               
  |                                                                                                                     
  = note: #[warn(deprecated)] on by default                                                                             
```

**Comment by icefoxen** [comment]
Described in this issue: https://github.com/ggez/ggez/issues/293

**Comment by johnthagen** [comment]
@icefoxen I was under the impression that since this is deprecated, the use of it should be removed. Should this be marked as a question?

**Comment by onelson** [comment]
Might be good to redo the examples with the state of the art, but I think I'd probably defer that work until whatever in the devel branch is closer to landing.

**Comment by icefoxen** [comment]
I don't think it's actually used in any of the examples?  I think there's just some place where it's exported or something and that makes rustc twig onto the warning.  I might be mistaken.

The examples in devel have been upgraded to the latest and greatest.  `BoundSpriteBatch` has been removed in devel as well.

**Comment by icefoxen** [comment]
This seems resolved, if you want to continue discussion please re-open the issue. :-)
