### ISSUE TITLE
"process didn't exit successfully" when running examples

### ISSUE THREAD

**Issue by Amomum** [ggez/ggez#510]
Platform: Windows 7
Rust: stable-i686-pc-windows-gnu (default), rustc 1.30.1 (1433507eb 2018-11-07)

What I did:
1) Installed MinGW, put it in path
2) Downloaded SDL (as per https://github.com/Rust-SDL2/rust-sdl2 section Windows (MinGW))
3) Put SDL2.dll right nest to `cargo.toml`
3) run `cargo run --example hello_world`

Got this:

```
Running `target\debug\examples\hello_world.exe`
error: process didn't exit successfully: `target\debug\examples\hello_world.exe` (exit code: 3221225781)
cargo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

As far as I could google - code 3221225781 is 0xc0000135 = STATUS_DLL_NOT_FOUND.

But what dll? I'm stuck :(

**Comment by Amomum** [comment]
32-bit toolchain is more or less intentional but the SDL2.dll was indeed 64-bit. Silly me :)

Thank you!

**Comment by icefoxen** [comment]
No problem!
