### ISSUE TITLE
Clarify (theoretical) thread-safety

### ISSUE THREAD

**Issue by Palladinium** [ggez/ggez#520]
In the README under Implementation Details:

> It should be entirely thread-safe outside of the basic event-handling loop, and portable to Windows, Linux and Mac.

I've had a dig around the docs and FAQ and I'm not entirely sure what that means. More specifically, in what way(s) is the event-handling loop not thread safe?

**Comment by icefoxen** [comment]
As I understand, on some platforms (Mac specifically?) it is a requirement that the system's event loop (getting key presses, mouse motions etc) only be queried from the program's main thread.  In Rust terms, the `poll_events()` method is attached to a structure that is not `Send`.  I believe this is also the case on Android, which isn't supported yet but hopefully will be in the future.

Dug up some sources: <https://developer.apple.com/library/archive/documentation/General/Devpedia-CocoaApp-MOSX/MainEventLoop.html>  <https://github.com/glfw/glfw/issues/136>  I'm not an expert on OSX development so I can't verify from experience whether these limitations still exist, but seems fairly decisive.

**Comment by Palladinium** [comment]
I stumbled upon this from the SDL docs, relating to `SDL_PumpEvents`, which is called by `event::run()`

>  This should only be run in the thread that initialized the video subsystem, and for extra safety, you should consider only doing those things on the main thread in any case.

Also, the ggez docs mention that the `Context` struct is not thread-safe, and a lot of operations use it, all of which make sense to be thread-unsafe (e.g. rendering, audio, resource loading). Those could probably reference it through a `Mutex`, but I'm not entirely sure if that would be safe.

**Comment by icefoxen** [comment]
Yeah, `winit` has similar constraints.

Audio: rodio already has a dedicated background thread, so doing stuff from another thread to manipulate it should be safe.

Resource loading: Can be multithreaded but should be blocked on hard drive anyway so besides having a background thread doing the loading while the main thread does other stuff, there's not much to gain from multithreading.

Rendering: Queueing render commands is thread-safe but there's again not much to be gained.

**Comment by icefoxen** [comment]
Fixed in 014c7be
