### ISSUE TITLE
[Question] Does ggez supports collision?

### ISSUE THREAD

**Issue by DuckerMan** [ggez/ggez#521]

**Comment by icefoxen** [comment]
Nope!  This is on purpose.  I suggest taking a look at `ncollide2d`, or just writing your own if you just need something simple.

A slightly vague run-down of how to integrate ggez, ncollide2d and specs is here: https://wiki.alopex.li/LD42Postmortem

**Comment by DuckerMan** [comment]
Okay, thank you, goodluck!
