### ISSUE TITLE
FAQ: Add some info about profile-overrides cargo feature

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#526]
"Image/sound loading and font rendering is slow!" section of the FAQ mentions that you can change the opt-level of the whole profile:

https://github.com/ggez/ggez/blob/e83645364/docs/FAQ.md#imagesound-loading-and-font-rendering-is-slow

But it doesn't mention ["Profile Overrides" feature of cargo](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-overrides). It's unstable at the moment (and works only with nightly toolchains), but I still find it useful for local development.

Basicly, the information is

> You need to add
>
> ```toml
> cargo-features = ["profile-overrides"]
> ```
> ... to the top of your `Cargo.toml` and than you can add
> 
> ```toml
> # All dependencies (but not this crate itself or any workspace member)
> # will be compiled with -Copt-level=2 . This includes build dependencies.
> [profile.dev.overrides."*"]
> opt-level = 2
> ```
>
> ... and now you can debug your code while all the deps (including ggez itself) should have a good performance.

But some additional explanations may be required.

**Comment by icefoxen** [comment]
Very nice, I didn't know about this.  That's one nightly feature I would really like to see hit stable!

**Comment by remag9330** [comment]
This has actually just hit stable as of Cargo 1.41!

https://doc.rust-lang.org/cargo/reference/profiles.html#overrides

Very under the radar IMO, I think lots of people may have missed it.

**Comment by icefoxen** [comment]
Aw yes, I am excited.

**Comment by icefoxen** [comment]
Done!  Thank you for the heads up.
