### ISSUE TITLE
Easy mirror functions for X and Y axis might be nice.

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#531]
Basically as part of `DrawParam`, probably.  Just a convenience.

**Comment by Ben-PH** [comment]
This might be a literal first issue for me. Are you able to give a bit of context for use-case, desired outcome, how it might be demo'd in an example, etc.?

**Comment by nobbele** [comment]
I tried implementing this, but it was harder that it looked. Flipping is easy but mirroring would need to readjust the position or something.

**Comment by icefoxen** [comment]
Yeah the sticky part is you have to have to move the X position based on the size of the thing you're drawing.  Maybe not a great idea after all, with ggez's current drawing model.
