### ISSUE TITLE
Wrong scaling when drawing

### ISSUE THREAD

**Issue by Givralix** [ggez/ggez#535]
When drawing my 16x16 sprites, they instead appear as 27x27. Is there any way around this?

**Comment by icefoxen** [comment]
Check the return value of https://docs.rs/ggez/0.5.0-rc.0/ggez/graphics/fn.hidpi_factor.html and see the docs attached to that. Letting you adjust/remove the hidpi scaling is on the menu , see the last couple posts in #391 . Doing it Right is just got to be a minor subproject of its own.

**Comment by Givralix** [comment]
I didn't take hidpi into account, thank you very much! hidpi_factor() returns 1.0 but os_hidpi_factor() returns 1.66666 which matches the upscale I noticed. I wish you luck figuring out a solution!!

**Comment by icefoxen** [comment]
Should be fixed in the devel branch now, please check it and see if it works!

**Comment by icefoxen** [comment]
Closing. See #587 for basically the reason why.
