### ISSUE TITLE
0.5 winit Linux and Imgui.

### ISSUE THREAD

**Issue by Catvert** [ggez/ggez#536]
Hi !
First of all, thank you for your work, this library is a real pleasure to use.
I've tried the new 0.5 rc on my Linux machine but winit failed to compile. This is the error : 
`
error[E0004]: non-exhaustive patterns: `Shape { .. }` and `Orientation { .. }` not covered
  --> ...winit-0.18.0/src/platform/linux/wayland/touch.rs:30:19
   |
30 |             match evt {
   |                   ^^^ patterns `Shape { .. }` and `Orientation { .. }` not covered
`
I have another question, I have for a while now made a fork to be able to access the gfx_context property of the Context struct from my game. Indeed, Imgui needs to access to initialize itself(the renderer..) with various information such as the factory, the screen_render_target, informations about the device... Do you think you will make these attributes public? Why did you only allow a "crate" access to gfx_context? I think that having the possibility to use Imgui is a real advantage for GGEZ (and according to my tests, it works very well!)

Thanks for your help,
Catvert.

**Comment by Catvert** [comment]
Wow that's really great ! I didn't know there were functions like this one, it's very interesting! it solves my problem. I leave this ticket open for the other problem with the winit compilation. In any case, thank you for your help and your quick answer!

**Comment by sunjay** [comment]
It's fixed!

**Comment by Catvert** [comment]
Nice ! 
Thanks all ! :)
