### ISSUE TITLE
Streaks and double images in move to 5.0

### ISSUE THREAD

**Issue by RGates94** [ggez/ggez#537]
In moving my project to ggez 5.0, some graphical issues arose, particularly, a "streaking" effect and a "double image" effect as shown below
![image](https://user-images.githubusercontent.com/21347614/50729009-93de4380-1100-11e9-989a-7ed63cb4b97b.png)
The streaking seems to effect all Drawables, and the doubling effect seems to occur only for images specifically.

I was also able to reproduce the effect in the astroblasto example.

![image](https://user-images.githubusercontent.com/21347614/50729050-2252c500-1101-11e9-9ff4-ba8aa2413ef0.png)

I am running Windows 10 with a NVIDIA GeForce GTX 980M graphics card.

**Comment by icefoxen** [comment]
Cannot reproduce on Windows 10 with an AMD RX 480.  Didn't really expect to.

...but I ALSO can't reproduce on Windows 10 with an NVidia GTX 960M graphics card, which is much weirder.  This is using NVidia driver version 391.25.  Could you please check which driver version you're running, and if possible update it and see what happens?  The driver version is printed as part of the output of the `logging` example, something like: "Actually got: Driver vendor: NVIDIA Corporation, renderer GeForce GTX 960M/PCIe/SSE2, version 3.2.0, **NVIDIA 391.25** ..."

**Comment by icefoxen** [comment]
Synopsis of talk on discord: can't reproduce, and get *heckin weird* other bugs when we try.  :-(
