### ISSUE TITLE
Scale starts correct then becomes wrong

### ISSUE THREAD

**Issue by DanCardin** [ggez/ggez#539]
With the following draw code
```
    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        self.generate_image(self.camera.render(&self.world).as_ref());
        graphics::Image::from_rgba8(
            ctx,
            self.width as u16,
            self.height as u16,
            self.image_buffer.as_ref(),
        )?
        .draw(ctx, DrawParam::default())?;
        Ok(())
    }
```

And no changing state, I see
<img width="603" alt="screen shot 2019-01-09 at 2 58 51 pm" src="https://user-images.githubusercontent.com/701548/50925210-a7025380-141f-11e9-9c28-97f57faf32dc.png">

This could be related to https://github.com/ggez/ggez/issues/535, however the fact that I see the correct scaling on the first frame made me think potentially not.

Same behavior on master/devel, but (what I thought was analagous) code on the latest crates published api works fine.

**Comment by icefoxen** [comment]
By "latest crates published api" you mean release `0.5.0-rc.0`?  `master` is only a couple commits ahead of that, and nothing that should touch drawing code.

Just to check whether #535 is involved, can you check what the return value of `os_hidpi_factor()` is?  Thanks.

**Comment by DanCardin** [comment]
Actually good point, I had just done `ggez = "*"`, which my bash scrollback tells me was `ggez v0.4.4`.

The result of `os_hidpi_factor()` is 2, which makes it seem related; except in that it draws the first frame at the correct (full screen) size.

**Comment by icefoxen** [comment]
`crate_version = "*"` is evil and you should never use it.  :-P  `ggez = "0.4"` is perfectly fine, and I try to take semver seriously.  It's fairly easy to dig into your `Cargo.lock` to see the exact version of a crate you're using, too.

HiDPI definitely is part of the issue but I've never quite seen something like this before.  What OS are you running this on?  In 0.4, the details are handled by SDL and I don't know exactly how they work.

Try toggling `allow_highdpi` to `false` in your `Conf`'s `WindowSetup` parameter and see if that changes anything?  Also try printing out any `Event`'s that contain `WindowEvent::Resized` and see if you're getting a resize event after the first frame that needs to be handled?

**Comment by DanCardin** [comment]
Running with `ggez v0.5.0-rc.0 (https://github.com/ggez/ggez.git?branch=devel#d455fd1e`, on osx mojave

I tried
```rust
            .window_mode(
                WindowMode::default()
                    .dimensions(width as f32, height as f32)
                    .hidpi(false),
            );
```

and printing out the resize event leads to:
```
os_hidpi_factor 2
resize 1024 768
resize 600 450
first draw
```
and i dont see any resizes after that.

**Comment by icefoxen** [comment]
Thanks.  This leads me to suspect that, well, `winit` creates the window at the size it's given, then resizes it instantly based on whatever `os_hidpi_factor` it thinks you should have.  Which is weird and annoying.

Are you handling `WindowEvent::Resized` at all?  Basically, after a resize you need to tell ggez what to do about it -- keep the same projection and just draw more of it, change the projection to scale the drawing to the new window size, etc.  See the `graphics_settings` example for how to do that.  You probably also want to start your `draw()` method with `ggez::graphics::clear()` if you're not already.

Keep me posted on whether this helps!  It'd be nice if we could make `winit` not do an unnecessary resize.

**Comment by isidornygren** [comment]
I'm having the same exact issue, running Mojave on a 2012 Macbook Pro.
I've tried adding 
`graphics::set_screen_coordinates(ctx, graphics::Rect::new(0.0, 0.0, width, height)).unwrap();` to the `resize_event` callback but to no avail (And I'm also clearing the graphics at the start of every draw call).

I recently updated to ggez v. `0.5.0-rc.0` from the latest stable release which worked fine for me.

**Comment by icefoxen** [comment]
Confirmed this issue on my own macbook, since I now have access to one.

**Comment by icefoxen** [comment]
Possibly related: https://github.com/tomaka/winit/issues/581  https://github.com/tomaka/winit/issues/663

From #615 and other discussion it becomes obvious that winit often resizes the window right after creation.  It sounds like an awkward situation of incomplete information: You can have two different monitors with DPI factors.  You don't always know when you create a window which monitor it will be created on.  So if you want to create a window with a given logical size, you have to create the window with a dummy size, find out which screen it is on, get the hidpi factor of that screen, then set the window to the right physical size for that scaling factor.

Yet another case where hidpi makes life way more awful for no reason.

**Comment by icefoxen** [comment]
But I'm dropping support for Mac, so.  :cry:
