### ISSUE TITLE
DrawMode constructors?

### ISSUE THREAD

**Issue by kaedroho** [ggez/ggez#546]
Just noticed the ``CustomLine``/``CustomFill`` options on ``DrawMode``. https://github.com/ggez/ggez/blob/master/src/graphics/types.rs#L374

Shame that these have to be separate options, could we instead make the "custom" ones the default and add constructors for a simple API?

I also think ``Line`` option should be renamed to ``Stroke`` as it can be used to represent the stroke around a shape that isn't a line.

Examples:

``DrawMode::fill()`` equivalent to ``DrawMode::Fill(FillOptions::default())``

``DrawMode::stroke(10.0)`` equivalent to ``DrawMode::Stroke(StrokeOptions::default().with_line_width(10.0))``

If someone wants custom behaviour, they can construct the ``DrawMode`` variant they want directly:

``DrawMode::Stroke(StrokeOptions::default().with_line_width(10.0).with_line_cap(LineCap::Round))``

Happy to carry out the work if you're happy with the change.

**Comment by icefoxen** [comment]
Sounds good to me, sure!

**Comment by icefoxen** [comment]
Fixed by #547 .
