### ISSUE TITLE
Split subsystems into multiple reusable crates

### ISSUE THREAD

**Issue by porky11** [ggez/ggez#550]
I like, how easy it is to get some graphics on the screen using ggez, but when trying to create some more complicated program I'm restricted by the design.
I could just use single components, but then I would just import a bunch of unnecessary dependencies.
The simplest way to solve this problem seems to be creating crates for the different subsystems (graphics, audio, etc.).

I also thought about some additions or changes to ggez to get work, what I want, but the needed changes seem to be too big. Instead a different engine using some of the same subsystems seems like a good option here.

The changes, I would like to make:

Instead of the trait `EventHandler`, which declares a bunch of methods, I prefer having a single function or trait method handling all events, stored as an Enum. I know I could just rewrite the run method or add a new version of run, which generates events, or define a version of `EventHandler`, which generates an event enum for each method. I already did that for some project.

The other problem is, I'm not able to get `context` as owned value. I always have to pass the state and the context around, but passing just one object around, which contains context and state seems preferable. Else it's not possible to use generic libraries, which let you pass a single reference around, because it cannot be generic over the reference type, because of lifetime issues. (the lifetime needs to be bound to the generic function, not to the generic type)

Additionally, some parts of the context should not be able to be accessed by the user because the engine already handles them correctly.
So instead of one context, there should be two contexts: One for functions, the user would use, (like drawing) and one for event handling (would store the events loop).

The run function would then almost look the same, but `Context` only contains the events_loop, but the state contains the part of the context, that implements drawing functions for example.

**Comment by ozkriff** [comment]
I'm concerned that splitting this simple engine into subcrates will increase the overall complexity of the system and may gradually turn it into Piston.

**Comment by porky11** [comment]
A first step could be to make the single subsystems usable without the need of a context.
But maybe I should just have another look at piston.

**Comment by icefoxen** [comment]
You don't need to use `EventHandler`, you can write your own event loop and do whatever you want in it, including get an owned `Context`.  See the `eventloop.rs` example.

In general, ggez isn't going to get broken into crates, since then finding the right crates makes life harder for the user.  I've spent too much time grappling with that issue while using `gfx` and such to ever do the same thing in my code.

**Comment by porky11** [comment]
I don't suggest making it harder for the user. The subsystems should just be imported like it's already done with types from winit for example.

**Comment by icefoxen** [comment]
So if the idea is to re-combine all the sub-crates together anyway, what is the gain of making separate crates?  The only part of `ggez` that actually does much more than wrap `rodio`, `glutin`, or such is the drawing layer and filesystem stuff, and I already have plans to pull those into separate crates sooner or later.

**Comment by porky11** [comment]
The main reason for my purposes would be the graphics wrapper. So if you already intent to split it off into a seperate crate, that's already fine.

**Comment by icefoxen** [comment]
Ah, that makes sense then.  It's really probably not going to happen any time terribly soon, and will be a bit of an experiment, but when it happens it will happen [here](https://crates.io/crates/ggraphics).
