### ISSUE TITLE
Bad screen offset on MacOS

### ISSUE THREAD

**Issue by lowczarc** [ggez/ggez#553]
When compiling the example `astroblasto` with `rust 1.31.1` and `ggez 0.5.0-rc.0` I have the following results:

On MacOS Sierra (iMac 27-inch, Late 2012):
![](https://user-images.githubusercontent.com/33480665/51331147-57540580-1a79-11e9-8b84-39a4ed8065fe.png)

And on MacOS High Sierra (MacBook pro 13-inch, 2018):
![](https://user-images.githubusercontent.com/33480665/51331208-7fdbff80-1a79-11e9-8794-2924733e6e1f.png)

I also tried the other examples and a personal project, same results.

Feel free to ask me if you need more informations.

**Comment by icefoxen** [comment]
Thanks.  Can you please tell me what the result is of calling [`graphics::os_hidpi_factor()`](https://docs.rs/ggez/0.5.0-rc.0/ggez/graphics/fn.os_hidpi_factor.html) on both platforms?

Maybe related: #539, #439

**Comment by lowczarc** [comment]
MacOS Sierra (iMac 27-inch, Late 2012) returns 1.0
And MacOS High Sierra (MacBook pro 13-inch, 2018) returns 2.0

**Comment by zaynetro** [comment]
I can confirm the same weird behaviour on macOS Mojave in examples. Use code from https://github.com/ggez/ggez/commit/1de12cd15ca7dc119b5aa1be1bd3cefb6c8035fe commit.

## Source

This is the minimal example that reproduces the issue:

```rust
use ggez::event;
use ggez::graphics;
use ggez::timer;
use ggez::{Context, GameResult};

use std::u32;

struct App {
    frames: u32,
}

impl App {
    fn new(_ctx: &mut Context) -> GameResult<Self> {
        let app = Self { frames: 0 };
        Ok(app)
    }
}

impl event::EventHandler for App {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());

        let (w, h) = graphics::size(ctx);
        let bounds = graphics::Rect::new(0.0, 0.0, w as f32, h as f32);
        let white_rect = graphics::Mesh::new_rectangle(
            ctx,
            graphics::DrawMode::fill(),
            bounds,
            graphics::WHITE,
        )?;

        let coords = graphics::screen_coordinates(ctx);
        let black_rect = graphics::Mesh::new_rectangle(
            ctx,
            graphics::DrawMode::fill(),
            coords,
            graphics::BLACK,
        )?;

        graphics::draw(ctx, &black_rect, graphics::DrawParam::default())?;
        graphics::draw(ctx, &white_rect, graphics::DrawParam::default())?;
        graphics::present(ctx)?;

        self.frames += 1;
        if (self.frames % 500) == 0 {
            println!("FPS: {}", ggez::timer::fps(ctx));
            println!("bounds: {:?}", bounds);
            println!("coords: {:?}", coords);
            let info = graphics::renderer_info(ctx)?;
            println!("info: {}", info);
            println!("HIDPI: {}", graphics::hidpi_factor(ctx));
        }

        timer::yield_now();

        Ok(())
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("rect_macos", "zaynetro")
        .window_mode(
            ggez::conf::WindowMode::default()
                // .dimensions(600.0, 500.0)
                .hidpi(false)
                .resizable(true),
        )
        .modules(ggez::conf::ModuleConf {
            gamepad: false,
            audio: true,
        });
    let (ctx, event_loop) = &mut cb.build()?;

    let app = &mut App::new(ctx)?;
    event::run(ctx, event_loop, app)
}
```

## Logs:

```
FPS: 122.84684794029447
bounds: Rect { x: 0.0, y: 0.0, w: 800.0, h: 622.0 }
coords: Rect { x: 0.0, y: 0.0, w: 800.0, h: 600.0 }
info: Requested OpenGl 3.2 Core profile, actually got Driver vendor: Intel Inc., renderer Intel Iris OpenGL Engine, version 4.1, INTEL-12.4.7, shading language 4.10.
HIDPI: 1
FPS: 146.60467243751526
bounds: Rect { x: 0.0, y: 0.0, w: 503.0, h: 413.0 }
coords: Rect { x: 0.0, y: 0.0, w: 800.0, h: 600.0 }
info: Requested OpenGl 3.2 Core profile, actually got Driver vendor: Intel Inc., renderer Intel Iris OpenGL Engine, version 4.1, INTEL-12.4.7, shading language 4.10.
HIDPI: 1
FPS: 111.11311114711174
bounds: Rect { x: 0.0, y: 0.0, w: 1079.0, h: 687.0 }
coords: Rect { x: 0.0, y: 0.0, w: 800.0, h: 600.0 }
info: Requested OpenGl 3.2 Core profile, actually got Driver vendor: Intel Inc., renderer Intel Iris OpenGL Engine, version 4.1, INTEL-12.4.7, shading language 4.10.
HIDPI: 1
```

## And screenshots

Initial window size: rect is already way off

<img width="802" alt="image" src="https://user-images.githubusercontent.com/627197/52896922-d8b4ca00-31d6-11e9-898d-ca67cfdf8730.png">

Resizing to a smaller window:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/627197/52896940-fa15b600-31d6-11e9-84ad-5ad7378478d6.png">


Resizing to a bigger window:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/627197/52896969-4f51c780-31d7-11e9-9ef6-5dd1a7c46b9c.png">

## Summary

It is not possible to make a rect larger by specifying larger width and height. Let me know if you'd like to know more details.

Adding a call to `set_screen_coordinates` fixes the issue of `coords` not changing on resize. The rect still only takes part of the screen.

```rust
    fn resize_event(&mut self, ctx: &mut Context, width: f32, height: f32) {
        println!("Resized screen to {}, {}", width, height);
        let new_rect = graphics::Rect::new(0.0, 0.0, width, height);
        graphics::set_screen_coordinates(ctx, new_rect).unwrap();
    }
```

Thanks for your effort!

**Comment by hughlang** [comment]
Hello. Another interesting fact is that the screen scaling problem doesn't happen when you specify 1024x768 window size. It draws the screen out normally. However, if you specify 800x600, it presents a window of the correct size, but the drawable area is scaled down to 800/1024 (0.78125) of window space. Also note that the mouse coordinate system is still accurate. 

It calls the window resize_event twice like this:
```
graphics::os_hidpi_factor: 2
resize_event w=1024 h=768
resize_event w=800 h=600
```
Here's a screenshot:
![image](https://user-images.githubusercontent.com/1090765/53021223-b4e7c300-3426-11e9-9582-2b31f197396c.png)

**Comment by hughlang** [comment]
I believe this is the line that causes the problem:

https://github.com/ggez/ggez/blob/08680af63de9d9aa4161bfe9a59275658a2f7476/src/context.rs#L121

I debugged this for a while, and it seems that this call to resize doesn't work well on macos. Here's a debug printout inside the process_event function. For no particular reason, it assumes my screen size is 1024x768, but my WindowMode dimensions are set to 800x600 like in the gist above. 

```
graphics::os_hidpi_factor: 2
process_event WindowEvent { window_id: WindowId(Id(140329700330864)), event: HiDpiFactorChanged(2.0) }
process_event WindowEvent { window_id: WindowId(Id(140329700330864)), event: Resized(LogicalSize { width: 1024.0, height: 768.0 }) }
resize_event w=1024 h=768
process_event WindowEvent { window_id: WindowId(Id(140329700330864)), event: Resized(LogicalSize { width: 800.0, height: 600.0 }) }
resize_event w=800 h=600
```

If there's a good reason to call `self.gfx_context.resize_viewport();` for some OS versions, then it should check that the WindowMode and the actual size before doing it. I commented it out, and everything works at any resolution I tried.

**Comment by tinaun** [comment]
right now, ggez spawns a winit window with the default size of 1024 x 768, then resizes it. passing the width and height to the window builder directly gets around the weird resizing issues, so at least the "i don't need to resize my window ever" cases can work.

it does't fix the core issue. resizing on macos seems to be inverted vertically somehow, but i have a hard time figuring out how exactly that happens

**Comment by icefoxen** [comment]
Odd that it spawns a window and then instantly resizes it; I sorta suspect that's a winit behavior, or perhaps a `gfx_window_glutin` thing, since all the window building should just happen here: https://github.com/ggez/ggez/blob/master/src/graphics/mod.rs#L230-L255  .  It's called here: https://github.com/ggez/ggez/blob/master/src/graphics/context.rs#L132-L147 and I don't see any obvious place a resize event would get triggered after it by ggez.

**Comment by tinaun** [comment]
when ggez creates a window builder it doesn't set the resolution, so the windowbuilder chooses a default of 1024 x 768 and `init` creates the initial buffers at that size.

**Comment by icefoxen** [comment]
...shoot, you know, I think you're right.  Well that's a bug.

**Comment by mcbernie** [comment]
I can see a likely similar issue on X11 (armbian, ARMv7) with openGLEs 3.2.

the same application on macOS with OpenGL 3.2 does the strange resizing thing and on X11 the application does no content resizing on window resize.

I currently build a direct 'gfx shader drawing think' like in cube.rs example. on top I draw some circles and a simple text directly in ggez. the direct gfx content resized correctly on macOS and the ggez thinks make the strange resizing. 

on X11 (opengles 3.2) no content get resized on window size changing. 

general it sounds like the ggez default shader program does something wrong, on resizing, (ex. the projection matrix). also i think that on gfx or winit is something wrong with setting the viewport size or something else...

I still investigate the issue and hope that I find a solution.

**Comment by icefoxen** [comment]
@mcbernie For your own content resizing on X11, look at the `graphics_settings` example and see if that solves the problem, you have to tell ggez that the viewport size has changed with `graphics::set_screen_coordinates()` if you're not already.

**Comment by mcbernie** [comment]
@icefoxen I already have the `graphics::set_screen_coordinates()` in the resize event. but no resize happens. I can also see that the 

I tried the gfx cube example this works like it should.

**Comment by icefoxen** [comment]
I'm dropping support for Mac, so.  :cry:
