### ISSUE TITLE
(0.5 feedback) There're still some non-mint types in the API

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#568]
They can be found with: https://docs.rs/ggez/0.5.0-rc.0/ggez/?search=Point2 and https://docs.rs/ggez/0.5.0-rc.0/ggez/?search=Matrix4 :

- `ggez::graphics::Rect::point` (field and getter)
- `ggez::graphics::Rect::move_to`
- `ggez::graphics::Rect::contains`

-----

- `ggez::input::mouse::position`
- `ggez::input::mouse::set_position`
- `ggez::input::mouse::delta`

------

- `ggez::graphics::mul_transform`
- `ggez::graphics::set_transform`
- `ggez::graphics::mul_projection`
- `ggez::graphics::push_transform`
- `ggez::graphics::set_projection`
- `ggez::graphics::DrawParam::to_matrix `
- `ggez::graphics::transform`
- `ggez::graphics::projection`

Related to #344

**Comment by icefoxen** [comment]
Should be fixed but needs verification.

**Comment by ozkriff** [comment]
Still exposed nalgebra types that I've found:

- set_transform
- transform
- DrawParam::to_matrix
- DrawParam: dest, scale, offset

**Comment by icefoxen** [comment]
Yeah not sure what to do about the innards of `DrawParam` now that they're exposed to the outside world again.  Or I wasn't sure last night.  Now that it's a new day and I'm basically snowed in, it's obvious they should be `mint` types 'cause if we leave them as `nalgebra` types then anyone who touches them has to use the exact same version of `nalgebra` that ggez does.

That's gonna be annoying.  Oh well.

**Comment by icefoxen** [comment]
Should be fixed... again.

**Comment by icefoxen** [comment]
@ozkriff Can you confirm?  You seem to be better at actually finding these details than I.  XD

**Comment by ozkriff** [comment]
Everything seems to be `mint`ified now, yay :)

> You seem to be better at actually finding these details than I. XD

It's basicly because [good-web-game](https://github.com/not-fl3/good-web-game) uses cgmath internally)

**Comment by nobbele** [comment]
shouldn't ggez::graphics::drawable_size return a mint type

**Comment by ozkriff** [comment]
a tuple of f32 isn't a part of any algebra library, so this sounds like another issue
