### ISSUE TITLE
(0.5 feedback) Text::dimensions height behavior changed

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#569]
Was that intentional? What is the reasonong? It breaks Zemeroth's UI code, because I'm scaling labels and buttons to 1/12th of the screen's height.

GGEZ v0.4 vs v0.5:

![image](https://user-images.githubusercontent.com/662976/51888356-e16c6a00-23a7-11e9-9ccc-e6a799d484a8.png) ![image](https://user-images.githubusercontent.com/662976/51888394-fd700b80-23a7-11e9-9427-e2193e9b724b.png)

If it was intentional, is there another method to get "old-fashined" bounding box of the text?

**Comment by icefoxen** [comment]
My first guess is that it is due to winit's hidpi functionality lying about how big the display is.  If the result of `graphics::os_hidpi_factor()` is >1.0 then that is probably it.

In general this isn't intentional, if we need to fix the text bounding box code to be accurate then we should do that.

**Comment by ozkriff** [comment]
No, that's definitely not a HDPI problem. Here's a screenshot with both versions overlapping.

![image](https://user-images.githubusercontent.com/662976/52166703-b2e0ed00-2721-11e9-9093-3bbbeb1ea54c.png)

Strings with descender parts in them ("strength:", etc) are of the same size and strings like "moves:" clearly has less pixels in them (and thus they looks bigger when scaled to the same screen height).

> In general this isn't intentional, if we need to fix the text bounding box code to be accurate then we should do that.

Ok, I'll try to look into the code.

**Comment by icefoxen** [comment]
Wow. Yeah that looks awful. Good call on noticing the descender and ascender parts are what make it different. I expect that we're just using the wrong font metrics for sizing somewhere. I will work on this as well, if we can't find it in a few days we might just want to ask for help from alexheretic.

**Comment by ozkriff** [comment]
So, I've experimented a little bit with this and the solution to bring the old behaviour for oneliners is:

```diff
     fn calculate_dimensions(&self, context: &mut Context) -> (u32, u32) {
         let mut max_width = 0;
         let mut max_height = 0;
         {
             let varied_section = self.generate_varied_section(Point2::new(0.0, 0.0), None);
+            for section in &varied_section.text {
+                let h = section.scale.y.ceil() as _;
+                if h > max_height {
+                    max_height = h;
+                }
+            }
             use glyph_brush::GlyphCruncher;
             let glyphs = context.gfx_context.glyph_brush.glyphs(varied_section);
```

This works for Zemeroth's gui at least.

**But** it doesn't adress multiline Text, like "test\ntext" and "test\njjj" still have different height.

**Comment by ozkriff** [comment]
Here's an updated patch (thanks, @not-fl3!) that seems to work for multiline Text:

```diff
diff --git a/src/graphics/text.rs b/src/graphics/text.rs
index bd66dc2..6763343 100644
--- a/src/graphics/text.rs
+++ b/src/graphics/text.rs
@@ -320,16 +320,16 @@ impl Text {
             let glyphs = context.gfx_context.glyph_brush.glyphs(varied_section);
             for positioned_glyph in glyphs {
                 if let Some(rect) = positioned_glyph.pixel_bounding_box() {
-                    if rect.max.x > max_width {
-                        max_width = rect.max.x;
-                    }
-                    if rect.max.y > max_height {
-                        max_height = rect.max.y;
-                    }
+                    let font = positioned_glyph.font().expect("Glyph doesn't have a font");
+                    let v_metrics = font.v_metrics(positioned_glyph.scale());
+                    let max_y = positioned_glyph.position().y + positioned_glyph.scale().y - v_metrics.ascent;
+                    let max_y = max_y.ceil() as u32;
+                    max_width = std::cmp::max(max_width, rect.max.x as u32);
+                    max_height = std::cmp::max(max_height, max_y);
                 }
             }
         }
-        let (width, height) = (max_width as u32, max_height as u32);
+        let (width, height) = (max_width, max_height);
         if let Ok(mut metrics) = self.cached_metrics.try_borrow_mut() {
             metrics.width = Some(width);
             metrics.height = Some(height);
```

What do you think? I can make a PR if this change seems fine to you.

**Comment by icefoxen** [comment]
Can't reproduce?  What am I doing wrong?

![image](https://user-images.githubusercontent.com/1335133/53305709-c2e87a00-3852-11e9-9285-73cbbbad1903.png)

The code is just:

```rust

        let t1 = Text::new(TextFragment::new("test\ntext"));
        let t2 = Text::new(TextFragment::new("test\njjj"));
        let t3 = Text::new(TextFragment::new("asdfjpgklti"));
        graphics::queue_text(
            ctx,
            &t1,
            Point2::new(0.0, 0.0),
            None,
        );
        graphics::draw_queued_text(
            ctx,
            DrawParam::new()
                .dest(Point2::new(400.0, 400.0))
        )?;
        graphics::queue_text(
            ctx,
            &t2,
            Point2::new(30.0, 0.0),
            None,
        );
        graphics::draw_queued_text(
            ctx,
            DrawParam::new()
                .dest(Point2::new(400.0, 400.0))
        )?;
        
        graphics::queue_text(
            ctx,
            &t3,
            Point2::new(60.0, 0.0),
            None,
        );
        graphics::draw_queued_text(
            ctx,
            DrawParam::new()
                .dest(Point2::new(400.0, 400.0))
        )?;
```

**Comment by icefoxen** [comment]
@ozkriff  What's the best way to confirm that this works now?  I want to write unit tests but I never figured out how to reproduce this.

**Comment by ozkriff** [comment]
> Can't reproduce? What am I doing wrong?

In Zemeorth's case, the text is scaled to always be 1/10 of a window's height.

> What's the best way to confirm that this works now?

The simplest thing to do is just to check that the height of "strength" and "moves" strings is the same, I guess.

**Comment by icefoxen** [comment]
Unit test added in ebc7d5c , finally!  Thank you for all your help.
