### ISSUE TITLE
ggez won't compile with rustc 1.32.0

### ISSUE THREAD

**Issue by willtunnels** [ggez/ggez#571]
Ggez won't compile with rust 1.32.0.
![image](https://user-images.githubusercontent.com/24933217/51945289-26f25c80-23d3-11e9-8d3e-a9f671482b12.png)
I've been having this issue since 1.32.0 was released but so far I've been working around it by compiling with rustc 1.31.0.

**Comment by ozkriff** [comment]
See https://github.com/ggez/ggez/issues/558

**Comment by willtunnels** [comment]
Thanks for the quick reply.
