### ISSUE TITLE
setVolume method for audioSource works only after play()

### ISSUE THREAD

**Issue by fedor-rusak** [ggez/ggez#573]
Environment: Win10

So I made repeatable sound for background noise and added sound of movement that was too loud for my taste.

I decided to setVolume for step sound  during initialization (reading sound file)... and it changed nothing.

But when I added setVolume right AFTER play() it made the required change.

Is it intentional?

**Comment by icefoxen** [comment]
Note to self: Should be fixed in #584.  Verify, unit test, then close.

**Comment by fedor-rusak** [comment]
Updated my project to use latest version from repo. Stumbled upon requirement to use trait SoundSource.

Added it and now set_volume works as intended before actual sound playing!

Should I close the issue?

**Comment by icefoxen** [comment]
Glad it works! I'm leaving this open until we have better tests for now, to make sure things don't backslide later.

**Comment by sampullman** [comment]
There are a couple unit tests, eventually there might be an overhaul if CI can be improved to handle integration testing. Until then I think it makes sense to close older issues like this.
