### ISSUE TITLE
Any plans to support textedit?

### ISSUE THREAD

**Issue by alanpoon** [ggez/ggez#575]
Any plans to support textedit?

**Comment by icefoxen** [comment]
You're going to have to be more specific about what you mean by "textedit", I'm afraid.

**Comment by alanpoon** [comment]
i am refering to textbox for input

**Comment by icefoxen** [comment]
No, a GUI library is not a priority. Having a 3rd party crate that draws a GUI using ggez is entirely possible though.

**Comment by icefoxen** [comment]
The only actual GUI library I know of so far though is this: https://github.com/ozkriff/zemeroth/tree/master/ggwp-zgui
