### ISSUE TITLE
Use of u16 indices causes `attempt to subtract with overflow` panic

### ISSUE THREAD

**Issue by gabrielecirulli** [ggez/ggez#576]
Hey, I just wanted to give you a heads-up about an issue I encountered while attempting to render a very large grid of individual squares using a MeshBuilder. I initially posted this issue over at [nical/lyon](https://github.com/nical/lyon/issues/440) (including code and reproduction steps, see link) because that's where the panic originated, but it seems to have to do with the way ggez interfaces with lyon and, while I'd been using 0.4, it seems to affect version 0.5.0, too.

I won't make my explanation long here because The issue I posted on lyon and @nical's explanations are already very eloquent. Please have a look here: https://github.com/nical/lyon/issues/440, and specifically at @nical's last post on the issue: https://github.com/nical/lyon/issues/440#issuecomment-460073482

Hope this helps. Thank you for ggez!

**Comment by icefoxen** [comment]
Awesome, thank you!  Entertainingly, #574 was created just recently due to an unrelated conversation elsewhere.  I like nical's suggestion of having it give an error when trying to generate too many indices though, I'll see if I can do that.

**Comment by nical** [comment]
Better error handling around this issue in lyon is implemented in https://github.com/nical/lyon/pull/445 which will be in the next release, probably in a week or so.
After that you will just have to check the returned error and handle `TessellationError::TooManyVertices`.
