### ISSUE TITLE
macOS unsupported due to glirs

### ISSUE THREAD

**Issue by pamarcos** [ggez/ggez#577]
According to the documentation, `ggez` fully supports macOS. However, I tried to run the examples from master but I got the following error in all of them:

`Error: GamepadError("Gamepad error: Gilrs does not support current platform.")`

Examples in tag `0.4` do work correctly, though. Seems [gilrs](https://gitlab.com/gilrs-project/gilrs) has never supported macOS according to the following table in their README:

Supported features
------------------
|                  | Input | Hotplugging | Force feedback |
|------------------|:-----:|:-----------:|:--------------:|
| Linux            |   ✓   |      ✓      |        ✓       |
| Windows (XInput) |   ✓   |      ✓      |        ✓       |
| OS X             |   ✕   |      ✕      |        ✕       |
| Emscripten       |   ✕   |      ✕      |       n/a      |
| Android          |   ✕   |      ✕      |        ✕       |

There is an issue opened to add macOS support, but it has not been resolved yet https://gitlab.com/gilrs-project/gilrs/issues/58

So, is there any way to opt out of `glirs` in macOS to use the rest of the library?

**Comment by icefoxen** [comment]
Sorry for the misleading docs.  There needs to be an option to opt out of `gilrs`, which isn't hard but doesn't exist yet.  Tracking here: #501

**Comment by icefoxen** [comment]
man, I feel dumb.  I read right past what your question was actually asking until I went back and started workin on this more.  I didn't realize that gilrs would build on mac but panic at runtime.  That's *easy* to fix, you just disable the gamepad module:

```rust
pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("super_simple", "ggez")
        .modules(ggez::conf::ModuleConf {
            gamepad: false,
            audio: true,
        });
    let (ctx, event_loop) = &mut cb.build()?;
    let state = &mut MainState::new(ctx)?;
    event::run(ctx, event_loop, state)
}
```

**Comment by icefoxen** [comment]
we should make `gamepad: false` the default on macos.

**Comment by icefoxen** [comment]
Should be fixed but needs verification.

**Comment by pamarcos** [comment]
It works for me now, thanks a lot 😃 . Should I close the issue or will you close it yourself?

**Comment by icefoxen** [comment]
Either way works.  :)  Thank you!
