### ISSUE TITLE
(0.5 feedback) Text::dimensions should return Rect, not (u32, u32)

### ISSUE THREAD

**Issue by ozkriff** [ggez/ggez#583]
Atm, `fn calculate_dimensions` can't return a bbox with a negative offset which results in a wrong left border of the bounding box when, for example, we're rendering letter "j" with a "Tangerine_Regular.ttf" font:

![image](https://user-images.githubusercontent.com/662976/52766380-0a435f00-3038-11e9-9dfe-984f8202e7ea.png)

This wasn't intentional, right?

**Comment by icefoxen** [comment]
I'm going to need to dig up one of those font metrics diagrams with all the possible offsets, aren't I. XD

That said, do you want the full bounding box of the glyph, or do you want the distance between the start of one letter and the next where they intersect with the text's baseline?

**Comment by ozkriff** [comment]
> do you want the full bounding box of the glyph, or do you want the distance between the start of one letter and the next where they intersect with the text's baseline?

The former I guess.

**Comment by Manghi** [comment]
I would also prefer the former (full bounding box) as that would be the expectation when working with monospaced fonts.

**Comment by bertin0** [comment]
I am trying to make a simple text editor and i'm struggling to figure out the width of a character too (for a monospaced font). I'm not familiar with fonts but could anyone give me a quick solution on finding the right width? I've been struggling to find a relationship between the height and the actual width.

**Comment by Manghi** [comment]
@bertin0

The averaging approach seems to be working for us for a monospaced font:
```Rust
let text = "xxxxxxxxxx"; // 10 arbitrary characters
let text_fragment = TextFragment::new(text)
    .scale(scale)
    .font(font);
let graphics_text = Text::new(text_fragment);
let char_dimensions = Vector2::new(
    graphics_text.width(ctx) as f32 / text.len() as f32,
    graphics_text.height(ctx) as f32
);
```

Any time we need to account for the dimensions of a character we use the `char_dimensions`. That way we don't have to (re)calculate the `width` and `height`.

**Comment by bertin0** [comment]
Thanks for replying. I have used a similar solution, but used `"x".repeat(precision)` for an arbitrary precision.
