### ISSUE TITLE
Broken link in in Windows build instructions

### ISSUE THREAD

**Issue by Ben-PH** [ggez/ggez#585]
Doc file https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md links to https://raw.githubusercontent.com/ggez/ggez/master/examples/hello_world.rs, which is broken for me.

A trivial fix, I imagine. I'll be forking soon - fixing this will be the first thing I do.

**Comment by icefoxen** [comment]
Already fixed in 1fe813d!  Thank you.  There's some other things in that file that need fixing that take a bit more double-checking though, if you're still interested.
