### ISSUE TITLE
Shader Generic over multiple Uniforms?

### ISSUE THREAD

**Issue by ducharmemp** [ggez/ggez#594]
Currently it seems like there's only the ability to pass in one uniform (unless I'm reading the examples and code incorrectly, in which case feel free to close this immediately!), but it would nice to be able to gfx_defines!  multiple uniforms and send them in one shot to the shader, instead of requiring multiple passes. I know I could drop to the gfx context in the Context object, is there a nice-ish way to achieve this in ggez?

**Comment by icefoxen** [comment]
That's a good question, but I'm not entirely sure what you mean.  You can put multiple `constant` definitions in a single `gfx_defines!` block, pretty much all `gfx_defines!` does is define a struct and some marker traits and stuff in a particular layout, IIRC.  You can define a struct that bundles together a set of multiple uniforms and just shove that into your shader, which seems equivalent to passing multiple uniforms to the shader at a time.  :man_shrugging: ?

Sorry, I'm a little dense in the mornings.

**Comment by ducharmemp** [comment]
I think I was really asking the wrong question, yesterday was a long day without much progress and I'm recovering from the flu. Instead of asking "how do I send a stuct with multiple uniforms" I should have asked "how do I send an array of structs, or a struct of arrays". I took a look at your shadows example and was wondering how I would be able to send in all lights at once, rather than shade light by light. I'm not sure it's possible after going through the gfx-rs issue list and documentation but I'm hopeful that someone more knowledgeable than me can chime in :) .

**Comment by PSteinhaus** [comment]
This situation has improved with the wgpu-transition as well.
You can now use `Canvas::set_shader_params` with `ShaderParams` including multiple uniforms, packed into one struct that satisfies `AsStd140`.
