### ISSUE TITLE
OpenGLES 3.0 Shader - whitespace before version

### ISSUE THREAD

**Issue by mcbernie** [ggez/ggez#599]
Try to run a simple  ggez v0.5.0-rc.1 example on an Armv7 with Mali openGLES 3.0 but got an error on compile Vertex shader caused of an whitespace right before the version tag

after removing the firstline in 
https://github.com/ggez/ggez/blob/08680af63de9d9aa4161bfe9a59275658a2f7476/src/graphics/shader/basic_es300.glslv#L1

ggez runs on ARMv7 (asustinkerboard s) with X11 an OpenGLES 3.0

**Comment by icefoxen** [comment]
Thank you for the PR, and it's awesome to hear it works on Real Hardware!  I can only test on my desktop NVidia graphics card, which either accepted the blank line just 'cause, or that blank somehow snuck in later.
