### ISSUE TITLE
Check whether drawing functions are actually thread-safe

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#60]
They *should* be but there may be some sticky non-thread-safe context in the `Context` object that prevents this.  Find out for sure!

**Comment by onelson** [comment]
I'm using channels to emit sets of draw call parameters from inside Specs systems... I tick the ECS in `update()` and then drain any of the resulting draw instructions inside `draw()` via `rx.try_iter()`. Seems to work ok. Not sure drawing from multiple threads is going to work great.

https://github.com/onelson/OmnLabsRS/blob/master/src/main.rs#L57

**Comment by icefoxen** [comment]
Hmmm, it could actually work fine if you could put the `Context` object in a `Mutex` or such... but you wouldn't get much multithreading out of it.  For drawing from multiple threads to really be worth it we need multiple `Encoder`s, which will basically do the same process as what you're doing except a bit lower level (and thus less redundant).  That's not currently terribly feasible with Love2D's drawing API, alas, but it might eventually be doable with a `SpriteBatch`-like structure.

What about playing sounds?

**Comment by onelson** [comment]
Assuming rodio, I'd be using a similar approach - ECS systems emit messages on channels, which would be drained from the channel buffer in the main `draw()` call. I'd keep the sink up in the game state struct (where I keep my other assets) and use handles to the audio across the channel bounds.

Should help with managing lifetime issues on the audio too, just having it all live in that one layer of the codebase...

That's my initial thought anyway.

**Comment by icefoxen** [comment]
FYI the SoundData object contains an Arc'ed buffer and so should be easy to clone and share between threads.

**Comment by icefoxen** [comment]
Ok, so it's "thread safe" in that it won't let you do something dumb, but you can't actually do multithreaded drawing unless we have multiple `Encoder`'s somehow.  That might be something to consider with sprite batches (which would be metal as fuck) but it's not a concern for now.
