### ISSUE TITLE
mul_transform is applying transformations in the wrong order

### ISSUE THREAD

**Issue by hcff** [ggez/ggez#605]
ggez seems to be multiplying the transformation matrices in the wrong order. Or at least, it's not doing it the same way as LÖVE.

Specifically, at this line:
https://github.com/ggez/ggez/blob/master/src/graphics/mod.rs#L660
`gfx.set_projection(transform * curr);` should be `gfx.set_projection(curr * transform);`

Here's an example program in LÖVE:

```lua
function love.draw()
    love.graphics.push()
    love.graphics.translate(100, 0)
    love.graphics.rectangle("line", 10, 10, 80, 80)
    love.graphics.scale(2)
    love.graphics.rectangle("line", 10, 10, 80, 80)
    love.graphics.pop()
end
```
And a screenshot:
![love example](https://user-images.githubusercontent.com/42674143/54237120-85a00f80-4515-11e9-98a9-ce87053728f6.png)

In LÖVE, the scaling is applied after the translation. So the left side of the big square is `100 + 2*10`.

Translated into ggez, this gives:
```rust
use ggez::graphics::{self, Drawable};

fn main() -> ggez::GameResult<()> {
    let (mut ctx, mut event_loop) = ggez::ContextBuilder::new("my cool game", "me")
        .build()
        .unwrap();

    ggez::event::run(&mut ctx, &mut event_loop, &mut Game {})
}

#[derive(Debug)]
struct Game {}

impl ggez::event::EventHandler for Game {
    fn update(&mut self, _ctx: &mut ggez::Context) -> ggez::GameResult<()> {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut ggez::Context) -> ggez::GameResult<()> {
        let square = graphics::Mesh::new_rectangle(
            ctx,
            graphics::DrawMode::stroke(2.0),
            [10.0, 10.0, 80.0, 80.0].into(),
            graphics::WHITE,
        )?;

        graphics::clear(ctx, graphics::BLACK);

        graphics::push_transform(ctx, None as Option<[f32; 16]>);
        graphics::mul_transform(
            ctx,
            graphics::DrawParam::default()
                .dest([100.0, 0.0])
                .to_matrix(),
        );
        graphics::apply_transformations(ctx)?;

        square.draw(ctx, graphics::DrawParam::default())?;

        graphics::mul_transform(
            ctx,
            graphics::DrawParam::default().scale([2.0, 2.0]).to_matrix(),
        );
        graphics::apply_transformations(ctx)?;

        square.draw(ctx, graphics::DrawParam::default())?;

        graphics::pop_transform(ctx);
        graphics::apply_transformations(ctx)?;

        graphics::present(ctx)?;
        Ok(())
    }
}
```
This gives me:
![ggez example](https://user-images.githubusercontent.com/42674143/54236917-15918980-4515-11e9-80c9-dd6baf37e4a6.png)
Here, the square's scaling affected the translation. So the left side of the big square is at `2 * (100 + 10)`.
The equivalent love program to what ggez is doing would be:
```lua
function love.draw()
    love.graphics.push()
    love.graphics.translate(100, 0)
    love.graphics.rectangle("line", 10, 10, 80, 80)
    love.graphics.pop()

    love.graphics.push()
    love.graphics.scale(2)
    love.graphics.translate(100, 0)
    love.graphics.rectangle("line", 10, 10, 80, 80)
    love.graphics.pop()
end
```

I found that problem when I tried implementing a camera system in my game, and then scaled a Text, and the camera's translation of the text would end up being scaled too.

**Comment by icefoxen** [comment]
Thanks for noticing this!  It's an easy fix, naturally, but really we should make better tests for this stuff even if it's something that a human has to eyeball and verify.  

Honestly I'm considering taking out the transform stack entirely...  I never use it and sort of feel like it's extra complexity that is easy to replicate in an external library (http://github.com/ggez/ggez-goodies/ ?).  Have any opinions on the matter?

**Comment by danieljpetersen** [comment]
I personally like the functionality that the transform stack provides, there are situations where it is indeed useful.  I'm not the one having to maintain it though so take that however you will.

**Comment by StrixVaria** [comment]
I'm just starting to play around with ggez and the fact that DrawParams aren't a transformation stack already is really off-putting and weird. That's the one thing I think Piston does better than ggez right now; it's so easy to position things in Piston relative to each other but I can't find a good way to do it here.

**Comment by icefoxen** [comment]
Well then, we'll keep the transform stack and this issue needs fixing.  Thanks everyone who chipped in.
