### ISSUE TITLE
Window is resizable regardless of WindowMode field resizable (Linux X11)

### ISSUE THREAD

**Issue by gardrek** [ggez/ggez#613]
Setting the `resizable` field on `WindowMode` seems to have no effect on whether or not the window can be resized on my desktop (Linux, X11, Awesome WM). That is, it can be resized regardless of the setting. Setting max and min window dimensions to the same value is a workaround.

**Comment by icefoxen** [comment]
Thanks for the report!  I'll try it out and see what I find.

It appears that WM's are capable of causing problems with this, see the "platform specific" bits on https://docs.rs/winit/0.19.0/winit/struct.Window.html#method.set_resizable

**Comment by icefoxen** [comment]
Confirmed on Linux X11 using MATE.  That's annoying.  :-/

**Comment by 0x1793d1** [comment]
On x11 this is only a hint, and is mostly ignored on tiling window managers. But the issue occurs also on gnome.
