### ISSUE TITLE
Mesh corrupted on first present() (0.4.4)

### ISSUE THREAD

**Issue by mikekchar** [ggez/ggez#617]
I'm new to ggez (and Rust in general) and I ran into a bit of a weird issue.  I'm drawing a grid on my screen as a big mesh (just a bunch of lines built using MeshBuilder).  When I have a resize event, I call `graphics::set_screen_coordinates` and then I rebuild the mesh.  That way the grid boxes are the same size, but I have more of them.  Everything seemed completely fine and then I thought, "There is no need to constantly call `graphics::present()`.  I'll just call it when the model is dirty (and `timer::sleep()` otherwise).  So this means that in my code I literally only draw the mesh one time.

I discovered that the first time I render the mesh, it is corrupted (the lines exist, but they are in the wrong place -- sometimes off the window, etc).  However, after the first `graphics::present()` it renders perfectly.  There is no need to actually render the mesh before the first `graphics::present()` -- just calling it after building the mesh is enough to fix the problem.

I'm guessing the problem may have something to do with `set_screen_coordinates`, although the corrupted mesh isn't particularly logical (the lines are still horizontal and vertical, but they do not have even spacing).  I'll try to provide a minimal failing example on Monday, but I thought I would make an issue in case anyone fancied looking at it themselves (or if somebody already knows it's fixed in 0.5.0 -- I haven't had a chance to try it there).

**Comment by icefoxen** [comment]
Well that's an  interesting issue.  But you *do* need to call `graphics::present()`.  Otherwise no drawing happens at all, and if you are seeing something on your screen, it's likely to be uninitialized graphics card memory -- quite possibly an old image buffer from the last time you ran the program.  I've seen this happen before with NVidia cards in particular.

I look forward to seeing your code!  :grin:

**Comment by mikekchar** [comment]
Thanks for the quick response.  You have encouraged me to avoid my paying work and do this instead :-)  BTW, I just wanted to say thank you for such a great library.  I'm having lots of fun!  It's been a wonderful introduction to Rust.

I should have been more clear in my description, though.  I am drawing and then calling `graphics::present()` *once*.  I've played around a little bit more and I can't understand what's going on.  I won't speculate on what's going on any longer.  I'll put the code here.  I'm sorry it's so long.

Basically it draws a grid that fits the screen (off by one errors galore... sorry!)  When you resize the window it grows the grid (i.e. adds more boxes, not zoom).  It's hard to see the problem if you resize the window slowly, but if you can make it small and then maximize it, you should be able to see the problem.  The next frame it will draw the grid incorrectly.  I think "corrupt" is not the right word in retrospect.  It just seems to be drawing in the wrong place with the wrong coordinate system (and losing some lines probably because they are on weird boundaries).

I've made it so that every 3 seconds it redraws the screen and you will be able to see that the next time it redraws it fixes itself.

I said I wouldn't speculate, but I'm guessing that this has to do with the transform changing when the window is resized but the `device` not being reset.  The `graphics::present` resets the device and this fixes the problem.  I was unable to test that theory because I don't seem to be able to build ggez properly (just being thick about Rust projects, I'm afraid).

Hope this helps.  Feel free to ask me for anything.  I'm on the road for a few days (right now, in fact!) so I might not be able to respond right away, though.  Again, thanks for the library.  I'm really having a blast.

```
extern crate ggez;
use ggez::conf;
use ggez::event::{self, Keycode, Mod};
use ggez::{Context, GameResult};
use ggez::graphics::{self, Color, Mesh, MeshBuilder, Point2};
use std::env;
use std::path;

const GRID_SIZE: f32 = 30.0;

fn to_i(x: f32) -> usize {
    (x / GRID_SIZE) as usize
}

fn to_g(x: usize) -> f32 {
    x as f32 * GRID_SIZE
}

fn seconds(frames: u32, fps: u32) -> f64 {
    frames as f64 / fps as f64
}

fn grid_mesh(ctx: &mut Context, mut width: f32, mut height: f32) -> GameResult<Mesh> {
    let mut mb = MeshBuilder::new();

    if width < GRID_SIZE * 2.0 {
        width = GRID_SIZE * 2.0;
    }
    if height < GRID_SIZE * 2.0 {
        height = GRID_SIZE * 2.0;
    }

    let size = Point2::new(width - GRID_SIZE * 2.0, height - GRID_SIZE * 2.0);
    for x in 0..to_i(size.x)  {
        let top = Point2::new(to_g(x), 0.0);
        let bottom = Point2::new(to_g(x), size.y);
        mb.line(&[top, bottom], 1.0);
    }
    for y in 1..to_i(size.y) {
        let left = Point2::new(0.0, to_g(y));
        let right = Point2::new(size.x, to_g(y));
        mb.line(&[left, right], 1.0);
    }

    mb.build(ctx)
}

pub enum Event {
    Continue,
    Quit,
    Resize(u32, u32),
}

struct MainState {
    grid: Mesh,
    frames: usize,
    dirty: bool,
    event: Event,
}

impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let s = MainState {
            grid: grid_mesh(ctx, 0.0, 0.0)?,
            frames: 0,
            dirty: true,
            event: Event::Continue,
        };
        Ok(s)
    }
}


impl event::EventHandler for MainState {
    fn update(&mut self, ctx: &mut Context) -> GameResult<()> {
        const DESIRED_FPS: u32 = 60;
        let mut updated = false;

        // Determine how many frames have elapsed since we last got here
        while ggez::timer::check_update_time(ctx, DESIRED_FPS) {
            self.frames += 1;
        }

        // Update the screen at least every 3 seconds
        if (seconds(self.frames as u32, DESIRED_FPS)) > 3.0 {
            updated = true;
            self.frames = 0;
        }

        match self.event {
            Event::Resize(width, height) => {
                graphics::set_screen_coordinates(ctx, graphics::Rect::new(0.0, 0.0, width as f32, height as f32))?;
                self.grid = grid_mesh(ctx, width as f32, height as f32)?;

                // FIXME: If I don't do a present after building the mesh,
                // the first time it is drawn it is drawn incorrectly.
                // graphics::present(ctx);
                updated = true;
            },
            Event::Quit => {
                let _ = ctx.quit();
            }
            _ => (),
        }        self.event = Event::Continue;
        self.dirty |= updated;

        // If we aren't going to draw something, we need to sleep
        if !self.dirty {
            let duration = ggez::timer::f64_to_duration(seconds(1, DESIRED_FPS));
            ggez::timer::sleep(duration);
        }
        Ok(())
    }

    fn resize_event(&mut self, _ctx: &mut Context, width: u32, height: u32) {
        self.event = Event::Resize(width, height);
    }

    fn key_up_event(&mut self, _ctx: &mut Context, keycode: Keycode, _keymod: Mod, _repeat: bool) {
        if keycode == event::Keycode::Q {
            self.event = Event::Quit;
        }
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        if self.dirty {
            let color = Color::new(1.0, 1.0, 1.0, 1.0);
            graphics::clear(ctx);
            graphics::set_color(ctx, color.clone())?;
            graphics::draw(ctx, &self.grid, Point2::new(GRID_SIZE, GRID_SIZE), 0.0)?;

            self.dirty = false;
            graphics::present(ctx);
        }
        Ok(())
    }
}

pub fn main() {
    let c = conf::Conf::new();
    let ctx = &mut Context::load_from_conf("helloworld", "ggez", c).unwrap();

    if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        let mut path = path::PathBuf::from(manifest_dir);
        path.push("resources");
        ctx.filesystem.mount(&path, true);
    }

    let state = &mut MainState::new(ctx).unwrap();
    if let Err(e) = event::run(ctx, state) {
        println!("Error encountered: {}", e);
    } else {
        println!("Game exited cleanly.");
    }
}
```

**Comment by icefoxen** [comment]
Well, when I run your code on my laptop, I get nothing displaying at all.  I have to change the size for `grid_mesh()` to get it showing something, and then it appears fine.  When I set the window resizable and resize it, it does the sadly-usual thing where the window contents lags behind the window size a little bit.  I'll try it on an NVidia GPU and see what happens.

In general though, trying to avoid extra redraws isn't worth the effort.  Especially for something this simple, the GPU barely notices.  Actually creating the mesh is far more of a performance burden than drawing it.

**Comment by mikekchar** [comment]
I think my window manager is doing something a bit strange and resizing the window as soon as I start the program, so I didn't realise it wasn't displaying anything at first.  I think the lagging behind the resize is basically the problem.  On my machine, for whatever reason if the resize is large (like you maximize the window) it draws it in a very funny place.  What I thought was corruption seems to be it not rendering lines because they are on a weird pixel boundary (I guess).

I'm trying to write a unit test to indicate the problem.  It's a bit complicated :-) I'm trying to  render to a canvas, create an image and then compare that image to one that I already saved.  I'm having lots of problems getting that to work on a frame by frame basis and I'm not sure why.  I figured now would be a good time to upgrade to 0.5 since some of that stuff has been refactored and it looks a bit easier to work with.  Hopefully I'll have some decent information eventually :-)

I've got ggez building properly now and I'm starting to understand the code, so possibly if I figure it out I might also be able to send a patch.  No promises.  I'm very much learning as I go.

**Comment by icefoxen** [comment]
Yeah, I tried your test program on a Linux desktop with an NVidia GTX 660 and don't see any artifacting or anything.  So I'm not sure where to go from here.  Note that 0.5 has its own share of weird bugs, so it's not *perfect*, but...

Good luck, and let me know if there's anything I can help with.

**Comment by mikekchar** [comment]
I have my original app running under 0.5.0 now.  Interestingly, now *all* of the drawing is "lagging behind" on a resize, not just meshes. It's not just lagging behind (although it does that), on a dramatic resize it just plain draws it in the wrong place.  Again a `present()` after resizing and before drawing fixes the problem.  However all of the lines in the mesh are intact, etc.  One other small thing I noticed is that depending on where it is drawn on the screen, some of my 1.0 wide mesh lines are 2 pixels wide.  I'm guessing this is a round off error somewhere in the mapping.

Given the more consistent behaviour in this version, I'm hoping it will be easy to see the problem eventually.  I'll slowly keep poking away at it.  Probably nobody cares about this kind of minutia except me :-)

**Comment by icefoxen** [comment]
The 1.0 wide meshes being 2 pixels wide probably happens when they're drawn somewhere that overlaps two pixels, a demonstration of the effect is here: https://github.com/icefoxen/heckin_dpi

The drawing lagging behind on resize is something I've seen too and would like to fix.  Not sure how though.

Trust me, you are not the only person who cares about this kind of minutia.  Rummage through ggez's other issues, open and closed, and you'll find examples.  If we weren't compulsive about tiny details we wouldn't enjoy programming, right?

**Comment by icefoxen** [comment]
Should be fixed.
