### ISSUE TITLE
ContextBuilder fails with a VideoError operation not supported

### ISSUE THREAD

**Issue by Manghi** [ggez/ggez#621]
When I try to create the context builder via `build()` I get the following error after the screen flickers black:

```
ContextBuilder failed: VideoError("That operation is not supported")
```
I feel like I have seen this issue before on the ggez issue list but I couldn't find one of this specific variant. 

I am using  ggez v0.4.3 under Arch Linux with a Nvidia GTX 1080ti. This isn't a Linux specific issue since I can run the Astroblaster example just fine out of the `ggez master` branch.

I just attempted to update to the ggez master from v0.4.3 branch directly but there are a lot of  API changes for me to fix at this moment. 

Minimal code to reproduce with ggez v0.4.3.
```Rust
    let mut cb = ContextBuilder::new("ggez")
        .window_setup(conf::WindowSetup::default() )
        .window_mode(conf::WindowMode::default() );

    if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        let mut path = path::PathBuf::from(manifest_dir);
        path.push("resources");
        println!("Adding path {:?}", path);
        cb = cb.add_resource_path(path);
    } else {
        println!("Not building from cargo? Okie dokie.");
    }

    let ctx = &mut cb.build().unwrap_or_else(|e| {
        error!("ContextBuilder failed: {:?}", e);
        std::process::exit(1);
    });
```

Because I can run the `master` Astroblaster example I have omitted `glxinfo` output. 

Any ideas?

**Comment by icefoxen** [comment]
Well given that `master` uses winit and 0.4.3 uses SDL2 and a much older version of gfx-hal, a backtrace and glxinfo output would be useful.  `VideoError` generally means "you asked for OpenGL settings I can't provide`, or something along those lines.  I can run your example just fine on Debian Linux using an NVidia GTX 660 and the NVidia drivers.

Do you get the same error using ggez 0.4.4?  What OpenGL drivers are you using?

**Comment by Manghi** [comment]
Thanks for the reply Icefoxen. 

I do get the same error using ggez 0.4.4. Here's the backtrace and glxinfo output (attached).
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VideoError("That operation is not supported")', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: client::main
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:798
             at conwayste/src/client.rs:1180
  10: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: main
  15: __libc_start_main
  16: _start
```

[glxinfo.txt](https://github.com/ggez/ggez/files/3076564/glxinfo.txt)
This says I'm using `OpenGL version string: 3.1 Mesa 19.0.0`.

I'm using the nouveau drivers as well. I've *heard* these do okay when compared to the closed-official Nvidia drivers but I've yet a reason to switch over. Which of the two are you using since you also have a nvidia card?
```
01:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1) (prog-if 00 [VGA controller])
        Subsystem: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti]
        Flags: bus master, fast devsel, latency 0, IRQ 33, NUMA node 0
        Memory at fd000000 (32-bit, non-prefetchable) [size=16M]
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Memory at d0000000 (64-bit, prefetchable) [size=32M]
        I/O ports at e000 [size=128]
        Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: nouveau
        Kernel modules: nouveau
```

**Comment by Manghi** [comment]
Going to close this one off as a driver issue. I switched over to the official nvidia linux drivers and I can now run the basic example I listed above. I'm not writing off the nouveau drivers, but rather something probably specific to my system. Thanks for your help.

**Comment by icefoxen** [comment]
`OpenGL version string: 3.1`  That's your problem there, I'm afraid.  ggez requires OpenGL 3.2 or greater, there's some parts that are *really quite inconvenient* to do with earlier versions.  Interestingly though your driver also advertises `OpenGL ES 3.0`, which should be able to run ggez.  Maybe give that a try and see what happens.

**Comment by Manghi** [comment]
That seemed to fix it. Under `OpenGL version 3.2` things are running smoothly.
