### ISSUE TITLE
Is the build really failing? I really see a great future for ggez ? 

### ISSUE THREAD

**Issue by cata0309** [ggez/ggez#629]

**Comment by icefoxen** [comment]
You're gonna need to be more specific.  Though if you're referring to the CI builds, those should be easy to fix; just one of those things I haven't gotten around to.

**Comment by cata0309** [comment]
I meant the ggez build from this repository

**Comment by icefoxen** [comment]
If you can't build the current `master` branch from this repo, can you please post an error message?  If necessary run `rustup update` to make sure you're using the latest Rust compiler.

**Comment by icefoxen** [comment]
Feel free to re-open if you have further questions.
