### ISSUE TITLE
How to make a borderless window movable?

### ISSUE THREAD

**Issue by armoha** [ggez/ggez#630]
Hello, thanks for good work on library which is easy-to-use and fun to play with!

I currently uses `WindowSetup.transparent(true)` and `WindowMode.borderless(true)` for non-square shaped background. Due to borderless option, there is no title bar. So I want to make window movable by dragging particular area. Should I use [**GraphicsContextGeneric.window.set_position**](https://github.com/ggez/ggez/blob/508c0e664a3082bd327230a0af96a5270e2b576d/src/graphics/context.rs) with mouse event? I don't know if it is correct way to do this.

**Comment by icefoxen** [comment]
That's a good question.  I haven't tried to do this before so however works is the correct way.  Using `window.set_position()` is probably the best option, I'll experiment and see if there's any better way of doing it.

**Comment by armoha** [comment]
Thanks for your prompt response! I did it using `window.set_position()`.
I had to add `2.0 * rel` since window follows halfway to mouse without it. Maybe because `window.set_position` also moves the origin of mouse coordinates? There is a little error about 70 pixels when dragging 1920 pixels but I feel it is negligible.
```rust
fn mouse_motion_event(&mut self, ctx: &mut Context, x: f32, y: f32, xrel: f32, yrel: f32) {
    let mouse = &mut self.mouse_info;  // { down, button, x, y }
    if mouse.down
        && mouse.button == MouseButton::Right
        && (mouse.x != x || mouse.y != y)
        && (mouse.x - 2.0 * xrel != x || mouse.y - 2.0 * yrel != y)
    {
        let window = graphics::window(ctx);
        let mut pos = window.get_position().unwrap();
        pos.x += (2.0 * xrel) as f64;
        pos.y += (2.0 * yrel) as f64;
        window.set_position(pos);
    }
    mouse.x = x;
    mouse.y = y;
}
```

**Comment by icefoxen** [comment]
Thank you!  We should expose `get_position()` and `set_position()` from `window` directly then.

**Comment by PSteinhaus** [comment]
Well, we now do expose `set_outer_position()` via `graphics::set_window_position` but there's still no `get_window_position`...
I guess we should add that?

**Comment by PSteinhaus** [comment]
Added in 3683d55
