### ISSUE TITLE
Scaling canvas larger doesn't use FilterMode

### ISSUE THREAD

**Issue by joshsharp** [ggez/ggez#635]
Hello! I apologise in advance if this is my fault, or a duplicate. I had a look through the related issues but couldn't see anything quite the same.

**Describe the bug**
I've used LÖVE a bit, and a recommended way to create crisp, upscaled pixel art there is to draw everything to a canvas with filter mode set to nearest-neighbour, then render the canvas at 2x. When I do this with ggez, the scaled canvas appears to be using linear filtering rather than nearest-neighbour, so everything's a little fuzzy. 

One critical difference here is that ggez does not have a `set_filter` method for the `Canvas` object, but I've used it on the images I'm drawing — not sure if that's enough.

**To Reproduce**
I don't have a full code sample, but as a sanity check my flow currently looks like:

```rust
// create an image
let mut tile0 = graphics::Image::new(ctx, "/tile0.png")?;
tile0.set_filter(graphics::FilterMode::Nearest);

fn draw(&mut self, ctx: &mut Context) -> GameResult {
  graphics::set_canvas(ctx, Some(&self.canvas)); // set the canvas
  graphics::clear(ctx, [0.0, 0.0, 0.0, 1.0].into()); // draw our background colour
  // loop through and draw our images - omitted
  graphics::set_canvas(ctx, None); // remove our canvas so we can draw it to screen
  graphics::draw(ctx, &self.canvas,  graphics::DrawParam::default().scale(nalgebra::Vector2::new(2.0,2.0)))?; // draw canvas at 2x
  graphics::present(ctx)?; // draw it all to screen
}
```
(The comments are not to tell you what I'm doing, but what I *think* I'm doing, in case I have it wrong.)

**Expected behavior**
I would like a scaled-up canvas to render with nearest-neighbour filtering.

**Hardware and Software:**
 - ggez version: 0.5.0-rc.2
 - OS: Windows 10
 - Graphics card: Nvidia GTX 1050Ti

**Comment by maciejhirsz** [comment]
#633 is waiting to be merged :)

**Comment by joshsharp** [comment]
Ah that's great! Thanks :)

**Comment by maciejhirsz** [comment]
I guess this can be closed now :)

**Comment by joshsharp** [comment]
Ah, it's merged, lovely! Thanks :)
