### ISSUE TITLE
What is the name of the syntax color used to highlight the code on the website? 

### ISSUE THREAD

**Issue by cata0309** [ggez/ggez#641]
I know it might sound weird but I would love to use that syntax color in my ID or some reference about it.

**Comment by zxey** [comment]
Looks like it is called 'Hopscotch', found it [here](https://github.com/ggez/ggez.github.io/blob/bddfe7ded1fb6d5f2b9e89ff9cb724b41fe7d544/index.html#L10).

**Comment by cata0309** [comment]
Thank you
