### ISSUE TITLE
(suggestion) Allow changing the window title at runtime

### ISSUE THREAD

**Issue by Kasran** [ggez/ggez#643]
LÖVE and Pygame allow you to change the title of the game window at runtime; it'd be nice to be able to do this using ggez, but I couldn't find any exposed methods to allow me to do so. Winit and Glutin both expose `set_title` methods on their respective `Window`s, so this should in theory be possible.

This is a relatively unimportant nice-to-have, and I haven't spent enough time with the internals of ggez to gauge how much of an effort it would be to implement this, so if your impression is that it would be too difficult or would break the API or something (or if this is already possible and I just didn't notice), then I'll happily run along. Otherwise, I may try to put together a pull request for it myself. This is mainly just to register that there's someone interested in this functionality.

**Comment by icefoxen** [comment]
https://docs.rs/ggez/0.5.0-rc.2/ggez/graphics/fn.set_window_title.html ?

**Comment by Kasran** [comment]
Great Scott, I'm blind. Thank you!

**Comment by icefoxen** [comment]
No problem! Glad to help. It's always nice to meet people with the "well I can just add it myself" attitude. Most things in ggez that actually do things are functions in module roots.
