### ISSUE TITLE
`graphics::Font::new` leaks memory

### ISSUE THREAD

**Issue by WaffleLapkin** [ggez/ggez#644]
**Describe the bug**
While playing with [02_hello_world](https://github.com/ggez/ggez/blob/master/examples/02_hello_world.rs) example I found that `graphics::Font::new` probably leaks memory.

**To Reproduce**
There is a simple [gist](https://gist.github.com/WaffleLapkin/2477669a20e6cc1de157cbb59b264ef1) example. Just add it to ggez examples and run.

**Expected behavior**
Memory doesn't leak.

**Screenshots or pasted code**
The problem is in [this](https://gist.github.com/WaffleLapkin/2477669a20e6cc1de157cbb59b264ef1#file-02_hello_world-rs-L37) code:
```rust
let text = graphics::Text::new(
(
    "Sample text",
    graphics::Font::new(ctx, "/DejaVuSerif.ttf")?,
    48.0
)
);
graphics::draw(ctx, &text, DrawParam::default().dest(cgmath::Point2::new(10.0, 10.0)))?;
```
If line `graphics::Font::new(ctx, "/DejaVuSerif.ttf")?,` will be replaced with saved font (`self.font` in gist example) memory leaks will be gone.

Screenshots of `htop` while running gist example:
30 seconds:
![30s](https://user-images.githubusercontent.com/38225716/59438420-28f60e80-8dfc-11e9-9758-6775b7585f71.png)

60 seconds:
![1m](https://user-images.githubusercontent.com/38225716/59438418-28f60e80-8dfc-11e9-87b2-f23dc4283ba4.png)

90 seconds:
![1m30s](https://user-images.githubusercontent.com/38225716/59438417-28f60e80-8dfc-11e9-8e3e-ef5423c671d3.png)

130 seconds:
![2m10s](https://user-images.githubusercontent.com/38225716/59438415-285d7800-8dfc-11e9-931d-cdcd06f47d76.png)

170 seconds:
![2m50s](https://user-images.githubusercontent.com/38225716/59438413-285d7800-8dfc-11e9-9703-570eff247cdb.png)

That gives us approximately  `0.27%` memory leaks per second. Or `21.6 MB` per second as there are `8 GB` RAM in my laptop.

**Hardware and Software:**
 - ggez version: `ggez v0.5.0-rc.2 `
 - OS: Arch linux
 - Graphics card: Intel Corporation UHD Graphics 620 (rev 07)

**Comment by icefoxen** [comment]
Yep, fonts are cached in a more-decoded form and the Font object itself is just a handle to it. So you're not creating more fonts, you're adding multiple copies to the cache, which never gets trimmed.

Easy answer: don't do that.

Good answer: it WOULD be nice if it deduped entries, but it isn't entirely clear the best way to do this right now. Either way it's the job of `glyph_brush` so we should talk with them about it. The relevant function is https://docs.rs/glyph_brush/0.5.0/glyph_brush/struct.GlyphBrush.html#method.add_font_bytes .

Either way, ggez's documention should make it more clear what's going on.

**Comment by icefoxen** [comment]
This has been documented in commit b1f9d6e , and an issue has been opened upstream to ask for a way to deal with this.  Thanks again!

**Comment by icefoxen** [comment]
Followup: #652
