### ISSUE TITLE
Cant install version 0.5

### ISSUE THREAD

**Issue by slier81** [ggez/ggez#646]
I cant install ggez for version 0.5

My `cargo.toml`
```
[package]
name = "ggez"
version = "0.1.0"
authors = ["user <user@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5"
```

When i run `cargo build`, i got:
failed to select a version for the requirement `ggez = "^0.5"`
candidate versions found which didn't match: 0.4.4, 0.4.3, 0.4.2, ...
location searched: crates.io index

**Comment by ozkriff** [comment]
That's because 0.5 isn't released yet. The newest version on crates.io is `ggez = "0.5.0-rc.2"`

**Comment by slier81** [comment]
@ozkriff yes this should be in the README..

Im new to rust and ggez, i simply follow the instruction on the README and when im building the code, it simply throw me the error..

I cant even use any of the sample code to run with `v0.4.4` cause there maybe an API changes

**Comment by icefoxen** [comment]
Yeah, thanks for reporting this.  This is definitely a bug.  Should be corrected in the readme now.  Please let us know if you have any other problems!

**Comment by slier81** [comment]
Using `ggez = "0.5.0-rc.2"` allow me to play with ggez already..
Thx @icefoxen
