### ISSUE TITLE
Make KeyCode serializable

### ISSUE THREAD

**Issue by duganc** [ggez/ggez#649]
It would be great if KeyCode derived `serde::Serialize` and `serde::Deserialize` so that consumers of the crate could easily use configs to bind keys etc.  The alternatives (wrapping KeyCode or writing custom implementations) are both fairly painful given how large the enum is.

**Comment by duganc** [comment]
Nevermind, tried to PR for this and it looks like it's being directly pulled from `winit`.

**Comment by icefoxen** [comment]
Yep, which isn't really ideal but is at least easy to implement.  It looks like `winit` has a `serde` feature though, have you tried activating that?

**Comment by duganc** [comment]
I saw that too but couldn't figure it out easily.  Instead, I used this workaround: https://serde.rs/remote-derive.html

It's fragile to changes but it works for my purposes for now.

**Comment by icefoxen** [comment]
You can override feature flags for dependencies.  In your `Cargo.toml`, add `winit = {version = "0.19", features = ["serde"]}`.  Then:

```rust
let x = serde_json::to_string(&keycode).unwrap();
```

**Comment by duganc** [comment]
Good tip.  I'll give that a shot.  Thanks.
