### ISSUE TITLE
How to get the current volume of a played sound?

### ISSUE THREAD

**Issue by FireCubez** [ggez/ggez#651]
Like in Geometry Dash, where the orbs get bigger as the music gets louder. Is this possible?

**Comment by icefoxen** [comment]
https://docs.rs/ggez/0.5.0-rc.2/ggez/audio/trait.SoundSource.html#tymethod.volume ?

**Comment by FireCubez** [comment]
Doesn't that just get a preset volume "multiplier"? I want to (at least roughly) estimate how much sound the human is hearing, not how much we increase/decrease the volume by.

**Comment by icefoxen** [comment]
So if I understand correctly you want to be able to play two arbitrary audio files with volume multiplier 1.0x or whatever, and know if one is louder than the other at a given moment?  'Cause that sort of audio balance is the job of the person doing the sound design and mixing.

**Comment by FireCubez** [comment]
No, I want to play a single arbitrary audio file, and know how loud it is. How much sound is roughly coming out of the speakers.

**Comment by FireCubez** [comment]
A use case for this is like I described above, Geometry Dash orbs become bigger as the music becomes louder creating a "beating" effect without necessarily knowing information about the song.

**Comment by icefoxen** [comment]
Then you decode the sound file and examine the raw samples, and do what you want based on the levels of them. ggez doesn't have a good way to do this but it's doable with rodio, the audio library it uses.

**Comment by FireCubez** [comment]
Alright, will try that

**Comment by icefoxen** [comment]
Feel free to re-open this if you have any followup questions!
