### ISSUE TITLE
Add a method to clear/replace the font cache.

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#652]
See https://github.com/ggez/ggez/issues/644 for motivation: you can never remove a font, so adding them leaks memory forever.

See https://github.com/alexheretic/glyph-brush/issues/72 for discussion: Removing a single font basically invalidates the entire cache anyway, so is Hard to do correctly.  But adding the ability to just clear the entire cache is not unreasonable, and is something `glyph_brush` may add in the future anyway.

In our current design this would result in a `Font` be a dangling handle after clearing the cache, but this is fixable by making `Font` include a generational index.  Increment the generation each time the cache is cleared, runtime check to error if someone uses a `Font` with a generation older than the current.

**Comment by nico-abram** [comment]
I can give this a shot. Is the comment above up to date?

**Comment by nico-abram** [comment]
Is this the only function that should check the generational index? https://github.com/ggez/ggez/blob/master/src/graphics/text.rs#L240

Would it be fine to store the current generation index in this context? https://github.com/ggez/ggez/blob/master/src/graphics/context.rs#L22

Just to clarify, by `Font` you mean https://github.com/ggez/ggez/blob/master/src/graphics/text.rs#L26 ?

What should be the generationa index of the default Font (https://github.com/ggez/ggez/blob/master/src/graphics/text.rs#L430)? Would making it 0 and making the context's begin at 1 be fine?

**Comment by icefoxen** [comment]
Yeah, not a whole lot has changed since Jul 12th, and nothing in fonts afaik.

> Is this the only function that should check the generational index? https://github.com/ggez/ggez/blob/master/src/graphics/text.rs#L240

Not sure off the top of my head, I'd do it in anything that might need to access the `Font`.

> Would it be fine to store the current generation index in this context? https://github.com/ggez/ggez/blob/master/src/graphics/context.rs#L22

Yes, though the `generational-arena` crate my be useful too.

> Just to clarify, by Font you mean https://github.com/ggez/ggez/blob/master/src/graphics/text.rs#L26 ?

Yes.

> What should be the generationa index of the default Font (https://github.com/ggez/ggez/blob/master/src/graphics/text.rs#L430)? Would making it 0 and making the context's begin at 1 be fine?

Seems reasonable to me.

**Comment by nico-abram** [comment]
What should the Default value of Text/Font do when used? Panic or silently ignore? I was originally ignoring it and letting it pass (Otherwise a bunch of tests break).

Also, I'm running into a small problem: When creating a Text, I'm not sure how I can get the generational index. Specifically, here:

    pub fn new<F>(fragment: F) -> Text
    where
        F: Into<TextFragment>,
    {
        let mut text = Text::default();
        let _ = text.add(fragment);
        text
    }

Unless I change what seems to be a public API (Text::new considering TextFragment is publically constructible, I think).

**Comment by icefoxen** [comment]
Sorry for the slow response.  Is your current work on a branch somewhere I can play with it?  I'm curious to try it out and see how it works.

> What should the Default value of Text/Font do when used?

I would hope for it to return a default font!  If that's not possible it should be removed, though as is currently done, hardwiring a particular font as the default is fine.  This may have to be a special case though to ensure it always exists.

> When creating a Text, I'm not sure how I can get the generational index.

I'm not sure what you mean there.  It's more or less the job of the `Into<TextFragment>` to produce a `Font`, which is where I'd expect the generational index to be.
