### ISSUE TITLE
winit "serde" cargo feature

### ISSUE THREAD

**Issue by WaffleLapkin** [ggez/ggez#655]
In `Cargo.toml` winit dependency  defined like `winit = { version = "0.19" }`.

1) Why use `{}`, if only the version is set?

2) Why there is no `features = ["serde"]`? It will be useful when saving key bindings to file for example.

I suggest to define winit dependency as `winit = { version = "0.19", features = ["serde"] }`.

Alternatively, we can add a feature that depends on winit "serde" feature:
```
# Cargo.toml
[features]
winit-serde = ["winit/serde"]
```

**Comment by WaffleLapkin** [comment]
Oops, I didn't know, but 2 can be covered with `winit = { version = "0.19", features = ["serde"] }` dependency in the "game crate" itself, so it's useless in ggez.

**Comment by icefoxen** [comment]
On July 14, 2019 6:03:39 AM EDT, Waffle Lapkin <notifications@github.com> wrote:
>In `Cargo.toml` winit dependency  defined like `winit = { version =
>"0.19" }`.
>
>1) Why use `{}`, if only the version is set?
>
>2) Why there is no `features = ["serde"]`? It will be useful when
>saving key bindings to file for example.
>
>I suggest to define winit dependency as `winit = { version = "0.19",
>features = ["serde"] }`.
>
>Alternatively, we can add a feature that depends on winit "serde"
>feature:
>```
># Cargo.toml
>[features]
>winit-serde = ["winit/serde"]
>```

For 1), occasionally I find bugs in winit and often switch the dependency to a git branch for testing and fixing. The {}'s are just left over from that.
-- 
Sent from my phone. Please excuse my brevity.
