### ISSUE TITLE
Color space example needs to be more complete

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#657]
Basically we need to have it draw every type of `Drawable` and make sure the colors are correct.  Done:

 * Mesh
 * `Image::from_rgba8` (more or less)
 * Text

To do still:

 * Image from file
 * SpriteBatch
 * Canvas(?!)
 * Mesh from MeshBuilder?
 * random shader?

**Comment by BrooksPatton** [comment]
Are you thinking these would be in one example or one per? For example a file for creating a drawable from an image file and another file for a MeshBuilder?

**Comment by icefoxen** [comment]
I was going to assume it was all in one example.

**Comment by BrooksPatton** [comment]
As you've done `Mesh` and `Image::from_rgba8` should I add these to the same example you did? Also, which example are those in?

**Comment by icefoxen** [comment]
Yes please.  Add any updates to https://github.com/ggez/ggez/blob/master/examples/colorspace.rs

**Comment by BrooksPatton** [comment]
I created a pull request (#699) to add a Text Drawable to the example.

**Comment by BrooksPatton** [comment]
What was your idea about the image from file? Would it be an image of the same color as the background?

**Comment by iolivia** [comment]
opened a PR for adding sprite batches, @icefoxen I was also wondering the same as @BrooksPatton about the image from file.
