### ISSUE TITLE
Drawing text completely messes up other things.

### ISSUE THREAD

**Issue by FireCubez** [ggez/ggez#664]
I have some code which draws some entities
```rust
for v in entities {
    let line = ...;// create mesh
    graphics::draw(ctx, &line, graphics::DrawParam::default()
        .offset(mint::Point2 {
            x: size.0 / 2.0,
            y: size.1 / 2.0
        })
        .rotation(v.angle)
    )?;
}
```

This works fine, but then I try to add some text drawing

```rust
graphics::draw(ctx, &key, graphics::DrawParam::default().offset(mint::Point2 {
        x: size.0 / 2.0,
        y: size.1 / 2.0
    })
    .dest(mint::Point2 {
        x: x.max(0.0),
        y: 0.0
    })
    .rotation(v.angle)
)?;
```

Then everything just goes... unpredictable. I draw 2 circles after that for loop:
```rust
let outc = graphics::Mesh::new_circle(
    ctx,
    graphics::DrawMode::fill(),
    mint::Point2 { x: size.0 / 2.0, y: size.1 / 2.0 },
    self.syncer().player_size() + 10.0,
    0.1,
    *self.level().get_color(1),
)?;
let inc = graphics::Mesh::new_circle(
    ctx,
    graphics::DrawMode::fill(),
    mint::Point2 { x: size.0 / 2.0, y: size.1 / 2.0 },
    self.syncer().player_size(),
    0.1,
    *self.level().get_color(2),
)?;
graphics::draw(ctx, &outc, graphics::DrawParam::default().dest(mint::Point2{x:0.0,y:0.0}))?;
graphics::draw(ctx, &inc, graphics::DrawParam::default().dest(mint::Point2{x:0.0,y:0.0}))?;
```

The outer circle (`outc`) *follows one of my entities*. As you can see it clearly has a static position (`size` is the size of the window). It's just weird...

**Comment by FireCubez** [comment]
To add, if I don't offset/rotate the text, it works fine.

**Comment by adumbidiot** [comment]
I'd also like to add that adding
```
ggez::graphics::pop_transform(ctx);
ggez::graphics::apply_transformations(ctx);`
```
fixes this problem in my use case. Not sure if that helps or not. I can post more details if you need.

**Comment by FireCubez** [comment]
Where exactly do you add that?

**Comment by adumbidiot** [comment]
After drawing the text. Here's more code:
```
let text = self //TODO: Make not stupid
    .text_cache
    .entry(val.to_string())
    .or_insert(Text::new(*val));

    graphics::draw(
            ctx,
            text,
            DrawParam::default().dest(nalgebra::Point2::new(*x, *y)),
    )
    .unwrap();

    ggez::graphics::pop_transform(ctx);
    ggez::graphics::apply_transformations(ctx);
``` 
My use case was pretty simple with very little objects, so its possible that this messes up other things. I haven't tested this extensively or bothered to make a simple example, though it stops the weird drawing behavior after drawing text.

**Comment by piotrek-szczygiel** [comment]
I have similar problem where drawing text makes my mesh invisible.
It happens only on my laptop with Intel graphics card enabled.
When switching to NVIDIA everything works fine.

Adding this after text draw indeed fixes it:
```rust
ggez::graphics::pop_transform(ctx);
ggez::graphics::apply_transformations(ctx);
```

**Comment by adumbidiot** [comment]
I think this might only happen on intel gpus, as drawing text seems to work fine on my nvidia card. I can't tell if an update fixed this though, as I don't have access to an intel card anymore.

**Comment by a2aaron** [comment]
I was able to achieve the same workaround by only doing `ggez::graphics::apply_transformations(ctx)` alone.

This might be a memory barrier problem????????

**Comment by AaronM04** [comment]
Is this bug only on Windows?

**Comment by icefoxen** [comment]
Should be fixed in `develop` branch, please verify.  See #836.  Re-open this issue if the problem persists!
