### ISSUE TITLE
Unable to run astroblasto example without adding nalgebra and rand as dependencies to cargo.toml

### ISSUE THREAD

**Issue by joekreydt** [ggez/ggez#667]
**Bug Description**
Followed steps here: https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md to run the astroblasto example game. Ran into two similar errors during compile:

**Error 1:**
error[E0432]: unresolved import 'nalgebra'
  --> src/main.rs:13:5
     |
13 | use nalgebra as na;
     |        ^^^^^^^^^^^^^^ no 'nalgebra' external crate

Error 2:
error[E0432]: unresolved import 'rand'
 --> src/main.rs:14:5
     |
14 | use rand;
     |        ^^^^ no 'rand' external crate

**To Reproduce**
Follow steps here: https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md to run the astroblasto example game.

**Expected behavior**
Expected the program would compile and run, launching a window with an Asteroids-like game.

**Hardware and Software:**
 - ggez version: 0.5
 - OS: Manjaro 18.0 GNOME Edition
 - Graphics card: VMWare SVGA II Adapter
 - Running OS as a VIrtualBox VM

**Comment by joekreydt** [comment]
I was able to work around this issue by adding the following lines beneath the _[dependencies]_ section of the program's _cargo.toml_ file:
`nalgebra = "0.18.0"`
`rand = "0.7.0"`

**Comment by icefoxen** [comment]
Awesome, thank you! This is a doc bug.

**Comment by IGBC** [comment]
better fix is to change `use nalgebra as na;` to use ggez::use nalgebra as na;` no need to add nalgebra as a dependancy

**Comment by icefoxen** [comment]
That's been done in commit c67ad14890ce6c55eb3bedca184bee8ab54692ae
