### ISSUE TITLE
Question: Disabling antialiasing on text

### ISSUE THREAD

**Issue by woubuc** [ggez/ggez#668]
Is it possible to disable antialiasing, or whatever it is that causes my pixel font to be displayed blurry like this?
![image](https://user-images.githubusercontent.com/1015540/62422259-b7299b00-b6af-11e9-92a8-c993014c2870.png)

I already use `NumSamples::Zero`.

**Comment by icefoxen** [comment]
Try setting [`FilterMode`](https://docs.rs/ggez/0.5.1/ggez/graphics/enum.FilterMode.html) to `Nearest`, either on `Image::set_filter` or in the params for `graphics::draw_queued_text()` or whatever.

**Comment by woubuc** [comment]
Using `draw_queued_text` with the Nearest filter (instead of just drawing the text directly) did the trick! I still have to mess around with pixel alignment to make it really look 'crisp' but I'm on the right track now. Thanks!

**Comment by pherrymason** [comment]
What's the solution when using `canvas.draw`? `draw_queued_text` is now deprecated.

**Comment by StativKaktus131** [comment]
> What's the solution when using `canvas.draw`? `draw_queued_text` is now deprecated. I see `canvas.set_sampler(Sampler::nearest_clamp());` would be the equivalent, but can it be enabled just for a specific text rendered? Does it makes sense?

I don't know if it works with text, but I had the same problem and found the solution is to set the canvas sampler to clamp nearest:

``` rust
// all of these are in ggez::graphics, so I do:
use ggez::graphics::*;

// in your draw function
let mut canvas = Canvas::from_frame(ctx, Color::BLACK);
canvas.set_sampler(Sampler::nearest_clamp());
```
