### ISSUE TITLE
Build failure on alsa after adding ggez dependency

### ISSUE THREAD

**Issue by corewired** [ggez/ggez#680]
**Describe the bug**
I added ggez as instructed to Cargo.toml and had a build failure apparently involving alsa. I'm pretty new to Rust so let me know if it is something I'm doing wrong. 

**To Reproduce**
Add ggez as dependency and cargo run

**Expected behavior**
Compilation of dependencies

**Screenshots or pasted code**
Compiling alsa-sys v0.1.2
error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/philip/git/rust/projects/ggez-testing/target/debug/build/alsa-sys-e784851eaf2a923a/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Hardware and Software:**
 - ggez version: 0.4 and also 0.5
 - OS: kubuntu 18.04
 - rustc 1.37.0 (eae3437df 2019-08-13)

**Comment by icefoxen** [comment]
Check out the [build docs](https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md#debian) ?

**Comment by corewired** [comment]
That did it. Sorry not sure how I missed that. Thanks
