### ISSUE TITLE
Inconsistent path prefix between directories and zip files

### ISSUE THREAD

**Issue by piotrek-szczygiel** [ggez/ggez#682]
I'd like to load my resources both from the zip file and the resources folder.
Default resources would be baked into the executable, and additional resources either in resources.zip or resources/ directory could be used to mod the game.

My problem is that resources in the zip files are obtained without the leading slash.

Example:

```rust

// resources/
let img = Image::new(ctx, "/background.png")?;

// resources.zip
let img = Image::new(ctx, "background.png")?;
```

Is there any reasoning behind this? How can I deal properly with it?

Should i just do something like:

```rust
pub fn path(ctx: &Context, path: &str) -> String {
    let slash_path = String::from("/") + path;

    if filesystem::is_file(ctx, &slash_path) || filesystem::is_dir(ctx, &slash_path) {
        slash_path
    } else {
        String::from(path)
    }
}
```

And then later:

```rust
let img = Image::new(ctx, path("background.png"))?;
```

**Comment by icefoxen** [comment]
That's a bug and needs fixing then.  Thanks!
