### ISSUE TITLE
[Question] Scale vs Text::width values for monospaced fonts

### ISSUE THREAD

**Issue by Manghi** [ggez/ggez#684]
I'm using a fixed-width font scaled to 20.0 pixels and am a bit confused about what the `Text` object reports it's size as. The reported width is always a few pixels smaller than what I expect. For example, querying the width of the letter 'a' returns 9 pixels whereas I was anticipating 20 px due to the scale. 

[This gist](https://gist.github.com/Manghi/039b9cae964fe0b8e2636a4c3a5293f8) is a reproduces of my question.

I'm speculating it's a gap in my understanding of how these two may differ so any help would be appreciated.

**Comment by ozkriff** [comment]
Related to #583 (_"Text::dimensions should return Rect, not (u32, u32)"_)?

**Comment by Manghi** [comment]
Ah I see. Thanks. I'll close this one out then.
