### ISSUE TITLE
Does not find resources.zip

### ISSUE THREAD

**Issue by sigod** [ggez/ggez#691]
ggez doesn't find resources.zip if it isn't located right next to an executable file. For example, when running with `cargo run`.

Also, zip files cannot have compression? That's not obvious from the docs.

**Comment by icefoxen** [comment]
Sorry for the delay!  It would be nice to be able to add this function, shouldn't be too hard.

Zip files should certainly be able to have compression, but afaik zip files can have many different types of compression.  Not sure which types the `zip` crate actually supports.
