### ISSUE TITLE
Resizing window (set_mode, set_screen_coordinates) freezes my entire OS

### ISSUE THREAD

**Issue by crsaracco** [ggez/ggez#692]
I will say up-front that I'm probably just Doing It Wrong™: I assume calling `set_mode` and/or `set_screen_coordinates` in rapid succession is probably what's breaking it. If so, I'd request adding a note about the correct usage (or even just "don't do X") in the documentation since I'm a noob and I don't know what I'm doing :D

**Describe the bug**
In my EventHandler's `resize_event`, I'm doing:

```rust
let window_mode = /* ... */;
graphics::set_mode(ctx, window_mode);
graphics::set_screen_coordinates(ctx, graphics::Rect{0.0, 0.0, width, height});
```

When I go to resize the window, this seems to freeze up my *entire system*, forcing me to hard-reboot. Not sure what's up, maybe overloading or corrupting memory in the GPU?

**To Reproduce**
(can make an example if needed)

**Expected behavior**
Game doesn't freeze my entire system (even if the game runs very slow) while resizing

**Screenshots or pasted code**
N/A

**Hardware and Software:**
 - ggez version: 0.5.1
 - OS: Arch linux
 - Graphics card: NVidia GeForce GTX 980 Ti
 - Graphics card drivers: `nvidia` 435.21-11
 - 4k screen, maybe DPI scaling is relevant?

If I'm just Doing It Wrong, what's the correct way to handle window resizing?

**Comment by icefoxen** [comment]
Now *that* sounds like a driver bug, and not one I've seen before.  NVidia drivers usually don't do this sort of nonsense.  What WM are you using?  Could you make a small reproduction please?

**Comment by crsaracco** [comment]
Cinnamon 4.2.4 / Muffin.

Sure! I'll probably be able to get to it later this week, or on the weekend at latest.

**Comment by crsaracco** [comment]
Actually, false alarm! I was calling `graphics::set_mode` from within `resize_event`, which was causing an infinite resize loop.

I'm not sure why, but before I thought `set_mode` was some function you should call on every reset (I misread something in the docs). It's obvious to me on this second reading that it potentially *causes* a resize event.

For completeness, here's a repro for crashing my system -- I basically just took the [basic project template](https://docs.rs/ggez/0.5.1/ggez/index.html#basic-project-template), enabled window resizing when constructing the window, and then added this function to the handler:

```rust
fn resize_event(&mut self, ctx: &mut Context, width: f32, height: f32) {
    let window_mode = WindowMode {
        width,
        height,
        resizable: true,
        ..Default::default()
    };
    graphics::set_mode(ctx, window_mode);
    
    graphics::set_screen_coordinates(ctx, graphics::Rect{x: 0.0, y: 0.0, w: width, h: height}).unwrap();
}
```

Feel free to reopen if I still misunderstood something, but I think I was indeed just Using It Wrong :)

**Comment by icefoxen** [comment]
Ah, no that would do it. I missed the fact that `set_mode()` was being called.
