### ISSUE TITLE
ContextBuilder::conf does not override conf.toml

### ISSUE THREAD

**Issue by Athorus** [ggez/ggez#696]
**Describe the bug**
When building a Context by calling ContextBuilder::new(..).conf(ggez_conf), ggez_conf parameter is ignored and file conf.toml is read.

**Expected behavior**
When a Context is built by calling ContextBuilder::conf, file conf.toml should be ignored.

**Screenshots or pasted code**
```rust
ContextBuilder::new("game", "author")
    .conf(ggez_conf).build().unwrap();
```
with_conf_file needs to be called in order to override conf.toml
```rust
ContextBuilder::new("game", "author")
    .with_conf_file(false)
    .conf(ggez_conf).build().unwrap();
```

**Hardware and Software:**
 - ggez version: 0.5.1
 - OS: Windows 10

**Comment by icefoxen** [comment]
That is correct, the `ContextBuilder` provides the defaults that the conf file overwrites.  That way a local user can change the conf file and it will actually use the values in the conf file instead of the hardwired ones.

This is documented in https://docs.rs/ggez/0.5.1/ggez/conf/index.html but it's not super explicit.

**Comment by Athorus** [comment]
As you've added the label bug, does it mean you will change the behavior ?

**Comment by icefoxen** [comment]
No, it means I will update the docs to better describe the behavior.  I'd like to know more about why you want the given conf to override the file before changing behavior.

**Comment by Athorus** [comment]
My need is to be able to rebuild a "Context" in the case where one attribute of "WindowSetup" has been changed. For example, if the user changes the flag "vsync" in the game menu (I want to save "conf.toml" only when the user exits the game).

In the other hand, when the game is launched, I need to build a "Context" by using a default "Conf" if "conf.toml" does not exist.

**Comment by icefoxen** [comment]
Save the conf.toml and then rebuild your Context?

**Comment by Athorus** [comment]
Well, with the current API, I can meet my needs. Maybe you should rename the ContextBuilder::conf to ContextBuilder::default_conf
