### ISSUE TITLE
Can't enable serde feature flag for ggez::nalgebra

### ISSUE THREAD

**Issue by yoloVoe** [ggez/ggez#700]
**Describe the bug**
In order to deserialize `ggez::nalgebra::Vector2` in our project, we introduced `nalgebra` as a dependency and enabled the `serde` feature flag on it. However, it doesn't compile.
```
   Compiling nalgebra v0.18.1
error[E0463]: can't find crate for `serde_derive`
   --> /home/yolovoe/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.18.1/src/lib.rs:100:1
    |
100 | extern crate serde_derive;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `nalgebra`.

To learn more, run the command again with --verbose.
```

**To Reproduce**
Clone this [repo](https://github.com/ClappingClowns/walpurgis/tree/serde_error) and run `cargo build`.

**Expected behavior**
We expect the code to compile.

**Screenshots or pasted code**
We have a `BoundingBox` struct in our [game](https://github.com/ClappingClowns/walpurgis/blob/serde_error/src/physics/mod.rs#L21) that needs to be deserialized:
```rust
use ggez::nalgebra as na;

type Radians = f32;

#[derive(Clone, Debug, Deserialize)]
pub struct BoundingBox {
    /// The pos (x, h) of the bounds. +x goes up and +y goes right.
    pub pos: na::Vector2<f32>,
    /// The size (w, h) of the bounds.
    pub size: na::Vector2<f32>,
    /// Orientation, i.e. radians to rotate the box in the counterclockwise directions.
    pub ori: Radians,
}
```
We have enabled the `serde` feature flag on the `nalgebra` dependency, like so:
```
ggez = { version = "0.5.1" }
nalgebra = { version = "0.18.1", features = ["serde"] }
```

**Hardware and Software:**
 - ggez version: 0.5.1
 - OS: Ubuntu 18.04.3 LTS
 - Graphics card: GeForce RTX 2080 SUPER/PCIe/SSE2
 - Graphics card drivers: [This one](https://www.nvidia.com/Download/driverResults.aspx/151568/en-us)

**Comment by yoloVoe** [comment]
One solution workaround be to have a feature flag in `ggez` that toggles on the `serde` feature flag in `ggez::nalgebra`.

I can look into this and submit a PR, if that's ok.

**Comment by icefoxen** [comment]
Thanks, that would be a reasonable workaround.  Frankly, since `ggez` uses `serde` already I'm not sure there's any reason not to just have the `serde` feature flag on for `nalgebra` all the time.  Compile times, maybe.

**Comment by icefoxen** [comment]
Hmm, it looks like you can also add to feature flags by just specifying the dependency in your own project.  So if you just specify the same version of `nalgebra` that ggez uses as a dep for your project and enable the `serde` feature flag, I think it *should* work.

**Comment by yoloVoe** [comment]
>  if you just specify the same version of nalgebra that ggez uses as a dep for your project and enable the serde feature flag

I made this issue after doing this prevented the code from compiling. Not really sure why this is happening :frowning: .

Let me know what you believe the best way to proceed forward is.

**Comment by yoloVoe** [comment]
@icefoxen

**Comment by yoloVoe** [comment]
For anyone else who has the same issue, I was able to resolve the issue.

The issue was my Cago.toml looked like this:
```
...
ggez = "0.5.1"
nalgebra = { version = "0.18", features = [ "serde" ]}
...
```

when it should have looked like this:
```
...
ggez = "0.5.1"
nalgebra = { version = "0.18", features = [ "serde", "serde_derive" ]}
...
```

**Comment by Kinrany** [comment]
@icefoxen it would be nice to have a ggez feature for this. This way we won't have to manually verify that nalgebra versions are the same.
