### ISSUE TITLE
`text` example does not work on `devel`

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#701]
**Describe the bug**
Just shows a blank screen.

**To Reproduce**
`git checkout devel; cargo run --example text`

Probably related: #645

**Comment by icefoxen** [comment]
Also related: #664

**Comment by mkhan45** [comment]
Hi, I just checked this on my pc and it works fine as far as I can tell:

![](https://i.imgur.com/Diu8Bnp.png)

OS: Void Linux kernel 5.6.7_1
CPU: Intel i5-6500
GPU: AMD RX 480
drivers: mesa 20.0.5_1, amdgpu 19.1.0_2

**Comment by PSteinhaus** [comment]
It also works now, on master as well as on devel, so I propose closing this.
