### ISSUE TITLE
Worth mentioning #![windows_subsystem = "windows"] somewhere in docs, or examples

### ISSUE THREAD

**Issue by jackmott** [ggez/ggez#702]
**Describe the bug**
People making games will want to be able to double click on the exe and not have a console window open up in windows.  How to achieve this is hard to figure out, but easy to do.  Perhaps somewhere in the docs the `#![windows_subsystem = "windows"]` could be mentioned or it could be used in the examples with a comment.

**To Reproduce**
Build a ggez game, double click on the exe. Console window opens up along with the graphical window.

**Expected behavior**
Docs should explain how to prevent this.

**Screenshots or pasted code**
just put `#![windows_subsystem = "windows"]` at the top of your main.rs

**Hardware and Software:**
 - ggez version:all
 - OS: windows

**Comment by icefoxen** [comment]
Awesome detail that i'd never thought about. Thanks!

**Comment by jackmott** [comment]
happy to do a PR just let me know where you want it.

**Comment by icefoxen** [comment]
I'm actually not sure where to put it now that I think of it.  Maybe in the FAQ?

**Comment by Athorus** [comment]
Thanks for this information, it will help me when I will publish my games in few days.

**Comment by Ratysz** [comment]
A variant: `#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]`. This will remove the console window for just the release builds, assuming debug assertions weren't manually enabled for the release profile, for whatever reason.

**Comment by Uriopass** [comment]
I think this can be closed ! one more issue towards the 0.6 milestone
