### ISSUE TITLE
Large crate size

### ISSUE THREAD

**Issue by spenserblack** [ggez/ggez#704]
The size of this crate is a bit large (0.95 MB @ 0.5.1). I think this is because files (mostly images) tracked by git are being included in the `.crate` file produced by `cargo package` and `cargo publish`.

Would it be possible look into [excluding](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional) files that aren't necessary to compile the library? It should improve download time when a user first fetches this crate.

**Comment by icefoxen** [comment]
Makes sense, sure.  Thanks!

**Comment by icefoxen** [comment]
Daaaaang, #707 did this for me.  `DejaVuSerif.ttf` is built into the library as the default font, so that has to be there, but it's also 371 kb.  I welcome suggestions for a smaller font to use instead if anyone has one, the requirements are:

 * Truetype
 * Compatible license
 * Decent glyph assortment (at least latin alphabets, cyrillic and arabic would be very nice as well, Indian and CJK languages would be a bonus but are large and complicated)
 * Looks cool

**Comment by icefoxen** [comment]
Some candidates:

 * Calling Code, 65 kb: https://www.dafont.com/calling-code.font?l[]=10 , latin only
 * Bitstream Vera Sans, 66 kb: https://www.dafont.com/bitstream-vera-sans.font?l[]=10 , latin only
 * Liberation Sans, 133 kb: https://www.dafont.com/liberation-sans.font?l[]=10 , latin and cyrillic

Good font viewer so you can see what glyphs they actually have: http://mathew-kurian.github.io/CharacterMap/

Contrast with the current DejaVu font which includes latin, cyrillic and also arabic glyphs... but Calling for opinions on people who use non-Latin-character-set languages and/or have slow internet... which do you prefer?  Keeping in mind that [Arabic doesn't render correctly anyway...](#378) ...

**Comment by ceranco** [comment]
I found another nice one:
* Comme, 52 kb: https://www.fontsquirrel.com/fonts/comme

How do you check the if cyrillic is supported?

**Comment by icefoxen** [comment]
I loaded it up in the font viewer app I linked and paged through thr character map looking for Cyrillic characters.  :D

**Comment by ceranco** [comment]
Makes sense :sweat_smile:
I updated my previous comment to add the glyph support of the font.

**Comment by icefoxen** [comment]
I like Comme, but let's use Liberation Sans for now, just to get a LITTLE bit of support for non-western-European languages by default.

**Comment by icefoxen** [comment]
Switched the default font to LiberationMono-Regular, which is ~106 kb.
