### ISSUE TITLE
Le Train Dispatcher not in the projects list

### ISSUE THREAD

**Issue by Athorus** [ggez/ggez#709]
I've published my game : Le Train Dispatcher 
http://athorus.itch.io/ltd

It uses ggez 0.5.1, so I would be glad and proud if you could add my game in the projects list. I can write something or give materials if needed.

Feel free to comment my work, even though it is not nice. I need that to improve the game.

**Comment by icefoxen** [comment]
Oh cool, thanks!  It's like the best part of Factorio!  😁 

Added it to the projects list, it looks great.  If you want to add more to describe it go ahead, just keep it to a sentence or two.  I love how the movements make the trains *feel* like they have weight, somehow.  Do you take the mass into account with how fast they can go around curves?

**Comment by Athorus** [comment]
Thank you very much! I've just watched some videos about Factorio and maybe I will get some ideas from it. Currently, you have to move cars from a point A to a point B, but I also want to carry merchandise in a future release.

My first goal was to create a game around a simulator, so yes each car have its own weight and I know the radius for each point of a curve. So in a future, I plan to compute the centrifugal force in order to limit the train speed in curves. You can imagine some tracks will be able to handle more force than others.
Have you notice than none of my curves are circles ? Why ? Because the radius must gradually decrease and then increase. In fact, my curves are spirals. Maybe LTD is the only one to do that. Real roads and railway networks work this way.

As a game designer with Zemeroth, do you have some tips to give? It seems very difficult to create a small community and to interest some players. I know I will not be rich! :D

**Comment by icefoxen** [comment]
I didn't notice it but it's brilliant.  Keep up the good work, and thank you!

**Comment by Athorus** [comment]
For the game description, here my proposal : 

Le Train Dispatcher : Route trains in a simulated rail network

Le Train Dispatcher allows you to route trains in a fully simulated rail network. Particular care has been taken on the realistic management of light signals (block systems, switches protection), train physics and curve tracing.

**Comment by icefoxen** [comment]
Description updated, thank you!
