### ISSUE TITLE
Fetching Resolution Information

### ISSUE THREAD

**Issue by rdelfin** [ggez/ggez#717]
I'm trying to solve an issue and I can't seem to find a simple solution to, so I'm turning here to help. I'm trying to figure out a way of fetching my current window's resolution without having to extract the information out of SDL. The specific case here is I'm putting a window in full-screen mode, and I want to get the resolution of the screen to properly scale everything up and down depending on the size of the screen. What is the best/recommended way of doing this here?

**Comment by icefoxen** [comment]
https://docs.rs/ggez/0.5.1/ggez/graphics/fn.drawable_size.html

**Comment by rdelfin** [comment]
Yep! That's exactly what I was looking for. Sorry couldn't find it :(
