### ISSUE TITLE
mouse leave/enter event

### ISSUE THREAD

**Issue by extrawurst** [ggez/ggez#724]
is there a way to know if the mouse left the window ?

**Comment by nathanielknight** [comment]
There's a `winit` event for it:

https://docs.rs/ggez/0.5.1/ggez/event/winit_event/enum.WindowEvent.html#variant.CursorLeft

**Comment by Extrawurst** [comment]
tried it but it does not reliably trigger (tried on my Mac) - it will only fire when moving in and out of the window buttons on the top left 🤔

**Comment by Extrawurst** [comment]
but I guess that is more of an winit issue

**Comment by Extrawurst** [comment]
seems fixed now: https://github.com/rust-windowing/winit/pull/1335

**Comment by Extrawurst** [comment]
bug report: https://github.com/rust-windowing/winit/issues/1128

**Comment by icefoxen** [comment]
Cool, thanks for the PR!

**Comment by IGBC** [comment]
This looks like its resolved. There is a merged PR and no further activity for 2 years. Closing
