### ISSUE TITLE
Multiple Keycodes missing

### ISSUE THREAD

**Issue by IGBC** [ggez/ggez#726]
**Describe the bug**
Keycodes to represent certain keys are missing or not recognised.

**To Reproduce**
add `println!("KeyDownEvent Key:{:?}, Mods:{:?}", keycode, _keymod);` to the `key_down_event(...)` function in your event handler. Use the output to note the results of pushing various keys. 

**Expected behaviour**
I expect every key to return _something_ even if it is incorrect, current behaviour has multiple dead keys in my layout including the `(` and `)` (shift + 8 and 9 on my keyboard) 

notibly `LBracket` and `RBracket` are fired on the square brackets. (Altgr + 8 and 9)

Also noteworthy is the # key doesn't even have an associated keycode listed in the docs and is also dead on my layout.

On my system the following lablelled key functions result in no event being fired:
`^ ° ! " § $ % & ( ) ? ß ´ € Ü Ö Ä * ~ [Capslock] { } # < > | _ [PrintScrn] [WinKey]`

**Hardware and Software:**
 - ggez version: 0.5.1
 - OS: Linux (Arch)
 - Graphics card: Not applicable
 - Graphics card drivers: Not applicable
 - Keyboard layout: German

**Comment by IGBC** [comment]
Its hard to write a game about programming with all these dead keys

**Comment by ygt-mikekchar** [comment]
I'm running into a similar problem (though it might be something else I'm doing).  I have a Japanese keyboard and every time I run my game the keyboard seems to be reinitialized as  US keyboard (so I end up with US keybinding).  I suspect you may be running into the same issue.

**Comment by icefoxen** [comment]
Hey, thanks for the bug report.  Can confirm that something squirrelly is going on with modifiers; pressing `5` gets key down and key up events, but shift-`5` which is mapped to `%` on my keyboard doesn't.  `ggez` itself doesn't do anything particular with key handling or input languages, so we might have to bump this upstream to winit.  But, `ggez` may also just be doing it wrong.  I will investigate.

If you are doing text input, then I suggest looking at using `EventHandler::text_input_event()`, which should give you the actual character you type after it has gone through the keyboard's language layout and such.  Please let me know if you find any other weirdness.

**Comment by IGBC** [comment]
thanks for the workaround, I was able to proceed with game development.

**Comment by LFalch** [comment]
I'm getting the same problems as well as those @icefoxen mentions using a Danish keyboard layout. When holding shift and pressing number keys nothing registers except if it coincides with a key on a US layout. For example pressing Shift+0, gives me a KeyCode::Equals.

Using Ubuntu, btw, if that's relevant.

**Comment by Tairesh** [comment]
Also no one working key on keyboard with russian (cyrillic) layout, and, as I understand, no one non-english key ever. Is there any simple way I can fix it in my fork?

**Comment by PSteinhaus** [comment]
This should be able to be closed once https://github.com/ggez/ggez/pull/1028 is merged, right?
With `text_input_event` giving us entered characters, for when we want to do character input, and the scancodes being exposed when pressed, even when not belonging to any known english keycode, we should be good right?

Using bare scancodes to write you controls instead of keycodes is a bit less intuitive, surely, but it's not hard either.

**Comment by Tairesh** [comment]
> This should be able to be closed once #1028 is merged, right? 

Yes, scancodes are the best solution for checking pressed buttons in games, so if they are available, the lack of some keycodes will not be a problem.

**Comment by nobbele** [comment]
this seems to be resolved?
