### ISSUE TITLE
Nothing moves in all the examples

### ISSUE THREAD

**Issue by Bietola** [ggez/ggez#737]
I know the issue sounds super-vague, but it's all I have... none of the example code is interactive at all; sprites and meshes either flicker or stay completely still.

I don't even know where to begin in terms of debugging this (not really a graphics kind of guy) so ask me any information you need on my system and I will gladly share it to solve this.

I am using Ubuntu 18.04, cargo 1.39.0 and ggez 0.5.1.

Any will help will be greatly appreciated.

**Comment by icefoxen** [comment]
Well that sucks, sorry to hear that.  What graphics card are you using?  Even the `super_simple` example should have a moving component.

**Comment by 456actual** [comment]
I am having the same problem. By using println statements I can see that the app is running and updating and that it is responding to input, however the screen never updates. My graphics card is an NVIDIA GeForce GTX 1060. The drivers appear to be up to date (version 26.21.14.3186).

**Comment by 456actual** [comment]
I figured out what was going on in my case and am posting here in case others have the same problem. Even though I have an NVIDIA card, Windows was choosing to use the integrated graphics chip. You can fix this for NVIDIA by opening up the NVIDIA control center and setting for Performance.

**Comment by icefoxen** [comment]
That's weird as heck.  Thank you for updating us on the issue!
