### ISSUE TITLE
key_down_event fired only once event if multiple key down. 

### ISSUE THREAD

**Issue by LBdN** [ggez/ggez#741]
**Describe the bug**
I use the arrow key to control the player's ship. But only one movement (up or left) is applied when 2 arrows ( like up and left ) are pressed down. it seems that key_down_event fired only once event if multiple key down.

**To Reproduce**
Assign orthogonal effects to different keys in key_down_event and see that only one if applied when more than one key is down.

**Expected behavior**
During a frame, I would expect the key_down_event fired for each key down. 

**Screenshots or pasted code**
```
fn key_down_event(&mut self, ctx: &mut Context, keycode: KeyCode, _keymod: KeyMods,  _repeat: bool) {
        if let Some(p) = self.player.as_mut(){

            let mut movex = 0.0;
            let mut movey = 0.0;
            match keycode {                
                KeyCode::Right => {                    
                    movex = 10.0;
                }
                KeyCode::Left => {
                    movex = -10.0;
                }
                KeyCode::Up => {
                    movey = -10.0
                }
                KeyCode::Down => {
                    movey = 10.0
                }
                KeyCode::Space => {
                    
                }
                _ => {}
            }
            
            p.actor.transform.x += movex;
            p.actor.transform.y += movey;
            

        }
    }
```

**Hardware and Software:**
 - ggez version: release 0.5.1
 - OS: Windows 10,
 - Graphics card: NVidia GTX 2070
 - Graphics card drivers: vendor-provided

**Comment by icefoxen** [comment]
Thanks for the report, I'll try to verify.  In the mean time, are you sure this isn't a [key rollover](https://en.wikipedia.org/wiki/Rollover_(key)) issue?

**Comment by LBdN** [comment]
I would be surprised it is was, I am a kind of a keyboard nerd and have a mechanical one (  cooler master : masterkeys pro ).

**Comment by icefoxen** [comment]
I'll assume it isn't then, just had to sanity check.  ;-)

**Comment by ffactory-ofcl** [comment]
I'm not sure if I understand your expectations correctly. You say that 
> During a frame, I would expect the key_down_event fired for each key down
but that isn't the documented behaviour, is it? I will be fired once, only when the key is pressed down, for each key. Then, when released, the `key_release` event will fire. If you want the effect of the keypress to be continuously applied, you'll have to keep track of the pressed keys using a `Vec<KeyCode>` and then simulate your own `pressed` event within your update function. I've solved this by wrapping `KeyCode` in a `KeyPressInfo` struct that also has `delta` and `repeat_count` fields. In my update, I will fire the event again if a certain time has passed.
