### ISSUE TITLE
Flickering meshes on one pc work fine on another

### ISSUE THREAD

**Issue by ffactory-ofcl** [ggez/ggez#743]
**Describe the bug**
I made a tetris clone. It works fine on my main pc, but has a weird bug when running on my laptop. As you can see [here](https://i.imgur.com/36ZwUIR.png), the hold piece in the top left corner and the ghost piece at the bottom of the field are missing a square, which occasionally flickers in for a second. The missing square of the hold piece may be the isolated one below the three connected ones, but it being there makes no sense, as it works fine on my pc and I also use the same method to generate all three pieces (hold, normal and ghost) and the normal piece renders fine as well.

**To Reproduce**
You can download the released build from [here](https://cdn.discordapp.com/attachments/211410844020375552/671739835349860363/tetro-98.zip) and I can paste code snippets but reproducing without the whole project may be hard.

**Expected behavior**
The four squares should render correctly in all instances.

**Screenshots or pasted code**
See above.

**Hardware and Software:**
 - ggez version: 0.5.1 on both machines
 - OS: Windows 10 on both machines. Version 18xx on pc, 19xx on laptop
 - Graphics card: GTX 980 on pc, Geforce MX250 on laptop
 - Graphics card drivers: Newest nvidia drivers on pc, windows drivers on laptop

**Comment by ffactory-ofcl** [comment]
I'm reading about opengl texture flickering with multiple objects and it seems that either the opengl version or the fact that I call the `clear(ctx, color)` more than once. Does that help?

**Comment by ffactory-ofcl** [comment]
**I've fixed it!!**
Writeup for whomever may encounter this problem in the future.
It turns out my laptop has an integrated graphics card (intel something) that supports opengl 4.5, which is very power efficient and used for most programs. For demanding stuff, it also has the aforementioned Gefore MX250 which supports OpenGl 4.6. (I found that out using OpenGl extension viewer, which you can download [here](https://download.cnet.com/OpenGL-Extensions-Viewer/3000-18487_4-34442.html).) When I go into the Nvidia control panel and set my game to use the nvidia card, it works fine, just like on PC.

_Ideally_, that should not be needed. I'm not sure what causes the bug as it's pretty obscure and probably has something to do with the underlying gfx-rs crate and its implementation of opengl.
If you're interested in solving this mystery, I'm happy to help. If we find out the problem could lie in the gfx-rs crate, it might be a good idea to link to this issue.

**Comment by icefoxen** [comment]
Calling `clear()` more than once is usually a sign of something fishy in one's design, alas.  Can't really say more without seeing the actual code though.  The OpenGL version shouldn't matter, the difference between 4.5 and 4.6 is minimal.  More likely is the fact that the two different graphics cards (Intel and NVidia) will use different drivers, which will behave differently in odd edge cases.

**Comment by ffactory-ofcl** [comment]
Calling clear once makes no difference. Drawing a fourth box after drawing three of them fine shouldn't be an odd edge case though. It's so strange to me. If you want to, I can give you access to the repo / send you a link and you can tell for yourself. No pressure. Congrats on the great work with ggez other than that. After getting to grips with some new concepts it's a pleasure to use. Truly, a good game easily.

**Comment by gamma-delta** [comment]
Sorry to necro this, but I have this same problem on my new laptop. My old laptop works fine but my new one doesn't come with OpenGL 4.6 for some reason.

Right now I'm trying to install it (apparently this computer didn't come with GLSL v4.60) but I think this might be really frustrating for people trying to play any games made with GGEZ who aren't willing to muck around with their drivers...

**Comment by ffactory-ofcl** [comment]
@gamma-delta Do you have a second grafics card as well? Maybe this screenshot can help you, even though it's in German. Try looking around the program-specific settings. https://i.imgur.com/t4XfFhr.png
