### ISSUE TITLE
how to use it with specs

### ISSUE THREAD

**Issue by SET001** [ggez/ggez#745]
I'm trying to play with `ggez` and `specs` library. I'd like to have a component which would hold the mesh object `ggez::graphics::Mesh::new_circle` and a system that would spawn entities with such component. `ggez::graphics::Mesh::new_circle` needs a `Context` object. So I have, somehow to pass `Context` into the system. There are a few ways I tried.
1. Passing context in system constructor

```
pub struct ZombieSpawner<'a>{
  ctx: &'a mut Context
}
```
and then
```
    let zs = ZombieSpawner { ctx };
    let mut dispatcher = DispatcherBuilder::new()
        .with(zs, "ZombieSpawner", &[])
	.build();
```

2. Inserting it like resource
```
struct Foo<'a>{
  ctx: &'a Context
}
```
and then
```
world.insert(Foo{
      ctx
    });
```
In both cases, I'm getting the same error:

```
  --> src/state.rs:52:8
 error[E0277]: `(dyn ggez::vfs::VFS + 'static)` cannot be sent between threads safely
  --> src/state.rs:52:8
   |
52 |       .with(zs, "ZombieSpawner", &[])
   |        ^^^^ `(dyn ggez::vfs::VFS + 'static)` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `(dyn ggez::vfs::VFS + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn ggez::vfs::VFS + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn ggez::vfs::VFS + 'static)>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<std::boxed::Box<(dyn ggez::vfs::VFS + 'static)>>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<std::boxed::Box<(dyn ggez::vfs::VFS + 'static)>>`
   = note: required because it appears within the type `std::collections::VecDeque<std::boxed::Box<(dyn ggez::vfs::VFS + 'static)>>`
   = note: required because it appears within the type `ggez::vfs::OverlayFS`
   = note: required because it appears within the type `ggez::filesystem::Filesystem`
   = note: required because it appears within the type `ggez::context::Context`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&mut ggez::context::Context`
   = note: required because it appears within the type `systems::spawner::ZombieSpawner<'_>`
```

I started with Rust just a week ago so I can't solve this myself and need help. I suspect that there is something in `Context` that avoids if from being `sent between threads safely`. How can I solve this?

**Comment by ischeinkman** [comment]
Do you need to actually generate the meshes themselves in this system? Or can you generate some `CircleArg` components that then get translated to meshes later? 
In reality, since the dispatcher would be running the systems and manipulating the context independently of the main `ggez` loop, you can't really shove the context reference into a system you are putting into a dispatcher.
What I did personally was have a render system *outside* of the dispatcher that I call via [world.exec](https://docs.rs/specs/0.15.1/specs/world/struct.World.html#method.exec) during the `draw` method which actually generates the meshes and renders them on screen.
Also, this is more a bug tracker than a help forum as far as I am aware; I've personally found the Discord much better for this kind of question.

**Comment by SET001** [comment]
` Or can you generate some CircleArg components that then get translated to meshes later` I suppose I can for this demo I'm working on in learning purposes, but in real-world project where I would have hundreds of entities with meshes how do I organize that other that putting in appropriate system/component?

**Comment by mkhan45** [comment]
what I've done before is a component like 
```
struct Drawable {
    enum type
    Color color
    etc
} 
```
and then in the draw() function
```
(&positions, &drawables).join().for_each(|(pos, drawable) |{
    match drawable.type{
       ... 
    }
} 
```

sorry about formatting, I'm on my phone

**Comment by SET001** [comment]
@mkhan45 what if you were to have tens and hundreds of objects with different render logic? `match` does not look good enough here

**Comment by mkhan45** [comment]
If all the types of objects have different render logic you're gonna have to end up writing a bunch of render functions anyways. I personally don't think it's too bad to have something like this, but I might be a bit naive:
```
match drawable.type {
   DrawType::Circle(r) => draw_circle(ctx, r, pos),
   DrawType::Square(w, h) => draw_square(ctx, x, y, pos),
}
```

This is really more of an ECS problem than a ggez problem though. Context can't be passed to the systems in any way afaik so you have to draw things in the draw() function.

**Comment by SET001** [comment]
this approach may be kinda naive because you have to join components and loop them. But different loop logic may need different components. So you will end up multiple loops each with match with multiple arms

**Comment by icefoxen** [comment]
https://github.com/ggez/ggez/blob/master/docs/FAQ.md#can-i-use-specs-legion-or-another-entity-component-system

Also there are multiple projects using `specs` in https://github.com/ggez/ggez/blob/master/docs/Projects.md

**Comment by iolivia** [comment]
@SET001 I have a rendering system, the trick I used is using a system with RunNow as opposed to the standard specs dispatcher. I manually instantiate and call the render system in the draw loop. Works quite well.

```
// main.rs 

fn draw(&mut self, context: &mut Context) -> GameResult<()> {

        // Render game entities
        {
            let mut rs = RenderingSystem::new(context);
            rs.run_now(&self.world);
        }
}

```
