### ISSUE TITLE
cargo doc takes about 16m!!!

### ISSUE THREAD

**Issue by adals** [ggez/ggez#746]
**Describe the bug**
cargo doc takes 16m
**To Reproduce**
cargo doc
Finished dev [unoptimized + debuginfo] target(s) in 16m 00s

$ cargo -V
cargo 1.41.0 (626f0f40e 2019-12-03)
$ rustup -V
rustup 1.21.1 (7832b2ebe 2019-12-20)
$ rustc -V
rustc 1.41.0 (5e1a79984 2020-01-27)

my system is MacBook Pro

**Comment by icefoxen** [comment]
Hi, thanks for the bug report.  My own benchmarks, using the Rust 1.41 release:

Linode dual-core server: 9m 5s
i7-7700 4-core desktop: 1m 14s

So, it looks like docs parallelize well.  It also looks like it runs `cargo check` on most things as part of the process, and caches the result.  Rebuilding docs on the Linode server "only" took 4 minutes.  

Note that this doesn't document just ggez, it also generates docs for all 300+ dependencies, down to libc and rand.  Particular deps that take a long time to generate docs for: serde, winit, nalgebra.  Deleting and rebuilding the actual ggez docs, and its first-level deps, took 1m 15s on the Linode server.  Not really sure what I can do about that.  If you have any bright ideas, I'm open to suggestions.
