### ISSUE TITLE
Sound is kinda meh and needs to be better

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#75]
rodio sort of has a perfectly reasonable and logical structure that is also quite inconvenient to actually use.

**Comment by icefoxen** [comment]
Desired functionality:

 * Ability to modify pitch of sources
 * Ability to do easy fade-in, fade-out, cross-mixing
 * Ability to tell length of a Source, current position
 * Positional sound (see https://docs.rs/rodio/0.5.1/rodio/source/struct.Spatial.html and https://love2d.org/wiki/love.audio )

**Comment by rap2hpoutre** [comment]
Looping! I would be super happy with something like https://love2d.org/wiki/Source:setLooping (for a micro-game I'm building)

**Comment by icefoxen** [comment]
Good call!

**Comment by icefoxen** [comment]
global `audio::start()`, stop, volume functions, etc?

**Comment by icefoxen** [comment]
Being able to query where in a playing sound you currently are.

**Comment by Nokel81** [comment]
Would trying to add `rust-portaudio` be too outside the realm. Because if not I should have some time to try and give it ago.

**Comment by icefoxen** [comment]
Lots of this has been improved in devel.
