### ISSUE TITLE
Launching app without a window.

### ISSUE THREAD

**Issue by IGBC** [ggez/ggez#753]
Don't ask me why but I would like to launch my app without a GL context or window. I still need the event handling logic and Audio subsystem, while giving me control of the a main game loop to handle drawing outside of the GGEZ framework. 

(Basically I am trying to run my game on the console) 

Any ideas how I can do this?

Decoupling the game logic from the framework and generating my own events for terminal seems the logical start, but then tasks like triggering audio playback become challenging.

**Comment by felixwatts** [comment]
This would also be useful in the context of a networked client-server game. The server still wants to use the event loop and some of the utilities of the `Context` object but without creating a window.

**Comment by IGBC** [comment]
true although the difference is that in my use-case I still need most of the input system and the audio system to function normally.

**Comment by icefoxen** [comment]
This is out of scope for ggez I'm afraid.  The window is an integral part of the event handling, which is an integral part of the game loop.  I'd like it myself so that I could do better unit tests for ggez, but supporting this would make ggez far more complicated to serve an edge-case.

**Comment by IGBC** [comment]
> use a console game lib.

not too many of those around unfortunately. I think I have found a viable solution however.

**Comment by icefoxen** [comment]
`libtcod` is the main one I know about, and I thought there were a couple Rust spinoffs of it as well.  Good luck!  What's your solution, out of curiosity?

**Comment by IGBC** [comment]
>  What's your solution, out of curiosity?

Honestly?

Separate as much of the game logic as I can from the Engine, then write the game twice!
