### ISSUE TITLE
WGL_ARB_create_context_profile not found

### ISSUE THREAD

**Issue by IGBC** [ggez/ggez#758]
**Describe the bug**
Window won't launch with the error `Error: WindowCreationError(NotSupported("required extension \"WGL_ARB_create_context_profile\" not found"))`

**To Reproduce**
Run a GGEZ game on windows 10 pro 64 bit with a lenovo X220 (intel 2500U with HD3000 Graphics)

**Expected behavior**
A window should apear

**Screenshots or pasted code**
nope

**Hardware and Software:**
 - ggez version: 0.5.1 release
 - OS: For example, Windows 10 pro 64 bit
 - Graphics card: Intel HD 3000 (OpenGL 3.1)
 - Graphics card drivers: 9.17.10.4229 5-26-2015 (Win 8.1 Build)

I hate Intel too, they never released an official Win 10 driver for the 2nd Gen Chipset, the 8.1 driver is supposed to be compatible. (yes other openGL applications work fine on the system)

**Comment by icefoxen** [comment]
Hmmm, that's interesting, though annoying.  ggez unfortunately doesn't support OpenGL 3.1, so I'm not sure what I can do to help make this work.
