### ISSUE TITLE
Make the library more modular

### ISSUE THREAD

**Issue by felixwatts** [ggez/ggez#760]
Currently many of utilities and services of ggez are rolled into one monolith: the `Context`. The utilities are written so that the user needs a whole Context object in order to use them, even though in many cases this is not a technical requirement. For example, take the function `ggez::timer::delta(ctx: &Context)`:

```
pub fn delta(ctx: &Context) -> time::Duration {
    let tc = &ctx.timer_context;
    tc.frame_durations.latest()
}
```
The function takes a `Context` object then only uses the `timer_context` field of it. If `delta()` was a method of `TimeContext` then it would be possible to use the function without having to create a `Context`, which comes with a file system and a graphics system etc.
 ```
impl TimeContext {
...
    pub fn delta(&self) -> time::Duration {
        self.frame_durations.latest()
    }
}
...
let mut time_context = ggez::time::TimeContext::new();
time_context.tick();
let delta = time_context.delta();
```
This pattern occurs in a few places and restricts the ways in which ggez can be used. It could easily be fixed as shown and the old API could be kept as well for backwards compatibility if required.

**Comment by icefoxen** [comment]
This has been discussed some in #480 .  I'm happy to discuss it further but we can do it there.
