### ISSUE TITLE
Wrong window size

### ISSUE THREAD

**Issue by mrlogick** [ggez/ggez#761]
With ggez 0.5.1, and i3 (window manager) with ArchLinux.
```
extern crate ggez;
use ggez::conf::{WindowSetup, WindowMode, NumSamples, FullscreenType};
use ggez::{Context, ContextBuilder, GameResult};
use ggez::event::{self, EventHandler};
use ggez::graphics;

fn main() -> GameResult {
    let (mut ctx, mut event_loop) = ContextBuilder::new("game", "author")
            .window_setup(WindowSetup::default()
                .title("Title")
                .samples(NumSamples::Zero)
                .vsync(false))
            .window_mode(WindowMode::default()
                .dimensions(320.0, 240.0)
                .maximized(false)
                .fullscreen_type(FullscreenType::Windowed)
                .borderless(false)
                .min_dimensions(0.0, 0.0)
                .max_dimensions(0.0, 0.0)
                .resizable(false))
            .build()?;
    let mut my_game = MyGame::new(&mut ctx);
    event::run(&mut ctx, &mut event_loop, &mut my_game)
}

struct MyGame { }
impl MyGame {
    pub fn new(_ctx: &mut Context) -> MyGame {
        MyGame { }
    }
}
impl EventHandler for MyGame {
    fn update(&mut self, _ctx: &mut Context) -> GameResult<()> {
        Ok(())
    }
    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx, graphics::WHITE);
        graphics::present(ctx)
    }
}
```
This program simply creates a white window with size: 320x240px. But in my laptop it's a bit larger than that. If I compare the window with one with the real dimensions I can see the difference. I tried several resolutions, the window it's always a bit larger than what I put in the source code. It scales proportionally: (about 7-8% I think). The problem persists even in fullscreen.

![screenshot](https://user-images.githubusercontent.com/22934806/78510437-5ea62280-7795-11ea-8e4d-c7ebbd41a15e.png)

I tried to run the same binary file in other two different laptops: with one laptop I had no issue, the window was exactly 320x240 (with xfce). With the other laptop the window was scaled but even more than mine. I tried to change xfce's dpi, but nothing.

**Comment by icefoxen** [comment]
First hunch is a hidpi issue; search the issue tracker for that to find various background info.  Does it change at all if you set the env variable `WINIT_HIDPI_FACTOR=1` ?

**Comment by mrlogick** [comment]
Thanks man! it worked.
`$ WINIT_HIDPI_FACTOR=1 cargo run --release`
Is there a function in ggez to manage this?

**Comment by icefoxen** [comment]
Not currently, but hopefully there will be in another version or two.

If you set that environment variable in your `main()` function before creating your `Context`, that should have the same effect.
