### ISSUE TITLE
Draw SpriteBatch is very slow: 27% of times is spent in DrawParam::to_matrix 

### ISSUE THREAD

**Issue by Datoh** [ggez/ggez#764]
**Describe the bug**
I would like to use GGEZ to draw a lot of sprites. For sample, I created a spritebatch of tiles (10 tiles on one row). Then I draw 200 000 times one of them at a random position. Perf are very bad compare to the same sample in LibGDX.

For instance, 27% of the time is spent in DrawParam::to_matrix

My sample code: [https://pastebin.com/3DGXJ3ah](https://pastebin.com/3DGXJ3ah)
The profiling screenshot: [https://ibb.co/1LdDHLk](https://ibb.co/1LdDHLk)

**Comment by icefoxen** [comment]
200000 sprites is a lot, yes.

Try using the `master` branch and see what you get, please.  There's been some serious performance improvements made in this PR: https://github.com/ggez/ggez/pull/716 .  I really need to make a release just to include those.
