### ISSUE TITLE
Open GL 2.1 support

### ISSUE THREAD

**Issue by gillesboisson** [ggez/ggez#770]
It seams opengl 2.1 not supported, I tried the getting started tutorial with opengl 2.1

```rs
// ...
fn main() {
    // Make a Context.

    let mut conf = Conf::new();
    let backend = Backend::OpenGL { major: 2, minor: 1 };
    // let backend = Backend::OpenGL { major: 3, minor: 2 };
    conf = conf.backend(backend);

    let mut cb = ContextBuilder::new("my_game", "Cool Game Author");

    cb = cb.conf(conf);

    let (mut ctx, mut event_loop) = cb.build().expect("aieee, could not create ggez context!");
	// ...
}

```

I tried on a raspberry pi and had this issue 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.18.2/src/factory.rs:152:9
```

I did some test with Piston to check if opengl 2.1 is supported by the device, and it seems to be supported.

Is there any thing else to do ?

**Comment by icefoxen** [comment]
Unfortunately OpenGL 2 is not supported.  Have to put the lowest bar on hardware somewhere.  :(  I do want to change this someday, but can't promise anything.
