### ISSUE TITLE
Enable MacOS gamepad support by default

### ISSUE THREAD

**Issue by bhickey** [ggez/ggez#773]
With issues #577 and #588 closed, gamepad support should be enabled by default.

https://github.com/ggez/ggez/blob/efdab624d346532f913bc8b9096dffacb3effbb5/src/conf.rs#L339

**Comment by icefoxen** [comment]
Sounds reasonable to me.  Fixed in devel branch, can you test and see if it works properly?

Thanks.

**Comment by bhickey** [comment]
Works for me!
