### ISSUE TITLE
Can't programmatically resize window without setting window as resizable

### ISSUE THREAD

**Issue by tomasgvivo** [ggez/ggez#777]
**Describe the bug**
I want to be able to update the window size after it's created (built).
I understand I can do this by updating the window mode and screen coordinates. But it only works if I set the new window mode as resizable... which is not the desired effect.

**To Reproduce**
(note this code works, but not if resizable is set to false)
```
let rect = graphics::Rect::new(0.0, 0.0, width, height);

let new_mode = WindowMode {
    width: rect.w,
    height: rect.h,
    maximized: false,
    fullscreen_type: FullscreenType::Windowed,
    borderless: false,
    min_width: 0.0,
    max_width: 0.0,
    min_height: 0.0,
    max_height: 0.0,
    resizable: true // This must set to true to apply the new size to the window. But it also allows the user to manually resize it.
};

graphics::set_mode(&mut ctx, new_mode);
graphics::set_screen_coordinates(&mut ctx, rect);
```

**Expected behavior**
I expect that the width and height of the window mode is applied to the window despite resizable being false.

**Hardware and Software:**
 - ggez version: 0.5.1
 - OS: Linux (Ubuntu 18.04)
 - Graphics card: NVidia RTX 2070 Super
 - Graphics card drivers: NVidia version 440.64.00

**Comment by vini-fda** [comment]
Weird. One workaround that I **thought** I had found was to just set the window as resizable _before_ resizing it through graphics::set_mode. After you're done resizing it, just switch back to a non-resizable window:

```rust
//(on fn main()), after building the window
[...]
    let new_rect = ggez::graphics::Rect::new(0.0,0.0, 480.0, 800.0);

    let new_mode = conf::WindowMode {
        width: new_rect.w,
        height: new_rect.h,
        maximized: false,
        fullscreen_type: ggez::conf::FullscreenType::Windowed,
        borderless: false,
        min_width: 0.0,
        max_width: 0.0,
        min_height: 0.0,
        max_height: 0.0,
        resizable: true, //Shouldn't really matter, as we're setting the mode to resizable before
        visible: true,
    };

    ggez::graphics::set_resizable(&mut ctx, true)?; //Set to resizable
    ggez::graphics::set_mode(&mut ctx, new_mode)?; //Apply changes
    ggez::graphics::set_screen_coordinates(&mut ctx, new_rect)?; //Update screen coordinates
    ggez::graphics::set_resizable(&mut ctx, false)?; //Set to non-resizable -> the code doesn't work!
[...]
```

But that has the effect of the window just being the default size(the one with which it was built), and not the new size, given by the dimensions of `new_rect`.

My ggez version is from the devel branch in this repository. Currently at commit c97f6f6a2f92e7d01c1fc1c215b5311b73f1e17b.

I'm using Kubuntu 20.04, running on an Nvidia RTX 2060. Currently installed driver version: 450.80.02

**Comment by PSteinhaus** [comment]
Just tested this using the devel branch and it seems to be fixed (probably by #884 or by something winit did?).
Could you test this again using 0.6.0-rc1 or the devel branch?

**Comment by cdknight** [comment]
@PSteinhaus I'm on 0.7 and this is still an issue.

**Comment by PSteinhaus** [comment]
Weird, for me on 0.7 it works fine. What exactly is your issue?

The following code allows me to resize the window without setting it to be resizable:
```rust
let rect = graphics::Rect::new(0.0, 0.0, 500.0, 500.0);

let new_mode = WindowMode {
    width: rect.w,
    height: rect.h,
    maximized: false,
    fullscreen_type: FullscreenType::Windowed,
    borderless: false,
    min_width: 0.0,
    max_width: 0.0,
    min_height: 0.0,
    max_height: 0.0,
    resizable: false, // no need to set this `true`
    visible: true,
    resize_on_scale_factor_change: false
};

graphics::set_mode(ctx, new_mode);
graphics::set_screen_coordinates(ctx, rect);
```

**Comment by Vixeliz** [comment]
I think this has been open (and without a response from a non maintainer) long enough we can close since we can't reproduce it
