### ISSUE TITLE
Question: How can I draw a single pixel?

### ISSUE THREAD

**Issue by tomasgvivo** [ggez/ggez#778]
It seems that in version 0.3.x it was possible using graphics::point().
Is it possible to do that on version 0.5.x?

**Comment by icefoxen** [comment]
Draw a 1x1 image, or draw a tiny `Mesh`.

Note that drawing complicated things out of single pixels is super inefficient; if you want an image buffer or something you can draw your "pixels" to a vector containing RGBA bytes, turn it into an `Image` using `Image::from_rgba8()`, and draw the `Image`.

**Comment by tomasgvivo** [comment]
@icefoxen Thank you very much.
I know it's inefficient to an entire image pixel by pixel. But it's part of an api I want to implement and expose.
I'm trying to re-implement the Processing framework in rust using ggez. So, expect more questions :smile:.

**Comment by icefoxen** [comment]
Best way is probably to have your own pixel buffer with a `Vec<u8>` and turn it into an `Image` each frame to get displayed, in that case.

**Comment by IGBC** [comment]
Seems resolved. If OP has further questions please reopen.

If OP wants to link to their project that would be cool.
