### ISSUE TITLE
Make stroked circles/ellipses work

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#78]
This will need a PR to Lyon, alas.  Shouldn't be hard though, the ellipse drawing code is already pretty much there, and figuring out normals shouldn't be too hard.

**Comment by nical** [comment]
As of 0.6.0, lyon supports stroking circles (but lost support for ellipses).

**Comment by icefoxen** [comment]
This will get a lot easier when #116 is done then!  :D
