### ISSUE TITLE
Performance issues drawing old-school rpg-like dialogue boxes and text

### ISSUE THREAD

**Issue by rshadown** [ggez/ggez#780]
I am building an old-school RPG (in the style of SNES RPG's; for example Final Fantasy 6).

I do not want all the text to appear instantaneously. I would like text in dialogue boxes to appear letter by letter. Example:
Frame 1: 'H'
Frame 2: 'He'
Frame 3: 'Hel'
Frame 4: 'Hell'
Frame 5: 'Hello'
An example of this effect in the aforementioned FF6: https://youtu.be/iGNskqYu2_0?t=168

I got a rudimentary version of this working. I draw a few meshes for the dialogue-box. Build up my Text from several TextFragments (multiple ones, since sizes, font, colors, etc, might vary in the same text). And then render a bit more of the text every frame.

So every frame in the GameLoop, a bunch of TextFragments are created and a single 'Text' is created. However, this introduces what I can only describe as very noticeable lag-spikes / FPS drops. I cannot re-use the same Text struct because the text being displayed changes constantly (until it completes, at which point I can just re-render the same Text).

I read through some topics and issues, and understand that this is because creating Text objects is slow in GGEZ. So I am trying to figure out how do to this:
- I cannot create the Text struct once, because it will keep changing until it is done
- I tried covering it up with other meshes and slowly revealing the text, but this is clumsy and you lose the option to have a transparent dialogue-box
- Running in release mode did not seem to have any noticeable effect

Is there a way I can achieve my desired effect?

**Comment by nobbele** [comment]
I think it's called a typewriter effect if you wanna change the title to something easier. Been looking at how to do this too but couldn't think anything better than what you did.

**Comment by Ratysz** [comment]
Would something like this work?
```rust
use ggez::{
    conf::{WindowMode, WindowSetup},
    event,
    graphics::{self, Color, Text, TextFragment},
    timer, {Context, ContextBuilder, GameResult},
};
use nalgebra::Point2;
use std::f32;

struct App {
    text: Text,
    cursor: usize,
    frame_count: u64,
}

const TEXT_COLOR: Color = Color::new(1.0, 1.0, 1.0, 0.0);

impl App {
    fn new() -> Self {
        let mut text = Text::new(TextFragment::new("H").color(TEXT_COLOR));
        text.add(TextFragment::new("e").color(TEXT_COLOR))
            .add(TextFragment::new("l").color(TEXT_COLOR))
            .add(TextFragment::new("l").color(TEXT_COLOR))
            .add(TextFragment::new("o").color(TEXT_COLOR))
            .add(TextFragment::new("!").color(TEXT_COLOR));
        Self {
            text,
            cursor: 0,
            frame_count: 0,
        }
    }
}

impl event::EventHandler for App {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        const DESIRED_FPS: u32 = 60;
        const TYPEWRITER_FRAMES_PER_LETTER: u64 = 15;

        if self.frame_count % TYPEWRITER_FRAMES_PER_LETTER == 0 {
            if self.cursor < self.text.fragments().len() {
                if let Some(color) = &mut self.text.fragments_mut()[self.cursor].color {
                    color.a = 1.0;
                }
                self.cursor += 1;
            } else {
                for fragment in self.text.fragments_mut() {
                    if let Some(color) = &mut fragment.color {
                        color.a = 0.0;
                    }
                }
                self.cursor = 0;
            }
        }

        while timer::check_update_time(ctx, DESIRED_FPS) {}
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, [0.2, 0.2, 0.2, 1.0].into());
        graphics::draw(ctx, &self.text, (Point2::new(50.0, 50.0), graphics::WHITE))?;
        graphics::present(ctx)?;
        self.frame_count += 1;
        timer::yield_now();
        Ok(())
    }

    fn resize_event(&mut self, ctx: &mut Context, width: f32, height: f32) {
        graphics::set_screen_coordinates(ctx, graphics::Rect::new(0.0, 0.0, width, height))
            .unwrap();
    }
}

fn main() -> GameResult {
    let (ctx, events_loop) = &mut ContextBuilder::new("typewriter", "ggez")
        .window_setup(WindowSetup::default().title("Typewriter example!"))
        .window_mode(
            WindowMode::default()
                .dimensions(640.0, 480.0)
                .resizable(true),
        )
        .build()?;
    let mut app = App::new();
    event::run(ctx, events_loop, &mut app)
}

```
(The trick is changing the letter's opacity.)

**Comment by nobbele** [comment]
that does work

**Comment by icefoxen** [comment]
That's interesting though, 'cause this shouldn't be slow, especially in release mode.  Drawing/modifying text should be fast, it's just an array of letters, and mesh offsets in a spritebatch.

**Comment by icefoxen** [comment]
This is investigated more in #867 , which includes a link upstream to `glyph_brush` that has some interesting info in it.  So, closing this in favor of that one.
