### ISSUE TITLE
Building complex meshes

### ISSUE THREAD

**Issue by akiross** [ggez/ggez#781]
First of all, thanks for ggez: I have been playing with it to practice with Rust and I really like it so far.

I'm trying to display a few things on the screen, which involve some "complex" meshes. What I would actually love is to have paths, gradients and boolean operations between paths. I get this is an hard task to implement, but since lyon is being used, is it possible to have access (or wrap) it when building meshes?

Lyon provides already some interesting features like quadratic/cubic Bézier curves: is it possible to have access to those?

**Comment by icefoxen** [comment]
At that point it's easiest to just build the geometry you want using Lyon and pass it to `Mesh::from_triangles()`
