### ISSUE TITLE
did center method disapear from old versions ?

### ISSUE THREAD

**Issue by laticoda** [ggez/ggez#788]
i need to check if the center of my little rectangle is inside a bigger one (not just hiting the border). i fear type conversions while doing it my self (Mesh, not Mesh,...).

**Comment by PSteinhaus** [comment]
I know I'm a bit late, but could you please explain what exactly you're trying to do?

If you want to calculate the center of a Rect you can just do so yourself:
```rust
fn center(rect: &Rect) -> Vec2 {
    Vec2::new(rect.x + rect.w / 2. , rect.y + rect.h / 2.)
}
```

**Comment by icefoxen** [comment]
There's also https://docs.rs/ggez/0.6.0-rc0/ggez/graphics/struct.Rect.html#method.center

**Comment by PSteinhaus** [comment]
Closing this since the question seems to have been answered.
