### ISSUE TITLE
The Road To 0.3

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#79]
There's few enough things now and they're small enough that it's easier to consolidate them into one issue

* Make more filesystem tests
* ~~Make sure filesystem user/data/config dirs are consistent and sensible~~
* ~~Make sure Srgb is always correct~~
* ~~Make sure bitmap fonts work (issue #64)~~
* Hit it with Clippy again
* ~~Test on Windows (issue #31)~~
* Update website
* Party down

Stuff that's being punted for later:

* Path tessellation for circles/ellipses (Issue #78)
* Sound system improvements (Issue #75)
* Graphics coordinate system BS
* Better ZipFS paths

**Comment by svenstaro** [comment]
Isn't this done by definition?

**Comment by icefoxen** [comment]
Yep, sorry.
