### ISSUE TITLE
Need Click and Drag to select

### ISSUE THREAD

**Issue by laticoda** [ggez/ggez#791]
Hello, i have to to send an army of rectangles to war , does exist something already implemented in GGEZ to **click and drag** them easily like in Command and Conquer : 
Click+Drag to select several units ;

So, i can add this:
 Selected + Ctrl + 1 : for grouping army 1,;
 deselect;
 Selected + Ctrl+2 for grouping army 2 ...

**Comment by Manghi** [comment]
Nothing like this exists in `ggez`, but you should be able to build that logic up yourself by using the interfaces it provides. See [`mouse_motion_event`](https://docs.rs/ggez/0.5.1/ggez/event/trait.EventHandler.html#method.mouse_motion_event), and it's friends the `mouse_button_down_event`, `mouse_button_up_event`. They'll provide the mouse X/Y coordinate so you just have to figure out what to do with the event/data.

**Comment by laticoda** [comment]
thank you Manghi
