### ISSUE TITLE
where does screenshot go ?

### ISSUE THREAD

**Issue by laticoda** [ggez/ggez#796]
hello, i cant find the resulting image, is it a bug or i was looking wrong ? I didn(t see any path in the doc.
I tried this inside update:
```
if keyboard::is_key_pressed(ctx, keyboard::KeyCode::P) {
            ggez::graphics::screenshot(ctx);
            
        }
```

**Comment by laticoda** [comment]
and is it possible to customize name picture and path ?

**Comment by BrettWitty** [comment]
If you look at the documentation for [screenshot](https://docs.rs/ggez/0.5.1/ggez/graphics/fn.screenshot.html), the function returns a `GameResult<Image>`. Your code doesn't do anything with that. You need to unwrap the `GameResult<Image>` and then encode it to a file.

You'll want something more like:
```rust
if keyboard::is_key_pressed(ctx, keyboard::KeyCode::P) {

    // Get a screenshot and store it as a GameResult<Image>
    match ggez::graphics::screenshot(ctx) {

        Ok(image) => image.encode(ctx, ggez::graphics::ImageFormat::Png, path::Path::new("/screenshots/1.png")),
        Err(_) => () // Do some error handling
        
    }
}
```

If you want to know where that path ends up, look at the [filesystem crate](https://docs.rs/ggez/0.5.1/ggez/filesystem/index.html).
