### ISSUE TITLE
Mesh is missing UV's

### ISSUE THREAD

**Issue by OvermindDL1** [ggez/ggez#801]
**Describe the bug**
Only way to set UV's on a Mesh currently is to use the raw function.  Should be able to set UV's for the individual helpers as well such as `rectangle` or `circle` by passing in a Rect and it inline the helper within that to maximum space usage.

**To Reproduce**
Mesh(Builder) has no ability to set UV's via helpers.

**Expected behavior**
Should be able to set UV's so we can properly match which parts of the texture goes to which parts of the mesh on the various helpers like `rectangle` via perhaps a Rect  passed to things like `circle` and `ellipse` that it can pull from (so they are filled/centered in that Rect of UV).

**Hardware and Software:**
 - ggez version: current git master
 - OS: Linux Ubuntu
 - Graphics card: AMD POLARIS
 - Graphics card drivers: MESA 20.*

**Comment by icefoxen** [comment]
There's UV's for filled meshes, beyond that I wasn't sure how to do it even remotely sanely.  Having a helper or hook for it isn't a terrible idea, might be nice to try out.
