### ISSUE TITLE
05_astroblasto doesn't build

### ISSUE THREAD

**Issue by Kinrany** [ggez/ggez#802]
The [05_astroblasto](https://github.com/ggez/ggez/blob/master/examples/05_astroblasto.rs) example doesn't build.

`nalgebra::Point2<f32>` does not implement `Into<mint::Point2<f32>>`.

**To Reproduce**
 * create a new Rust binary project
 * add `ggez`, `rand` and `nalgebra` to `Cargo.toml`
 * copy-paste the example to `src/main.rs`
 * run `cargo build`

**Screenshots or pasted code**

```rust
fn draw_actor(
  assets: &mut Assets,
  ctx: &mut Context,
  actor: &Actor,
  world_coords: (f32, f32),
) -> GameResult {
  let (screen_w, screen_h) = world_coords;
  let pos = world_to_screen_coords(screen_w, screen_h, actor.pos);
  let image = assets.actor_image(actor);
  let drawparams = graphics::DrawParam::new()
    .dest(pos)
    .rotation(actor.facing as f32)
    .offset(Point2::new(0.5, 0.5));
  graphics::draw(ctx, image, drawparams)
}
```

```
error[E0277]: the trait bound `mint::vector::Point2<f32>: std::convert::From<nalgebra::geometry::point::Point<f32, nalgebra::base::dimension::U2>>` is not satisfied
   --> src\main.rs:415:6
    |
415 |     .dest(pos)
    |      ^^^^ the trait `std::convert::From<nalgebra::geometry::point::Point<f32, nalgebra::base::dimension::U2>>` is not implemented for `mint::vector::Point2<f32>`
    |
    = help: the following implementations were found:
              <mint::vector::Point2<T> as std::convert::From<[T; 2]>>
              <mint::vector::Point2<T> as std::convert::From<mint::vector::Vector2<T>>>
    = note: required because of the requirements on the impl of `std::convert::Into<mint::vector::Point2<f32>>` for `nalgebra::geometry::point::Point<f32, nalgebra::base::dimension::U2>`
```

**Hardware and Software:**
 - ggez version: release `0.5.1`
 - OS: Windows 10

**Comment by Ratysz** [comment]
This may have been caused by `nalgebra` version mismatch somewhere.

**Comment by AlbertoGP** [comment]
Yes, you need a version of `nalgebra` that is compatible with the one used in that version of `ggez`, and you can find out which one it is from https://crates.io/crates/ggez under “Dependencies”, where you can see that `ggez 0.5.1` uses `nalgebra 0.18`.

Therefore, in your `Cargo.toml` you need to specify that version, or a compatible one:
```
[dependencies]
ggez = "0.5.1"
rand = "0.7"
nalgebra = "0.18"
```

With this, and copying the `resources/` directory, you can copy-paste `05_astroblasto.rs` (or another example) into your `src/main.rs` and it compiles and runs fine.

**Comment by Kinrany** [comment]
I guess `use nalgebra as na;` should be replaced with `use ggez::nalgebra as na;`?

**Comment by AlbertoGP** [comment]
I’m not a ggez maintainer, but I think that makes a lot of sense so I’ve made a pull request that fixes the issue for all examples affected:
- 05_astroblasto
- bunnymark
- cube
- graphics_settings
- hello_canvas
- transforms

I’ve just tested each one with this change and they all work fine.
