### ISSUE TITLE
There is no way to set the position of a window!! Please provide access to set_position().

### ISSUE THREAD

**Issue by squint2** [ggez/ggez#807]
There is no way to set the GGEZ window position.

**Comment by Ratysz** [comment]
I'm assuming you're the person who emailed me earlier? Did the solution I gave (`ggez::graphics::window()` then `winit::Window::set_position()`) not work?

**Comment by squint2** [comment]
Yes, I'm the person who emailed you earlier.
Yes, you really helped me with your expert suggestion!  I know I shouldn't contact you, but you really helped a desperate Rustacean newb in need. Thanks again!
 // Set window position here  let (ref mut ctx, event_loop) = &mut cb.build()?; let window = graphics::window(ctx); let mut pos = window.get_position().unwrap(); pos.x = 0.0; pos.y = 0.0; window.set_position(pos);

    On Tuesday, August 4, 2020, 06:37:49 AM MDT, Alexander Sepity <notifications@github.com> wrote:  
 
 


I'm assuming you're the person who emailed me earlier? Did the solution I gave (ggez::graphics::window() then winit::Window::set_position()) not work?

**Comment by icefoxen** [comment]
Looks like this has mutated a little in recent versions of winit but is still there: <https://docs.rs/winit/0.22.2/winit/window/struct.Window.html#method.outer_position>  I thought it had been removed.  Thanks, Ratysz.

**Comment by icefoxen** [comment]
Resolved in  #839.  :heart:
