### ISSUE TITLE
OpenGL ES 2 support

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#808]
This is a wishlist/tracking issue on the feasibility of this.  Basically, there's lots of hardware still out there that's old as heck but is also cheap as heck and so is getting used for cool things.  Clockwork Pi, Pinebook Pro, ODroid C2, Raspberry Pi 3, etc.  This hardware is now outdated, but is still *useful*, so it should still be useful.

This is going to be a bit wild though.  There will be design compromises.

Things OpenGL ES 2 lacks:

 * VAO's
 * Instanced drawing
 * Indirect drawing
 * Scripting language is more stupid
 * Shader attribute layout info
 * Sampler objects

Things OpenGL ES 2 still has:

 * VBO's
 * Vertex+fragment shaders
 * Indexed drawing
 * Lame GLSL with bad version numbers

**Comment by Vixeliz** [comment]
@nobbele I think we can close this no? Since ggez uses wgpu now? It doesn't support es 2.0 but it has gles 3.0 plus I don't think there are any plans to have multiple graphic backends

**Comment by sampullman** [comment]
Yeah, this unfortunately relies on `wgpu` adding support for ES 2.0 (unlikely), or GGEZ adding support for multiple backends. Maybe OSMesa would work through wgpu at some point? For Raspberry PI specifically, there are some interesting options like this: https://github.com/Yours3lf/rpi-vk-driver

Maybe I'll try getting that Vulkan driver working on an old PI 2B, but I think it's safe to close this issue.
