### ISSUE TITLE
Creating and using a custom pipeline

### ISSUE THREAD

**Issue by arunchaganty** [ggez/ggez#809]
For a game I'm building, I need to use two `sampler2D` textures in a shader (fragment shader code below); the TL;DR of this issue is a request for pointers on how to support such a use case.

As I understand it, this requires me to create a new gfx pipeline. I've been using [this post](https://wiki.alopex.li/LearningGfx) as a reference, and in an attempt to get something to work with minimal effort, I forked `ggez` and updated `ggez::graphics::pipe` to include an additional texture `t_Aux`, and accordingly updated `pipe::Data`. The code compiles, tests pass and shaders that do not use the new `t_Aux` work fine. However, when compiling a shader that does use the new `t_Aux` variables causes a panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VideoError("Error constructing pipeline!\nThis should probably not be happening; it probably means an error in a shader or something.\nError was: DescriptorInit(ResourceView(\"t_Aux\", None))")', src/main.rs:60:21
```

A minimal set of edits that might be relevant is here, though the full version is probably easier to see [here](https://github.com/ggez/ggez/compare/master...arunchaganty:aux-texture?expand=1).

```rust
impl GraphicsContextGeneric<GlBackendSpec> {
    /// Create a new GraphicsContext
    pub(crate) fn new()
        // ...
        let typed_thingy_copy = backend.raw_to_typed_shader_resource(white_image.texture.clone());
        let sampler_copy = samplers.get_or_insert(sampler_info, &mut factory);

        let data = pipe::Data {
            vbuf: quad_vertex_buffer.clone(),
            tex: (typed_thingy, sampler),
            // Adding the aux texture data
            aux: (typed_thingy_copy, sampler_copy),
            rect_instance_properties: rect_inst_props,
            globals: globals_buffer,
            out: screen_render_target.clone(),
        };
       // ...
```

Accompanying fragment shader:

```glsl
/**
 * Advects flow 
 */
#version 150 core

/** The underlying texture we are advecting. **/
uniform sampler2D t_Texture;

/** The underlying texture we are advecting. **/
uniform sampler2D t_Aux;
/** Our coordinates **/
in vec2 v_Uv;
/** Final output **/
out vec4 Target0;

layout (std140) uniform ShaderState {
    vec4 u_Color;
    vec2 u_ScreenSize;
    vec2 u_Pos;
    uint u_Tick;
    float u_TimeDelta;
};

void main() {
  // Get the previous timestamp.
  vec2 u = v_Uv - u_TimeDelta * texture(t_Aux, v_Uv).xy;
  Target0 = texture(t_Texture, u);
}
```

**Comment by animanathome** [comment]
Hi @arunchaganty, did you get this working? I'm trying to do the same thing. Any help would be much appreciated.

**Comment by arunchaganty** [comment]
Ah, no I did not and gave up on the endeavor :/

**Comment by nobbele** [comment]
Two samplers should be possible now, if I understand the issue correctly
