### ISSUE TITLE
Panic when trying to draw text

### ISSUE THREAD

**Issue by Peohta** [ggez/ggez#810]
I tried to run `02_hello_world.rs` and got the following:

```thread 'main' panicked at 'Error InvalidOperation executing command: UpdateTexture(TextureCopyRegion { texture: 2, kind: D2(256, 256, Single), cube_face: None, info: ImageInfoCommon { xoffset: 14, yoffset: 0, zoffset: 0, width: 14, height: 35, depth: 0, format: Format(R8_G8_B8_A8, Srgb), mipmap: 0 } }, DataPointer { offset: 64, size: 1960 })', C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.16.2\src\lib.rs:828:13```

```04_snake.rs``` works flawlessly.

**Setup:**
 - ggez = "0.5",
 - OS: Windows 10,
 - Graphics card: ATI Radeon 3000 Graphics,
- Opengl 3.3

**Comment by icefoxen** [comment]
Not able to duplicate this I'm afraid.  :-(
