### ISSUE TITLE
Question: Is there a way to draw on a specific area without using Canvas?

### ISSUE THREAD

**Issue by atsisy** [ggez/ggez#817]
Hello. I want to draw a ```ggez::graphics::Mesh``` on a ```ggez::graphics::Canvas``` with multi-sampling enabled, but #695  says
I can't do that. Is there a way to draw on a specific area without using Canvas?

**Comment by icefoxen** [comment]
Not sure what you mean by this question.  Just draw the mesh wherever you want it to be with `ggez::graphics::draw()`, setting location/scale/etc using a `DrawParam`.
