### ISSUE TITLE
Canvas is trimmed when bigger than the window

### ISSUE THREAD

**Issue by GOKOP** [ggez/ggez#818]
**Describe the bug**
Creating a canvas bigger than the window will result in the canvas being silently trimmed to the size of the window. This can be easily seen when scaling down the canvas.

**To Reproduce**
Setup basic rendering, create a canvas that's bigger than the window created for the program, print something to it so you can see what's going on, then print the texture with DrawPram that scales it down by 0.5 for example

**Expected behavior**
I'd expect the canvas to exist and work as declared, or to panic (although this is the less preferred option)

**Hardware and Software:**
 - ggez version: 0.5.1
 - OS: Artix Linux
 - Graphics card: NVidia GTX 960
 - Graphics card drivers: proprietary

**Comment by jabdoa2** [comment]
DId you call `graphics::set_screen_coordinates` after activating your canvas? Otherwise, you might get the effect you described.

**Comment by GOKOP** [comment]
Seems like this was the issue. Thanks!

**Comment by jabdoa2** [comment]
Do you know where you copied your code from? At which docs did you look? Maybe we can add a reference there so future users know.
