### ISSUE TITLE
Make an example using ezing

### ISSUE THREAD

**Issue by svenstaro** [ggez/ggez#82]
This is basically a memo to myself to make a little example using https://github.com/michaelfairley/ezing

**Comment by termhn** [comment]
My [branch of ggez-goodies](https://github.com/termhn/ggez-goodies) now uses ezing as the recommended provider of easing functions for the camera and uses it in the camera example.

**Comment by icefoxen** [comment]
https://github.com/ggez/ggez-goodies should probably also use ezing in the particle system.

**Comment by nico-abram** [comment]
Can this be closed now that that PR was merged?

**Comment by icefoxen** [comment]
Yep, thanks!
