### ISSUE TITLE
Version bump gilrs to v0.8 for MacOS hats support

### ISSUE THREAD

**Issue by bhickey** [ggez/ggez#829]
`gilrs` shipped hats support on MacOS in version 0.8 (thanks @CleanCut!) Bumping the dependency will automatically pull this feature into `ggez`. I've verified this in my own development.

**Comment by CleanCut** [comment]
@bhickey You are most welcome! 😄

**Comment by icefoxen** [comment]
This has been bumped in the `devel` branch, please try it out and see how it goes!
