### ISSUE TITLE
Error NotAvailablePixelFormat

### ISSUE THREAD

**Issue by shirshak55** [ggez/ggez#835]
ggez version = 0.5
graphics card Nvidea GTX 1070
Driver version = 26.1
DirectX 12

When i run the example input it gives me following error

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target\debug\ui.exe`
Error: WindowCreationError(NoAvailablePixelFormat)
error: process didn't exit successfully: `target\debug\ui.exe` (exit code: 1)
```

Is it because I am using remote desktop on microsoft windows?

**Comment by icefoxen** [comment]
That's the most likely explaination, 3D graphics stuff (which is almost all graphics these days) generally doesn't work well with remote desktop.
