### ISSUE TITLE
MeshBuilder's methods don't return same type 

### ISSUE THREAD

**Issue by Mayrixon** [ggez/ggez#840]
As I found in the document, the methods of `graphics::MeshBuilder` would return different type. The methods `circle()`, `ellipse()`, `rectangle()`, `texture()` and `raw()` would return `MeshBuilder`, while others would return `GameResult<MeshBuilder>`. This may confuse people when creating meshes.

Would you like to change these methods to make sure that people not thinking adding question mark at the end of each method?

**Comment by TrveFenris** [comment]
I can easily make this change but we'd need @icefoxen 's input here. Do we want to return `MeshBuilder` or `GameResult` from each of the methods? This will be a breaking change.

**Comment by Mayrixon** [comment]
I agree that would be a big change but we have two convenient excuses for the API's changing:
1. `ggez`'s version is still below `1.0`.
2. Cargo would do the great work on the package version control.

But anyway, as you said, we need the response.

**Comment by icefoxen** [comment]
Good call; some of these methods can fail and others can't, but having the same result for all of them would be a good idea.  If we make everything return `GameResult<MeshBuilder>` we could get it done in the 0.6 version I'm hoping to release at the end of the year.  PR's welcome!

**Comment by icefoxen** [comment]
Resolved by #848
