### ISSUE TITLE
Few questions regarding this project.

### ISSUE THREAD

**Issue by Joe23232** [ggez/ggez#841]
Hi I have a few questions regarding this project:

1. Can this do 3D graphics?
2. Is there a GUI game editor, preferably a Blender addon integration? If not is it being planned to be made?
3. Does it have ECS integration?
4. Is there some forum page or a Discord server or something?
5. Is this game engine supposed to be simpler to code in compared to the [Bevy game engine](https://bevyengine.org/)?
6. What are the compile times like?

**Comment by tlboright** [comment]
Hey @Joe23232 ,
I think I can answer a couple of your questions at least.
I've been building a prototype with this for the past couple weeks.
There is a good starting point boilerplate project with ECS integration through the [specs](https://github.com/amethyst/specs) crate [here](https://github.com/ggez/game-template).
This is what I've been building with.

Compile times have been fine for me, especially after the first cargo run.  My project is currently small, however, so I assume times will go up as I add more code.

**Comment by Joe23232** [comment]
@tlboright I see, thanks mate :)

**Comment by icefoxen** [comment]
Can this do 3D graphics?

In theory, but not very well.  You basically 

    Is there a GUI game editor, preferably a Blender addon integration? If not is it being planned to be made?

No and no, at least not by me.  I don't have the time.

    Does it have ECS integration?

Not directly, but it's designed to be usable with just about any ECS crate.  I've used it with `specs` and `hecs` personally.

    Is there some forum page or a Discord server or something?

Occasionally discussion happens on Reddit in /r/rust_gamedev , and there's a fair few people on the [Rust Community Discord](https://discord.com/invite/tcbkpyQ) and the [Rust Gamedev Discord](https://discord.gg/yNtPTb2) who are familiar with ggez (including myself).

    Is this game engine supposed to be simpler to code in compared to the Bevy game engine?

I haven't used Bevy, so, I don't know.  I expect ggez will be smaller and more minimal, but simpler for simple things.  My experience is that the more complete/complicated your game becomes, the more the features from more complicated game engines matter.

    What are the compile times like?

They're okay-ish at best.  Compiling ggez itself from scratch with all dependencies takes a good couple minutes, especially in release mode or on old hardware, but compiling a game that *uses* ggez is usually much quicker.  I'm making a game with it now (using the `devel` branch) and once all the dependencies are built, the game itself builds in ~8 seconds on mediocre hardware.

**Comment by Joe23232** [comment]
I see, thanks mate for letting me know
