### ISSUE TITLE
basic shapes in meshbuilder are missing a rounded rectangle for menus.

### ISSUE THREAD

**Issue by tlboright** [ggez/ggez#844]
This is more of an enhancement, but I noticed there isn't a rounded_rectangle (with border radius) type of basic shape.
I saw that lyon will have support for them in their tessellations [here](https://github.com/nical/lyon/blob/c1160f1e312182c9e95d263caf19007eb68d1168/path/src/builder.rs#L1058).

Do people think this could be helpful to add to ggez?

**Comment by tlboright** [comment]
I just realized this was for a pr that was

**Comment by icefoxen** [comment]
Sure, seems reasonable to me.  It's a pretty common shape, especially for UI stuff as you said.

**Comment by icefoxen** [comment]
Easily done, the functions are here: https://docs.rs/lyon_tessellation/0.16.2/lyon_tessellation/basic_shapes/fn.fill_rounded_rectangle.html

**Comment by icefoxen** [comment]
Fixed in #860.
