### ISSUE TITLE
BindVao error with Arrayfire

### ISSUE THREAD

**Issue by littleTitan** [ggez/ggez#845]
**Describe the bug**
The bug seems to be an issue with the BindVao command and something from Arrayfire interfering.

**To Reproduce**
Install Arrayfire

cargo.toml
```rust,skt-template
arrayfire 3.7.2
```

main.rs
```rust,skt-template
use arrayfire::set_device;

// anywhere in the draw eventloop of a ggez program 
set_device(0); // or any array creation or manipulation
```

**Expected behavior**
thread main will panic:

thread 'main' panicked at 'Error InvalidOperation executing command: BindVao', C:\Users\%USERNAME%\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.16.2\src\lib.rs:828:13

**Screenshots or pasted code**

```rust,skt-template
/// Super simple example with Arrayfire

use ggez;
use ggez::event;
use ggez::graphics;
use ggez::nalgebra as na;
use ggez::{Context, GameResult};
use arrayfire::set_device;

struct MainState {
    pos_x: f32,
}

impl MainState {
    fn new() -> GameResult<MainState> {
        let s = MainState { pos_x: 0.0 };
        Ok(s)
    }
}

impl event::EventHandler for MainState {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        self.pos_x = self.pos_x % 800.0 + 1.0;
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        set_device(0); // <--

        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());

        let circle = graphics::Mesh::new_circle(
            ctx,
            graphics::DrawMode::fill(),
            na::Point2::new(0.0, 0.0),
            100.0,
            2.0,
            graphics::WHITE,
        )?;
        graphics::draw(ctx, &circle, (na::Point2::new(self.pos_x, 380.0),))?;

        graphics::present(ctx)?;
        Ok(())
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("super_simple", "ggez");
    let (ctx, event_loop) = &mut cb.build()?;
    let state = &mut MainState::new()?;
    event::run(ctx, event_loop, state)
}
```

**Hardware and Software:**
 - ggez version: 0.5.1
 - arrayfire version: 3.7.2
 - OS: Windows 10
 - Graphics card: Intel HD Graphics 520
 - Graphics card drivers: vendor-provided

**Comment by icefoxen** [comment]
Sorry @littleTitan , was there a resolution or fix to this?

**Comment by littleTitan** [comment]
As it turns out calling the set_device function in the draw loop seemed to cause the issue. However, a call to set_device in the main function seemed to resolve the issue. After the call was made, I was able to create and modify arrays within the draw loop freely.
