### ISSUE TITLE
License compliance issue

### ISSUE THREAD

**Issue by jnqnfe** [ggez/ggez#846]
I would like to bring to your attention the fact that your licensing is incompatible with your dependencies.

Your crate is MIT licensed but depends upon multiple crates which are Apache-2.0 licensed only. While Apache-2.0 projects can use MIT licensed components, the reverse is not so.

Consider for instance that MIT is GPL v2 compatible, while Apache-2.0 is not; Your crate being MIT licensed is thus misleading to any potential GPL-v2 projects that consider using your crate - they'd end up constructing a non-compliant product.

**Comment by jnqnfe** [comment]
Actually, looking into things a little more today, I believe I was mistaken about the compatibility issue. Apologies for the noise, please ignore. (The last sentence is correct though, your project being MIT licensed rather than Apache-2.0 or 'MIT OR Apache-2.0 masks the underlying use of Apache-2.0 only components which could lead to users making such mistakes with GPL projects).

**Comment by icefoxen** [comment]
Thanks for the heads up anyway though, good to know.
