### ISSUE TITLE
State stack?

### ISSUE THREAD

**Issue by HaNaK0** [ggez/ggez#864]
For me it seems like the engine should have a state stack due to the fact that you specify a state whenever you start the event loop. I know this isn't a feature present in löve but it's something that could be useful for most people using the engine. Especially usefull for things like loading screens and menues.

**Suggestion**
- To add a state stack letting you change state by pushing it ontop of another or swaping it for the topemost state
- To add functionality to be able to controll if an event is let through to a state below the current one

**Comment by icefoxen** [comment]
It's easy enough to add and hard enough to get *right for every game* that I personally think it's best to leave this out and let people use their own.
