### ISSUE TITLE
Changing the drawable size should automatically rescale the coordinate system

### ISSUE THREAD

**Issue by tesselode** [ggez/ggez#866]
**Describe the bug**
Changing the drawable size doesn't adjust the coordinate system, leading to unintuitive scaling issues.

**To Reproduce**
Run this code and press F11 to switch window sizes:
```rust
use std::error::Error;

use ggez::{
	event::{EventHandler, KeyCode, KeyMods},
	graphics, Context, ContextBuilder, GameResult,
};
use graphics::{DrawMode, Mesh};

pub struct MainState {
	fullscreen: bool,
}

impl MainState {
	pub fn new() -> Self {
		Self { fullscreen: false }
	}
}

impl EventHandler for MainState {
	fn key_down_event(
		&mut self,
		ctx: &mut Context,
		keycode: KeyCode,
		_keymods: KeyMods,
		_repeat: bool,
	) {
		match keycode {
			KeyCode::F11 => {
				if self.fullscreen {
					graphics::set_drawable_size(ctx, 800.0, 600.0).unwrap();
				} else {
					graphics::set_drawable_size(ctx, 1280.0, 720.0).unwrap();
				}
				self.fullscreen = !self.fullscreen;
			}
			_ => {}
		}
	}

	fn update(&mut self, _ctx: &mut Context) -> GameResult {
		Ok(())
	}

	fn draw(&mut self, ctx: &mut Context) -> GameResult {
		graphics::clear(ctx, graphics::BLACK);
		let (drawable_width, drawable_height) = graphics::drawable_size(ctx);
		let circle = Mesh::new_circle(
			ctx,
			DrawMode::fill(),
			[drawable_width / 2.0, drawable_height / 2.0],
			drawable_height / 2.0,
			0.1,
			graphics::WHITE,
		)?;
		graphics::draw(ctx, &circle, ([0.0, 0.0],))?;
		graphics::present(ctx)?;
		Ok(())
	}
}

fn main() -> Result<(), Box<dyn Error>> {
	let (ctx, event_loop) = ContextBuilder::new("test", "test").build()?;
	let main_state = MainState::new();
	ggez::event::run(ctx, event_loop, main_state);
}
```

**Expected behavior**
I expected the circle to remain centered in the window and the top and bottom of the circle to remain touching the top and bottom of the window, respectively.

**Screenshots or pasted code**
Before changing the window size:
![image](https://user-images.githubusercontent.com/2637802/103609761-912fa800-4eec-11eb-83a3-dea6818b5564.png)

After changing the window size:
![image](https://user-images.githubusercontent.com/2637802/103609777-97be1f80-4eec-11eb-92fa-ae0f953204ca.png)

**Hardware and Software:**
 - ggez version: current git devel
 - OS: Windows 10
 - Graphics card: NVidia GTX 970

**Comment by tesselode** [comment]
I thought about this a little more, and while this behavior is confusing for someone coming from LOVE, it is nice if you want to have a fixed coordinate system and scale it to fill the screen. So games with simple scaling needs will benefit from this.

This isn't really a bug, just a consideration.

**Comment by adam-bates** [comment]
I actually prefer the way it is now. What I love about ggez is how EZ is it is to make a GG (and by that I mean a simple 2D game lol). In this case we only need to design for a single coordinate system, and let the draw calls scale to whatever window size.

I think it's fair to maintain this, but also communicate how to scale with the window size if it's what you want for your game, (as the `graphics_settings` example does):
```rust
impl event::EventHandler for MainState {
    fn resize_event(&mut self, ctx: &mut Context, width: f32, height: f32) {
            graphics::set_screen_coordinates(ctx, [0., 0., width, height].into()).unwrap();
    }
}
```

**Comment by icefoxen** [comment]
Related: https://github.com/ggez/ggez/pull/690
