### ISSUE TITLE
Low text performance

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#867]
I'm having performance issues with texts, possibly related to #780.

I tried running the text example on two different machines:

- my own PC (Windows 10, GTX 1060 3GB, driver version: 27.21.14.5671)
- and an older PC (Windows 7, Radeon HD 5450, driver version 15.201.1701.0)

It runs very poorly on my machine (either 50 FPS, if I set the screen refresh rate to 60, or about 105 if I set it to 120), while it runs smoothly on the older PC. 
I'm using ggez 5.1 running in release mode.

I've had similar problems when trying to use texts in the game I'm currently working on (changing the string of a single text or its position leads to major performance issues on the first, but not on the second machine for some reason).

I know this might be hard to replicate and debug, but text seems to be such an important feature to me that I still wanted to mention this.
I'll gladly supply more info. Just tell me what you need.

**Comment by adam-bates** [comment]
Can you provide some code that replicates this issue for you?

**Comment by PSteinhaus** [comment]
[This example](https://github.com/ggez/ggez/blob/master/examples/text.rs) is what I'm referring to.

**Comment by adam-bates** [comment]
Ah, it was worth asking just in case it was something that could be solved without a deep understanding of GGEZ, but considering it's an example and it runs smooth for me, I'll leave this one to the pros

**Comment by icefoxen** [comment]
That's a weird one, gotta admit.  Not sure what would cause that, since others with nvidia cards or such haven't reported similar problems AFAIR.  What's the CPU usage like when you run the text example?

**Comment by PSteinhaus** [comment]
The CPU usage is something like 25%.
For reference: Running a test of my own game (which is based on a physics simulation of a graph where the edges are springs) with something like a thousand nodes and two thousand edges takes about half of that.

**Comment by icefoxen** [comment]
And just so I have all the information, this is just using the `example/text.rs` example?  Have you tried in both master and devel branch?

**Comment by PSteinhaus** [comment]
Yes, I'm just using ```example/text.rs```.
I was running on master, but I just tried running it on the devel branch and interestingly I do now get 50% CPU usage and less than half the framerate...

**Comment by icefoxen** [comment]
Confirmed, `text` example in current devel branch consumes ~30-40% of my CPU, built in release mode.  Debian Linux, Ryzen 3700X, AMD RX 480 GPU.  Interestingly, on Windows 10, it uses 4-5% CPU measured using task manager, which is more what I'd expect (Ryzen 2600, AMD RX 5700).

Some profiling on the Linux machine shows that about 30% of this time is spent in `crossbeam` of all things, which should be far from necessary... wonder if `glyph_brush` is getting a little over-elaborate?  :sweat_smile:  Bumping this upstream to see if they have anything to say about it.

Potential alternatives to `glyph_brush`: `fontdue`, `elefont`...?

**Comment by icefoxen** [comment]
Tested this on `glyph_brush` 0.7.2 and it went from 40% CPU to like 5%.  Good times.

**Comment by PSteinhaus** [comment]
Just tested it and can confirm it as well :)
