### ISSUE TITLE
Bitmap font support

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#868]
I really like to work with bitmap fonts and I've been thinking about implementing my own bitmap font system ontop of a Spritebatch.
I ran into some performance issues using the current text system recently (see #867), so now I'm even more determined to write it and I'd like to ask if there's any interest in integrating such a feature into ggez.

Reading the documentation and older issues I found out that there once was bitmap font support in ggez, but it disappeared some versions ago. I'd really like to know why and what you think about bringing bitmap support back by simply using a spritebatch to hold the spritefont and working with the existing interface to replicate the behavior of Text (though that would probably mean having to implement alignment and wrapping ourselves).

This would probably lead to adding a second independant text system though and I'm not sure whether such an addition would be useful enough to justify this increase in complexity.

**Comment by adam-bates** [comment]
As far as I understand it, under the hood, ggez already uses [glyph-brush](https://github.com/alexheretic/glyph-brush) to break down into characters with offsets and draw using spritebatch.

I've gotten bitmap fonts working in my game using the default method of loading fonts. Could you maybe elaborate on what's not working for you, or maybe provide code? I'm no ggez expert but I could try to help.

**Comment by PSteinhaus** [comment]
Oh that's interesting. How do you load your fonts? From what I can see the [Font struct used by Text](https://docs.rs/ggez/0.5.1/ggez/graphics/struct.Font.html) is only meant as a handle for Truetype font.

**Comment by adam-bates** [comment]
Ahh maybe I'm just misunderstanding here (my background is REST APIs so please forgive my lack of knowledge in this department), but I looked up and downloaded a bitmap font, which has a `.ttf` extension. And that worked perfectly.

I'm now guessing there's another extension meant for bitmap fonts that are not yet supported? Is that correct?

**Comment by PSteinhaus** [comment]
```.ttf``` means that it's a Truetype font, [which is a vector font](https://en.wikipedia.org/wiki/Computer_font#OUTLINE) and no bitmap font by definition.

Maybe you meant that it is a pixel-style font?

You're correct that bitmap fonts would have a different extension, which are currently not supported (as far as I can see).

**Comment by icefoxen** [comment]
Under the hood ggez already uses a `SpriteBatch` for font drawing, along with `glyph_brush` to manage font rendering and caching as PSteinhaus helpfully mentioned.  So a more optimized text system *shouldn't* be necessary.  In general I'd be reluctant to accept another text system, but better optimizing what's there wouldn't be a bad idea.

**Comment by PSteinhaus** [comment]
Looking a bit deeper into this I asked myself whether this might be a limitation of ```glyph_brush```, and looking into that I found out that you yourself did ask whether bitmap font support should be integrated since it's basically a pretty simple edge case where everything could happen as it currently does, just without the initial stage of creating bitmaps from vector texts, here: alexheretic/glyph-brush/issues/17

I totally agree with you there, but seeing that this issue is still open and nowhere near closure I want to cite your final comment on this issue here:

> That said, for ggez it's not too hard to write our own bitmap font stuff using instanced textures anyway. That might be easiest since bitmap fonts have a lot of properties that make them simple: they don't change, often all the glyphs are the same size, all the rendering has been done for you already, etc. That might be the easiest option all around.

This is exactly what I'm about to do. But for my personal needs I don't need wrapping, layouts etc. so I plan on creating something very small just for myself. The question is whether we might want to implement this a bit more thorougly and then integrate it into ggez itself, so that it functions as a second text system.

Adding another text system is something I as well am not all that sure about, but I imagine that everyone wanting to use bitmap fonts would run into this issue and would thus have to create his own system again and again, so I think it might be worthwhile.

On the other hand... the **perfect** solution (it seems to me) would be to go and solve this issue within glyph-brush, so that everyone can profit off that and no ugly second system API needs to be established.

**Comment by PSteinhaus** [comment]
I'm closing this now, since I mainly agree that building your own solution for this is not that difficult and probably even best given the unknown font formats that one may want to use.

It would still be nice if glyph-brush one day had support for bitmap fonts, though...
