### ISSUE TITLE
DrawParam { src } is not measured in pixels

### ISSUE THREAD

**Issue by eiko** [ggez/ggez#87]
the documentation says the src rect for DrawParam is in pixels, but it's actually a fraction. eg:

` DrawParam { src: Rect::new(0.0, 0.0, 0.5, 1.0) .. Default::default() }`

will display only the left half of the image. 

which is correct and which is the bug- the code or the documentation?

**Comment by icefoxen** [comment]
Exciting!  I'll double-check this and figure out which it should be.  Thanks for the report.

**Comment by icefoxen** [comment]
Looks like it should be pixels, per <www.love2d.org/wiki/love.graphics.newQuad>

BUT

That makes it impossible to have `DrawParam::default()` create a default that is "the whole image" for any image.

So I think the current behavior is the objectively correct one.  I will update the docs to reflect this.  Thank you!
