### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#875]
Been thinking about this for a while, but it's time for me to officially step down from maintaining ggez.  It's been a rough year, work is probably going to consume even more of my time and energy in 2021, and I really want to be able to move on to spending time on other projects.  Maybe even make a game for once!

So it's been a good ride, but when  you spend multiple months actively avoiding looking at github issues, it's time to step down.  I wouldn't trade this for the world, but I've been doing it for over four years now, so it's time to move on.  So after the 0.6.0 release any active development, responses to issues or pull requests will be on a 100% "if I feel like it" basis with no commitments.  I'll probably honestly stop following the issue tracker.

If anyone wants to step up and take over maintainership of ggez, reply here and we'll talk.

**Comment by AaronM04** [comment]
Thanks for the hard work you've put into ggez! [Our game](https://github.com/conwayste/conwayste) wouldn't have come nearly as far as it has without it.

From my vantage point, it seems like this may be a job for more than one person, and even if there's some other person out there who can take this on all by themselves, well, they may be unwilling to step up because of the size of this. However, delegating smaller components to people may be more feasible.

Also, it may be worth looking into [OpenCollective](https://opencollective.com/) or something similar as a way for developers to get compensated for the work they do on ggez. Without this, there is a tendency for the "un-fun" parts of an open source project to not get done. Just an idea.

**Comment by icefoxen** [comment]
> Also, it may be worth looking into OpenCollective or something similar as a way for developers to get compensated for the work they do on ggez. Without this, there is a tendency for the "un-fun" parts of an open source project to not get done. Just an idea.

Just for reference, I had a Patreon for a while -- and technically still have it, though I don't ask for donations anymore.  It's paid for some new computer hardware for testing different platforms, and a lot of money given to other patreon people I like, but currently my bottleneck really isn't money since I already make more than I need.  More just a matter of what I put my creative time and energy into.

**Comment by AaronM04** [comment]
Oh yeah, I figured time was the bottleneck for you. I'm thinking of other contributors in the future; donations may make a difference for them.

**Comment by alula** [comment]
Well I think I might have time to maintain ggez, since [doukutsu-rs](https://github.com/doukutsu-rs) depends on it, the project-specific fork even has (hacky atm) support for Android already and I was thinking about building a dx11 backend and modularizing it recently.

**Comment by Andy-Python-Programmer** [comment]
> If anyone wants to step up and take over maintainership of ggez, reply here and we'll talk.

Hello icefoxen!! First of all thanks for all of your hard work on ggez! The game recently I made called CallofFerris would not have been possible without ggez. Also I am a 13 year old programmer so, after school and play time I think I have plenty time to maintain ggez and I would love to!

**Comment by GiraffeKey** [comment]
I wouldn't have the time or resources for full maintenance, however if anyone leaves a bounty on Bountysource every now and then I'd be interested in helping out! May do some volunteer work regardless as I am interested in this project.

OpenCollective -> Bountysource would be an interesting financial pipeline.

**Comment by icefoxen** [comment]
It actually would.  OpenCollective or github donations that funneled into bounties for particular issues would be kinda cool.

The main problem with that is that bug fixes and feature enhancements are only part of the story, the other part is curation.  Deciding what goes in and doesn't, looking at old stuff and reworking or removing it when it becomes unnecessary, writing docs for releases, etc.  Sometimes this involves telling contributors "no", or taking something half-done and finishing it off.  I have a hard time seeing a good way of doing that with bounties.

**Comment by IGBC** [comment]
If you can stay onboard with the project till the end of the year I can take over the roll in the late summer.

I am developing a "proper" game on GGEZ with at least 12 months of development left ahead of it, and past that was planning on building an engine ontop of GGEZ's framework, for personal use. So its safe to say I have a vested interest in keeping it alive and available.

I have three years in rust, most of it in the embedded scene. I have seen how communities live and die, and I think I am well positioned to maintain the engine for the next few years.

**Comment by icefoxen** [comment]
Hi @IGBC , and thanks for the kind offer!  Out of curiosity, is there any particular direction you'd like to see ggez going in the future?  What do you like/dislike about it?  Basically, if you were in charge of GGEZ, what would you want to do with it?

This is a *little* bit of an interview, but also just me being curious :smile: .  I've done a bit of thinking about how to do this well lately, and it basically comes down to "figure out what goals are", "make sure there's some long-term commitment involved", and "give commit access for a trial period".  This isn't a promise, just how I'm thinking about the problem for now.

**Comment by nobbele** [comment]
I've been working on my own library-thing using this library for quite some time. I could definitely spend time helping out if there's a need

**Comment by alula** [comment]
I'm fine with working in a team.

My project switched away from ggez for several reasons, but that doesn't mean I won't use it in a future project or wouldn't want to improve it in certain ways - my first thing to do would likely be modularizing it, since some projects don't need stuff such as TTF don't rendering or want to run their own audio pipeline.

I've also had plans to give some maintenance to the legacy `gfx` crate - notably by updating it to latest `winit` and improving the GLES support in certain ARM platforms.

**Comment by erlend-sh** [comment]
This would be a good time for prospective ggez leaders to familiarize themselves with the [miniquad discussion](https://github.com/ggez/ggez/issues/71).

@not-fl3 has been continuously improving it for the past year since the discussion paused. And he even expressed willingness to do a lot of the work & guidance necessary to port ggez to miniquad, if I understand his comment correctly. This basically means giving ggez full mobile & web support. If several of the new leaders just give this proposal the 🆗, that’s already a big step forward for ggez set in motion.

**Comment by Andy-Python-Programmer** [comment]
It will be great to be a part of the team!

**Comment by IGBC** [comment]
my main focus would be to turn some of the major interfaces into modules, I like the idea that the graphics system can be turned off for example, allowing a client and server to share the same code base. I would also focus on bringing a vulkan backend to the rendering once that is a module that can be so easilly switched.

However past a few small quality of life changes I think the biggest roll for maintaining GGEZ is preventing feature creep. RN GGEZ's biggest asset is its small (ish) API which is easy to learn, and biggest boon is compile time. Adding progressively more features over the next 5 years will hurt both of those and possibly remove the appeal of GGEZ for new developers.

Also I will lobby for bringing back NAlgebra ;) (the new system is so clunky!)

**Comment by icefoxen** [comment]
@PSteinhaus Any thoughts? You're the one who's done the most ticket triage and communication lately.

**Comment by PSteinhaus** [comment]
I feel honored and I'd be lying if I told you that I didn't think about applying for maintainership.

But to be honest I really don't want to take on this responsibility, neither alone, nor in a team. I have a bad history of binding myself to projects for way longer than I actually want and I really want to stop doing that. I'm sorry.

Nevertheless, I think I'm going to follow the developement of ggez for a bit longer and I hope that I can be of a little help to the future maintainers, whoever they may be :)

**Comment by IGBC** [comment]
@PSteinhaus Fixing Canvases? What's broken with Canvases?

**Comment by PSteinhaus** [comment]
@IGBC well there's #747, #693, #694, #411 and if you're still not convinced there's #390  ;-)
And there's more. Search for "canvas" in the issue tracker.

For most things one might just be able to get them to work somehow, but it would be so much better if we could just trust in them instead of applying workarounds and praying all the time.

**Comment by PSteinhaus** [comment]
> @PSteinhaus Any thoughts? You're the one who's done the most ticket triage and communication lately.

To revive the conversation I want to say that, having had a bit more time to think about it, I'd be ready to take over maintenance for ggez, at least temporary. 
I still don't know whether this is something I want to commit to in the long term, but I could definately imagine to maintain it until the end of the year, when @IGBC and/or @alula / @nobbele could take over.

I think others that have stepped up here are better suited than me to maintain ggez in the long run, due to their experience, but in the short term I may be able to keep the development somewhat running and especially to handle a good portion of the upcoming issues.

I'm currently doing my master in computer science, but this semester is going to be a bit more relaxed, so I have time to spare. I have something like 5 years of coding experience and a half year of Rust, so I'm as I said not the most experienced developer, but I think I've gained enough of an understanding of the inner workings of ggez to be able to maintain it, though I probably wouldn't attempt any big leaps or additions.

**Comment by nobbele** [comment]
I do have time to maintain it, what about co-maintaining?

**Comment by PSteinhaus** [comment]
I'd absolutely appreciate that.

**Comment by nobbele** [comment]
@icefoxen what do you think

**Comment by icefoxen** [comment]
I'M BACK!  ...briefly.  Holy hell it's been a crazy three months.  I'm sorry for leaving everything hanging for so long.

@nobbele and @PSteinhaus , I hereby nominate you as provisional maintainers.  Your task: Help get everything shipshape for a 0.6.0 release.  I'll help where I can, but I won't lie, it won't be too much.  Once we do that and make a release, if you're not scared off yet, I'll step down.  

I have added "Maintainer's code of conduct" to [the CONTRIBUTING.md file here](https://github.com/ggez/ggez/blob/master/CONTRIBUTING.md#maintainers-code-of-conduct), outlining the conduct expected of project maintainers.  If you agree to this, post here saying so and I'll grant commit access.  Thank you so much for putting up with me!

@IGBC , still interested in the same deal?

**Comment by nobbele** [comment]
I agree to follow the maintainer's code of conduct

**Comment by PSteinhaus** [comment]
I too hereby agree to follow the maintainer's code of conduct.

**Comment by icefoxen** [comment]
Thank you!  You should both have invitations to the org, and permission to commit, merge PR's, etc.  Ping me here or by email if you have any issues.

**Comment by nobbele** [comment]
I made a mistake of merging a PR into master (forgot to check what the PR merged into), luckily it was docs only and has been reverted anyway (is there a better way to revert on github than to re-PR a revert or reset in the CLI?) but, we should probably get some kind of bot to tell people to PR into devel rather than master

**Comment by icefoxen** [comment]
A bot to control PR's would be nice, actually.  I never thought of that myself, but I'm in favor.  I just don't know how to actually set it up...  As for reverting changes on github, I seem to recall there's a way to create a new commit that reverts an existing one, but it's not really any different than reverting from the git CLI.

Winit has issues creating contexts outside of main threads 'cause some OS's don't let you do that, as far as I recall.  I can't find an issue for it at the moment, but you can get around it by doing `cargo test -- --test-threads=1`.  This is the sort of issues that behavior fixes:  https://github.com/rust-windowing/winit/issues/1107  In general the answer to the question "how do I multithread windowing/graphics" seems to be "you don't", and this is an OS-level issue... you *can* write such code, but you'll use OS-specific API's to do it.

**Comment by nobbele** [comment]
the revert pr is what I did

**Comment by icefoxen** [comment]
Okay, note for future reference that the https://ggez.rs/ website domain is run by @svenstaro , and its contents are in https://github.com/ggez/ggez.github.io .  I asked him on discord and his response was pretty much "it's not very expensive, I'll keep paying for the domain".  I've kinda ignored it for quite a while (*awkward cough*) since IMO github does everything we need it to do, but it's there to do stuff with if we ever want to.

**Comment by IGBC** [comment]
> @IGBC , still interested in the same deal?

woa waiting six days to reply is probably not a good look.

Yea I am still interested in the same deal, tho I am still 2 weeks away from finishing Uni and having time to work on the project, (which yes means I am busy doing exams for the next 2 weeks)

**Comment by icefoxen** [comment]
> woa waiting six days to reply is probably not a good look.

I mean, I waited two months to reply earlier, so I'm not exactly going to blame you.

I sent you an invite, but concentrate on exams for now.

**Comment by IGBC** [comment]
I hereby agree to uphold the maintainers code of conduct as well.

**Comment by IGBC** [comment]
@icefoxen @nobbele @PSteinhaus is there a developer chat anywhere. It would be good to have somewhere where we can ask eachother questions, especially about meta stuff, such as what is the policy on closing issues, and do I fork or branch. You know admin boring stuff, that doesn't need to clutter up the issue board.

**Comment by nobbele** [comment]
Thought of that too maybe a discord server or something

**Comment by IGBC** [comment]
I can't use discord (or won't on ethical grounds) So I would suggest Matrix.

**Comment by nobbele** [comment]
Fair

**Comment by icefoxen** [comment]
I mostly just use the Unofficial Rust or Rust Gamedev Discord's as my communication media.  I'm fine with Matrix or IRC instead, no real preference.

**Comment by IGBC** [comment]
> Fair (is a bridge fine?)

Bridge to where? Currently IRC is going through "a transitional" period bridging into that mess is a disaster RN.

TBH I think it might just be simplest to make a room on Matrix.org and hand out invites to the members of the dev team.

**Comment by nobbele** [comment]
My id is @nobbele:matrix.org I guess. Not sure if that's what you need to invite, not that familiar with matrix.

**Comment by PSteinhaus** [comment]
Mine is @psteinhaus:matrix.org.

**Comment by svenstaro** [comment]
I suggest you guys start a public Matrix channel and stick a badge in the README so people know where to find it. :)

**Comment by nobbele** [comment]
and that's where discord(+bridge) makes more sense in my opinion. I don't see how a public community can be properly organized on matrix when there's only one channel and most people don't even have matrix anyway. It doesn't matter that much but that's my thoughts.

**Comment by IGBC** [comment]
> Mine is @PSteinhaus:matrix.org.

I have added @nobbele to the room but @PSteinhaus my matrix client says there is no one registered with the name @PSteinhaus:matrix.org (or anything similar).

**Comment by PSteinhaus** [comment]
Oops, my mistake. It should actually be @psteinhaus:matrix.org.

**Comment by svenstaro** [comment]
If there's a good Discord bridge for Matrix then that's probably the best solution that captures all the current needs.

**Comment by IGBC** [comment]
> and that's where discord(+bridge) makes more sense in my opinion.

I personally would like to keep as much of the community chatter on GitHub. Its public and easily accessible (which discord is not). And Github has just introduced a new discussions feature exactly for that. I really feel uncomfortable channeling the community into a proprietary chat app that is known to sell user data.

**Comment by IGBC** [comment]
> Oops, my mistake. It should actually be @PSteinhaus:matrix.org.
I am confused, unless I am reading it wrong its identical to the last one but this time it works?

**Comment by IGBC** [comment]
> and most people don't even have matrix anyway.

Incidentally Rust orga's main help channels are on Matrix, so most rust developer's are sorta expected to use one of IRC or Matrix anyway.

**Comment by PSteinhaus** [comment]
> I am confused, unless I am reading it wrong its identical to the last one but this time it works?

I just edited it, sry. Github automatically replaces the ```@psteinhaus``` with its own version, I didn't realize that for a moment.

**Comment by icefoxen** [comment]
Mine is `icefox@matrix.org`

And my experience is that there's a small but steady stream of people who just pop into the various Rust discord servers to ask a question or two rather than opening github issues, plus they're good places to talk with other gamedev people.  So IMO github isn't necessarily the best place for "community chatter", just 'cause it is fairly heavily silo'd.  "Where to chat about stuff" isn't a question that has to be answered instantly right now and never changed again, though.

**Comment by icefoxen** [comment]
Okay, we have released 0.6.0-rc2 and it looks like barring last minute fixes that will be the version that becomes 0.6.0 in... I dunno, a couple weeks I suppose?  So I consider this issue closed.  Thank PSteinhaus, nobbele and IGBC for keeping the dream alive.  :heart:
