### ISSUE TITLE
unresolved reference to DrawTransform in docs

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#878]
This is very minor:
The doc entries of [push_transform](https://docs.rs/ggez/0.5.1/ggez/graphics/fn.push_transform.html) and [mul_transform](https://docs.rs/ggez/0.5.1/ggez/graphics/fn.mul_transform.html) reference DrawTransform, which isn't public, so the reference fails.

**Comment by icefoxen** [comment]
Thanks!  Easy to fix.

**Comment by icefoxen** [comment]
Fixed in 0.6, `push_transform` and such are removed.
