### ISSUE TITLE
Text is not rendered correctly

### ISSUE THREAD

**Issue by patriksvensson** [ggez/ggez#882]
**Describe the bug**

On one of my computers, the text rendered by the draw function below shows up as garbage.

```rust
fn draw(&mut self, ctx: &mut ggez::Context) -> ggez::GameResult {
    graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());

    let text = Text::new("Press SPACE to start");
    graphics::draw(ctx, &text, (Point2::<f32>::new(0., 0.), graphics::WHITE))?;

    graphics::present(ctx)?;
    Ok(())
}
```

**EDIT:** Se comments below

![image](https://user-images.githubusercontent.com/357872/105967830-995fab00-6086-11eb-957b-7b12a46855d9.png)

**To Reproduce**

I can only reproduce this on one computer. Specs can be found below.

**Expected behavior**

(Image is taken from the computer where the code works as expected)

![image](https://user-images.githubusercontent.com/357872/105968108-efcce980-6086-11eb-870b-a489694edda9.png)

**Hardware and Software:**

Where it **doesn't** work:

 - ggez version: 0.5.1
 - OS: For example, Windows 10
 - Graphics card: NVidia RTX 2080 SUPER
 - Graphics card drivers: Vendor drivers, v461.40

Where it **does** work:

 - ggez version: 0.5.1
 - OS: For example, Windows 10
 - Graphics card: Intel UHD Graphics 620
 - Graphics card drivers: Vendor drivers, v26.20.100.7262

**Comment by patriksvensson** [comment]
Here is the text rendered with the scale set to 500, rendering the text "ABC".

![image](https://user-images.githubusercontent.com/357872/105970721-f90b8580-6089-11eb-903b-cea1ee212e10.png)

**Comment by patriksvensson** [comment]
Ok, this is super strange. If I put the whole program in an example, and run that, it works as expected.
I am completely confused. I have no idea what's going on.

![image](https://user-images.githubusercontent.com/357872/105979901-7f2cc980-6094-11eb-8814-941c5006b4aa.png)

```rust
use cgmath::Point2;
use ggez::graphics::{self, Text};
use ggez::event;

struct Game { }

impl Game {
    fn new() -> ggez::GameResult<Game> {
        Ok(Game { })
    }
}

impl event::EventHandler for Game {
    fn update(&mut self, _ctx: &mut ggez::Context) -> ggez::GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut ggez::Context) -> ggez::GameResult {
        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());
        
        let text = Text::new(format!("Press SPACE to start"));
        let size = text.dimensions(ctx);
        let pos = Point2::<f32>::new((800 - size.0) as f32 / 2., (600 - size.1) as f32 / 2.);
        graphics::draw(ctx, &text, (pos, graphics::WHITE))?;

        graphics::present(ctx)?;
        Ok(())
    }
}

pub fn main() -> ggez::GameResult {
    let cb = ggez::ContextBuilder::new("super_simple", "ggez");
    let (ctx, event_loop) = &mut cb.build()?;
    let state = &mut Game::new()?;
    event::run(ctx, event_loop, state)
}
```

**Comment by icefoxen** [comment]
Well That's Interesting(tm).  Anyone else out there with an NVidia card on Windows who can try to reproduce this?

**Comment by patriksvensson** [comment]
@icefoxen I've tried with `0.6.0-rc0` crate and I get the same results. I've also specified ggez dependency as a git dependency with the same results.

**Comment by PSteinhaus** [comment]
I tried reproducing this on Windows 10, NVidia GTX 1060, but couldn't.
For me this code produces the expected result in both cases.
I tried with ```0.6.0-rc0```.

But to get this code to run I had to change it to:
```
use ggez::mint::Point2;
use ggez::graphics::{self, Text};
use ggez::event;

struct Game { }

impl Game {
    fn new() -> ggez::GameResult<Game> {
        Ok(Game { })
    }
}

impl event::EventHandler for Game {
    fn update(&mut self, _ctx: &mut ggez::Context) -> ggez::GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut ggez::Context) -> ggez::GameResult {
        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());

        let text = Text::new(format!("Press SPACE to start"));
        let size = text.dimensions(ctx);
        let pos = Point2::<f32>::from([(800. - size.x) as f32 / 2., (600. - size.y) as f32 / 2.]);
        graphics::draw(ctx, &text, (pos, graphics::WHITE))?;

        graphics::present(ctx)?;
        Ok(())
    }
}

pub fn main() -> ggez::GameResult {
    let cb = ggez::ContextBuilder::new("super_simple", "ggez");
    let (ctx, event_loop) = cb.build()?;
    let state = Game::new()?;
    event::run(ctx, event_loop, state)
}
```
So I wonder how you were able to run your code if you really used ```0.6.0-rc0```...

**Comment by patriksvensson** [comment]
The code above was from 0.5.1.

**Comment by PSteinhaus** [comment]
Ah sry, of course. I simply misread.
No need to post the other code I think, I was just confused for a moment.

**Comment by patriksvensson** [comment]
I renamed my game in Cargo.toml and suddenly it starts working.

If I rename the game to the old name in Cargo.toml, the problem comes back. Cleaned the target directory and removed the Cargo.lock file and it makes no difference.

Closing this issue until I can find a way to properly reproduce it.

**Comment by patriksvensson** [comment]
@PSteinhaus This might sound strange, but could you rename the binary to "shine" and see if it still works for you? I suspect that either NVidia might optimize something for an existing game called "shine.exe".

I have no clue if they do this, but it's the only theory I have why this happens. Just changing the crate name makes everything magically work for me, and changing it back breaks it.

**Comment by PSteinhaus** [comment]
...ok now I'm a bit spooked.
Renaming the binary to "shine.exe" changed the output to this:
![bug](https://user-images.githubusercontent.com/40324631/106126884-40fbdc80-615e-11eb-872c-ab73ab3f85c5.png)
So it seems you're right. It's somehow connected to the name. Strange.

**Comment by patriksvensson** [comment]
@PSteinhaus i think NVidia adds backward compatibility shims for specific apps, and there is probably a game or app with that name that it tries to fix.

**Comment by icefoxen** [comment]
...oh, I'm spooked as hell as well now.  I think there's an option in the nvidia driver console somewhere to turn off compat fixes, maybe try that?  Or, worst case, record the two in RenderDoc and see if anything different is actually happening in the draw commands being issued.

**Comment by Systemcluster** [comment]
Nvidia profiles contain a profile for "shine.exe" which is "Hired Team". The same profile is used for example for Hexen 2, and naming the executable "glh2.exe" instead of "shine.exe" displays the same issue. (This seems to be a very old profile...)

I'm not sure if there's a way to opt-out of Nvidia's driver-internal "optimization" from within a program, the safest course of action would be to avoid filenames that trigger this particular profile (or at best any existing profile). A list of existing profiles can be exported with e.g. Nvidia Profile Inspector.

**Comment by Systemcluster** [comment]
The offender seems to be the "Extension Limit" override. Creating a new profile with only "Extension Limit" set, and applying it to a ggez application, reproduces this as well.

Extension limit seems to control the following behavior:

> Extension limit indicates whether the driver extension string has been trimmed for compatibility with particular applications. Some older applications cannot process long extension strings and will crash if extensions are unlimited.

**Comment by icefoxen** [comment]
@Systemcluster Is there a way we can make ggez disable that option explicitly?

**Comment by Systemcluster** [comment]
@icefoxen I couldn't find a way to do that. I'd be very interested to hear if anyone comes up with something though!

You might be able to work around the trimmed extension strings, but it might be easiest to just add a note about executable names to avoid. I can compile a list of names that trigger this profile if you want to go that route.

**Comment by icefoxen** [comment]
If it's easy for you to collect that list I'd at least be interested in having it written down somewhere!

**Comment by Systemcluster** [comment]
Sure! These executable names trigger the same extension limit setting `0x00001B58`:

* darks.exe (Dark Salvation)
* heretic2.exe (Heretic 2)
* glh2.exe (Hexen 2)
* shine.exe (Hired Team)
* kingpin.exe (Kingpin)
* glquake.exe, quake.exe, glqwcl.exe (Quake)
* quake2.exe (Quake 2)
* quake3.exe (Quake 3)
* stvoyhm.exe, stvoy.exe (Star Trek Elite Force)

These executable names trigger another extension limit setting `0x00004844` (which presents the same issue in the test application):

* codsp.exe, codmp.exe (Call of Duty)
* coduomp.exe, coduosp.exe (Call of Duty: United Offensive)
* globe21.exe, globe.exe (GLOBE Graphics Test Tool)
* wolfmp.exe, wolfsp.exe (Return to Castle Wolfenstein)
* sof2.exe, sof2mp.exe (Soldier of Fortune 2: Double Helix)
* jediacademy.exe, jasp.exe, jamp.exe (Star Wars: Jedi Knight - Jedi Academy)
* jk2sp.exe, jk2mp.exe (Star Wars: Jedi Knight II - Jedi Outcast)
* swkotor.exe (Star Wars: Knights Of The Old Republic)
* swkotor2.exe (Star Wars: Knights of the Old Republic 2)

A few settings only apply to a single game each but also reproduce this:

* mohaademo.exe, moh_breakthrough.exe, moh_breakthrough_demo.exe, moh_spearhead.exe, moh_spearhead_demo.exe, mohaa.exe (Medal of Honor: Allied Assault) with setting `0x000011a8`
* x29.exe (X29) with setting `0x00000001`

(Then there are some others with more specific triggers than just the executable name)

[Profile list export from driver version 460.89](https://github.com/ggez/ggez/files/5926189/nvidia.profiles.txt)

Those are a few more than I thought, it might actually be worth to check if there's a way to work around this.

**Comment by icefoxen** [comment]
Thank you!  This is...  downright hilarious.  Thanks.  I don't know if I have the time and energy to actually do anything about this, but having the list around in the issue tracker is very useful.
