### ISSUE TITLE
Add helper function to translate physical coordinates into logical ones

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#886]
#883 shows that translating physical coordinates (for example the coords of a mouse click) to logical ones is a very common task.

Therefore I think we shouldn't force people to write their own helper here.
Instead we could just add something like ```to_logical(pos: Point2<f32>) -> Point2<f32>``` to the ```graphics``` module.

The reason why I put this here as an issue instead of just creating a pull request is that I'm not quite sure about the implementation.

I would probably do this:

Get the screen coordinate system and the physical window size (i.e. the inner size) and calculate as follows:
```rust
let screen_rect = graphics::screen_coordinates(ctx);
let size = graphics::window(ctx).inner_size();
logical_x = (x / (size.width  as f32)) * screen_rect.w + screen_rect.x;
logical_y = (y / (size.height as f32)) * screen_rect.h + screen_rect.y;
```
The problem with this approach is that it will work for people who are simply using ```set_screen_coordinates``` to control their global projection (which is probably like 99.9%), but it **won't** work for those who control their projection manually, i.e. by calling ```set_projection```.
For those it would probably better to write an implementation based upon the projection matrix, but that would take some math crunching and also I'm not sure if I'm over-engineering here... 

Also, is it even possible? The straightforward way would be to use the inverse of the projection matrix, which is probably not a good idea, because one would need to calculate such an inverse first (if it even exists), which sounds horribly inefficient.

Maybe there is a better way, but maybe we should just let those crazy enough to use custom projections figure out how to translate physical to logical coordinates themselves (since they probably know best what they're doing, for example rotating the camera)?

What do you think?

**Comment by PSteinhaus** [comment]
Hmm, ok now that I know that all coordinates in ggez are supposed to be physcial I'm not so sure anymore if this is really needed...

**Comment by icefoxen** [comment]
Probably not!  Do we need a `physical_to_logical` conversion function?  I forget if we already have one somewhere, but it doesn't look like it.  The information is basically conveyed through `event::WindowEvent::ScaleFactorChanged`.

**Comment by PSteinhaus** [comment]
If you just look at #883 then yes, one would just need to factor in the scale factor (or as soon as #884 gets merged not even that).

But my thought behind this is that it might be useful for people who change their coordinate system with ```graphics::set_screen_coordinates```.
On the other hand we might say that people who actively do that might be informed enough that they can easily write the code I mentioned above themselves.

I therefore propose closing this, since I think it's not important enough to clutter ```ggez::graphics``` even more and since I've also already added an explanation (and even the code from above) to the [input_test](https://github.com/ggez/ggez/pull/884/files#diff-9957b79e80d6d57fd77b86c4e4820990f4bf6f6fb88d579c6a387a51b1508644) example.
