### ISSUE TITLE
Question about missing transform functions in preview version

### ISSUE THREAD

**Issue by patriksvensson** [ggez/ggez#889]
Not a bug report per se, just a question about some changes in ggez.

I noticed that `ggez::graphics::push_transform`, `ggez::graphics::pop_transform`, and `ggez::graphics::apply_transformations` is missing after I upgraded to the preview.

What is the new recommended way of replacing this functionality?

**Comment by patriksvensson** [comment]
I managed to solve this by simply using my camera transform matrix with the draw calls.
I assume this is how it's supposed to work and this is the direction you want to push consumers of the library?

```rust
ggez::graphics::draw(ctx, 
    &tileset.tileset.batch, 
    DrawParam {
        src: Rect::one(),
        color: ggez::graphics::WHITE,
        trans: camera.transform().into(),
})?;
```

**Comment by icefoxen** [comment]
Yep, exactly.
