### ISSUE TITLE
EventHandler::resize_event gets wrong width and height

### ISSUE THREAD

**Issue by gorilskij** [ggez/ggez#890]
**Description**
The `width` and `height` parameters passed to `resize_event` are different from the ones previously set using `ContextBuilder` or `graphics::set_mode`. On my machine the values passed to `resize_event` are exactly twice as large as expected.

**To reproduce**
```rust
struct Handler;

impl EventHandler for Handler {
    fn update(&mut self, _ctx: &mut Context) -> GameResult { Ok(()) }

    fn draw(&mut self, _ctx: &mut Context) -> GameResult { Ok(()) }

    fn resize_event(&mut self, ctx: &mut Context, width: f32, height: f32) {
        println!("new dimensions: {}x{}", width, height);
    }
}

fn main() {
    let window_mode = WindowMode {
        // width and height start at 400
        width: 400.0,
        height: 400.0,

        maximized: false,
        fullscreen_type: FullscreenType::Windowed,
        borderless: false,
        min_width: 0.0,
        min_height: 0.0,
        max_width: 0.0,
        max_height: 0.0,
        resizable: true,
        visible: true,
    };

    let (mut ctx, event_loop) = ContextBuilder::new("hex_snake", "gorilskij")
        .window_mode(window_mode)
        .build()
        .unwrap();

    ggez::event::run(ctx, event_loop, Handler)
}
```

The output of running this program and slightly resizing the window is something like the following:
```
new dimensions: 790x796
new dimensions: 790x794
new dimensions: 792x794
new dimensions: 794x794
new dimensions: 796x794
new dimensions: 798x794
new dimensions: 800x794
new dimensions: 800x796
new dimensions: 802x796
new dimensions: 802x800
new dimensions: 804x800
```

**Expected behavior**
I would expect `resize_event` to receive values around 400, note that this is what happens on ggez 0.5.1.

**Hardware and Software:**
 - ggez version: current git master, current git devel
 - OS: macOS 10.15.7 (Catalina)
 - Graphics card: Radeon Pro 560X
 - Graphics card drivers: Vendor-provided

**Comment by PSteinhaus** [comment]
This is a known hidpi issue (related to #883, for example).
#884 should fix this.

**Comment by gorilskij** [comment]
Indeed, [#884](https://github.com/ggez/ggez/pull/884) fixes this, thank you.
