### ISSUE TITLE
[0.6.0rc1] Use of Transform::Matrix makes Image vanish

### ISSUE THREAD

**Issue by V02460** [ggez/ggez#894]
When drawing an `Image`, swapping out `DrawParam`’s transformation from `Transform::Values` to `Transform::Matrix` does no longer paint the image on screen.

**To Reproduce**
No image is shown on screen when drawing the image with the identity `Transform::Matrix`:
```rust
let draw_param = DrawParam {
    src: Rect::one(),
    color: Color::WHITE,
    trans: Transform::Matrix(Mat4::identity().into()),
};
image.draw(ctx, draw_param);
```

**Expected behavior**
It is expected to have the image shown on screen in the same way it works with `Transform::Values`:
```rust
let draw_param = DrawParam {
    src: Rect::one(),
    color: Color::WHITE,
    trans: Transform::default(), // Defaults to Transform::Values
};
image.draw(ctx, draw_param);
```

I found that calling `to_bare_matrix` on both variants results in the identity matrix, so the result should be the same.

**Hardware and Software:**
 - ggez version: 0.6.0rc1
 - OS: Fedora33

**Comment by icefoxen** [comment]
I bet your image is being drawn as a 1x1 pixel.  https://github.com/ggez/ggez/blob/master/src/graphics/image.rs#L347-L356
