### ISSUE TITLE
Mac Developers - ensuring all requirements are met

### ISSUE THREAD

**Issue by sullivant** [ggez/ggez#900]
While working on a simple process (I *love* this library, by the way; the class documentation is fantastic), I noticed that my TravisCI instance was failing its builds:

`error: failed to run custom build command for alsa-sys v0.1.2`

However, I also realized I didn't directly specify this crate/lib in my Cargo.toml, and am using:

`[dependencies]

  rand = "0.7.0"
  structopt = "0.3.21"
  ggez = "0.5.1"
  glam = { version = "0.12", features = ["mint"]}
`

If I add alsa-sys to my dependencies, a cargo build freaks out.  

The page about building for every platform does not mention Mac OS developers: https://github.com/ggez/ggez/blob/master/docs/BuildingForEveryPlatform.md

Do we have any advice so I can fix travis (I can apt install before running in the config, that should not be a problem) but more importantly, ensure that I have all the tools necessary for development on a Mac?  

I'm happy to document my process/progress and keep the mentioned blob updated for every platform, too!

Thanks,

-Thomas

**Comment by IGBC** [comment]
At the moment we unfortunately cannot provide support for developing on mac (none of the developers have hardware). While GGEZ technically supports mac that is a DIY target. If you resolve this issue feel free to open a PR
