### ISSUE TITLE
[0.6.0 rc1] egui integration

### ISSUE THREAD

**Issue by Elinvynia** [ggez/ggez#902]
Hello, I'm trying to integrate `egui` into `ggez`, but I've run into some issues. Because the `egui::Mesh` doesn't guarantee the winding order of the vertices, it results in drawing text in differently sized rectangles.

I guess since the representation is so different, I'll have to use some lower-level things that I'm not sure `ggez` provides, since the `Context.gtx_context` is `pub(crate)`

You can take a look at my current, broken attempt here: https://github.com/Elinvynia/Enfaria/blob/ggez/enfaria-game/src/egui.rs

It results in a "Hello world!" string looking like this: 
![image](https://user-images.githubusercontent.com/59487684/108498045-27cbe480-7261-11eb-9db5-9307ead6add8.png)

What would be a better way of approaching this?

**Comment by icefoxen** [comment]
Unless the egui maintainer changes their mind, the simple solution is to make an option for allowing changes to the culling face and/or winding order here: https://github.com/ggez/ggez/blob/devel/src/graphics/shader.rs#L241

However, it looks like `ggez` is already set to not do any face culling, so I'm not sure why it's not drawing textures on the rectangles.

**Comment by Elinvynia** [comment]
I've been playing with it a fair bit and trying many combinations of windings and the order of indices/vertices, unfortunately, everything I tried only seemed to produce abstract art, though the last attempt at least produced a triangle and not just rectangles.

**Comment by Elinvynia** [comment]
Update, after fiddling with it more: everything about egui rendering seems just slightly off - the text being symbols instead of letter (meaning its consistent), the round corners not really being round but having black to make it a square, the checkbox not being a square, weird black artifact pixels around the sliders, the backgrounds being pretty wrong as well. Just have a look yourself - 
![image](https://user-images.githubusercontent.com/59487684/108546482-00dfd380-729e-11eb-9788-883cd2fd9946.png)


Is it possible that perhaps passing a single solid image as the texture is wrong? Or is the rendering borked in some other way? I'm really trying hard to figure this one out.

**Comment by emilk** [comment]
Hi, `egui` maintainer here!

The black border around the window in the screenshot is likely from the shadow that all egui windows have, so it looks like the wrong blend mode is set. As [documented here](https://github.com/emilk/egui#writing-your-own-egui-integration), you need to set the blend mode to `(ONE, ONE_MINUS_SRC_ALPHA)`. This could also explain the blocky text, or that is a symptom of bad UV coordinates or wrong texture.

**Comment by Elinvynia** [comment]
Thanks a lot! I managed to fix the blocky text, but unfortunately not the overall texture issues.

My main mistake was not passing in the texture at all - I've fixed that. I'm creating an `Image::from_rgba8()` where the rest of the pixels are white (except alpha) as documented on egui. 

Fiddling with the `BlendMode` available in ggez didn't produce any results at all, which is pretty weird. I suppose there may be some internal implementation issue, as I've been able to integrate egui into tetra (which has a very similar API to ggez). 

Reference code: https://github.com/Elinvynia/Enfaria/blob/tetra/enfaria-game/src/egui.rs

**Comment by emilk** [comment]
It seems like ggez doesn't support the premultiplied alpha blend mode (`ONE, ONE_MINUS_SRC_ALPHA`): https://docs.rs/ggez/0.5.1/ggez/graphics/enum.BlendMode.html

Egui specifies all vertex colors with premultiplied alpha, and if you use [`Text::srgba_pixel`](https://docs.rs/egui/0.9.0/egui/struct.Texture.html#method.srgba_pixels) that's what you'll get aswell.

I guess you can unumltiply all vertex colors, but better to add support for premultiplied alpha in ggez. For translucent textures especially, premultiplied alpha is the only right choice.

**Comment by icefoxen** [comment]
Sure, adding another blend mode looks easy enough.

**Comment by emilk** [comment]
It might be helpful to take a look at the reference egui renderer for glium: https://github.com/emilk/egui/blob/master/egui_glium/src/painter.rs

**Comment by Elinvynia** [comment]
I've successfully integrated egui into tetra, it shouldn't be THAT different for ggez but the blendmodes are giving me trouble :/

Here is the working repo example: https://github.com/Elinvynia/tetra-egui

**Comment by PSteinhaus** [comment]
Now that the blendmodes are working (more) properly and we fixed that nasty bug you discovered, that caused meshes to not be drawn with their respective blend mode, I hope egui integration might now be achievable.

The only thing that may stand in its way right now is [the current regression in real-time-canvas drawing](https://github.com/ggez/ggez/issues/813#issuecomment-852928033), though I'm not sure about that.

**Comment by PSteinhaus** [comment]
> The only thing that may stand in its way right now is [the current regression in real-time-canvas drawing](https://github.com/ggez/ggez/issues/813#issuecomment-852928033), though I'm not sure about that.

Update: This has now been fixed. If anyone wants to take a shot at integrating egui into ggez now, he/she should now be able to.

**Comment by nobbele** [comment]
I've been using https://github.com/NemuiSen/ggez-egui it works well

**Comment by PSteinhaus** [comment]
So I guess this can be closed?

**Comment by nobbele** [comment]
yes
