### ISSUE TITLE
Asset Manager

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [ggez/ggez#907]
We need a better way to keep our assets.

## Current Situation
```rust
struct GameState {
    asset_1: Image,
    asset_2: Image,
    // ...
}

impl GameState {
    pub fn new() -> Self { Self { /*...init...*/ } }
}
```

Certainly this makes our game structs large and this problem can be simplified using an asset manager!

## What it should be like.
```rust
struct GameState {
    asset_manager: AssetManager
}

impl GameState {
    pub fn new() -> Self {
        let asset_manager = AssetManager::new();
        
        asset_manager.load_image("image1.png");
        asset_manager.load_sound("sound1.mp3");
        
        /*
        ...etc...
        */
        
        Self {
            asset_manager
        }   
    }
}
```

You will be able to access the image through `asset_manager.get_image("image1.png");`

I am not certainly sure if we should panic if asset manager does not have an image or return an result.

**Comment by mkhan45** [comment]
Haha I know you don't like ECS but it's quite useful for asset management.

**Comment by icefoxen** [comment]
IMO this is useful but doesn't need to be part of ggez itself.  There's various asset managers as independent crates already: `warmy`, `goods`, `amethyst_assets`, etc.

**Comment by nobbele** [comment]
do those work well with the ggez filesystem though?

**Comment by IGBC** [comment]
Candidate for a GGEZ Goodies package I think. @icefoxen @nobbele @PSteinhaus  can we have a vote for fix / wontfix

**wontfix**

**Comment by nobbele** [comment]
wontfix
