### ISSUE TITLE
Question on using mint

### ISSUE THREAD

**Issue by willparsons** [ggez/ggez#908]
What is the proper way to use mint / nalgebra for GGEZ? I'm trying to use parry2d for collision detection but I am having a lot of issues with converting between the different re-exports of nalgebra through these libraries.

**Comment by PSteinhaus** [comment]
Duplicate of #789.
You're absolutely right though, it'd be really good to at least have some idiomatic examples for this.

**Comment by icefoxen** [comment]
Closing as duplicate :C
