### ISSUE TITLE
Extra color constants disappear

### ISSUE THREAD

**Issue by sanpii** [ggez/ggez#909]
[This merge commit](https://github.com/ggez/ggez/commit/3723307b6d4f21a14c9e523ae2759f69f133300d) removes `Color` constants introduce in deccb2d0453bf320657625d619d88c6f72d7751e.

**Comment by eduardocanellas** [comment]
The `BLACK` and `WHITE` constants were moved inside `impl Color`, though. The others are missing.

**Comment by IGBC** [comment]
Do we really need the others?

**Comment by nobbele** [comment]
yes

**Comment by IGBC** [comment]
#fixed in #947
