### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by PSteinhaus** [ggez/ggez#910]
The discussion in #875 about the direction of ggez made me remember what I'd really like ggez to have one day!
### Animation
Animation is a crucial feature for most games (and one asked for in #235 by multiple people), so I think it's important to finally provide some sort of framework for it.
This could be an expansion of the API, but it could also (maybe) just be a simple example showcasing how to achieve animation through Spritebatches and DrawParams with source rects shifting for every animation step (but only if we come to the agreement that this is how animation should be handled in ggez).

I personally favor the latter approach, since it would keep ggez simple to learn while giving those who seek for them the necessary tools for handling simple animation, instead of forcing them to invent the wheel anew.

If you agree I would start a PR adding such an example. But I'm really interested in other opinions here, since this is just my kind of naive approach to animation in ggez and there might be better.

**Comment by nobbele** [comment]
The way I did animations in my ggez game was have like
struct Game {
    fading_box: Tween<Sprite<Rect>>, // ggez doesnt have a type with both a drawable and a drawparam for some reason so thats what sprite is
}

Game {
    fading_box: Tween {
        current: Rect { x: 0, y: 0, w: 100, h: 100 }
        time: 10.0,
        func: Box::new(|target: &mut Rect, progress: f32| { target.x = 100*progress }) //progress goes from 0.0 to 1.0
}

makes x go from 0 to 100 in 10 seconds

**Comment by PSteinhaus** [comment]
> Couldn't such a thing be implemented with tween though? |current: &mut DrawParam, progress: f32| { *current = sourceRects[(progress * sourceRects.len() as f32) as usize] } or something

You're right. It's probably a good idea to just use a tween for that. We would also need some kind of helper function though, to scale the source rects according to the image used in the spritebatch, so I'd still create and use a dedicated Animation struct as shown above, but passing a Tween to an Animation to control how progress gets mapped to source rects is probably a good idea.

> about the tween implementation you mentioned, would that be like iterator in that you could do tween::linear::().sin() to get Sin<Linear>

Hmm. Yes, we could combine them that way, but honestly I'd rather just have ```tween::linear()```, ```tween::sin()```, ... , and then a ```tween::custom(|t| sin(t) /* or whatever combination you want here */)``` for more complex cases.

**Comment by nobbele** [comment]
I just coded something up an idea I had
```rust
let mut tweener = Tweener {
    data: 0.5,
    tween: Linear::new(1.0) // 1.0 means 1.0/second aka adds 1.0dt each processing
        .with_step(), // this makes it step aka flooring, 0.0 -> 0.0; 0.5 -> 0.0; 0.9 -> 0.0; 1.0 -> 1.0; 1.4 -> 1.0; etc
};

tweener.process(0.1);
assert_eq!(0, tweener.value() as usize);
tweener.process(0.1);
assert_eq!(0, tweener.value() as usize);
tweener.process(0.3);
assert_eq!(1, tweener.value() as usize);
tweener.process(0.5);
assert_eq!(1, tweener.value() as usize);
tweener.process(0.5);
assert_eq!(2, tweener.value() as usize);
```

could add

```rust
.with_custom(|step: f32| tweener.value() as usize)
```

so the value it returns would be the index of the sprites
you could even add

```rust
.with_custom(|idx: usize| Rect { x: (idx % len) * size, y: (idx / len) * size, width: size, height: size })
```

and there could be a function animator() that constructs all of that. Could that work maybe?

**Comment by PSteinhaus** [comment]
I like that!

Not sure about the animator() solution (I'd probably need some examples to think through it a bit more properly), but in principle you're correct. A dedicated Animation struct may not be necessary after all.

Copying such a library may be a good approach... but on the other hand it's more fun to do it ourselves ^^ and we also may have different needs (though I'm speaking out of the blue here, I'd have to look into that library more closely to say whether this is the case).

**Comment by PSteinhaus** [comment]
This calculation is what would need to be changed:
```rust
/* ... */ x: (idx % len) * size, y: (idx / len) * size, width: size, height: size /* ... */
```
In it you assume that all frames are of size ```size``` and placed right next to each other (as in my initial example).
But I guess if the frames differ in size and are thus placed strangely on the image, all we'd need to do would be to give the closure ownership of ```sourceRects``` and the copied image dimensions and then index into it as you said:
```rust
let dim = spritebatch.into_inner().dimensions();
.with_custom(|idx: usize| {
    s_r = sourceRects[idx];
    Rect { x: s_r.x * dim.w, y: s_r.y * dim.h, width: s_r.w * dim.w, height: s_r.h * dim.h}
})
```
Then again, from what little I know about this style of animation this (i.e. frames being in such a weird layout) shouldn't really happen in most cases. Right now I'm actually asking myself whether there's even a single use case where we'd have to define an individual Rect for each frame...
A more usual use case would probably just look like this:
```rust
let dim = spritebatch.into_inner().dimensions();
let f_size = (32., 24.);
let size = f_size / (dim.w, dim.h);
.with_custom(|idx: usize| Rect { x: (idx % len) * size.0, y: (idx / len) * size.1, width: size.0, height: size.1 })
```

**Comment by PSteinhaus** [comment]
So now I guess the main question is whether we want to introduce a whole new ```tween``` module into ggez. (So that we can build animations of all kinds on top of it)

I have to be honest that I'm hesitant to do so... Tweens sure are useful, but so are ECSs and we don't force these (and a miriad of other useful, but non-essential things) on our users, since ggez is supposed to be rather minimalistic and simple...

From the look of it I'd say that this is rather a candidate to be a "[ggez goodie](https://github.com/ggez/ggez-goodies)".
Animation on the other hand should definetely be a core feature, which is at odds with adding the base of it as a "goodie"...

But if animation is essential then in the end I guess tweens are essential as well...
What do you think?

**Comment by nobbele** [comment]
I was thinking of exactly that, maybe icefoxen has an opinion

**Comment by nobbele** [comment]
one idea I have is that we make it a separate generic crate called tween or something and then reexport that in ggez and implement animations there on top of the tweens. doing this would improve compilation times, make it easier to split animations from the main library if that's wanted later on and allow others to use the library as well

**Comment by PSteinhaus** [comment]
That sounds pretty much ideal to me.

**Comment by IGBC** [comment]
I like the idea of a simple Animation system that can plug in to GGEZ simply, but I feel like animations are complex enough they would warrant tying into an events routing layer, and actor system, neither of which are provided by GGEZ. 

So maybe we should consider developing this initially as an external extension library, which provides hooks to attach it to whatever code is provided by the users game code?

**Comment by PSteinhaus** [comment]
You have a point.
The whole idea of creating tween animations this way is (at least for me) heavily inspired by how Cocos2d does things.
And it does this whole tweening stuff by using so called "Actions" that in fact really directly tie into the event loop and also their actor system.

These "Actions" are immensly powerful, since you cannot only use them to visually move actors from A to B over time. You can also pass any other closure, that takes time progress as an input, to them, to do all kinds of things over time in a linear/exponential/... way (like changing a background color, or raising some percentage or other number (which can look really nice if you visualize it)).

BUT, when I created [CocosSharpMathGame](https://github.com/PSteinhaus/CocosSharpMathGame) using them I didn't use them from the start. Instead I only started using them after learning the other nooks and crannies of Cocos(Sharp) and I only started creating more advanced custom Actions (changing the bg-color, raising percentages, etc.) almost at the very end when I felt really at home in it.

### What I want to say with that is the following:

IF we choose to handle animations through tweens, then I'd really like to integrate these tweens somehow smoothly into the event loop and I'd also like them to be as flexible/powerful as possible, by allowing them to not only handle animations, but also all other kinds of actions that progress through time in some (linear/exponential/...) fashion.

But integrating them into the event loop doesn't necessarily mean that we have to do so globally, by adding it into ggez directly.
**I think you're probably right and we should instead develop this feature as a "ggez goodie"**, with an example in ggez (or maybe even only the "ggez goodies" repo) showcasing how to (hopefully simply) integrate it into the event loop if wanted.

**Comment by PSteinhaus** [comment]
Ok, turns out someone actually already basically made what we're talking about here at such lengths with [keyframe](https://github.com/HannesMann/keyframe).

I just tried it out and it works pretty well! They even did their one example using ggez, so it's pretty much made for us.
I changed the code of their example to use `0.6.0-rc1` (since it heavily uses text rendering which is incredibly slow for some people, like me, which was luckily fixed now) and will probably open a PR for this later today.

For it to really do exactly what we discussed here I guess we'd need to add another example to their library, showcasing how to use it to achieve frame-by-frame animation using spritebatches and DrawParams with manipulated src parameters. (On the other hand... that's more a ggez-domain than a keyframe one, so maybe we'll just add it as an example here in ggez instead.)

**Comment by nobbele** [comment]
That does look like a great library. We should add an example here I think since that's where users will look for animations.
Is it actively maintained though? It looks like the most recent commit was almost a year ago.

**Comment by PSteinhaus** [comment]
> We should add an example here I think since that's where users will look for animations.

Ok, agreed.

> Is it actively maintained though?

One of the maintainers responded and merged my PR very quickly, so I'd say yes. Besides, there just isn't much to maintain, as far as I can see. It's a small, but elegant tool.

**Comment by nobbele** [comment]
keyframe doesn't work very well for non-tweened animation. I ended up implementing my own simple frame-by-frame animation system in my game, could probably be published as a crate.
```rust
struct Game {
    pub player: AnimatedSprite,
}

impl Game {
    pub fn new(ctx: &mut Context) -> Self {
        Self {
            player: AnimatedSprite::new(
                ctx,
                Path::new("/Player.png"),
                vec2(32.0, 32.0),
                &[4, 5, 6, 7],
                0.5,
            )
            .unwrap(),
        }
    }
}

impl EventHandler<GameError> for Game {
    fn update(&mut self, ctx: &mut ggez::Context) -> Result<(), GameError> {
        self.player.update(ctx)?;
        Ok(())
    }

    fn draw(&mut self, ctx: &mut ggez::Context) -> Result<(), GameError> {
        graphics::clear(ctx, Color::CYAN);
        println!("{:?}", self.player.current_rect());
        self.player
            .sprite_sheet
            .draw(ctx, DrawParam::new().src(self.player.current_rect()))?;
        graphics::present(ctx)?;
        Ok(())
    }
}```

**Comment by PSteinhaus** [comment]
Thanks @nobbele for looking into it.
I had hoped that it could be adapted to frame-by-frame animation using keyframes and the `Step` easing function (or maybe better a self defined `Floor` one). But I guess it's just too clunky to do it that way?

If I understand it correctly, your method specifies the sprite size (32x32 here) and the frames which it takes up on the sprite sheet (4th to 7th frame here) and you tell it to advance with a certain speed (each 0.5 seconds?). From what you wrote earlier I assume that the spritesheet can be one long strip of frames, or an image with multiple lines of frames.

That's a simple system that gives you basically everything that you need. I like that.
Thinking back on what I said about the possibility of having frames with different rect sizes I now think that this can very well be considered "too advanced and annoying to get into" for ggez, since all it does is saving some filesize and some rendering effort (which shouldn't be necessary, really, except if you use this system to animate something like a small sprite wandering over the screen, by making each frame with the size of the screen with mostly empty space in it, but then again, I think most people should be able to recognize immediately that this is no good idea anyway...) at the cost of making the interface a bit more difficult to work with.

What I'd like though, is an option to specify different kinds of easing functions (other than linear), possibly even for individual parts of the animation (time x till time y), which I think keyframe could be useful for. On the other hand: instead of coding a different easing function into their animated sprite most people working with such animations might just fire up their animation tool and create a new fitting animation there?

Quite possibly I'm overthinking all of this.

If you published it as a crate we could add it as a ggez-goodie and create an example based on it.
Alternatively, depending on the actual size of the implementation, we could just create another example containing the whole implementation and a small working example.

**Comment by nobbele** [comment]
I actually didn't see the step function, I will have to try it again.

**Comment by PSteinhaus** [comment]
Having merged the animation example I am pretty content with how it turned out.
The example is rather large, but not large enough to make a ggez-goodie on its own out of it, but that's just my opinion.
Do you agree to close this, or is further work necessary?

**Comment by nobbele** [comment]
Looks fine
