### ISSUE TITLE
Setting window-size to 1920x1080, doesn't cover entire screen

### ISSUE THREAD

**Issue by traditionalism** [ggez/ggez#915]
Not sure if this is a 'bug' perhaps but rather a question (I'm new to the engine).  Upon forcing the window to the following dimensions of **1920x1080** I then run the game and I get greeted by a half-white half-black window. Normal resolution works fine with the window having a pure white back-drop,

Would I have to import `ggez::graphics` and just paint the background canvas from there?

(Example of window when 1920x1080 is set)
![batman-hash_lSHbaBPinE](https://user-images.githubusercontent.com/57818674/111603225-2202e980-87a2-11eb-9455-cd2711352b7f.png)

(Example of window when default resolution is set)
![batman-hash_NL7BsOwg9Z](https://user-images.githubusercontent.com/57818674/111603300-31823280-87a2-11eb-973a-675ab72948c8.png)

(Code being used)
![Code_JYL6tS1rMj](https://user-images.githubusercontent.com/57818674/111603348-3fd04e80-87a2-11eb-9509-11e8edd7718c.png)

**Comment by PSteinhaus** [comment]
Hmm, what version of ggez do you use?
What do you do in your draw() call (do you have one)? Do you clear the screen using ```ggez::graphics::clear```?
If not then I think what happens could be something like the following:
- your window gets created and the window canvas is filled with white (for some reason... would have to check why exactly)
- your window immediately resizes and the canvas size is increased, but no new drawing happens, so the white stays and the rest stays how it was created, black

Does this behavior pose a problem for you in any way?

**Comment by traditionalism** [comment]
I'm using the most recent stable release (0.5.1)

Here is my draw()
![Code_Bt8XtBKWda](https://user-images.githubusercontent.com/57818674/112704301-14b3c200-8e68-11eb-989b-4e8b6b670c68.png)

But the odd thing is I've updated the cb and just changed a few things (that shouldn't relate), and I don't seem to be getting the arbitrary half-black-half-white background. At first I thought it could be the fact that I was passing .resizeable() but then that doesn't change anything :/

Here is my updated CB
![Code_rVNC8dhGya](https://user-images.githubusercontent.com/57818674/112704095-6e67bc80-8e67-11eb-8ce0-9219eff9785b.png)

And yeah I was hoping to make an extremely simple example without tapping into ggez::graphics yet, but it seemed that whatever I was doing before wasn't working.

I'm going to continue to look into the code I was using before to see if I can find the perpetrator.

**Comment by traditionalism** [comment]
I'll close this issue until/if I can find anything about actual reproducible instructions. (If of-course this wasn't just a me thing)

**Comment by PSteinhaus** [comment]
Hmm, it's still strange...
The window stuff has changed a bit in 0.6.0-rc1, so it'd be interesting to know if the problem persists there as well.
