### ISSUE TITLE
Startup crash when use MeshBuilder

### ISSUE THREAD

**Issue by buxx** [ggez/ggez#927]
**Describe the bug**

When I use `MeshBuilder` with specific way, program crash at startup without explaination.

**To Reproduce**

The bug is not easy to reproduce. There is my case: Source code is [here](https://github.com/buxx/OpenCombat/tree/480e488e2ce3d66fd7bb7b7ded9fb3d1fffebd0d).

My draw function is:

```rust
fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, graphics::BLACK);
        let mut scene_mesh_builder = MeshBuilder::new();

        self.generate_scene_item_sprites()?;
        self.generate_scene_item_menu_sprites()?;
        self.generate_map_sprites()?;

        scene_mesh_builder = self.update_mesh_builder_with_debug(scene_mesh_builder)?;
        scene_mesh_builder = self.update_mesh_builder_with_selected_items(scene_mesh_builder)?;
        scene_mesh_builder = self.update_mesh_builder_with_selection_area(scene_mesh_builder)?;
        scene_mesh_builder = self.update_mesh_builder_with_prepare_order(scene_mesh_builder)?;

        let scene_mesh = scene_mesh_builder.build(ctx)?;
        let window_draw_param = graphics::DrawParam::new().dest(window_point_from_scene_point(
            &ScenePoint::new(0.0, 0.0),
            &self.display_offset,
        ));

        graphics::draw(ctx, &self.map_batch, window_draw_param)?;
        graphics::draw(ctx, &self.sprite_sheet_batch, window_draw_param)?;
        graphics::draw(ctx, &scene_mesh, window_draw_param)?;
        graphics::draw(ctx, &self.ui_batch, window_draw_param)?;

        self.sprite_sheet_batch.clear();
        self.map_batch.clear();
        self.ui_batch.clear();

        graphics::present(ctx)?;

        Ok(())
    }
```

All is fine when execute this. But if I comment this line (or have `DEBUG` const to `false`):

    scene_mesh_builder = self.update_mesh_builder_with_debug(scene_mesh_builder)?;

My program crash at startup (return code is 0).

There is the content of `update_mesh_builder_with_debug`:

```rust
fn update_mesh_builder_with_debug(
        &self,
        mut mesh_builder: MeshBuilder,
    ) -> GameResult<MeshBuilder> {
        if DEBUG {
            // Draw circle on each scene item position
            for scene_item in self.scene_items.iter() {
                mesh_builder.circle(
                    DrawMode::fill(),
                    scene_item.position.clone(),
                    2.0,
                    2.0,
                    graphics::WHITE,
                )?;
            }

            // Draw circle where left click down
            if let Some(window_left_click_down_point) = self.left_click_down {
                let scene_left_click_down_point = scene_point_from_window_point(
                    &window_left_click_down_point,
                    &self.display_offset,
                );
                mesh_builder.circle(
                    DrawMode::fill(),
                    scene_left_click_down_point,
                    2.0,
                    2.0,
                    graphics::YELLOW,
                )?;
            }

            // Draw circle at cursor position
            mesh_builder.circle(
                DrawMode::fill(),
                scene_point_from_window_point(&self.current_cursor_position, &self.display_offset),
                2.0,
                2.0,
                graphics::BLUE,
            )?;
        }

        GameResult::Ok(mesh_builder)
    }
```
I don't understand why program crash when `update_mesh_builder_with_debug` code is not executed :thinking: . I just know my graphic drivers are not "very good" because some features are not present (for example, vulkan is not fully supported). For example, when I use multiple `MeshBuilder`, program crash too.

**Expected behavior**

Don't crash or print something about crash.

**Hardware and Software:**
 - ggez version: 0.6.0-rc0
 - OS: Ubuntu 20.04.1 LTS
 - Graphics card: NVIDIA GK107M [GeForce GT 750M]
 - Graphics card drivers: ![2021-05-04_09-57](https://user-images.githubusercontent.com/1104637/116974893-17070880-acbf-11eb-974a-d2b662017628.png)

**Comment by PSteinhaus** [comment]
Interesting.

**Comment by PSteinhaus** [comment]
Ok, I was able to reproduce your problem.
Sadly using #918 didn't change anything.

The problem occurs if the first and third call to ```mesh_builder.circle``` are commented out. The crash happens when
```rust
let scene_mesh = scene_mesh_builder.build(ctx)?;
```
is called. So it fails to build the mesh for some reason.

Doing a bit more testing the reason seems to be that the mesh builder mustn't be empty when being built, which it often seems to be when the debug stuff is commented out. Looking at [the docs](https://docs.rs/ggez/0.6.0-rc0/ggez/graphics/struct.MeshBuilder.html) you can see that
> [...] this doesn't try very hard to handle degenerate cases. It can easily break if you tell it to do things that result in a circle of radius 0, a line of width 0, an infintessimally skinny triangle, or other mathematically inconvenient things like that.

So, empty mesh builders are not allowed to be built. Perhaps we should make this a bit more explicit there...

**Comment by buxx** [comment]
Hello, thanks for this debugging ! I will prevent build if mesh builder is empty. 

> Perhaps we should make this a bit more explicit there...

Yes ^^

I close the issue because bug source has been found. Maybe you want i open a feature suggestion about mesh builder ?

**Comment by PSteinhaus** [comment]
You're welcome :)
No need to add a feature suggestion, I'll just add a PR adding a bit of text to the docs right now.
