### ISSUE TITLE
eventloop example broken

### ISSUE THREAD

**Issue by jiyinyiyong** [ggez/ggez#931]
`cargo run --example eventloop` brings:

![image](https://user-images.githubusercontent.com/449224/117580039-7aae8d00-b128-11eb-8d00-3118e6ad9003.png)

code after `events_loop.run_return(...)` appears to be unreachable, and if I change that to `.run(...)`(which is actually used in `ggez`) then Rust just tell me the code behind is unreachable.

https://github.com/ggez/ggez/blob/a039db8b94bf56029ab6525a88829fe1e4a259c3/examples/eventloop.rs#L32-L76

while the actual issue is because its underlying API `event_loop.run_return(...)` has issues, the example itself seems to be outdated.

Plus more context in https://github.com/ggez/ggez/issues/930#issuecomment-836748285 .

**Comment by PSteinhaus** [comment]
fixed in e71e0eecf4926d0add7991248a7c19df9da08966

**Comment by jiyinyiyong** [comment]
by reading the code, pressing `Esc` should close the window, but as I pretter `Esc` I got log on my side:
```
Other window event fired: ReceivedCharacter('\u{1b}')
```
and the `eventloop` demo also does not close when I press `Esc`. too many logs I'm not sure.

could you confirm if `Esc` still working correctly?

my platform:
```
=>> uname -v
Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
```

**Comment by jiyinyiyong** [comment]
didn't notice new commits happen in `devel` branch. turned out to work.

**Comment by PSteinhaus** [comment]
True. Still, it's good to hear people running into this, just as a reminder to us that we need to release a new release candidate soon 😅

**Comment by jiyinyiyong** [comment]
This fix actually helped reduce types confusions occured in copying previous version of example https://github.com/calcit-lang/calcit-paint/pull/8/files .

**Comment by nobbele** [comment]
You should probably use a specific revision rather than the branch

**Comment by jiyinyiyong** [comment]
My project is far from stable and relies on lyon `0.17.5`. I can stay in this branch for a while until ggez got a new version.

**Comment by jiyinyiyong** [comment]
turned out your are right, if I want to publish my project as a command line, to crates io, I still need to depend on a crate 😅 . Although it would always work with local installation using github branches.
