### ISSUE TITLE
Can ggez run headless?

### ISSUE THREAD

**Issue by fairbairn** [ggez/ggez#935]
Really like ggez.  Have built around it and it's performing great. 

That said, I may have put myself into a corner.  

I originally had prototyped work on ggez and had read that you can leverage an off-screen canvas for rendering without the need of a window.  Specifically, I had assumed it could, in some way, run "headless".

I'm not able to find a way to configure ggez to run without a window.  We're rendering to an off-screen canvas, and our product (which is a video production system that runs in the cloud) can do everything up to this point perfectly; however, from the ContextBuilder to Conf overrides, I have been unable to find a method in which the window itself can be disabled, while maintaining the necessary window loop itself.  In fact, I can find no way for it not to have a visible window.

I had looked into the winit crate as well, and they too had (at one point) a headless feature, but that seems to have been disbanded (or hidden) in their latest releases.  If it's there, it's not apparent.

So my question is..

Is it possible to run ggez fully headless, without a window system?  

I know it's possible for us to get OpenGL working on a headless machine, and in fact, we intend to use some drivers to support access to an NVIDIA GPU card, so it's conceivable that there could be a blank window running and it work on a cloud machine with no video card, but before we go down that path, I wanted to inquire...

Can ggez run headless?
Would this run on a headless system, even with a window?
Has anyone else run ggez fully headless (ie, basically just rendering, and streaming, no direct video display or inputs)?
Is there a path to provide this capability?
If not ggez, then what would be the logical alternative (short of getting into the lower level wgpu api, which is not ideal).

Any direction would be greatly appreciated.

**Comment by nobbele** [comment]
I don't think you can right now, I have tried doing it before but never got it to work properly. I ended up making a blank window and rendering to a canvas

**Comment by fairbairn** [comment]
I appreciate the feedback.  That's disappointing.

I guess our only options are to see if we can have it run headless with a blank window, or rip out ggez and use something a bit more low-level like wgpu.

It would seem that it would be straightforward to disable the visible window part, especially since the engine can draw to an off-screen canvas.

I think I'll keep this open to see if anyone else has additional insights.

**Comment by nobbele** [comment]
The way it's currently done is that creating a graphics context calls a glutin function which creates the opengl context and a window at the same time. graphics/mod.rs:254 for anyone interested

**Comment by fairbairn** [comment]
I bet coffee does it the same way.  I may investigate.  

If I forked ggez, disabled the window creation, and only leveraged winit's event loop, would the existing graphics calls and off screen canvas work as-is?

**Comment by IGBC** [comment]
This has been on my wish-list for a while, but from a different angle. I have had the goal of firing up the main events loop with winit hard disabled, not even programmed in. This was mostly for creating game servers using a common code base, and running tests with a main loop on CI.

But I have a couple of questions and then I will put some research into your suggestion cos its an interesting idea:

How did you intend to access the hidden frame-buffer for streaming, and did you expect GGEZ or winit to provide the streaming interface? As it stands right now if we can convince winit to hand over a GL context off screen (which BTW can have some really very platform dependent quirks, like windows not knowing which accelerator to use) you could render to a canvas and then serialise the data in the canvas and pipe it out over a socket. But that still requires you to roll a lot of your own code.

Incidentally if you're putting an Nvidia in your sever anyway it may be easier to run an x-server on it, and use a "dummy display", from that it doesn't matter that there's a window on screen if you're rendering everything to a canvas and serializing it over a socket anyway, because you'd never actually draw anything to the window.

**Comment by fairbairn** [comment]
We are in agreement.

We really just need ggez to work the way it does now, but provide us the option to not have a visible Window generated.

It already allows us to create a separate off-screen Canvas, where we perform all our drawing.  For our streaming application, we simply grab the bytes from that canvas, encode it, and stream it out our particular pathway.

Our draw() function (from the winit impl requirements), is simply...

```
    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        self.clear(ctx);
        self.draw(ctx);
        self.capture(ctx);
        self.render(ctx);
        graphics::present(ctx)
    }
```
That last `self.render(ctx);` will become optional for debug vs production.  That routine is where we choose to render to the visible window, otherwise, everything works off-screen, but we still get a blank Window in our face while our application runs.  Maybe I'm being particular, but it just seems unnecessary to have that given we don't draw to it in production.

```
    /// renders the off-screen canvas to the on-screen canvas
    fn render(&self, ctx: &mut Context) {
        let params = DrawParam::new().dest(Point2::new(0.0, 0.0));
        graphics::set_canvas(ctx, None);
        graphics::draw(ctx, &self.canvas, params).unwrap();
    }
```
So to answer your question, our code is already rolled and working.
We already render to an off-screen canvas.
We already capture it, encode it, stream it, and play it back in real-time elsewhere.
It already performs, we're decoding 12 live full motion inputs, compositing, encoding, and streaming out at 55fps on a laptop.
We're already reading about how to configure NVIDIA on a headless server; however, it would be nicer if we didn't necessarily have to require an x-server on it.   EGL might help, not sure yet.

You're on the right path, and we started to peek into some options.  It really comes down to if we can instantiate everything else within ggez, but have an option NOT to define a visible Window...

```
    let cb = ContextBuilder::new("me", "our_app")
        .window_mode(
            ggez::conf::WindowMode::default()
                .borderless(false)
                .dimensions(STAGE_WIDTH, STAGE_HEIGHT),
        )
        .window_setup(ggez::conf::WindowSetup::default().title("This"));
```
Unfortunately, the current code does not provide that ability.

Hope it's a simple addition and can be done.
If not, we're likely forced into using something lower level like `pixels`.  Coffee might could do it, but they have not confirmed this is possible (we posted to them).  `wgpu` is also another option, but far more low-level than we'd prefer to go at this juncture.

And you're right, it could be that the NVIDIA setup on a headless server can work out of the box, and we'll just live with a blank window there in the background for a while.  If it was a background process deployed to someone's machine though, it would not be ideal.  We can't close the window either, it would shut down the winit loop and hence the app.  We could however, likely hide it from the OS in some way, if we wanted to hack on it further.

The right way is simply not to generate the display, while keeping the loop in-tact.

**Comment by IGBC** [comment]
Update your `ContextBuilder` to include this snippet and GGEZ will not generate a visible window.

```rust
use ggez::conf::WindowMode;
ContextBuilder::new("my_game", "Cool Game Author")
        .window_mode(WindowMode::default().visible(false)).build()
```
(tested in 0.6.0-rc1)

Unless anyone is going to object I am going to close this.

**Comment by fairbairn** [comment]
Seems we'll have to upgrade to 0.6.0-rc1.  Thanks, we'll give it a try.
