### ISSUE TITLE
Code simplification in `mesh.rs`, as mentioned in the internal comment

### ISSUE THREAD

**Issue by saveriomiroddi** [ggez/ggez#940]
I was looking at the source code, when I've noticed [this](https://github.com/ggez/ggez/blob/359442b7869b580e8dae8435226e3888617ea5e8/src/graphics/mesh.rs#L433-L436):

```rust
// Stripped version

pub fn raw<V>(
    verts: &[V],
) -> GameResult<&mut Self>
where
    V: Into<Vertex> + Clone,
{
    // Can we remove the clone here?
    // I can't find a way to, because `into()` consumes its source and
    // `Borrow` or `AsRef` aren't really right.
    let vertices = verts.iter().cloned().map(|v: V| -> Vertex { v.into() });
}
```

Based on my knowledge, this can be accomplished by defining `From` traits for all the types that are intended to be converted from `&T` to `Vertex`, then accordingly modifying the function:

```rust
struct Vertex { /* fields */ }

impl<'a> From<&'a Vertex> for Vertex {
    fn from(instance: &'a Vertex) -> Self {
        Self { /* fields */ }
    }
}

fn myfn<V>(verts: &[V])
where
    for<'a> &'a V: Into<Vertex>,
{
    let mut buffer_vertices: Vec<Vertex> = vec![];

    let vertices = verts.iter().map::<Vertex, _>(|i| i.into());

    buffer_vertices.extend(vertices);
}
```

An alternative to this, which may be simpler, is to use an explicit conversion trait, rather than `Into`:

```
struct Vertex { /* fields */ }

trait ToVertex {
    fn to_vertex(&self) -> Vertex;
}

impl ToVertex for Vertex {
    fn to_vertex(&self) -> Self {
        Self { /* fields */ }
    }
}

fn myfn<V>(verts: &[V])
where
    V: ToVertex,
{
    let mut buffer_vertices: Vec<Vertex> = vec![];

    let vertices = verts.iter().map(|i| i.to_vertex());

    buffer_vertices.extend(vertices);
}
```

If you have any comment, I can follow up with a PR (hoping that it plays well with the macro, as I've seen that Vertex is defined via macro).

**Comment by nobbele** [comment]
Isn't this solution just a more complicated clone?

**Comment by saveriomiroddi** [comment]
> Isn't this solution just a more complicated clone?

So, let me clarify all the cases and the underlying operations, based on my understanding.

## Designs

### Current case (`From<T> for Vertex`)

The iterator does:

- clone a borrowed `T` instance (`&T`) into an owned one
- then, `T.into()` returns a new instance (unless `T` is a Vertex already, in which case, `self` is returned.

So we have two instantiations (assuming the compiler doesn't do fancy optimizations), unless T is a Vertex, in which case only one is performed.

To directly answer the question in the code comment ("Can we remove the clone here?"): no, it's not possible to remove it, because `into()` requires an owned instance, while the slice only provides borrowed ones.

With this design, every type that can be passed to the function requires an `Into<Vertex>` implementation (except `Vertex`).

### Simple Trait

This trait requires the type to instantiate a `Vertex` by a borrowed version of `Self`. For this reason, there's no intermediate `clone()`ing required.

This design requires, compared to the current:

1. the trait `ToVertex`
2. an implementation of `ToVertex` for `&Vertex`.

The other complexity is the same - instead of implementing `Into<Vertex>`, other types will require to implement `ToVertex`

### `From<&T> for Vertex`

This trait requires the type to instantiate a `Vertex` by a borrowed version of `Self`. It's just a fancy version of the previous, and relies on Rust's `into()` patterns. It has the same advantage - it saves `clone()`ing.

This design requires, compared to the current:

1. an implementation of `From<T> for Vertex`, which can't be implicitly provided by Rust
2. change the signature of the `raw()` to use the higher ranked trait bound (that ugly thing in the example :laughing:).

## Conclusions

This entire discussion may be purely academic, for two reasons:

1. there are no measurements provided on the performance hit by `clone()`ing.
2. there aren't even any `From<T> for Vertex` (/`Into<Vertex>`), at least in the ggez codebase (and I don't know if projects use it)

Essentially, the objective of this issue was to provided context and potential solutions to the question in the code.

For what I'm concerned, the code can be left as is - I think it'd be nice if somebody can verify that all I've written is correct, and then just put a link in the code (and close the issue), so that the code isn't left with an open question.

SYS 64738 :)

**Comment by icefoxen** [comment]
Now that I look at the code again, it looks like the input type `V` is going to be almost always `Copy` anyway, so that comment is wrong... it doesn't necessarily allocate heap memory for each `V`, just creates an iterator and uses it to extend the `Vec` of vertices.  So the `clone()` will generally just be a copy, and the comment is a little misguided.  I think it was written mostly out of frustration at not being able to go from `&V` to `Vertex` but having to do `&V` to `V` to `Vertex`.

**Comment by saveriomiroddi** [comment]
> Now that I look at the code again, it looks like the input type `V` is going to be almost always `Copy` anyway, so that comment is wrong... it doesn't necessarily allocate heap memory for each `V`, just creates an iterator and uses it to extend the `Vec` of vertices. So the `clone()` will generally just be a copy, and the comment is a little misguided. I think it was written mostly out of frustration at not being able to go from `&V` to `Vertex` but having to do `&V` to `V` to `Vertex`.

Right! "Allocation" was vague (I included stack allocation, if any). But even with that, I guess what happens with `clone()` (and an underlying `copy()` is that a temporary vector is created, the values are copied, then iterated to produce the `into()` result.

I'll correct the comment, but this issue can anyway be closed for me :smile: 

I'm not familiar with general Rust API design, and ultimately, this is just a single `cloned()` invocation :sweat_smile:

**Comment by PSteinhaus** [comment]
It's true that since it doesn't allocate it doesn't really need to get optimized more (at least IMO). All it could ever give us is going from 2 simple copies down to one.

Yet, I think @saveriomiroddi is right and using the ```From<&'a T> for Vertex``` method should be the most efficient and elegant. It could (in theory) save a copy, by getting rid of the ```clone()```.
The only downside that I can see would be, that some people reading the new signature of ```raw``` would scratch their head for a minute and maybe end up having to read up on "higher-ranked trait bounds", before being able to pass anything to it. Lifetimes are essential to Rust, yes, but life is always easier when they're not around, especially for those new to Rust.

In practice though, since even [the documentation of ```cloned```](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.cloned) says:
> This is useful when you have an iterator over &T, but you need an iterator over T.

I'd think that the compiler might be smart enough rationalize the unnecessary copy away, since this appears to be such a common use case.

**Comment by saveriomiroddi** [comment]
> But all in all, since raw is a method that probably speaks more to people who are a bit more advanced, I think we should change the signature to adapt the From<&'a T> for Vertex method, since losing the clone is just nicer.
What do you think?

I say that the interesting finding in the documentation (I wasn't expecting that!), indicates that it's at least an accepted pattern.

My discussion was mostly academical, aimed primarily at researching the comment I've read :)

I also agree that user-first design is important. Although examples in the documentation can help, I definitely remember seeing odd signatures and going :exploding_head: (and requiring help on the rust forum...) :laughing:

**Comment by PSteinhaus** [comment]
Hah ^^ ok then. Then we'll leave it as is for now and just add a link to this issue.

**Comment by saveriomiroddi** [comment]
> To be honest, now I'd be interested too in finding out how the compiler deals with this, but not interested enough yet to actually research it properly. But if you happen to find out something I'd be delighted if you'd share it with us.

I'll have a look over the next weeks, as I find it very interesting. For example, it may reveal how `cloned()` is purely semantic and not functional, which would make sense.

I've created two sample programs which implement the problems in the two ways (via `cloned()` and via `From<&'a T>`, and sent them to Godbolt for processing:

- via `cloned()`: https://godbolt.org/z/z9dG6a5rP
- via `From<&'a T>`: https://godbolt.org/z/xT4j6hK1a

The intrinsics - `std::hint::spin_loop();` - are to delimit the area of interest, which hopefully should not be subject of significant reordering.

Interestingly, it seems that the area of interest of the `cloned()` version is smaller (the outer area is similar/same for both versions) :exploding_head:

But one can't be sure of what's happening without interpreting the ASM. I'll do it some day over the next weeks, and write back :smile:

**Comment by saveriomiroddi** [comment]
So, well, I've done the research.

I've used slightly different code, which is not different in essence:

- via `cloned()`: https://godbolt.org/z/rKcWGzh46
- via `From<&'a T>`: https://godbolt.org/z/o89zePzvh

I've used `uint`s instead (originally, to track the code better), and some prints to make sure that unused variables/fields were not (smartly) discarded by the compiler.

The result is (drum roll!) that the intereting section of both versions is identical. So, this confirms that `cloned()` does not _necessarily_ result in an extra allocation (I can't prove it never does :smile:).

You can observe the section between the `pause` instructions, that I've put in the hope that they'd clearly hightlight the section (there's no significant reordering, so they accomplish the task).

Comment here:

```
# ... initialization
mov     edi, 36                                 # total size of the vector
mov     esi, 4                                  # (see API)
call    qword ptr [rip + __rust_alloc@GOTPCREL] # allocate the vector
test    rax, rax                                # test for success
je      .LBB2_12                                # exit procedure, if failure
mov     r14, rax                                # rax holds the allocated space
                                                # use r14 as address of the vector
movaps  xmm0, xmmword ptr [rip + .LCPI2_0]      # load data into xmm0, 16 bytes
movups  xmmword ptr [rax], xmm0                 # write data into [vec[0].x ... vec[1].x]
add     rax, 4                                  # (irrelevant to the copy)
lea     rcx, [r14 + 8]                          # (irrelevant to the copy)
movaps  xmm0, xmmword ptr [rip + .LCPI2_1]      # load data into xmm0, other 16 bytes
movups  xmmword ptr [r14 + 16], xmm0            # write data into [vec[1].y ... vec[2].y]
mov     dword ptr [r14 + 32], 9                 # write data vec[2].z

# ... printing; r14 is not overwritten

mov     edi, 36                                 # vector len
mov     esi, 4                                  # (see API)
call    qword ptr [rip + __rust_alloc@GOTPCREL] # allocate another vector
test    rax, rax                                # ^^^
je      .LBB2_12                                # ^^^
mov     rbx, rax                                # use rbx as address of the new vector
mov     qword ptr [rsp + 120], rax              # store vector address into stack [rsp + 120]
mov     qword ptr [rsp + 128], 3                # ?
mov     eax, dword ptr [r14 + 8]                # load vec[0].z into eax
mov     rcx, qword ptr [r14]                    # load vec[0].x and vec[0].y into rcx
mov     qword ptr [rbx], rcx                    # load vec[0].x and vec[0].y into new vector
mov     dword ptr [rbx + 8], eax                # store vec[0].z into new vector
mov     eax, dword ptr [r14 + 20]               # (copy vec[1] the same way)
mov     rcx, qword ptr [r14 + 12]               # ^^^
mov     qword ptr [rbx + 12], rcx               # ^^^
mov     dword ptr [rbx + 20], eax               # ^^^
mov     eax, dword ptr [r14 + 32]               # (copy vec[2] the same way)
mov     rcx, qword ptr [r14 + 24]               # ^^^
mov     qword ptr [rbx + 24], rcx               # ^^^
mov     dword ptr [rbx + 32], eax               # ^^^

# ... printing and exit
```

SYS 64738 to everybody :smile:

**Comment by PSteinhaus** [comment]
Well this is good news ^^ thanks for providing it.
It's always good to know that one can trust in the compiler.

> `mov     qword ptr [rsp + 128], 3                # ?`

Changing the source code a little I come to the conclusion that this is the vector length (of the new vector). But I don't see either why it has to be saved on the stack here, since it doesn't seem to ever be used.

**Comment by saveriomiroddi** [comment]
> Well this is good news ^^ thanks for providing it.
> It's always good to know that one can trust in the compiler.
> 
> > `mov     qword ptr [rsp + 128], 3                # ?`
> 
> Changing the source code a little I come to the conclusion that this is the vector length (of the new vector). But I don't see either why it has to be saved on the stack here, since it doesn't seem to ever be used.

Interesting. I guess that the compiler fully allocates a vector, which includes a size field (rather than just the fields, even if the size known in this context).
