### ISSUE TITLE
Add working directory to Filesystem paths

### ISSUE THREAD

**Issue by nobbele** [ggez/ggez#944]

**Comment by icefoxen** [comment]
Need some rationale for this.  :P  I would personally be careful about it, since it makes it easy to load data *other* than what you intend.  The current arrangement where it is opt-in works fine for me, and we haven't gotten any issues about people being confused by the behavior in a long time.

**Comment by nobbele** [comment]
true but like why would you ever run `cargo run` or `game.exe` from another directory that happens to also contain an unrelated resources folder

**Comment by IGBC** [comment]
> Need some rationale for this. :P I would personally be careful about it, since it makes it easy to load data _other_ than what you intend.

I second this, On some platforms it can be quite unclear what the working dir actually is. For example launching a .exe on windows will set the working dir to where ever the link is unless the Target field is explicitly filled in (old trick I learnt back in my modding days)

**Comment by nobbele** [comment]
yeah compiled one is different. I was thinking more on the development side, having to copy resources to target or add a path feels unintuitive if you don't know it doesn't auto-add working(or rather project) directory, especially for new people

**Comment by IGBC** [comment]
I feel if we put a configuration switch in there for debug vs release we'd get a lot of issues in the form of "it worked in dev but now it won't and I didn't read the fine print in the docs, help!"

And if we leave it hard on we're exposing our users to having resources injected into their programs (could be a problem if they are loading scripts, or heaven forbid other binaries, but hey game developers to weird and terrifying things)

**Comment by nobbele** [comment]
Yes I agree. We could add a .use_working_directory_for_resources(bool) (not real name obv) or something though I don't know. What a conflicting issue.
Using working directory as resource path by default is easier for beginners but creates non-obvious problems for some use cases

**Comment by PSteinhaus** [comment]
What about the approach used in many of the examples:
```rust
    // We add the CARGO_MANIFEST_DIR/resources to the resource paths
    // so that ggez will look in our cargo project directory for files.
    let resource_dir = if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        let mut path = path::PathBuf::from(manifest_dir);
        path.push("resources");
        path
    } else {
        path::PathBuf::from("./resources")
    };
```
This makes development easier, since you can just place all your resources in CARGO_MANIFEST_DIR/resources, so you don't need to copy them into the debug/release folders. It's also really easy to set up. I mean, most of the examples use it and you can just copy paste the code into your own project.

**Comment by nobbele** [comment]
right yeah let's use that

**Comment by IGBC** [comment]
> What about the approach used in many of the examples:
> 
> ```rust
>     // We add the CARGO_MANIFEST_DIR/resources to the resource paths
>     // so that ggez will look in our cargo project directory for files.
>     let resource_dir = if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
>         let mut path = path::PathBuf::from(manifest_dir);
>         path.push("resources");
>         path
>     } else {
>         path::PathBuf::from("./resources")
>     };
> ```
> 
> This makes development easier, since you can just place all your resources in CARGO_MANIFEST_DIR/resources, so you don't need to copy them into the debug/release folders. It's also really easy to set up. I mean, most of the examples use it and you can just copy paste the code into your own project.

That's what I have at the top of my projects. its even in the default project template.

**Comment by nobbele** [comment]
I mean why can't we add it to the default paths?

**Comment by PSteinhaus** [comment]
Hmm, let's say someone wants to distribute a game, without all the cargo stuff.
Then calling ```env::var("CARGO_MANIFEST_DIR")``` wouldn't return with Ok, meaning this path wouldn't be added to the default paths at all...

It would work, but wouldn't it also lead to problems like
> we'd get a lot of issues in the form of "it worked in dev but now it won't and I didn't read the fine print in the docs, help!"

?
Since placing things you need in the root directory would only work as long as that's defined to be the CARGO_MANIFEST_DIR.
Or would that even be the case when there are no cargo files?

**Comment by nobbele** [comment]
that would still apply if you add it to your game manually, and even if you dont it would still apply anyway since your resources will be in Debug and not Release

**Comment by nobbele** [comment]
I think it's more reasonable to get an error about resources not found when running an exe that doesn't have the resources folder beside it than it is to get an error when cargo running the project despite the resources folder being in there. Most people who don't know how to deal with the error probably won't be distributing binaries anyway.

**Comment by icefoxen** [comment]
> I mean why can't we add it to the default paths?

The reason it isn't there already is to be extra paranoid about hardwiring build-time paths into the executable.  Finding it at runtime seems pretty reasonable, but adding this to the default paths means that if you run your game with `cargo run` then it has one behavior, and if you run the game by executing `./target/debug/mygame.exe` then you will get a different behavior.  This doesn't mean it's a bad idea, it just seemed to me like a gotcha that can trip people up.

The only good solution I could find was to force the user to specify what to do, so they can see all the magic happening.  :shrug:

**Comment by PSteinhaus** [comment]
How about adding something like
```rust
cb = cb.add_resource_path(path::PathBuf::from("."));
```
to the files example together with a comment to explain it? (Also mentioning possible downfalls like launching a .exe from a link file on windows)

This way we'd keep our filesystem from being hardcoded to doing magical stuff, but we'd also show users that they can directly access the working directory and how to do so.

**Comment by nobbele** [comment]
keeping as is then I suppose
