### ISSUE TITLE
The struct Color is not associated with item WHITE

### ISSUE THREAD

**Issue by Blatko1** [ggez/ggez#953]
https://github.com/ggez/ggez/blob/359442b7869b580e8dae8435226e3888617ea5e8/examples/01_super_simple.rs#L34

![image](https://user-images.githubusercontent.com/51339494/122983962-cd709b00-d39c-11eb-8fa1-c27ef0070b5a.png)

The only solution is having: `[1.0, 1.0, 1.0, 1.0].into()` instead of `Color::WHITE`.
So I recommend changing the source code of examples.

**Comment by PSteinhaus** [comment]
I'm sry, but could it be that you're trying to run an example from the devel branch on something like ggez `0.5.1`?
[The color constants used to be a part of the graphics module directly back then](https://docs.rs/ggez/0.5.1/ggez/graphics/index.html#constants).
But in the latest released version [the constants are now part of the `Color` struct](https://docs.rs/ggez/0.6.0-rc1/ggez/graphics/struct.Color.html#impl). [In the devel branch, we now even added all the other color constants back there](https://github.com/ggez/ggez/blob/121d078790ec1e6aee5534f3fa9f81869632c975/src/graphics/types.rs#L238-L325).
