### ISSUE TITLE
is_key_repeated() takes some time to detect the repetition

### ISSUE THREAD

**Issue by saveriomiroddi** [ggez/ggez#954]
**Describe the bug**

If I keep a button pressed, and test the `is_key_pressed` and `is_key_repeated_status`, the latter takes a while to return true, even if the first returned true for some time.

The delay seems to be time-based. On the test case below, it can take more than a hundred thousand cycles, while on a basic game, it take a couple dozens.

I had a very brief look at the source code:

```rust
// src/input/keyboard.rs
    pub(crate) fn is_key_repeated(&self) -> bool {
        if self.last_pressed.is_some() {
            self.last_pressed == self.current_pressed
        } else {
            false
        }
    }
```

and I don't see anything obvious in this specific function (didn't check the context) that would hint at the delay.

**To Reproduce**

```rust
pub struct GlobalState {}

impl EventHandler for GlobalState {
    fn update(&mut self, ctx: &mut ggez::Context) -> ggez::GameResult {
        let kp = is_key_pressed(ctx, KeyCode::Space);
        let kr = is_key_repeated(ctx);

        println!("KP:{} KR:{}", kp, kr);

        yield_now();

        Ok(())
    }

    fn draw(&mut self, _ctx: &mut ggez::Context) -> ggez::GameResult {
        Ok(())
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let context_builder = ggez::ContextBuilder::new("foo", "bar")
        .window_setup(ggez::conf::WindowSetup::default().title("baz"))
        .window_mode(ggez::conf::WindowMode::default().dimensions(1280., 720.));

    let (context, event_loop) = context_builder.build()?;
    let state = GlobalState {};

    event::run(context, event_loop, state)
}
```

**Expected behavior**

When I press a key, on the given loop, `is_key_pressed` should return true, and `is_key_repeated_status` false, then, on the subsequent loop, both should return true.

**Hardware and Software:**

 - ggez version: current `devel` (121d078)
 - OS: Ubuntu 20.04
 - Graphics card: GT 710
 - Graphics card drivers: nvidia-driver-465 (`465.27-0ubuntu0.20.04.2`), which includes, as dependency, the OpenGL/GLX/EGL/GLES GLVND libraries.

**Comment by saveriomiroddi** [comment]
I've done a similar test with Macroquad:

```rs
#[macroquad::main("Test")]
async fn main() -> Result<(), Box<dyn error::Error>> {
    loop {
        let kd = is_key_down(KeyCode::Space);
        let kp = is_key_pressed(KeyCode::Space);

        println!("KD:{}, KP:{}", kd, kp);

        next_frame().await
    }
}
```

MQ has different semantics, but it detects immediately the state change:

```
// Space kept pressed

KD:false, KP:false
KD:true, KP:true   # here
KD:true, KP:false
```

**Comment by PSteinhaus** [comment]
Honestly, looking at this for the first time, the behaviour you describe for `is_key_repeated` is pretty much one of the two behaviours I'd expect. Either it should return true immediately in the second loop, or it should return true after a period of time. Both are common.

The docs for `is_key_repeated` say
> Checks if the last keystroke sent by the system is repeated, like when a key is held down for a period of time.

so we already made sure to publicly state that `is_key_repeated` represents the latter kind of functionality.

> MQ has different semantics, but it detects immediately the state change

This is true. "key pressed" vs "key down" is a different kind of comparison than "key pressed" vs "key repeated".
As far as I can see "key pressed" in MQ is equivalent to the `key_down_event` firing in ggez, while "key down" in MQ should be equivalent to `is_key_pressed` returning true.

**Comment by saveriomiroddi** [comment]
I see. I mistakenly thought that the returning true on the next loop was the only correct behavior.

Thanks for the clarification :smile:
