### ISSUE TITLE
[0.6.0-rc1] Memory allocation sometimes fails

### ISSUE THREAD

**Issue by Kirottu** [ggez/ggez#955]
**Describe the bug**
Sometimes when launching a release build of my project it will fail with a message:
`memory allocation of <big number> bytes failed`

**To Reproduce**
Run any project in release mode. I could reproduce this with my own project and the examples in the examples directory. Non release builds do not crash with this issue with my testing and release builds for windows do not crash either.

**Expected behavior**
I expected a release build for linux not to crash.

**Screenshots or pasted code**
![image](https://user-images.githubusercontent.com/56396750/123553441-db029800-d783-11eb-8834-4a3ca8a8aff2.png)

**Hardware and Software:**
 - ggez version: 0.6.0-rc1
 - OS: Arch Linux
 - Graphics card: RX 570 8GB
 - Graphics card drivers: open source amdgpu driver

**Comment by PSteinhaus** [comment]
Thanks for reporting!

Trying it on windows I get no crashes in release mode as well.
No idea why it would try to allocate so much memory... and why only in release mode...

I personally don't use linux much, but I know that @icefoxen and @IGBC do and I'm relatively sure they ran some examples in release mode on 0.6.0-rc1 in the recent past, so I'm pretty sure we can't reproduce that bug right away, sadly (or luckily, depending on the view point).

**Comment by nobbele** [comment]
That number is over 4 exabytes by the way. Is rust up to date?

**Comment by Kirottu** [comment]
That is.... alot. I'll check out if my rust needs updates when i get to my pc.

**Comment by Kirottu** [comment]
Alright I updated my rust toolchain from 1.51.0 to 1.53.0 and the issue still persists.

**Comment by Kirottu** [comment]
Another update it would seem like after tackling whole another issue with audio and installing the pulseaudio alsa configuration, allowing for alsa audio to work with pulse made the memory allocation issue disappear.

**Comment by icefoxen** [comment]
Tried on my Linux PC, which has an AMD RX 480 and is also using the open source drivers, so it's pretty close in terms of hardware generation.  Didn't get an out of memory, but I'm using pulseaudio as well.  I'll try without pulse installed and see if anything changes, though that's a little bit of an annoying production.

**Comment by Kirottu** [comment]
The problem wasn't pulseaudio, the problem was the lack of the ALSA Configuration for pulse (`pulseaudio-alsa` package on Arch Linux) which meant the program couldn't play audio at all.

**Comment by nobbele** [comment]
I will consider this resolved since I think we can assume that ggez requires a working audio system.
