### ISSUE TITLE
You can't override the "escape" key firing a quit event

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#97]
I thought you could but it turns out not.  This should be fixed; you can ignore or handle the quit event, but there's no way to make pressing "escape" not fire it.

**Comment by icefoxen** [comment]
We... can't actually make `EventHandler::key_down_event()` call `Context::quit()` by default because it never has access to a `Context`.

So far it seems the only sensible thing is to remove this feature entirely and make sure the tutorials have a `key_down_event()` handler to handle escape button presses.

**Comment by icefoxen** [comment]
IT'S EVEN WORSE because `key_down_event()` doesn't get a `Context` either, so it can't call `Context::quit()`.

When I wrote `EventHandler` I couldn't think of any use case that would need the `Context`: most operations you need it for are expensive things like creating resources, which are best done outside event handlers, or things like drawing which have their own event.  However, we are slowly accumulating more options to mess around with the game/window state, like `graphics::set_mode()`, and accessing those needs the Context.

So it seems like the Right Thing might be to update the `EventHandler` trait to pass the `Context` to the event callbacks as well, however that is a breaking change so would have to wait for 0.4.

**Comment by obsoke** [comment]
I agree that this is the right change to make; otherwise, you are left setting flags from the event handling methods to then act upon in `update`. Better to just act directly, IMO.

In a similar vein, what about arguments passed to `update` such as `dt`? Would those be useful in other methods? e.g.: From `key_down_event`, some other method would be called when <kbd>Space</kbd> is held down to do something like `speed * dt` to move a character. 
Or perhaps being able to get a `Duration` object from the `Context` representing the current delta time would be a cleaner alternative to passing an additional argument to each of the `EventHandler` methods.

**Comment by icefoxen** [comment]
Eeeeeeh.  I'm wary of passing dt to event handlers because the Right Way is almost always to do as little as possible in event handlers besides register that events happened.  Getting a Duration from the context isn't a terrible idea though...

**Comment by Manghi** [comment]
@obsoke Small tidbit: the way I avoided this was to set a flag which would detect if a key was already pressed. 

For a small menu system which has an option to exit the game, I had to manually call `Context::quit()` that way. Wasn't that big of deal, but it sounds like its not the best method??

**Comment by rofrol** [comment]
@icefoxen Maybe add to 0.4 milestone?

**Comment by icefoxen** [comment]
Oops, thought I had already.

**Comment by Manghi** [comment]
@icefoxen  You mentioned that you could ignore the `Context::quit()-from-ESC-key` event in your first post. 

How exactly would this be done?

**Comment by icefoxen** [comment]
Override the `quit_event` method on your `EventHandler` and have it check whether the escape key is pressed, exactly like you said.  If the `quit_event` method returns true, the game does not exit.

**Comment by Manghi** [comment]
`quit_event`, so obvious. Thanks! Works like a charm.

**Comment by icefoxen** [comment]
DONE!  \o/
