### ISSUE TITLE
graphics::Text compatibility issue with integers/floats? Can't "draw" an i32

### ISSUE THREAD

**Issue by garlwt** [ggez/ggez#972]
GitHub noob and Rust amateur here, forgive me for format mistakes if there are any. Also, ggez is a very fun way to get your hands dirty with Rust and I have enjoyed my experience with it so far, so thank you dev team.

**Describe the bug**
I would like to be able to create a running score tracker similar to the one in the google dino jump game. The issue I am having is that all the traits required to do that are not implemented/available to use on integers and are only available within graphics::Text. I would like to be able to create a score keeper in the font of my choice and scale it to the size of my choice. I can create a score keeper yes but it doesn't have the attributes that are available with graphics::Text. I'm not sure if it is possible or not but if it is I would love to know.

**To Reproduce**
`struct MainState {
    pos_x: f32,
    score: graphics::Text,
}

impl MainState {
    fn new(ctx: &mut Context) -> GameResult<MainState> {
        let font = graphics::Font::new(ctx, "/Tangerine_Regular.ttf")?;

        let score = graphics::Text::new((format!("{}", 0.0 ), font, 60.0));

        let s = MainState { pos_x: 0.0, score, };
        Ok(s)
    }
}

impl event::EventHandler<ggez::GameError> for MainState {
    fn update(&mut self, _ctx: &mut Context) -> GameResult {
        self.pos_x = self.pos_x % 800.0 + 1.0;
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());

        let circle = graphics::Mesh::new_circle(
            ctx,
            graphics::DrawMode::fill(),
            Vec2::new(0.0, 0.0),
            100.0,
            2.0,
            Color::WHITE,
        )?;
        graphics::draw(ctx, &circle, (Vec2::new(self.pos_x, 380.0),))?;

        let dest_point = glam::vec2(670.0, 5.0);
        graphics::draw(ctx, &self.score, DrawParam::default().dest(dest_point))?;     

        graphics::present(ctx)?;
        Ok(())
    }
}

pub fn main() -> GameResult {
    let cb = ggez::ContextBuilder::new("super_simple", "ggez");
    let (ctx, event_loop) = cb.build()?;
    let state = MainState::new()?;
    event::run(ctx, event_loop, state)
}
`
**Expected behavior**
That example probably doesn't help much as it is pretty obvious that string and integers do not have the same functionality as previously mentioned. If anyone has any idea as to whether or not it is possible to set integer font and size that would be great if you could point me in the right direction. If it is not possible that would be great to know as well. Thanks

**Hardware and Software:**
 - ggez version: For example, release 0.4.4, current git master, current git devel branch, etc.
 - OS: For example, Windows 10, Linux (Debian 9), etc
 - Graphics card: For example, NVidia GTX 660, Intel Iris 520, etc.
 - Graphics card drivers: Whether you're using the vendor-provided drivers or open source, if applicable on your platform -- generally only relevant for Linux using NVidia hardware

**Comment by IGBC** [comment]
Hi, what you want to do is possible, but not using the method you have imagined.

Store your score as a integer and use the `format!()` macro to turn it into a temporary string inside the draw call just before you render said string.

Have fun!

- Segfault

10 Aug 2021 12:51:30 am garlwt ***@***.***>:

> GitHub noob and Rust amateur here, forgive me for format mistakes if there are any. Also, ggez is a very fun way to get your hands dirty with Rust and I have enjoyed my experience with it so far, so thank you dev team.
> 
> *Describe the bug*
> I would like to be able to create a running score tracker similar to the one in the google dino jump game. The issue I am having is that all the traits required to do that are not implemented/available to use on integers and are only available within graphics::Text. I would like to be able to create a score keeper in the font of my choice and scale it to the size of my choice. I can create a score keeper yes but it doesn't have the attributes that are available with graphics::Text. I'm not sure if it is possible or not but if it is I would love to know.
> 
> *To Reproduce*
> `struct MainState {
> pos_x: f32,
> score: graphics::Text,
> }
> 
> impl MainState {
> fn new(ctx: &mut Context) -> GameResult {
> let font = graphics::Font::new(ctx, "/Tangerine_Regular.ttf")?;
> 
>     let score = graphics::Text::new((format!("{}", 0.0 ), font, 60.0));
> 
> 
>     let s = MainState { pos_x: 0.0, score, };
>     Ok(s)
> }
> 
> }
> 
> impl event::EventHandlerggez::GameError for MainState {
> fn update(&mut self, _ctx: &mut Context) -> GameResult {
> self.pos_x = self.pos_x % 800.0 + 1.0;
> Ok(())
> }
> 
> fn draw(&mut self, ctx: &mut Context) -> GameResult {
>     graphics::clear(ctx, [0.1, 0.2, 0.3, 1.0].into());
> 
>     let circle = graphics::Mesh::new_circle(
>         ctx,
>         graphics::DrawMode::fill(),
>         Vec2::new(0.0, 0.0),
>         100.0,
>         2.0,
>         Color::WHITE,
>     )?;
>     graphics::draw(ctx, &circle, (Vec2::new(self.pos_x, 380.0),))?;
> 
>     let dest_point = glam::vec2(670.0, 5.0);
>     graphics::draw(ctx, &self.score, DrawParam::default().dest(dest_point))?;     
> 
> 
>     graphics::present(ctx)?;
>     Ok(())
> }
> 
> }
> 
> pub fn main() -> GameResult {
> let cb = ggez::ContextBuilder::new("super_simple", "ggez");
> let (ctx, event_loop) = cb.build()?;
> let state = MainState::new()?;
> event::run(ctx, event_loop, state)
> }`
> 
> *Expected behavior*
> That example probably doesn't help much as it is pretty obvious that string and integers do not have the same functionality as previously mentioned. If anyone has any idea as to whether or not it is possible to set integer font and size that would be great if you could point me in the right direction. If it is not possible that would be great to know as well. Thanks
> 
> *Hardware and Software:*
> 
* > ggez version: For example, release 0.4.4, current git master, current git devel branch, etc.
* > OS: For example, Windows 10, Linux (Debian 9), etc
* > Graphics card: For example, NVidia GTX 660, Intel Iris 520, etc.
* > Graphics card drivers: Whether you're using the vendor-provided drivers or open source, if applicable on your platform -- generally only relevant for Linux using NVidia hardware

**Comment by nobbele** [comment]
Reopen the issue if you have further questions

**Comment by garlwt** [comment]
@IGBC thanks for the reply this worked

`
let font = graphics::Font::new(ctx, "/ARCADECLASSIC.ttf")?;
let scoreboard = graphics::Text::new((format!("{}", 0.0 ), font, 60.0));

self.scoreboard = graphics::Text::new((format!("{}", self.score),
graphics::Font::new(ctx, "/ARCADECLASSIC.ttf")?, 60.0));

`

score was an i32 that i += to as the game ran
