### ISSUE TITLE
Memory leak in set_screen_coordinates()

### ISSUE THREAD

**Issue by ghost** [ggez/ggez#989]
**Bug description**
My game is leaking memory (at the speed of about 1MB in 5 seconds?) and while I was debugging I realized that after changing this line:
```rs
graphics::set_screen_coordinates(context, new_screen_view).unwrap();
```
to this:
```rs
// graphics::set_screen_coordinates(context, new_screen_view).unwrap();
```
... I could get the leak to disappear.

**To Reproduce**
I was able to reproduce the issue by adding a call to the `set_screen_coordinates` function in the `update` implementation of the [basic example](https://docs.rs/ggez/0.6.1/ggez/#basic-project-template) for this ggez version (ggez version number below).

**Expected behavior**
This is kinda obvious, but the expected behavior is just the function not causing a memory leak.

**Screenshots or pasted code**
As I said before, adding a call to the `set_screen_coordinates` function in the basic template reproduces the issue:
```rs
use ggez::{Context, ContextBuilder, GameResult};
use ggez::graphics::{self, Color, Rect};
use ggez::event::{self, EventHandler};

fn main() {
    let (mut ctx, event_loop) = ContextBuilder::new("my_game", "Cool Game Author")
        .build()
        .expect("aieee, could not create ggez context!");
    let my_game = MyGame::new(&mut ctx);
    event::run(ctx, event_loop, my_game);
}

struct MyGame;

impl MyGame {
    pub fn new(_ctx: &mut Context) -> MyGame {
        MyGame {}
    }
}

impl EventHandler<ggez::GameError> for MyGame {
    fn update(&mut self, ctx: &mut Context) -> GameResult<()> {
        let new_screen_view = Rect::new(0.0, 0.0, 800.0, 600.0);
        graphics::set_screen_coordinates(ctx, new_screen_view).unwrap();
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx, Color::WHITE);
        graphics::present(ctx)
    }
}
```

**Hardware and Software:**
 - ggez version: `0.6.1`
 - OS: Windows 11

**Comment by nobbele** [comment]
Thanks for reporting.
set_screen_coordinates barely does anything, this is most likely yet another gfx-rs leak

**Comment by PSteinhaus** [comment]
Can't replicate on Windows 10. Possibly gfx-rs is just too old to handle Windows 11 correctly.
Another motivation to tackle replacing it.

**Comment by PSteinhaus** [comment]
Ok, the wgpu-transition should have solved this issue.
Since the reporting user sadly deleted their account I'll just close this now as we can't ask for verification.
