### ISSUE TITLE
[Question] Drawing many different "morphable" meshes at once.

### ISSUE THREAD

**Issue by Bastczuak** [ggez/ggez#990]
I am trying to draw many many meshes. So by trying (I simply tried to draw 2000 rectangles) and then reading the documentation I figured out, I have to use `MeshBatch` to ensure good performance. So but now I am hitting a wall. 

Let's take the tutorial for [bytepath I am following](https://github.com/a327ex/blog/issues/21) (scroll do the paragraph boost resource). Here the author animates meshes over time by using Love2d draw functions. The effect includes two meshes, or in this case two draw calls, per instance/entity. It's simple in Love2D because draw calls is batched there.

How can I realize that using `MeshBatch`??? The documentation says `Meshbatch`should only be used when meshes are not moving. Also a `MeshBatch` only allows to add one kind of mesh. But in this case I have meshes which values are interpolated over time. I really really don't know how to realize that in ggez.

Thanks in advance!!!

**Comment by PSteinhaus** [comment]
I guess we should change the documantation a bit there. The part about "using it when geometry doesn't move around very often" is a bit misleading, I think.

A `MeshBatch` should be used whenever you have some kind of mesh that needs to be drawn a lot, in different places, with different scales, rotations, etc.

Glancing over the paragraph you mentioned I'd spontaneously say: just use two `MeshBatch`es, one for the solid inner square and one for the non-solid outer one. Then you can position, rotate and scale individual instances of these meshes however you like by `add`ing `DrawParam`s containing that information to them. Once an instance changes (moves, rotates, etc.) just use `set` with the corresponding mesh id to update these values : )

**Comment by Bastczuak** [comment]
@PSteinhaus thanks for your answer. Sclaing would also mean that the pixel size, and so the line width, would increase, right? But that is not wanted. Also I would not like to keep the state of the meshes. Right now I clear the batch after each draw cycle. I guess that is not good?! I also tried to define, let's call it mesh atlas, and then use [src rect](https://docs.rs/ggez/0.6.1/ggez/graphics/struct.DrawParam.html) to clip a mesh. That would have made things easier but it doesn't work somehow with a mesh.

**Comment by Bastczuak** [comment]
So heres a rough sketch:
```rs
pub fn render(
  ctx: &mut Context,
  canvas: &graphics::Canvas,
  background: graphics::Color,
) -> GameResult {
  graphics::set_canvas(ctx, Some(canvas));
  graphics::clear(ctx, background);

  let filled_rect = graphics::MeshBuilder::new()
    .rectangle(
      graphics::DrawMode::fill(),
      graphics::Rect::new(0.0, 0.0, 8.0, 8.0),
      graphics::Color::WHITE,
    )?
    .build(ctx)?;
  let stroke_rect = graphics::MeshBuilder::new()
    .rectangle(
      graphics::DrawMode::stroke(1.0),
      graphics::Rect::new(0.0, 0.0, 8.0, 8.0),
      graphics::Color::WHITE,
    )?
    .build(ctx)?;
  let mut mesh_batch_1 = graphics::MeshBatch::new(filled_rect)?;
  let mut mesh_batch_2 = graphics::MeshBatch::new(stroke_rect)?;

  let p = graphics::DrawParam::new()
    .rotation(45.0)
    .dest(glam::Vec2::new(SCREEN_WIDTH / 2.0, SCREEN_HEIGHT / 2.0));
  mesh_batch_1.add(p);

  let p = graphics::DrawParam::new()
    .rotation(45.0)
    .scale(glam::Vec2::new(2.0, 2.0))
    .dest(glam::Vec2::new(SCREEN_WIDTH / 2.0, SCREEN_HEIGHT / 2.0));
  mesh_batch_2.add(p);
  let p = graphics::DrawParam::new()
    .rotation(45.0)
    .scale(glam::Vec2::new(4.0, 4.0))
    .dest(glam::Vec2::new(SCREEN_WIDTH / 2.0, SCREEN_HEIGHT / 2.0));
  mesh_batch_2.add(p);
  let p = graphics::DrawParam::new()
    .rotation(45.0)
    .scale(glam::Vec2::new(8.0, 8.0))
    .dest(glam::Vec2::new(SCREEN_WIDTH / 2.0, SCREEN_HEIGHT / 2.0));
  mesh_batch_2.add(p);

  mesh_batch_1.draw(ctx, graphics::DrawParam::default())?;
  mesh_batch_2.draw(ctx, graphics::DrawParam::default())?;
  graphics::set_canvas(ctx, None);
  graphics::draw(ctx, canvas, graphics::DrawParam::default())?;
  graphics::present(ctx)?;
  Ok(())
}
```
Maybe know you understand what I meant with scaling increases the line width. Also the scaling is not centered somhow and if my eyes are not deceive me that is not a 45 degree rotation.
<img width="954" alt="Screen Shot 2021-10-19 at 10 31 42" src="https://user-images.githubusercontent.com/50180188/137873856-1d8e684c-4dd0-42ce-95bd-9023aa0f74b4.png">

**Comment by Bastczuak** [comment]
@PSteinhaus ok figured out I have to use offset([-half width of mesh, -half height of mesh]) center the scaled mesh. But my problem with line width and scaling still exist.
<img width="944" alt="Screen Shot 2021-10-19 at 16 24 37" src="https://user-images.githubusercontent.com/50180188/137930446-409493c1-7e60-412d-b920-66c7d58299ca.png">
s.

**Comment by Bastczuak** [comment]
@PSteinhaus ok then I will close this and try one of the suggestions.

**Comment by Bastczuak** [comment]
@PSteinhaus before I create a new issue, may it be feasable to make 'graphics::draw' make batch call draws automagically/internally. Or is this never ever planned to do? I mean there must be a reason why you guys decided not to do it like Love2D does.
