### ISSUE TITLE
Initializing ggez with 8BitDo SN30 pro connected is 180 times slower

### ISSUE THREAD

**Issue by Tubbles** [ggez/ggez#997]
**Describe the bug**
When starting ggez stack with an `8BitDo SN30 pro` gamepad connected, the initalization takes up to 40 seconds. Normally (without the gamepad) it takes under 1 second.

And when I disconnect the gamepad the init finishes immediately.

Reproduced with two different computers and two different `8BitDo SN30 pro` gamepads.

Possibly also reproducible with other gamepads, although I was not able to do so with my `045e:028e Microsoft Corp. Xbox360 Controller`.

Also debug mode or release mode does not make any difference.

**To Reproduce**
Clone my repo https://github.com/Tubbles/ggez_gamepad_mve
Run `cargo run --release` with an `8BitDo SN30 pro` gamepad connected.

**Expected behavior**
Start up of a maximum couple of seconds.

**Actual behavior**
Start up of 10~40 seconds.

**Screenshots or pasted code**
![image](https://user-images.githubusercontent.com/2370561/144872747-899b955c-0edc-4314-91ff-b5213d81d137.png)
Also read the README.md in the repo

**Hardware and Software:**
 - ggez version: 0.7.0
 - OS: Manjaro rolling release as of 2021-12-06
 - Graphics card: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
 - Graphics card drivers: video-linux 2018.05.04

**Comment by PSteinhaus** [comment]
Thanks for reporting!

This looks like a gilrs dependency bug, I guess. I'll try to look into it once I get back to my place later this week.

What happens if you start the game and only then plug in the controller?

Do you get a delay/freeze or does it just go on normally? And does the controller work then?

**Comment by Tubbles** [comment]
Wow great, thanks!

If I connect the 8bitdo after ggez has loaded, the connection takes an equal amount of time as it does usually, and also starts to work immediately within ggez (detected and callbacks are run correctly)

**Comment by PSteinhaus** [comment]
Hmm, interesting. Then I assume it's the `Context` creation that causes this behavior (and in it the creation of the `GilrsGamepadContext`).

Could you move the line `let start = Instant::now();` after `let (ctx, event_loop) = cb.build()?;`, to verify (or falsify) this?

If it's not the context creation then my next best idea would be that the problem might occur the first time the gamepad context is used in the event loop.

**Comment by Tubbles** [comment]
I added two more instants, this is the break down. If I understand your comment correctly, you are correct in that it seems that the `Context` creation is the one that seems to take time.
![image](https://user-images.githubusercontent.com/2370561/145235460-53f4edcc-d322-4dca-9f42-58885aaf3955.png)

**Comment by PSteinhaus** [comment]
Wonderful, thank you!

That's good news for us, because it means that this is indeed a dependency bug with `gilrs`, as our `GilrsGamepadContext` creation doesn't do anything more than calling `Gilrs::new`.

**Comment by nobbele** [comment]
closing due to dependency bug
